### ISSUE TITLE
`ImOnlineUnsignedPriority`

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot#1049]
`ImOnlineUnsignedPriority`:
https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L496

---

?`ModuleId` might be better:
https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L400

**Comment by bkchr** [comment]
What do you want to say with this issue?

**Comment by AurevoirXavier** [comment]
> What do you want to say with this issue?

Just a bug report.
