### ISSUE TITLE
Set Polkadot Election Lookahead Window

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#1060]
Polkadot's election [lookahead window](https://github.com/paritytech/polkadot/blob/cfcef38/runtime/polkadot/src/lib.rs#L315) is set to `EPOCH_DURATION / 4`, like Kusama, but Polkadot's epochs are four times longer. The offchain election window should probably be `EPOCH_DURATION / 16` unless there is some justification for a longer window.

Tagging as annoyance since it will be a UX problem for staking functions to be closed for so long.

**Comment by kianenigma** [comment]
was already fixed when we released CC1 

https://github.com/paritytech/polkadot/blob/5629242d9eed1429c26c852f715c88e856a6d04f/runtime/polkadot/src/lib.rs#L318
