### ISSUE TITLE
Panic error  with  kusama sync node

### ISSUE THREAD

**Issue by freehere107** [paritytech/polkadot#1073]
Version: 0.7.30-0353c979-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   2: std::panicking::begin_panic
   3: <kusama_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,kusama_runtime::Call,sp_runtime::MultiSignature,(kusama_runtime::RestrictFunctionality, frame_system::CheckVersion<kusama_runtime::Runtime>, frame_system::CheckGenesis<kusama_runtime::Runtime>, frame_system::CheckEra<kusama_runtime::Runtime>, frame_system::CheckNonce<kusama_runtime::Runtime>, frame_system::CheckWeight<kusama_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<kusama_runtime::Runtime>, polkadot_runtime_common::registrar::LimitParathreadCommits<kusama_runtime::Runtime>, polkadot_runtime_common::parachains::ValidateDoubleVoteReports<kusama_runtime::Runtime>)>>>>::execute_block
   4: std::panicking::try::do_call
   5: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
   6: std::thread::local::LocalKey<T>::with
   7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
   8: sc_executor::wasm_runtime::RuntimeCache::with_instance
   9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
  11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  12: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  13: <sc_client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  14: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  15: sp_api::Core::execute_block
  16: <&sc_client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  17: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  18: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: sp_consensus::import_queue::import_single_block
  20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  21: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: futures_executor::thread_pool::PoolState::work
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1017
  29: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/boxed.rs:1017
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  30: start_thread
  31: __clone

Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', <::std::macros::panic macros>:2

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

Hash: given=49cd57fd1e0e111c907cab8369040ecb2eda26ce9ac9c1a89ccc193f704fc755, expected=cc5aac92e8a75161b91e574b0470fa5455bd55f84eebee3b2689733a78c4f205
2020-05-07 08:10:04 Block prepare storage changes error:
Execution(RuntimePanicked("Storage root must match that calculated."))

**Comment by freddieee** [comment]
encountered the same problem:

`Error importing block 0x478f359d51519b954a49567ae01afd2d62b315bd06d94e433fba212c8a7eef76: Err(Other(ClientImport("Import failed: Execution: Runtime panicked: Storage root must match that calculated.")))`

**Comment by bkchr** [comment]
0.7.30 is incompatible with the latest runtime. Please update to the latest release.
