### ISSUE TITLE
Const Transaction Fee

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot#1109]
When the `FeeMultiplier` hit `-1000000000000000000`, it won't change anymore. Then all the extrinsics's fee turn in to `1` milli KSM.

Does this make sense?

This make all the weight settings useless.

This can be found in kusama live. Or on a dev chain set storage `FeeMultiplier` to `-1000000000000000000`.

**Comment by bkchr** [comment]
CC @shawntabrizi @kianenigma

**Comment by kianenigma** [comment]
> When the FeeMultiplier hit -1000000000000000000, it won't change anymore.

This is not correct. It _will_ change again if we have blocks in which more than 25% of the weight is consumed. In kusama, this hardly happens at the moment. 

We might change the 25% limit later on but as of now, this is expected and fine.

**Comment by HackFisher** [comment]
@kianenigma please take a look at the analysis: https://github.com/darwinia-network/darwinia/issues/447
