### ISSUE TITLE
`build-spec` outputs the raw spec

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/polkadot#1115]
`polkadot build-spec` outputs the raw chain spec.  It should instead output a non-raw spec, so users can edit it to include their own choices of validators.

**Comment by arkpar** [comment]
There's a `--raw` CLI flag that should control that. Is it not working properly?

**Comment by DemiMarie-parity** [comment]
With or without `--raw`, I still only get `raw` entries in the `consensus` object.

**Comment by arkpar** [comment]
What's a `consensus` object? I don't think it's part of the chain spec. Could you specify your complete command to build the spec?

**Comment by DemiMarie-parity** [comment]
Sorry, I meant the `genesis` object.  I have attached the gzipped output of `cargo run --release -- build-spec`.
[spec.json.gz](https://github.com/paritytech/polkadot/files/4652873/spec.json.gz)

**Comment by arkpar** [comment]
If you want to have runtime-generated json spec you need to use native runtime genesis source. E.g `--chain kusma-staging`.

**Comment by DemiMarie-parity** [comment]
Got it.  Can that be documented?

**Comment by bkchr** [comment]
It is, please read the cli docs.
