### ISSUE TITLE
`polkadot -- build-spec` fails with unhelpful error message

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/polkadot#1116]
If I run `polkadot -- build-spec`, I get this unhelpful error message:

    error: The subcommand 'build-spec' wasn't recognized
    	Did you mean 'build-spec'?
    
    If you believe you received this message in error, try re-running with 'polkadot -- build-spec'
    
    USAGE:
        polkadot [FLAGS] [OPTIONS]
        polkadot <SUBCOMMAND>
    
    For more information try --help

**Comment by bkchr** [comment]
Why do you run `-- build-spec`?

As the command tells you run `--help` and it will help you.
