### ISSUE TITLE
Provide a container image that contains a network ready to launch

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/polkadot#1117]
This would make testing significantly easier.  The hash of the container image should be included in the signed release artefacts.

**Comment by ddorgan** [comment]
Something like https://github.com/paritytech/substrate/blob/master/.maintain/sentry-node/docker-compose.yml?

**Comment by DemiMarie-parity** [comment]
Somewhat.  I was envisioning a configuration that would generate a genesis block for a development network at startup.

**Comment by fgimenez** [comment]
Take a look at https://github.com/w3f/polkadot-deployer it allows you to run local or remote networks with variable number of validators, generating the chainspec accordingly.

**Comment by bkchr** [comment]
Sounds like we can close this.
