### ISSUE TITLE
Thread 'tokio-runtime-worker-1' panicked at 'attempting to canonicalize unknown block', src/libcore/option.rs:1008

### ISSUE THREAD

**Issue by lows93** [paritytech/polkadot#112]
stack backtrace: 0: 0x561a0f1afc8d - backtrace::backtrace::trace::h544964ff9f0fac62 1: 0x561a0f1aedb2 - <backtrace::capture::Backtrace as core::default::Default>::default::he75e8a7c41cf8eac 2: 0x561a0e9b7658 - substrate_cli::panic_hook::panic_hook::hf12b8f01f2b8e6ce 3: 0x561a0e9b7358 - core::ops::function::Fn::call::he685eb7bb2039c66 4: 0x561a0f2b4649 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be at src/libstd/panicking.rs:495 5: 0x561a0f2b40f1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1 at src/libstd/panicking.rs:398 6: 0x561a0f2b3fd5 - rust_begin_unwind at src/libstd/panicking.rs:325 7: 0x561a0f2cbfac - core::panicking::panic_fmt::h4d67173bc68f6d5a at src/libcore/panicking.rs:95 8: 0x561a0f2cc022 - core::option::expect_failed::h2f881c519f1d8001 at src/libcore/option.rs:1008 9: 0x561a0e4b5c16 - <substrate_state_db::noncanonical::NonCanonicalOverlay<BlockHash, Key>>::canonicalize::h723e5617421c2c27 10: 0x561a0e896489 - <substrate_state_db::StateDb<BlockHash, Key>>::canonicalize_block::h3006664f5d9a7b4d 11: 0x561a0e7ba291 - <substrate_client_db::Backend<Block>>::note_finalized::h0217d85fc53f080b 12: 0x561a0e794013 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::finalize_block::h5a6a0e6753f8f8e3 13: 0x561a0e5ace84 - <substrate_client::client::Client<B, E, Block, RA>>::apply_finality::hb0167a0f968daeae 14: 0x561a0e5aea1e - <substrate_client::client::Client<B, E, Block, RA>>::finalize_block::h0f21727f8b8c368d 15: 0x561a0e529fbf - substrate_finality_grandpa::finalize_block::haf23c8dd3323dd57 16: 0x561a0e6964d4 - <finality_grandpa::voter::Voter<H, N, E, CommitIn, CommitOut>>::process_commits::ha224611522bc7723 17: 0x561a0e65bcfe - <finality_grandpa::voter::Voter<H, N, E, CommitIn, CommitOut> as futures::future::Future>::poll::h6421d5bcdef0bd8a 18: 0x561a0e5c33f2 - <futures::future::select2::Select2<A, B> as futures::future::Future>::poll::h144a6b9bc21daa2e 19: 0x561a0e48b403 - <futures::future::chain::Chain<A, B, C>>::poll::h7732cf25960009ed 20: 0x561a0e721821 - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::h91b38d51f8979592 21: 0x561a0e8a3887 - <futures::future::join::Join<A, B> as futures::future::Future>::poll::h437ce0dadbb7fae3 22: 0x561a0e7c6d80 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h1c5c1e19f27bf96b 23: 0x561a0e779322 - <futures::future::select::Select<A, B> as futures::future::Future>::poll::ha59aa93f074d5312 24: 0x561a0e49a2f1 - <futures::future::chain::Chain<A, B, C>>::poll::hf6d3656dc5fbea5d 25: 0x561a0f27df01 - futures::task_impl::std::set::ha675998835d9777e 26: 0x561a0f27f805 - <futures::task_impl::Spawn<T>>::poll_future_notify::hf56f5259b11d209f 27: 0x561a0f282cb0 - std::panicking::try::do_call::h3e2dc8917104e71c 28: 0x561a0f2c52a9 - __rust_maybe_catch_panic at src/libpanic_unwind/lib.rs:102 29: 0x561a0f280a3b - tokio_threadpool::task::Task::run::h9855397de4f00f81 30: 0x561a0f27a495 - tokio_threadpool::worker::Worker::run_task::h1da4ec4c3810b26a 31: 0x561a0f27993d - tokio_threadpool::worker::Worker::run::hfa53eb1e4f72e585 32: 0x561a0f260686 - <std::thread::local::LocalKey<T>>::with::h26c07fb6016527e8 33: 0x561a0f260567 - <std::thread::local::LocalKey<T>>::with::h08191b9fffdc4f3d 34: 0x561a0f260871 - <std::thread::local::LocalKey<T>>::with::h36347f1e44b69600 35: 0x561a0f25a7f9 - tokio::runtime::builder::Builder::build::{{closure}}::hbd376883e27277f8 36: 0x561a0f281072 - <std::thread::local::LocalKey<T>>::with::h2713c564c73e54ca 37: 0x561a0f2812d9 - <std::thread::local::LocalKey<T>>::with::hadef08c65db6f195 38: 0x561a0f282857 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0518f89ec5981bad 39: 0x561a0f282c6b - std::panicking::try::do_call::h05819a532c24c309 40: 0x561a0f2c52a9 - __rust_maybe_catch_panic at src/libpanic_unwind/lib.rs:102 41: 0x561a0f28499f - <F as alloc::boxed::FnBox<A>>::call_box::h699e6129d11aa145 42: 0x561a0f2b8e8d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683 - std::sys_common::thread::start_thread::h9605a7df0f911844 at src/libstd/sys_common/thread.rs:24 - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291 at src/libstd/sys/unix/thread.rs:90 43: 0x7f93ec8f8163 - start_thread 44: 0x7f93ec804dee - __clone 45: 0x0 - <unknown>
Thread 'tokio-runtime-worker-1' panicked at 'attempting to canonicalize unknown block', src/libcore/option.rs:1008
This is a bug. Please report it at:
https://github.com/paritytech/polkadot/issues/new

Im running Version 0.3.6 on Alexander

**Comment by rphmeier** [comment]
Try 0.3.8 -- this should be fixed by https://github.com/paritytech/substrate/pull/1616
You will probably need a clean DB
