### ISSUE TITLE
Unable to properly set --rpc-cors

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/polkadot#1132]
I am unable to access my node though the polkadot-ui if I attempt to set "--rpc-cors" to anything but "all".

Starting from scratch and without any "--rpc-cors" configured, when I attempt to access the node, in the log I get: "Blocked connection to WebSockets server from untrusted origin: Some("https://1.2.3.4:8080")"

Fine, so I add the following string and try again: "--rpc-cors "https://1.2.3.4:8080""

There's progress, I am now asked for a different cors string: "Blocked connection to WebSockets server with untrusted host: Some("1.2.3.4")"

I then add "1.2.3.4": "--rpc-cors "https://1.2.3.4:8080,1.2.3.4""

At which point I am getting the same exact error logged: "Blocked connection to WebSockets server with untrusted host: Some("1.2.3.4")"

I am accessing my Kusama node through a Wireguard VPN, where the node is behind a nginx instance. Locally (MacOS / Brave), I use the polkadot-ui interface hosted on IPFS (https://polkadot.js.org/apps/ipfs/).

Again, it is working perfectly fine with "--rpc-cors all". At this point I am simply trying to tie loose ends and make sure my security is as solid as it can be, ready for Polkadot.

Thanks.

**Comment by dillu24** [comment]
Same issue for me. Is this a problem or is it expected behaviour?

**Comment by leopoldjoy** [comment]
We're seeing the same issue. Any progress?

**Comment by tomusdrw** [comment]
If `rpc-cors` is set to something else than `all` we only whitelist `Host` that matches the listening address of the server.  So if your node by default listens on `localhost` it's not possible to connect to it using `1.2.3.4` address.

If your node is already behind `nginx` you can simply rewrite `Host` header when proxying to match the interface it listens on (`localhost` or `127.0.0.1`):
```
  proxy_set_header Host localhost:9944; 
```

**Comment by bkchr** [comment]
@dillu24 @leopoldjoy any update?

**Comment by LukeWheeldon** [comment]
This fixes my issue, thanks @tomusdrw!

@dillu24 @leopoldjoy please confirm whenever you can if this fixes your issue as well so we can close this ticket, thanks!

**Comment by nazar-pc** [comment]
Proxy server doesn't work for me because I connect from one Docker container to another by host name like `ws://node:9944`, so there is no other way to get things to work except `--rpc-cors all` :confused:

Would be nice to be able to specify both origins and hosts, but the issue is for Substrate, not Polkadot.

**Comment by nazar-pc** [comment]
Was this fixed? I don't see any PRs pointing to this issue.
