### ISSUE TITLE
Instantiation: Export ext_misc_runtime_version_version_1 not found

### ISSUE THREAD

**Issue by endro-00** [paritytech/polkadot#1133]
I am syncing a node from scratch and suddenly i get following message:

Syncing  0.0 bps, target=#2451258 (1 peers), best: #693487 (0xd9c1…732f), finalized #693248 (0xabea…8810), ⬇ 39.8kiB/s ⬆ 1.1kiB/s
2020-05-24 20:42:02 Received message on non-registered protocol: [100, 111, 116, 50]
2020-05-24 20:42:03 Verification failed from peer: Failed to get runtime version: InvalidCode("Instantiation(\"Instantiation: Export ext_misc_runtime_version_version_1 not found\")")

--------- stacktrace:

Version: 0.7.16-7207d975-x86_64-linux-gnu

stack backtrace:
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   4: core::result::unwrap_failed
             at src/libcore/result.rs:1188
   5: sc_network::protocol::sync::extra_requests::ExtraRequests<B>::new::{{closure}}
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::panicking::try::do_call
   8: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  12: start_thread
  13: __clone

**Comment by bkchr** [comment]
Please use the latest node version. Yours is completely outdated.
