### ISSUE TITLE
Determine Collator Subsystems

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1141]
Determine what subsystems are necessary for a collator to operate. We need to be cognizant of the boundary with Cumulus, as it embeds the entire service with a provided context for the parachain.

The relay-chain side makes asynchronous requests to Cumulus to author blocks under given conditions, and it would be reasonable to employ a subsystem for that. Collators should also be connected to validators via networking subsystems.

**Comment by burdges** [comment]
We discussed this before, and it'll be more apparent to anyone working on cumulus, but cumulus should ideally isolate towards later stages its code that builds witnesses about the relay chain's state at the relay chain parent.

**Comment by rphmeier** [comment]
Right now we have stubs for Collation Distribution and Collation Generation.

We will want to extract out the validator-side of the collator networking protocol from the Candidate Selection subsystem, since the `NetworkBridge` can only support one subsystem per protocol ID. But that is beyond-scope of this issue
