### ISSUE TITLE
Guide: Block Authorship Integration

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1170]
The Substrate block authorship pipeline cannot reasonably be made into a Subsystem.

Related: #1143

In practice, we will have a subsystem that provides all information that we need to provide as `InherentData` to the block authorship system, so we just need an asynchronous interface for the block authorship system to fetch that data.

We should have a section in the guide on the actual block authorship pipeline and its interface to the overseer, and clarify that the block authorship subsystem is not actually responsible for authoring blocks.

**Comment by coriolinus** [comment]
Does the channel-based mechanism from https://github.com/paritytech/polkadot/pull/1257 satisfy this requirement, or should we add more design work to complete this?

**Comment by rphmeier** [comment]
#1257 Provides enough information that I'm comfortable pushing this to Rockville. It'll just be a small paragraph explaining the workings of the block authorship worker and how it'll query the `Provisioner` via a handle to the overseer, and then bundle that data into a block along with transactions.

**Comment by coriolinus** [comment]
I think [this paragraph](https://github.com/paritytech/polkadot/pull/1320/files#diff-304f5581c93a7eac91495e9070d60305) may satisfy the requirement laid out here; do you agree?

**Comment by rphmeier** [comment]
Yeah, after tweaks I think that will be sufficient

**Comment by rphmeier** [comment]
#1170 was closed which included something for this
