### ISSUE TITLE
Westend faucet can't register

### ISSUE THREAD

**Issue by Wangmmx** [paritytech/polkadot#1177]
Can someone give me a WND to test? I can buy a little with ETH :(
I can't register in https://riot.w3f.tech/#westend_faucet:matrix.org, I need to test it

address: 5Dgq3axpAPE7nUDKdhsxfvHKjBiRTwCQJesfxZ2z12b91TC3

**Comment by bkchr** [comment]
CC @ddorgan

**Comment by Wangmmx** [comment]
please help me, I can't continue my test without WND

**Comment by ddorgan** [comment]
@Wangmmx the url of the room is #matrix_faucet:matrix.org

**Comment by Wangmmx** [comment]
This url won't work either. I can't register an account with matrix. I also filed an issue in the official website. After some effort, it still won't work.

https://github.com/matrix-org/synapse/issues/7608#event-3392918461

**Comment by ddorgan** [comment]
So you cannot login to matrix? This is not a polkadot related issue.

**Comment by ddorgan** [comment]
Do not register at: https://riot.w3f.tech/#/register - instead use https://riot.im/app/#/register

**Comment by Wangmmx** [comment]
I have tried these sites without success，I just want to get a bit of WND, I can't get it in the current ways, Is there any other way to get WND？ I have no way to enter the matrix and riot

I was assembling the transaction body and broadcasting it all the time, and I kept reporting that the balance was insufficient. In the past three days, I did not get WND. I just want to continue my test

**Comment by ddorgan** [comment]
@Wangmmx sent you 0.3 WND's, the same as two faucet requests that are allowed per 24 hours.

Looks like you need to signup to matrix/riot using their public service, then join the faucet room and you can request WND's from that point.

**Comment by ddorgan** [comment]
p.s. do not buy WND's for ETH as mentioned in the first comment in this issue, this is a test network and tokens hold no value.

**Comment by Wangmmx** [comment]
thank you very much!
Moved to cry 
I will continue to try to get WND's by joining the faucet room.

I know these WND's hold no value, but it is very important to me for now
Anyway, thanks again! You helped me a lot

**Comment by Wangmmx** [comment]
My attempts to register matrix/riot all failed. People who encountered the same problem as me found that it might be blocked.
![image](https://user-images.githubusercontent.com/22836587/83592055-12f0d900-a58c-11ea-8b03-d66de3c98329.png)


 I have no way to get WND's. I know that this request is very unreasonable, but can you give me a little more WND's? Sending a transaction will cost at least 0.001, and I dare not use it

**Comment by ddorgan** [comment]
@Wangmmx sent

**Comment by Wangmmx** [comment]
Thank you very much!

**Comment by islishude** [comment]
Hi,I can't use [faucet](https://riot.im/app/#/room/!cJFtAIkwxuofiSYkPN:matrix.org)

![屏幕快照 2020-07-20 下午6 03 45](https://user-images.githubusercontent.com/24730006/87925873-7d65c600-cab3-11ea-8446-01536347d4fe.png)

**Comment by Wangmmx** [comment]
> Hi,I can't use [faucet](https://riot.im/app/#/room/!cJFtAIkwxuofiSYkPN:matrix.org)
> 
> ![屏幕快照 2020-07-20 下午6 03 45](https://user-images.githubusercontent.com/24730006/87925873-7d65c600-cab3-11ea-8446-01536347d4fe.png)

How did you solve it? please
