### ISSUE TITLE
--sentry-nodes connection issue

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/polkadot#1193]
As a validator, when relying solely on the flags '--reserved-nodes' and '--reserved-only', everything is working fine. If the flag '--reserved-only' is kept but '--reserved-nodes' is replaced with '--sentry-nodes', the node won't try connecting to the sentries anymore.

This can be observed particularly when using a firewall blocking all inbound TCP/30333. That configuration implies relying on the validator to establish connection to the sentries.

Please let me know if any more details would be useful to this bug report.

edit/note: this can be alleviated by cumulating '--reserved-nodes' along with '--sentry-nodes' with both reflecting each other(s) values.

**Comment by bkchr** [comment]
I think this should be fixed by: https://github.com/paritytech/polkadot/pull/1196

CC @tomaka

**Comment by tomaka** [comment]
Indeed

**Comment by bkchr** [comment]
@LukeWheeldon so this will be fixed with 0.8.4 next week.
