### ISSUE TITLE
Guide: it's big, and getting bigger. Should we use mdBook or similar to organize it?

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1195]
My branch of the implementer's guide currently has 1335 lines and 13419 words: it's the size of a novella. It's also very incomplete; there is a lot of work yet to come to expand it to flesh out several areas.

I'd suggest breaking it into separate files for ease of working with and to help us organize it. There are plenty of tools for merging a collection of files into a single book; [mdBook](https://github.com/rust-lang/mdBook) is well known, but others are available as well.

@rphmeier If this isn't a good idea, feel free to unceremoniously close this issue.

**Comment by rphmeier** [comment]
I am ambivalent without a personal preference against a long document, but happy to have it broken down as well.
