### ISSUE TITLE
Make a runtime that uses all Parachains-runtime modules and ties them together with a Sudo registrar

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1209]
This will be a simple runtime:
  - BABE
  - GRANDPA
  - Other consensus support
  - Session
  - Balances
  - Most other stuff from Substrate-node
  - All Parachains-core modules
  - Sudo

And a simple wrapper that allows Sudo to make calls for changing configuration, registering parachains, etc.

**Comment by rphmeier** [comment]
Although this is tagged "Deploy", it doesn't have any dependencies beyond #1242.

**Comment by drahnr** [comment]
Should this be integrated with `node/service.rs`? This would imply a couple of requirements on the runtime API (offchain workers i.e.), is that desired?
