### ISSUE TITLE
Add Unit Tests for `IsCallable` filters

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#1217]
We should add some unit tests at the Runtime level making sure the `IsCallable` filters adhere to the intended usage, and does not allow for additional access beyond what we intend.

**Comment by edjroz** [comment]
Hey trying to help out here, but I can't find references on runtime to `IsCallable` implementations ? can you provide more details on what exactly are you looking to test ?

**Comment by shawntabrizi** [comment]
@edjroz Sorry, I dont remember what exactly I had in mind when I wrote this issue. But it looks like there are already tests in place for `IsCallable`.

Take a look at some of the other easy/mentor issues and I will be happy to help where I can.
