### ISSUE TITLE
Can not sync normally  - Disconnected from /dns/teleme.. : Closed

### ISSUE THREAD

**Issue by garysdevil** [paritytech/polkadot#1224]
- role: full node
- command-line: /home/polkadot/polkadot --pruning archive --name wx_test_westend_node01 -d /data/polkadot --rpc-external --ws-external --rpc-cors all --chain westend
- log:
![图片](https://user-images.githubusercontent.com/41293784/84246734-9b95e900-ab39-11ea-8a9a-e830e518b4e6.png)

**Comment by bkchr** [comment]
Every time you start the node?

**Comment by garysdevil** [comment]
> 
> 
> Every time you start the node?
Thank your reply.
Yes, it showed same log every time I started node.
I thought that the data was corrupted becouse last 'oom'. So I cleared data and sync form 0, it is normal now.

**Comment by bkchr** [comment]
So we can close this for now?

**Comment by garysdevil** [comment]
> 
> 
> So we can close this for now?

ok
