### ISSUE TITLE
Implement: Availability Store

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1240]

**Comment by rphmeier** [comment]
The guide goes into detail on pruning and pruning constraints. We shouldn't need to implement the pruning stuff at first. Most important is just that the necessary data is stored and queryable.

@montekki What's described in the guide is pretty different from the API in the existing `av_store` crate

**Comment by montekki** [comment]
I don't think that porting is worth the effort, I say rewrite

**Comment by rphmeier** [comment]
https://github.com/paritytech/polkadot/pull/1312/files#r451847813 - The store should also support storing full PoVs of things that we've validated, and should be able to answer all `QueryChunk` messages

**Comment by montekki** [comment]
Implemeted in #1404 . Pruning implementation is moved to #1488
