### ISSUE TITLE
Implement: Candidate Validation

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1241]

**Comment by bkchr** [comment]
This validation should ensure that if a candidate fails, it does not invalidates all the other candidates in the `set_heads` call. This is currently done and brings down the network, as the logic always tries to apply the same candidate, which always fails.

**Comment by rphmeier** [comment]
So this is just about the raw candidate validation subsystem, which takes in a request to validate a specific candidate and outputs a `Result<bool,()>`.

However we want the property that blocks are invalid if they include badly-formed para candidates within them. Validators shouldn't be submitting blocks that contain bad candidates or backings

**Comment by rphmeier** [comment]
The conversation above is actually what caused us to write up #1327 as it was a red herring. But that is addressed now, for closure.

**Comment by burdges** [comment]
I'll clarify:  Relay chain block remain valid, and can be built upon, even if they declared an invalid candidate to be backed.  We just slash that candidate's backers based upon that evidence.  

We've hashed out elsewhere the subtle rules for extending relay chains with relay chain blocks that declare a disputed candidates available.  You cannot extend any relay chain with a relay chain block that declare an invalid candidates available. 

In theory, we could weaken this last conditions slightly but only by making candidates actually execute in the next relay chain block, which sucks probably.

**Comment by rphmeier** [comment]
@burdges That is a separate issue. The candidate can be included if it represents a well-formed but invalid parameter-set to a validation function. But this is about the candidate being a badly-formed parameter-set to the validation function. We want all candidates on-chain to be possible to check.
