### ISSUE TITLE
Unnamed tasks leaking on RPC nodes

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot#1255]
![Screenshot from 2020-06-12 16-30-10](https://user-images.githubusercontent.com/1412254/84513739-2b6a9d00-acca-11ea-9478-4ebb3858cc75.png)

Here is a screenshot of the number of unnamed tasks on our RPC nodes.
As you can see, we're at around 25000 such tasks at the moment, and it is increasing, which I suppose isn't normal.

An "unnamed task" in this context is a `Future` that we spawn through the `futures::task::Spawn` trait. If I'm not mistaken, we don't have any unnamed task in Substrate anymore, so this is probably coming from somewhere in Polkadot.
cc https://github.com/paritytech/polkadot/issues/1244

This leak apparently happens on our two Polkadot RPC nodes and Kusama RPC node, but not our bootnode nor on my own node that has been running for two days. Also doesn't happen on any ~~Kusama~~ non-RPC node.
The flags on these RPC nodes are `--ws-port 5556 --unsafe-ws-external --ws-max-connections 5000 --rpc-cors '*'`.

**Comment by tomaka** [comment]
Memory consumption seems to increase by around 100 MiB/day on these nodes, but it's unclear how much that is due to these tasks.

**Comment by bkchr** [comment]
I think this could be fixed by this pr as well: https://github.com/paritytech/substrate/pull/6341

It lead to transaction notifiers not being closed down, but this would mean the connection stayed open all the time or there is also a bug on the RPC not closing tasks properly. Maybe worth to monitor with 0.8.8.

**Comment by tomaka** [comment]
Still leaking on 0.8.10-183848b6

**Comment by tomaka** [comment]
Around 150000 such tasks alive on each RPC node at the moment.

**Comment by tomaka** [comment]
The tasks are still unnamed despite running 0.8.14.
We probably have to do https://github.com/paritytech/polkadot/issues/1378 to continue here.

**Comment by tomaka** [comment]
The leaking task is still unnamed on 0.8.17, despite #1430

**Comment by tomaka** [comment]
We have reached a peak of 772k tasks a bit earlier

**Comment by tomaka** [comment]
As Rob suggested, this might be the JSON-RPC code registering finality and chain heads notifications for when users subscribe.

**Comment by tomaka** [comment]
The leaking task is `substrate_rpc_subscription`

**Comment by tomaka** [comment]
Tasks are now named. A new issue should be opened if a task is leaking.
