### ISSUE TITLE
The Trust Settings Record was corrupted.

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#1295]
Building master and starting polkadot, I get a panic on MacOS.
It could be due to old local data.

Version: 0.8.11-fb66e42f-x86_64-macos

<summary>
<details>
2020-06-20 10:46:01 Starting parachain attestation session on top of parent 0x63f7d5d5573fc6c07a...2773bff99128abb. Local parachain duty is Some(LocalDuty { validation: Relay, index: 0 })

====================

Version: 0.8.11-fb66e42f-x86_64-macos

   0: backtrace::capture::Backtrace::create
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: _rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
   8: sc_offchain::api::http::http
   9: <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::panic::catch_unwind
  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: tokio::runtime::task::raw::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::runtime::thread_pool::worker::Context::run_task
  18: tokio::runtime::thread_pool::worker::Context::run
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
  20: tokio::runtime::thread_pool::worker::run
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: tokio::runtime::context::enter
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: std::sys::unix::thread::Thread::new::thread_start
  29: __pthread_start

Thread 'tokio-runtime-worker' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }', /Users/will/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.20.0/src/connector.rs:46

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
</details></summary>

**Comment by chevdor** [comment]
Only shows when using `--dev`(I am using `--dev --alice`

**Comment by chevdor** [comment]
likely related to https://github.com/ctz/rustls-native-certs/issues/4
starting with sudo indeed works

**Comment by chevdor** [comment]
So this is likely an issue with the certificates on my machine. Running as sudo means running as *another* user with different certificates (usually none) and that does not expose issue.

**Comment by bkchr** [comment]
Yeah that is probably nothing we can fix, maybe you have some corrupt certificate?

**Comment by chevdor** [comment]
Agreed, I did not fix it yet but I don't think anything can be fixed in polkadot.

**Comment by chevdor** [comment]
I confirm the relevance of the issue I linked above.
One of my certification was resulting in a `Err(BadDER)` (see code snippet in the linked issue).
Once you have the name of the certificate, you may remove it using `security delete-certificate -c TheNameHere`

After that, I can start using `--dev --alice` again...
