### ISSUE TITLE
Wiki extrinsic nonce definition error

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/polkadot#131]
The wiki with the Extrinsic format specification (https://wiki.parity.io/Extrinsic) appears to have a mistake due to changes with POC3. Check any signed extrinsic on Alexander for details.

The nonce seems to have a compact encoding, while the specification in the wiki stills lists it as 8 byte fixed length.

**Comment by gavofyork** [comment]
yeah the wiki is wrong. should be sorted now.
