### ISSUE TITLE
SignedAvailabilityBitfields should be a typedef, not a newtype

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1339]
https://github.com/paritytech/polkadot/blob/90d5dbe564ae795d68aff1c936cbdd1f98c9d536/primitives/src/parachain.rs#L727-L728

Rationale: 
- We pass around binary encoded bitfields. A newtype may not encode to the same representation as its wrapped type; a typedef always will.
- The wrapped type is public and we do not implement any interesting traits on the newtype; we aren't gaining any advantage in type safety or ease-of-use. 

I suspect this was simply an oversight, but we may as well fix it.

**Comment by bkchr** [comment]
> We pass around binary encoded bitfields. A newtype may not encode to the same representation as its wrapped type; a typedef always will.

The encoding will always be the same, as SCALE does not encodes `structs`, just its fields.

> The wrapped type is public and we do not implement any interesting traits on the newtype; we aren't gaining any advantage in type safety or ease-of-use.

You get type safety. That is mostly the reason why you choose a new type wrapper and it also often makes the code better to read.

**Comment by coriolinus** [comment]
You get type safety for cases like `struct Meter(f32); struct Foot(f32);`, which prevents you from adding inches and feet without an appropriate conversion. I submit that there is no `Vec<SignedAvailabilityBitfield>` for which it is inappropriate to interact with a `SignedAvailabilityBitfields`; the fact that the wrapped vector is public tends to support this assertion.

Here, it makes the code worse to read, because we need to add a sprinkling of `.0` and `.into()` wherever we need to convert between one form and the other.
