### ISSUE TITLE
RPC: Extrinsic submission & inclusion notification pub/sub

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#134]
Websockets/pub-sub RPCs should be expanded to allow RPC clients to submit extrinsics and get full lifetime notifications of them.

- -> `author_submitExtrinsic(xt: Vec<u8>) -> Result<ExtrinsicHash, Error>`
- <- `author_extrinsicUpdate(xt: ExtrinsicHash, status: Status)`

`Error` may be:
- `InvalidFormat` (i.e. it's plain old invalid and will never become valid)
- `Dead` (i.e. it was once valid but has now become invalid)
- `Immature` (i.e. it's currently invalid and while it may become valid at some point, that's too far ahead to care about)
- `PoolFull` (i.e. there's no room at the inn)
- ~`AlreadyKnown`~ If we already know about it but yet it's valid for inclusion, then it's not an error - we carry on as before and trace the pre-existing extrinsic instead.

`Status` may be:
- `Finalised(BlockHash)` (it's finalised and all is well)
- `Usurped(ExtrinsicHash)` (some state change (perhaps another extrinsic was included) rendered this extrinsic invalid)
- `Broadcast(Vec<PeerId>)` (it has been broadcast to the given peers) *version 2.0 only*

**Comment by gavofyork** [comment]
@tomusdrw any movement on this?

**Comment by tomusdrw** [comment]
Not yet, working on it on my local branch, jumped in to couple of parity issues in the meantime. Will focus on this later this week.

**Comment by gavofyork** [comment]
kk
