### ISSUE TITLE
High deposit on Westend for setting up a proxy

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#1345]
I tried setting an `IdentityJudgement` proxy on Westend. It did work but ended up taking a 20 WND deposit which sounds odd.

As seen below:
https://westend.subscan.io/extrinsic/0xbc5ce5bf6a51383c8c8373bc1e0f46810f2c8a3aa672bdaa682c8c7fc0f8c5c2

`20041000000000` was reserved. That is 20.041 WND

**Comment by wpank** [comment]
#1341 reduced the deposit costs for proxies on westend. Closing this.
