### ISSUE TITLE
Improve misbehavior reports in CandidateBackingSubsystem

### ISSUE THREAD

**Issue by montekki** [paritytech/polkadot#1387]
as noted in https://github.com/paritytech/polkadot/pull/1312#discussion_r451846093 we have to be able to slash for a _set_ of offences rather than for a _single_ offence. To do that we likely need to

* Unify the types used in subsystems and in `statement-table`.
* Improve `statement-table` so it would report a set of offences for an `AuthorityId`.

**Comment by rphmeier** [comment]
`statement-table` can `drain_misbehavior`, giving proofs of all misbehavior observed within that table. It should not be overcomplicated to transform those into many different reports. The only property we need is that there is a 1:1 mapping of reports issued by the statement table to reports issued to the relay chain.

**Comment by rphmeier** [comment]
Have just seen [this comment](https://github.com/paritytech/polkadot/pull/1312#discussion_r452302940) and realize that I misremembered the API of the statement table.
