### ISSUE TITLE
The same transaction exist in different blocks

### ISSUE THREAD

**Issue by shenyaqi9527** [paritytech/polkadot#1396]
chain:KSM
version:v0.8.13
txId: 0x869111d31350ada53eef2455953b3b9cca8d40f036abfc765f24f2d6b80c92e9
block height: 3152899  3152945

**Comment by tomusdrw** [comment]
That's perfectly fine. Transaction hash cannot be used be used as unique identifier of a transaction, please see more explanations here: https://github.com/paritytech/substrate/issues/5153#issuecomment-595656056

**Comment by shenyaqi9527** [comment]
The transaction signature information in both blocks is the same @tomusdrw

**Comment by tomusdrw** [comment]
Your transaction was reaped in the meantime (means it dropped below Existential Deposit and was removed from the chain) - that causes the nonce to be reset back to `0` and if the transaction is marked as `Immortal` (or simply is still within the limits), it can be included on-chain again.

To prevent that in the future make sure to either:
1. Keep your account above ED
2. Use `Mortal` transactions, which has a limited validity (for instance only for 256 blocks) - it's generally a more reasonable choice anyway.

**Comment by yz89** [comment]
Won't there be a replay attack? @tomusdrw

**Comment by yz89** [comment]
The hacker spies on all reaped accounts. Replay the previous transaction once the account is deposited again.
