### ISSUE TITLE
how to fix it 'westend2/db/MANIFEST-141472'

### ISSUE THREAD

**Issue by garysdevil** [paritytech/polkadot#1402]
Version: polkadot 0.8.6-1fc6e5f8-x86_64-linux-gnu
Details: The polkadot stoped because disk became full. Then I expand disk by lvm and restart it , but failed. 
I don't want to sync from 0, can I fix it?
![图片](https://user-images.githubusercontent.com/41293784/87382186-ec7d7f00-c5c8-11ea-9044-add0139e6e51.png)

**Comment by rphmeier** [comment]
I am not an expert on the workings of the DB, but it seems that your DB has become corrupted and re-sync is the most likely option.

**Comment by garysdevil** [comment]
> 
> 
> I am not an expert on the workings of the DB, but it seems that your DB has become corrupted and re-sync is the most likely option.

Ok thank you. I resynced.
