### ISSUE TITLE
Tokio-runtime-worker -  panicked in Version 0.8.14

### ISSUE THREAD

**Issue by m-saxemberg** [paritytech/polkadot#1409]
I'm reporting the following message with the below mentioned version and last block processed. This message was the output of a sentry node and the node itself stopped completely.

2020-07-15 01:28:27 👴 Applying GRANDPA set change to new set with 400 authorites                                                                              
2020-07-15 01:28:27 Re-finalized block #0xd62311f5441ea98df5e9c83bc605872dba84c6
09db30ae3b4908d75ce1b98eb0 (3175348) in the canonical chain, current best finalized is #3175348

Version: 0.8.14-d0e553fe-x86_64-linux-gnu                                       
                                                                                
   0: sp_panic_handler::set::{{closure}}                                        
   1: std::panicking::rust_panic_with_hook                                      
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic$
ing.rs:515                                                                      
   2: std::panicking::begin_panic                                               
   3: sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC>::impo$
t_justification                                                                 
   4: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp
_consensus::block_import::BlockImport<Block>>::import_block
   5: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::b
lock_import::BlockImport<Block>>::import_block
   6: sp_consensus::import_queue::import_single_block_metered
   7: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>
::poll
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Fu
ture>::poll
   9: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::
future::Future>::Output> as core::future::future::Future>::poll
  10: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>
::poll
  11: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core:
:future::future::Future>::poll
  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: std::thread::local::LocalKey<T>::with
  15: futures_executor::local_pool::block_on
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  17: std::panicking::try
  18: tokio::runtime::task::raw::poll
  19: tokio::runtime::blocking::pool::Inner::run
  20: tokio::runtime::context::enter
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
  24: start_thread
  25: clone

Thread 'tokio-runtime-worker' panicked at 'returns Ok when no authority set chan
ge should be enacted; qed;', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src
/libstd/macros.rs:13

This is a bug. Please report it at:

https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
CC @andresilva

**Comment by andresilva** [comment]
@m-saxemberg Do you have more logs on this? Some more log entries before this happened would be helpful. It seems like we tried to import this block twice (which shouldn't have happened). What db are you using?

**Comment by m-saxemberg** [comment]
>Do you have more logs on this? Some more log entries before this happened would be helpful.
They're not available anymore and the node wasn't using the rust debug flag so that's not available either.

>What db are you using?
ParityDB
