### ISSUE TITLE
Guide: Chain API Subsystem

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1415]
A simple subsystem that provides access to chain data via Request/Response.

An initial set of requests:
  * Block hash to number
  * Finalized block number to hash
  * Finalized block number

**Comment by rphmeier** [comment]
Another good one would be an ancestry request which accepts a `(Hash, usize)` returns a `Vec` of the requested number of ancestor-hashes of the requested hash.

#1460 will probably need that.

And all of these request types should be fallible.

**Comment by ordian** [comment]
> Another good one would be an ancestry request which accepts a (Hash, usize) returns a Vec of the requested number of ancestor-hashes of the requested hash.

We could implement that by calling `header().parent_hash` the requested number of times on the client, but maybe there is a more efficient way?

**Comment by rphmeier** [comment]
At the moment, that's the best way to do it without altering the lower-level database schema somehow. We won't need that many ancestors, though.
