### ISSUE TITLE
I was running v0.8.15 for several days. But then it crashed with the following bug:

### ISSUE THREAD

**Issue by iTrouble** [paritytech/polkadot#1434]
Thread 'tokio-runtime-worker' panicked at 'Critical database eror: Custom { kind: Other, error: Error { message: "IO error: While open a file for random read: /home/polkava/.local/share/polkadot/chains/polkadot/db/007060.sst: Too many open files" } }', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/macros.rs:16

**Comment by bkchr** [comment]
How many days was it running?

**Comment by iTrouble** [comment]
First start on 2020-07-17 22:09:09 (Role FULL)

Restart on 2020-07-18 20:36:32 (Role AUTHORITY)

**Comment by redpenguin-validator** [comment]
similar problem for me on v0.8.18
https://github.com/paritytech/polkadot/issues/1451
