### ISSUE TITLE
Implement: Provisioner

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1436]
The provisioner is responsible for answering requests for data from the block authorship proposer. It will largely serve as a go-between that fetches data from the Candidate Backing subsystem at first. This will probably also come with some changes to the candidate backing subsystem and guide.

**Comment by rphmeier** [comment]
The main complication here is going to be around handling occupied-core-assumptions. We might have candidates that are only includable when some bitfields are included. And we might have candidates that are not includable when certain bitfields are included.

When we're choosing bitfields to include, the rule should be simple: maximize availability. So basically, include all bitfields. And then choose a coherent set of candidates along with that.

**Comment by coriolinus** [comment]
I'm sketching out some work on this, but it's very likely that not much will get finished today, and much of Monday is going to be taken responding to reviews of #1458 and #1466. If someone else wants to work on this before then, then they should feel free.
