### ISSUE TITLE
Verification failed for block on v0.8.18 and node crashed

### ISSUE THREAD

**Issue by redpenguin-validator** [paritytech/polkadot#1451]
I found node crashed on v0.8.18. This is what there was in log immediately before the crash:
Verification failed for block 0x50b7e1fe969c90e417ff3c494c2e51fa34b6b9b577bad6b7a7e56fd41d508612 received from peer: 12D3KooWJ4eyPowiVcPU46pXuE2cDsiAmuBKXnFcFPapm4xKFdMJ, "Database: IO error: While open a file for appending: /home/ubuntu/.local/share/polkadot/chains/polkadot/db/1646695.log: Too many open files"
Thread 'tokio-runtime-worker' panicked at 'Can't read /proc/: Os { code: 24, kind: Other, message: "Too many open files" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/netstat2-0.8.1/src/integrations/linux/procfs.rs:6

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
Should be fixed with the latest version.
