### ISSUE TITLE
Implement past-session validator discovery APIs for Network Bridge

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1461]
#1452 introduced some APIs for the network bridge to enable validator discovery. Those APIs are open for discussion, but the information provided by them should stay pretty much the same: a way to signal to connect to particular validator IDs and learn the `PeerId`s associated with that set so as to be aware of when we are connected to those validators.

**Comment by rphmeier** [comment]
Related: https://github.com/paritytech/substrate/issues/6595#issuecomment-664252786 but this is probably not a blocker.

Note that the network-bridge API will accept `ValidatorId`s, which we need to transform into the authority-discovery session keys somehow.

**Comment by tomaka** [comment]
> Note that the network-bridge API will accept ValidatorIds, which we need to transform into the authority-discovery session keys somehow. A runtime API might be the best way to do that.

Having no knowledge of the runtime nor about the various types of keys, I'd appreciate some help from someone here.

**Comment by rphmeier** [comment]
The `ValidatorId->AuthorityDiscoveryKey` we can handle on parachains-core side; what we need is a networking API accepting `AuthorityDiscoveryKey`s.to that we can implement `ConnectToValidators` in the [`NetworkBridge`](https://w3f.github.io/parachain-implementers-guide/node/utility/network-bridge.html).

**Comment by tomaka** [comment]
The way I see things are laid out in my mind is:

- The `NetworkBridge` would own some sort of `AuthorityDiscoveryService` (see [this PR](https://github.com/paritytech/substrate/pull/6760)) in addition to the `sc_network::NetworkService` it already has.
- Whenever a peer connects, the `NetworkBridge` can look up from that `AuthorityDiscoveryService` the `AuthorityDiscoveryKey` potentially associated to the `PeerId` we have just connected to.
- At the start of each rotation N, the `NetworkBridge` would look up from the `AuthorityDiscoveryService` the addresses and `PeerId`s of the parachain-assigned validators of rotation N and N+1, then call `NetworkService::set_priority_group("collation", that_list)`.

The authority-discovery module ensures, at any time, that it holds the `PeerId`s and addresses of all the validators of the current session/epoch and of the next one.
(at the moment, it only works with the current session, see https://github.com/paritytech/substrate/issues/6772)

**Comment by rphmeier** [comment]
I'd rather not have the network bridge be directly responsible for dealing with rotations but rather just receive requests to connect to validators based on validator IDs.

This feature is not only for collator networking, but it is our first major use-case of it. We also need this to make PoV Distribution production-ready and for recovery of availability pieces for approval

**Comment by mxinden** [comment]
Like Pierre above, I am in favor of the `NetworkBridge` to first query the authority discovery [`Service`](https://github.com/paritytech/substrate/pull/6760/files#diff-c3332dfa5c66645a3f312396bad23529R27) for the `Multiaddr`s of the authorities and then pass these on via the `NetworkService` to the peerset.

With the above we would separate concerns, as in the authority discovery only being concerned with discovering authorities.

Within `NetworkBridge`'s event handling matching events from other subsystems:

```rust
ConnectToValidators(validators: Vec<AuthorityId>) => {
  let multiaddress = validators.into_iter()
    // `get_addresses_for_authority_id` accesses the cached addresses, thus the `await` does not take long.
    .map(|id| self.authority_discovery.get_addresses_for_authority_id(id).await)
    .filter(|addresses| addresses.is_some())
    .collect::<HashSet<_>>();

  self.network.set_priority_group(COLLATOR_PRIORITY_GROUP_NAME, multiaddresses)?;
}
```

Within `NetworkBridge`'s event handling matching events from the underlying network:

```rust
sc_network::event::Event::NotificationStreamOpened { remote, .. } => {
  let authority_id: Option<AuthorityId> = self.authority_discovery.get_authority_id_for_peer_id(remote).await;
  return NetworkBridgeEvent::PeerConnected {
    authority_id,
    peer_id: remote,
  };
}
```

What do you think @rphmeier?

**Comment by rphmeier** [comment]
That proposal breaks the abstraction that the network bridge provides substantially.

With my proposal, the network bridge doesn't need to track validator rotations (which the subsystems would have to do anyway) or the peer-sets that would be interested in any particular validator connection - this is also the responsibility of the subsystem.

The first snippet is fine, because the actual API takes a `PeerSet` parameter. But the second snippet is not correct because it doesn't account for rotations.

**Comment by rphmeier** [comment]
We have the following networking subsystems which would heavily benefit from point-to-point networking between validators:
  * Collator Protocol
  * Availability Distribution
  * Availability Recovery
  * PoV Distribution

All of these, except Availability Recovery, are what I'd call "immediate" because they only have to deal with validators of the current session. 

However, Availability Recovery may need to perform recovery of data from prior sessions. If we allow disputes for up to a day after inclusion, then that would be 4 full sessions. At the session boundary, validators can both change their keys or even leave the set.

We will need some kind of discovery mechanism for associating old `AuthorityId`s with current Peer IDs. We will also want authorities to publish their addresses under not only their most recent `AuthorityId` but also their `AuthorityId`s for the last `N` sessions. There should be some glue in the authority discovery logic that we can fill out with blockchain-specific logic for determining our set of authority IDs. i.e. the authority discovery could be dependent on a `Box<Fn() -> Vec<AuthorityId>>` which yields all the authority IDs it should attempt to see if it has control over and sign messages with.

**Comment by mxinden** [comment]
Implementation for address lookups of past sessions as described above is tracked in https://github.com/paritytech/substrate/issues/6910.

**Comment by rphmeier** [comment]
@ordian is this addressed by #1699?

**Comment by ordian** [comment]
@rphmeier right, but only for the validators in the current session

if we'll find a way to circumvent as you mentioned in https://github.com/paritytech/polkadot/pull/1699#discussion_r486389522, we can close the issue

**Comment by rphmeier** [comment]
Triage: session info makes this possible for other sessions. current session already implemented and functioning. Shifting milestone.
