### ISSUE TITLE
Implement: Collation Generation Subsystem

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1464]
cc @bkchr @cecton - this is the point where we will integrate Cumulus into the Overseer/Subsystem configuration of node-side code. As such, it's open to the Cumulus team to implement as well.

Depends on #1452

**Comment by bkchr** [comment]
Whoever will implement this, please get in touch with me and @cecton :)

**Comment by rphmeier** [comment]
We might want to set this up so that it's initialized with a message passed in from an external source via the overseer. That would make set-up of the Cumulus node easier, since it can go in these three steps:
  * Set up Polkadot node
  * Set up Cumulus node wrapping Polkadot node
  * Send a message to the Collation Generation Subsystem giving a trait object wrapping the Cumulus node

And I assume we should write this subsystem as a wrapper around a trait object for convenience in this respect as well.

**Comment by bkchr** [comment]
Sounds good :)
