### ISSUE TITLE
protocol::tests::erasure_fetch_drop_also_drops_gossip_sender is flaky

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1474]
See discussion beginning [here](https://github.com/paritytech/polkadot/pull/1466#issuecomment-664333834).

Demonstration: of the most recent 5 (at the time of writing) commits to `master`, 2 of them timed out on that test. Both of those passed that test as PRs.

![Screenshot from 2020-07-27 15-51-32](https://user-images.githubusercontent.com/7822926/88549915-30d53a00-d021-11ea-8de1-c43b5b9258c2.png)

**Comment by rphmeier** [comment]
This can be taken care of by just removing the `polkadot-network` crate, which we'll be able to do soon.
