### ISSUE TITLE
rocksdb build script fails in clang-sys with: function not loaded: clang_createIndex

### ISSUE THREAD

**Issue by joshtriplett** [paritytech/polkadot#1476]
I tried to compile polkadot on latest Debian sid. 

I installed `clang`, `pkg-config`, and `libssl-dev`, and then ran `cargo install --git https://github.com/paritytech/polkadot polkadot`.

That resulted in this error:

```text
error: failed to run custom build command for `librocksdb-sys v6.7.4`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installhZ9LCD/release/build/librocksdb-sys-d487ffd7e62de0a3/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs

--- stderr
thread 'main' panicked at 'function not loaded: clang_createIndex', /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/lib.rs:1659:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ordian** [comment]
The error comes from https://github.com/rust-rocksdb/rust-rocksdb, maybe `llvm` package is missing?

**Comment by joshtriplett** [comment]
I have llvm-dev installed, in addition to all the packages mentioned in the README.

**Comment by joshtriplett** [comment]
Ah, figured it out. In addition to the packages in the `README`, building polkadot also requires installing `libclang-dev`. With that installed, it builds.

**Comment by ordian** [comment]
Would you mind submitting a PR? :)

**Comment by danforbes** [comment]
Can we solve this problem by linking to the https://getsubstrate.io script?

**Comment by joshtriplett** [comment]
Having an actual list of dependencies is helpful, rather than just a script. The script could certainly go at the top as a quick-start, but then the documentation should still list the actual dependencies required and the build command to run once you have those dependencies.

**Comment by danforbes** [comment]
Absolutely, Josh - thanks for that feedback. I'll work on whipping up some enhanced documentation :rocket: Thanks for raising this issue :pray:
