### ISSUE TITLE
Refine handling of lower-level Wasm validation errors for Candidate Validation Subsystem

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1477]
Currently we have a blanket `ValidationFailed` type which indicates all types of errors.

The mapping that we have from `wasm_executor::Error` to `ValidationFailed` or `ValidationResult::Invalid` also needs refinement.

It would be better to have more variants under `ValidationFailed` and to go through the `wasm_executor::Error` enum to determine which variants should be treated as the candidate being invalid and which variants imply an internal error of some kind. The rule of thumb to use is: if we treat the candidate as invalid, we should expect that validators will issue signed statements to that effect. So it shouldn't encompass any spurious errors.

**Comment by rphmeier** [comment]
@arkpar Is this one you can help on?

**Comment by arkpar** [comment]
As far as I see `ValidationFailed ` is generated only on internal errors.  Any error in `wasm_executor::Error` and therefore `ValidationFailed `should be treated as (possibly fatal) host error, and not as invalid candidate. The actual result that tells if the candidate is valid or not is contained in the `ValidationResult` type.

**Comment by rphmeier** [comment]
@arkpar `wasm_executor::Error::BadReturn` should be invalid parachain block, though, right? What about `TimedOut`?

**Comment by rphmeier** [comment]
@arkpar 

> ValidationFailed should be treated as (possibly fatal) host error, and not as invalid candidate.

I agree with this, and it is the goal of the issue, but I disagree with

> Any error in wasm_executor::Error

having the same property. The reason is that `wasm_executor::validate_candidate` returns `Result<PrimitiveValidationResult, wasm_executor::Error>` and `ValidationResult` contains all the outputs of a successful validation. So clearly there is another option beyond successful validation and internal error, and all of those options are encompassed by `wasm_executor::Error` somewhere. Just looking to find out which variants should indeed be mapped to `ValidationResult::Invalid`.

Yes, the naming is confusing...`PrimitiveValidationResult != ValidationResult` on the higher level...

**Comment by arkpar** [comment]
@rphmeier I see your point. `wasm_executor::Error` should be handled differently indeed. We will also have to assume that all of the wasm host functions are infallible. I.e. you can't get an IO error when accessing proof storage. If a host function panics for whatever reason this will be considered an invalid candidate.  Anyway, some changes to out-of-process error handling are required. Currently all errors are marshaled between processes as string. Might be a good idea to scale-encode them instead.

**Comment by burdges** [comment]
https://github.com/paritytech/polkadot/issues/1269#issuecomment-667650052

**Comment by rphmeier** [comment]
@burdges Yeah, I guess we'd expose those failure variants at this level so the higher-level code can make a decision on how to vote. I think we can make the conclusion that we don't want to issue `Invalid` statements on time-out. We can add a different type of statement encompassing further statements for the approval phase.

**Comment by burdges** [comment]
Any thoughts about the two timeout solution I suggest there?
