### ISSUE TITLE
Parachain/thread swapping

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1509]
The old registrar removed in #1501 allowed the ability to swap parachains/threads. This kept the ID stable but swapped ownership of all deposits and removed any parathread scheduling.

The `Paras` and `Scheduler` modules need to be amended to support swapping. Swaps should occur only at session boundaries and only one swap per `ParaId`. It could be implemented by simply swapping within the `Paras` module and then making sure the `Scheduler`'s `initializer_on_new_session` handler clears all entries from the `ParathreadQueue` which are not parachains - previously, this was not possible, but a thread<->chain swap makes it a case to account for.

**Comment by rphmeier** [comment]
This is addressed by #2406 to an extent?

**Comment by shawntabrizi** [comment]
From what I can read in the description of this issue, this should be fixed by #2406
