### ISSUE TITLE
Create a parathread auction module for collators to bid on parathread slots

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1512]
This functionality was already implemented as a `SignedExtension` in [the old Registrar](https://github.com/paritytech/polkadot/blob/3b6235793971bb4904b0d44cde1984b9925cab5c/runtime/common/src/registrar.rs#L592) prior to #1501. The same logic should be ported over here, except wrapping around the `Paras` and `Scheduler` modules. This should live in `polkadot-runtime-common` as it is "glue" code and not core code.

**Comment by coriolinus** [comment]
As I'm reading through this, I find myself getting more and more confused. What does this line even mean?

https://github.com/paritytech/polkadot/blob/3b6235793971bb4904b0d44cde1984b9925cab5c/runtime/common/src/registrar.rs#L616

That sure looks like it's using a function call as the receiver of an `if let` binding, which just doesn't make any sense to me.

**Comment by coriolinus** [comment]
Guessing that this has to do with macro magic by which `Call::select_parathread` is somehow simultaneously an enum variant and an actual function. (Apropos of external discussion: this does not feel like responsible use of great power.)

If I'm reading the code properly, the registrar code didn't actually implement any kind of priority queue selection mechanism which would make it an auction; it was more of a first-come, first-served parathread registration thing. This leads to two questions:

- If I'm reading the code incorrectly, where is the actual auction logic with bids etc?
- If I'm reading it correctly, should the new module allow competing parathreads to competitively bid on slots, or just do the same registration stuff that the existing code does?

**Comment by shawntabrizi** [comment]
@coriolinus you are correct that this is both an enum variant and a function name. Something that is mostly needed to be able to get a list of the possible functions in a module.

The way the auction works is through the "priority" of the tx. The TX queue order txs by priority, and one direct way a user can increase their priority is including a `tip`, which is some extra fee that is paid to the blockchain (and split between treasury and block producer).

So users who want to make their way into the auction must have the highest tip, thus forming a 1 block auction.

I talk about this at a high level including the signed extension here: https://youtu.be/95Ji5u0q3AU?t=1004

**Comment by coriolinus** [comment]
@shawntabrizi Thanks for the link! Watching that now.

**Comment by burdges** [comment]
We've found one cute trick that improves auction fairness:

We run auctions as currently planned:  We bid over some babe epochs x, x+1, ..., y.  After y, we take the epoch randomness output by y for epoch y+1, compute a function f(y) that samples a slot uniformly from epoch y.

We initially implement f(y) inside the runtime with a simple hash function, but we keep f kinda modular by isolating running f inside one relay chain block, and delay beginning the slot by at least one babe epoch.  

We might later decide auctions require more fairness.  If so, then we replace f off-chain with a 10 min VDF computation, and replace f on-chain with verifying a VDF verification posted in a relay chain block, which sounds fast enough to do inside the runtime.  If we make this change, then all auction participants should run this off-chain VDF program to determine if they won or not, and the winner can post their victory transaction on-chain.

**Comment by rphmeier** [comment]
@shawntabrizi still needed?

**Comment by shawntabrizi** [comment]
Yes, it is needed

**Comment by rphmeier** [comment]
#5492 outdates this
