### ISSUE TITLE
Revert reversion of authority-discovery enabling

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot#1544]
https://github.com/paritytech/polkadot/pull/1532 should be reverted again.
I don't know under which criteria, though.

**Comment by andresilva** [comment]
I don't really have a suggestion for expected absolute numbers, but certainly spawning 4k sockets so that we can connect to an extra 10 authorities is excessive (I know it's because of the DHT querying). With authority discovery enabled the lower bound for the number of sockets on my local node was about 1.4k sockets. We should try to reduce this number before re-enabling it.

**Comment by tomaka** [comment]
cc https://github.com/paritytech/substrate/issues/5612

**Comment by mxinden** [comment]
Documenting insights looking at the metrics of a single sentry node running with `--enable-authority-discovery`:

- Successful lookup ups are fast. They are either served right from the local cache (< 2 secs) or quickly looked up (~< 20 secs). See yellow line below.

- Eventually failing lookups are the slow ones. The 95th percentile is around 1 minute. See blue line below.

- For the reference number of TCP connections in green (scaled down by `/ 100`).


![image](https://user-images.githubusercontent.com/7047859/90254439-036ef580-de43-11ea-9719-ce6d7ac11029.png)

**Comment by mxinden** [comment]
> Unfortunately I don't know what the threshold is before validators start complaining about reaching the limit.

I have asked the validator community what the file descriptor limit on their nodes is. Sadly only 2 reported back. Both of them had a hard limit of `1_048_576` and a soft limit of `1024`. Given that Substrate sets the soft limit to the hard limit (see https://github.com/paritytech/polkadot/issues/1544#issuecomment-678186782) the latter can be ignored.

In addition I reached out to our internal operations team. Our nodes are running with a hard limit of `524_288`.

With the above in mind and the fact that the amount of connections initiated through authority discovery is below 10_000 I am having difficulties understanding how the authority discovery module exhausted the file descriptor limit of a node.

---

As suggested above I would like to enable the authority discovery module on all Parity nodes once a new Polkadot version with libp2p 0.24.0 (https://github.com/paritytech/substrate/pull/6891) is released. In case those nodes are running without issues I will prepare a pull request reverting https://github.com/paritytech/polkadot/pull/1532 thus the authority discovery module being enabled by default. With https://github.com/paritytech/substrate/pull/6946 Prometheus will alert us once the number of file descriptors on our nodes is high.
