### ISSUE TITLE
Parachain Auction Mechanism does not account for the fact that DOTs are locked before the slot lease begins.

### ISSUE THREAD

**Issue by lucasvo** [paritytech/polkadot#1551]
It seems like the slot auction mechanism only optimizes for DOTs locked during the lease of the slot. When someone places a bid on a future period (not the one immediately starting after the auction)  the DOTs are locked up from the end of the auction to the end of the slot. 

Here's an extreme example:
```
| Bidders | P1 | P2 | P3 | P4 | Bid | Locked Value |
|---------|----|----|----|----|-----|--------------|
| Alice   | x  | x  | x  | x  | 10  | 40           |
| Bob     |    |    |    | x  | 15  |  15          |
```
This is because the current implementation counts Bob's 15 DOTs only for one period (P4). Upon winning the auction though Bob's tokens are not unlocked and remain locked until the slot lease starts. Therefore looking at the economics it should actually look like this: 

```
| Bidders | P1 | P2 | P3 | P4 | Bid | Locked Value |
|---------|----|----|----|----|-----|--------------|
| Alice   | x  | x  | x  | x  | 10  | 40           |
| Bob     | r  | r  | r  |  x | 15  |  60          |
```

This becomes more complicated when you take into account that a single account can place multiple bids:

```
| Bidders | P1 | P2 | P3 | P4 | Bid | Locked Value |
|---------|----|----|----|----|-----|--------------|
| Alice   | x  | x  | x  | x  | 10  | 40           |
| Bob     | r  | r  | r  | x  | 15  | 60           |
| Charlie | x  | x  |    |    | 5   | 10           | 
| Charlie |    |    | x  |    | 20  | 20           | 
| Charlie |    |    |    | x  | 15  | 15           | 
```

In this example the locked value as calculated by the current implementation reports 45 for Charlie even though it should report 75.

```
P1: 20 total (5 in lease, 15 locked for P3)
P2: 20 total (5 in lease, 15 locked for P3)
P3: 20 total (20 in lease, none locked)
P4: 15 total (15 in lease)
= 75 total
```

It seems like this could lead to some weird incentives that are not intended. Specifically @xlc mentioned that that likely it is easier to get people to commit to locking up DOTs for 1yr than 2yrs so a scenario where you would only bid a specific amount for one year and then a much lower amount for the second year. If this was your strategy then you would have a significant advantage over someone else bidding on a slot that only started 1 year from now as you don't have to pay the cost of inflation for the first year while your dots are locked but the current mechanism doesn't count it towards your bid. 

I think the current design is not fundamentally broken and it seems that the only effect it will have is that it will make bidding on slots that don't start immediately less attractive. That by itself doesn't seem like a big issue but I wanted to document this scenario and ask if this was every discussed when coming up with the design?

Especially because it seems like correcting the optimization function to count locked dots from the beginning (auction end) should be trivial.

**Comment by lucasvo** [comment]
Link to the relevant code: https://github.com/paritytech/polkadot/blob/master/runtime/common/src/slots.rs#L823

**Comment by lucasvo** [comment]
The code mentions the original implementation was made by Al. Tagging you here @alistairstewart

**Comment by AlistairStewart** [comment]
I only wrote the reference implementation, which didn't deal with locking. This code was witten by gavofyork . It should not be possible for Charlie to bit on ranges that are not either intersecting or contiguous (and I think this code only allows intersecting ranges currently), which means that your example is impossible.

The complexity of implementing this is that we don't know if Bob already has those tokens locked up for parachain slots or not, in which case they shouldn't count more.

I'm not convinced that changing this is a good idea. One example where I'm not sure if it is, is the following:

```
| Bidders | P1 | P2 | P3 | P4 | Bid | Locked Value |
|---------|----|----|----|----|-----|--------------|
| Alice   | x  | x  | x  |    | 10  | 40           |
| Bob     |    |    |    | x  | 15  | 60 or 15?    |
| Bob     | x  | x  | x  | x  | 15  | 60           | 
```

Now it is not in Bob's interest if his bid on P4 alone is considered as valuable as the one on P1-P4, because he does not win the entire period with your change, but instead Alice wins P1-P3 and Bob wins P4. On the other hand, with the current logic, Bob might bid this way to ensure that he would still get P4 even if Alice raised her bid on T1-T3 to 20.

**Comment by shawntabrizi** [comment]
>  It should not be possible for Charlie to bit on ranges that are not either intersecting or contiguous

I can confirm this is the case in the pallet code.

* When submitting a bid, we only allow starting period and ending period as input, so any bid will be contiguous.

* When checking the submitted bid, we confirm it overlaps with any existing bids: https://github.com/paritytech/polkadot/blob/master/runtime/common/src/slots.rs#L761

**Comment by AlistairStewart** [comment]
>     * When submitting a bid, we only allow starting period and ending period as input, so any bid will be contiguous.

The contigous case I meant that is not allowed by the code is when the ranges in different bids are adjacent e.g.  Charlie bids on P1-P2 and P3. In this case it is ok for Charlie to win both. The case we wanted to avoid is a bidder winning ranges with gaps. So the condition could be relaxed from what is currently coded.

**Comment by lucasvo** [comment]
@AlistairStewart good point on requiring continuous bids. I think however this scenario still works, Charlie is bidding on P1-P2, P3, P4:

```
| Bidders | P1 | P2 | P3 | P4 | Bid | Locked Value |
|---------|----|----|----|----|-----|--------------|
| Alice   | x  | x  | x  | x  | 10  | 40           |
| Bob     | r  | r  | r  | x  | 15  | 60           |
| Charlie | x  | x  |    |    | 5   | 10           | 
| Charlie |    |    | x  |    | 20  | 20           | 
| Charlie |    |    |    | x  | 15  | 15           | 
```

I think there is one optimal solution purely from a standpoint of locking the most amount of DOTs:
P1-P2: Charlie, P3: Charlie - Locks 3x20 DOTs (i.e. 60 DOTs locked for one period)
P4: Bob - Locks 4x15 DOTs (60 DOTs locked for one period)

If P1-P4 were awarded all to Charlie it would only result in 60 DOTs less locked. I think looking at this in isolation though is not very helpful. What the current system does is it heavily favors a single account to place several continuous bids over different accounts bidding independently for later segments even at a loss for Polkadot. I think all in all this is an acceptable bias if we want to favor stability: the same account (or chain) gets a slot for longer.

**Comment by shawntabrizi** [comment]
@lucasvo your example would not be allowed with the auction pallet.

> When checking the submitted bid, we confirm it must overlap with any existing bids: https://github.com/paritytech/polkadot/blob/master/runtime/common/src/slots.rs#L761

So this would be allowed:

Since charlie's 2nd and 3rd bid do not intersect with anything, the bid would not be allowed.

This would be allowed:

```
| Charlie | x  | x  | x   |    | 5   | 10           | 
| Charlie |    | x   | x  | x   | 20  | 20           | 
| Charlie |    |    |  x  | x  | 15  | 15           | 
```

This would not

```
```
| Charlie | x  | x  | x   |    | 5   | 10           | 
| Charlie |    | x   | x  | x   | 20  | 20           | 
| Charlie |    |    |    | x  | 15  | 15           |

**Comment by AlistairStewart** [comment]
@shawntabrizi  One point that I was trying to make is that the current code is perhaps too restrictive. It should be ok for Charlie to win any range, even if that means winning two bids. If  your example were valid,  Charlie could not win anything with a gap.

@lucasvo , you didn't answer any of my other points. Namely that Bob can sabotage his own bids on longer ranges, and that we would have to differentiate between freshly locked DOTs and those already locked for earlier auctions.

**Comment by rphmeier** [comment]
closing as stale - seems that this may still be relevant but also introduces complexity in implementation
