### ISSUE TITLE
Inclusion and heavy blocks

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1555]
In Substrate there are some heavy operational extrinsics or other stuff that consumes the whole block weight.

For example, if governance enacts a new runtime upgrade, then it consumes the whole block worth of weight. At the same time, the inclusion inherent currently is required thus all the parachain processing is mandatory.

I wonder if it can lead to problems and if we should allow not skip inclusion if there is a lot of work scheduled in the block already?

**Comment by burdges** [comment]
I'd think runtime upgrades could be handled through the availability system, so first a parathread-like block publishes the upgrade across the validator set, and then your extrinsics triggers some _slow_ reconstruction by all validators.  We'd equalizes the work this way and availability avoids being quite so paranoid about everyone obtaining the upgrade when initially published. 

We've other systems like Phragmen for which one wants custom off-chain logic, unrelated to availability, but usually parathread-like. 

We could delay inclusion of course but approval checks should be our heaviest functionality, not inclusion per se.  A priori, backing requires checking at most one candidate per relay chain block, while approval checks should require checking like 4+ candidates per relay chain block.  We've some slack in approval checks but it gets complicated, so yeah maybe delaying inclusion for the purpose of delaying approval checks uniformly makes sense, not sure.

**Comment by rphmeier** [comment]
> I wonder if it can lead to problems and if we should allow not skip inclusion if there is a lot of work scheduled in the block already?

Yeah, that's a good point. That would be done an improvement to the proposer, where if we have a high expected weight we'll provide an empty `InherentData`.
