### ISSUE TITLE
Build on `Occupied` cores when we have enough bitfields

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1573]
I suggest we file the whole `Occupied` case for later. The exact logic that we want to employ here is going to need design of its own, because we won't want collators to wait for bitfields as a heuristic as to whether they should create a new block or not. The reason for that is that we want backing validators to have as much time to validate as possible.

AFAIK the `CandidateBacking` subsystem doesn't handle the non-`Scheduled` case anyway

_Originally posted by @rphmeier in https://github.com/paritytech/polkadot/pull/1557_

**Comment by burdges** [comment]
Yes.  

We should discuss the opposite direction eventually too:  A backing validator or relay chain block producers might apply roughly a parachain fork choice rule by not excluding or even just selecting a block with more descendants.  Are forks limited to 1-2 block length differences or something?  I suppose no..
