### ISSUE TITLE
Expose token decimals 

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#1593]
Currently various runtime are having different number of decimals, Westend/Kusama/Rococo is 12, Polkadot is going to be 10, the default local one is 15 (I think it is hardcoded in polkadot.js?)

This makes an issue for parachain to deal with relaychain tokens. Acala is going to have parachains connecting to Polkadot, Kusama, Rococ, and local devnet. Currently Acala internal logics assumes the all token decimals is 18 so we need to scale up / down for relaychain tokens on cross-chain boundaries.

This is our current incorrect conversion code
https://github.com/AcalaNetwork/Acala/blob/cdc802bca57342d856a17b8a92a67c66b9feed6f/runtime/src/lib.rs#L1033-L1049

**Comment by rphmeier** [comment]
What would the best way to expose the token decimals be? Substrate chains don't necessarily have a `Balances` module.

**Comment by emielvanderhoek** [comment]
> 
> 
> What would the best way to expose the token decimals be? Substrate chains don't necessarily have a `Balances` module.

Perhaps a runtime constant in the balance module. That would ensure inclusion in metadata for any runtime.

**Comment by xlc** [comment]
The quick way is just expose a constant in runtime like how the BalancesCall is exposed

https://github.com/paritytech/polkadot/blob/25bf025be9657a2a58ed8f8853671d53e1353849/runtime/polkadot/src/lib.rs#L69

**Comment by emielvanderhoek** [comment]
Summarized thee three values can currently only be retrieved from the Substrate-Client.
The proposed change would embed these three variables/values in the runtime's metadata.

**Comment by rphmeier** [comment]
(stale, out of scope)
