### ISSUE TITLE
Is there a detailed RPC call document containing the request and return

### ISSUE THREAD

**Issue by OctoberSouth** [paritytech/polkadot#1608]

**Comment by bkchr** [comment]
@lamafab was there something in the spec about the RPC calls?

**Comment by OctoberSouth** [comment]
https://polkadot.js.org/api/substrate/rpc.html   This is only a rough idea, not clear how to use it

**Comment by OctoberSouth** [comment]
For example, which interface to use to get transaction details

**Comment by lamafab** [comment]
@bkchr @OctoberSouth We have an open draft in the [PSP repo](https://github.com/w3f/PSPs/pull/6). The document can be seen here:

https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md

This was created quite a while ago, some API calls are missing (such us the child storages).

**Comment by OctoberSouth** [comment]
How do I get transaction details @lamafab

**Comment by bkchr** [comment]
@OctoberSouth what you mean by transaction details?

**Comment by OctoberSouth** [comment]
such as how to generate an address, how to obtain the payer and payee in the transaction information @bkchr

**Comment by tinshen** [comment]
@bkchr hi bro，we all  need   transaction details by the rpc.

**Comment by bkchr** [comment]
@danforbes @JoshOrndorff could one of you help here?

**Comment by danforbes** [comment]
There is an open issue related to this: https://github.com/substrate-developer-hub/knowledgebase/issues/56
