### ISSUE TITLE
Guide: Deposits Module

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1617]
We want a module that handles all deposits: parachain, parathread, XCMP, HRMP. At the moment, these are all spread across many modules.

We can give each parachain an account in `Balances` and use locks to keep the deposits locked. Locks in Balances are allowed to overlap, so two locks of 2000 and 1000 each would have the same effect as a single lock of 2000, not a single lock of 3000. This implies that we should maintain a single lock per parachain account. Paras should also be able to set the address that the deposit is returned to when it offboards. 

The intent is to update the `slots` module (parachain candle auctions) so it uses the deposits module to handle its deposits.

**Comment by rphmeier** [comment]
@pepyakin @shawntabrizi needed or outdated?

**Comment by shawntabrizi** [comment]
Right now, all deposits are independently tracked in the separate modules.

We use reserves, not locks, so there is no worry about overlapping balances not being tracked.

We do NOT want to allow reserved balances to be sent elsewhere through offboarding. This could lead to a backdoor allowing transfers to happen to accounts with transfer locks or that funds would not make their way back to the right users (for example in a crowdloan).

So I think this is outdated design unless there are reasons for wanting things done this way.
