### ISSUE TITLE
Get v1 Rococo running on a localnet

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1620]
At this point, we should have implemented enough v1 code that it's possible to get a Rococo localnet up and processing transactions. The point of this issue is to document the progress actually doing so.

Initial state: [`polkadot/runtime/rococo-v1/src/lib.rs`](https://github.com/paritytech/polkadot/blob/8c881e4/runtime/rococo-v1/src/lib.rs)

End state: it is possible to run a multi-node local network which uses no v0 components. There are at least two relay chain validators in this net, and one parachain collator. There is a human-readable script which guides a user though this process. Optional: there is a bash, python, or docker script which automates this process. 

Future work: expand the number of local nodes and parachains. The ultimate goal is to run a fully-distributed rococo network on independent hardware supporting 100 independent parachains.

Related work: https://github.com/paritytech/cumulus/pull/67

---

- [x] delete old `/service` crate
  - [x] except the various chain specs
- [x] use the `/node/service` crate in its place
- [ ] plug in the various real subsystems into `fn real_overseer`
- [ ] get versions of `chain_spec.rs` and the CLI definitions from `rococo-branch`; ensure they're up to date

**Comment by rphmeier** [comment]
This is working, I believe, barring some known errors in Cumulus.
