### ISSUE TITLE
reserved-only flag is ignored

### ISSUE THREAD

**Issue by subtly** [paritytech/polkadot#1625]
I am running two polkadot nodes, one with paritydb and one with rocksdb. I would like to have these nodes connected, but prevent the second node from connecting to the public network. To do this I ran the second node with reserved-only:

```
./target/release/polkadot -d /path/to/data --listen-addr /ip4/x.x.x.y/tcp/12345 --pruning archive --reserved-nodes /ip4/x.x.x.z/tcp/30333/p2p/12D3KooW... --no-telemetry --no-prometheus --no-mdns --reserved-only
```

When running with --reserved-only, logs show there is only 1 peers, however the node still establishes arbitrary connections to arbitrary peers. Output shows only one peer connected in logs, but network connectivity from a tool like netstat or lsof shows a significant amount of network connectivity (over 150 established network connections).

I'm guessing that its still running a discovery process? Is there a way to disable the discovery process?

If so, a flag to disable discovery would be beneficial so that testing and local-only nodes don't pollute public network with discovery.

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
If I understand correctly, that'd be https://github.com/paritytech/substrate/issues/6031
If so, we can close as duplicate?
