### ISSUE TITLE
cargo install --force --git https://github.com/airalab/robonomics --tag v0.21.0 node-cli

### ISSUE THREAD

**Issue by redeyeSPB** [paritytech/polkadot#1626]
Do you still have the issues?

_Originally posted by @bkchr in https://github.com/paritytech/polkadot/issues/250#issuecomment-500863766_

cargo install --force --git https://github.com/airalab/robonomics --tag v0.21.0 node-cli

Compiling polkadot-service v0.8.22 (https://github.com/paritytech/polkadot?branch=rococo-branch#29e799da)
error: could not compile `polkadot-service`.
Caused by:
  process didn't exit successfully: `rustc --crate-name polkadot_service --edition=2018 /home/g9280101/.cargo/git/checkouts/polkadot-4038f27d5
e4ea2e8/29e799d/service/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,lin
k -C opt-level=3 -Cembed-bitcode=no --cfg 'feature="av_store"' --cfg 'feature="consensus"' --cfg 'feature="db"' --cfg 'feature="default"' --cf
g 'feature="full-node"' --cfg 'feature="polkadot-network"' -C metadata=f0c57b228a85bef8 -C extra-filename=-f0c57b228a85bef8 --out-dir /tmp/car
go-installzBhvr2/release/deps -L dependency=/tmp/cargo-installzBhvr2/release/deps --extern frame_benchmarking=/tmp/cargo-installzBhvr2/release
/deps/libframe_benchmarking-74b26c2bc7e1d1c6.rmeta --extern system_rpc_runtime_api=/tmp/cargo-installzBhvr2/release/deps/libframe_system_rpc_r
untime_api-3e643b2cf6c80f36.rmeta --extern futures=/tmp/cargo-installzBhvr2/release/deps/libfutures-984f1b33ac966a6b.rmeta --extern hex_litera
l=/tmp/cargo-installzBhvr2/release/deps/libhex_literal-adfc2646b3dbeabb.rmeta --extern kusama_runtime=/tmp/cargo-installzBhvr2/release/deps/li
bkusama_runtime-f1f88925afb10d60.rmeta --extern lazy_static=/tmp/cargo-installzBhvr2/release/deps/liblazy_static-53201e5af8cd3135.rmeta --exte
rn log=/tmp/cargo-installzBhvr2/release/deps/liblog-d62f4447e0f5f5e8.rmeta --extern pallet_babe=/tmp/cargo-installzBhvr2/release/deps/libpalle
t_babe-554d31bc99c2e48a.rmeta --extern im_online=/tmp/cargo-installzBhvr2/release/deps/libpallet_im_online-ebe8addb2ada93b2.rmeta --extern pal
let_staking=/tmp/cargo-installzBhvr2/release/deps/libpallet_staking-058fa9839a080312.rmeta --extern pallet_transaction_payment_rpc_runtime_api
=/tmp/cargo-installzBhvr2/release/deps/libpallet_transaction_payment_rpc_runtime_api-001b5e0184cdd4a4.rmeta --extern codec=/tmp/cargo-installz
Bhvr2/release/deps/libparity_scale_codec-00e6e5e862f6df59.rmeta --extern parking_lot=/tmp/cargo-installzBhvr2/release/deps/libparking_lot-4955
5444f2a96264.rmeta --extern av_store=/tmp/cargo-installzBhvr2/release/deps/libpolkadot_availability_store-0b23d6e5d0a6526d.rmeta --extern polk
adot_network=/tmp/cargo-installzBhvr2/release/deps/libpolkadot_network-a3e70947fcfe131c.rmeta --extern polkadot_primitives=/tmp/cargo-installz
Bhvr2/release/deps/libpolkadot_primitives-da0fb1426d4b13c6.rmeta --extern polkadot_rpc=/tmp/cargo-installzBhvr2/release/deps/libpolkadot_rpc-6
2692b2e2abe9dca.rmeta --extern polkadot_runtime=/tmp/cargo-installzBhvr2/release/deps/libpolkadot_runtime-bb7c58a3181a43b0.rmeta --extern cons
ensus=/tmp/cargo-installzBhvr2/release/deps/libpolkadot_validation-a7ea2513072a2250.rmeta --extern rococo_runtime=/tmp/cargo-installzBhvr2/rel
ease/deps/librococo_runtime-0d88310b3c83b4de.rmeta --extern authority_discovery=/tmp/cargo-installzBhvr2/release/deps/libsc_authority_discover
y-48fbabac9dfc6e88.rmeta --extern sc_block_builder=/tmp/cargo-installzBhvr2/release/deps/libsc_block_builder-119d4df84581df8b.rmeta --extern s
c_chain_spec=/tmp/cargo-installzBhvr2/release/deps/libsc_chain_spec-08aa50d073474a9b.rmeta --extern sc_client_api=/tmp/cargo-installzBhvr2/rel
ease/deps/libsc_client_api-1446b8af13e7db67.rmeta --extern sc_client_db=/tmp/cargo-installzBhvr2/release/deps/libsc_client_db-24300f0d7faeb1cf
.rmeta --extern sc_consensus=/tmp/cargo-installzBhvr2/release/deps/libsc_consensus-7678877f175f44da.rmeta --extern babe=/tmp/cargo-installzBhv
r2/release/deps/libsc_consensus_babe-f1f28c4fa2457bd7.rmeta --extern sc_executor=/tmp/cargo-installzBhvr2/release/deps/libsc_executor-92fd4b31
813c2d9d.rmeta --extern grandpa=/tmp/cargo-installzBhvr2/release/deps/libsc_finality_grandpa-b452e55494c717c4.rmeta --extern sc_keystore=/tmp/
cargo-installzBhvr2/release/deps/libsc_keystore-60ade4e0b6a6b292.rmeta --extern sc_network=/tmp/cargo-installzBhvr2/release/deps/libsc_network
-747d371c4af34112.rmeta --extern service=/tmp/cargo-installzBhvr2/release/deps/libsc_service-37e960e8b625bb04.rmeta --extern telemetry=/tmp/ca
rgo-installzBhvr2/release/deps/libsc_telemetry-9cbdc10a055771e3.rmeta --extern sc_transaction_pool=/tmp/cargo-installzBhvr2/release/deps/libsc
_transaction_pool-2a3cd08ce3c7501e.rmeta --extern serde=/tmp/cargo-installzBhvr2/release/deps/libserde-cfc47cf763bd0ce9.rmeta --extern slog=/t
mp/cargo-installzBhvr2/release/deps/libslog-0c3f33ed49d1fd18.rmeta --extern sp_api=/tmp/cargo-installzBhvr2/release/deps/libsp_api-db2100d0a77
fbbe2.rmeta --extern authority_discovery_primitives=/tmp/cargo-installzBhvr2/release/deps/libsp_authority_discovery-d8628ad70c5a350b.rmeta --e
xtern sp_block_builder=/tmp/cargo-installzBhvr2/release/deps/libsp_block_builder-e7b533cf48a320dc.rmeta --extern sp_blockchain=/tmp/cargo-inst
allzBhvr2/release/deps/libsp_blockchain-089d0f61f9e40501.rmeta --extern consensus_common=/tmp/cargo-installzBhvr2/release/deps/libsp_consensus
-c4da4bdc343313d7.rmeta --extern babe_primitives=/tmp/cargo-installzBhvr2/release/deps/libsp_consensus_babe-a81485f6baccd0d8.rmeta --extern sp
_core=/tmp/cargo-installzBhvr2/release/deps/libsp_core-689708c99a08d18a.rmeta --extern grandpa_primitives=/tmp/cargo-installzBhvr2/release/dep
s/libsp_finality_grandpa-2b177dc312c39614.rmeta --extern inherents=/tmp/cargo-installzBhvr2/release/deps/libsp_inherents-7649976595efa893.rmet
a --extern sp_io=/tmp/cargo-installzBhvr2/release/deps/libsp_io-213b250310f8bbff.rmeta --extern sp_offchain=/tmp/cargo-installzBhvr2/release/d
eps/libsp_offchain-4da01c8a2e0d35d3.rmeta --extern sp_runtime=/tmp/cargo-installzBhvr2/release/deps/libsp_runtime-e10bbb118bf52b8e.rmeta --ext
ern sp_session=/tmp/cargo-installzBhvr2/release/deps/libsp_session-84433f435694bd4c.rmeta --extern sp_transaction_pool=/tmp/cargo-installzBhvr
2/release/deps/libsp_transaction_pool-e74befaea0b11eaf.rmeta --extern sp_trie=/tmp/cargo-installzBhvr2/release/deps/libsp_trie-86c9d8d0734d94f
e.rmeta --extern prometheus_endpoint=/tmp/cargo-installzBhvr2/release/deps/libsubstrate_prometheus_endpoint-9de1fa492ed19d7f.rmeta --extern we
stend_runtime=/tmp/cargo-installzBhvr2/release/deps/libwestend_runtime-fc27c4f15514c7d2.rmeta --cap-lints allow -L native=/tmp/cargo-installzB
hvr2/release/build/blake3-d933c0436ab9a93f/out -L native=/tmp/cargo-installzBhvr2/release/build/blake3-d933c0436ab9a93f/out -L native=/tmp/car
go-installzBhvr2/release/build/ring-a5aafcd580e18e74/out -L native=/tmp/cargo-installzBhvr2/release/build/zstd-sys-57a3385c51014978/out -L nat
ive=/tmp/cargo-installzBhvr2/release/build/wasmtime-runtime-ed60438d4ba65517/out -L native=/tmp/cargo-installzBhvr2/release/build/librocksdb-s
ys-b72b8b750f9e0d7f/out -L native=/tmp/cargo-installzBhvr2/release/build/librocksdb-sys-b72b8b750f9e0d7f/out` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `node-cli v0.21.0 (https://github.com/airalab/robonomics?tag=v0.21.0#31a135b2)`, intermediate artifacts can be found 
at `/tmp/cargo-installzBhvr2`
Caused by:
  build failed

rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

rustc --version
rustc 1.47.0-nightly (e15510ca3 2020-08-20)

**Comment by bkchr** [comment]
Looks like you run out of memory. There is no compilation error.
