### ISSUE TITLE
Crowdfund refactor

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#1634]
Found some code that can be improved in crowdfund pallet

There are no more additional transfer fees

https://github.com/paritytech/polkadot/blob/102aa6fd72b7fcb092d5f8d64ce3d98b78b0a286/runtime/common/src/crowdfund.rs#L449-L453

https://github.com/paritytech/polkadot/blob/102aa6fd72b7fcb092d5f8d64ce3d98b78b0a286/runtime/common/src/crowdfund.rs#L480-L483

Many places can be updated using `mutate` or `try_mutate` to improve performance

https://github.com/paritytech/polkadot/blob/102aa6fd72b7fcb092d5f8d64ce3d98b78b0a286/runtime/common/src/crowdfund.rs#L272-L274

https://github.com/paritytech/polkadot/blob/102aa6fd72b7fcb092d5f8d64ce3d98b78b0a286/runtime/common/src/crowdfund.rs#L367-L373

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by shawntabrizi** [comment]
Yeah I expect all the Polkadot pallets will need to be reviewed and updated.

Here is another issue I opened about crowdfund: https://github.com/paritytech/polkadot/issues/662

**Comment by shawntabrizi** [comment]
One more thing, if I remember correctly, crowdfund does not guarantee that funds make it back to the end users. Since the funds become property of the parachain origin, the owner of that origin can move the funds anywhere a the end of the slot.

Probably something we want to patch.

**Comment by xlc** [comment]
Another thing that will be helpful to improve is that currently the participants have to call withdraw before `RetirementPeriod` passed, or they will lost their funds. It is likely after two years, people will forgot about this so some may not be able to withdraw in a timely manner.

An easy improvement will be allow anyone to trigger withdraw on behalf others so at least the crowdfund owner can choose to refund everyone before calling `dissolve`.
