### ISSUE TITLE
MY 12 WORD SEED GENERATED A DIFFERENT ADDRESS ON POLKADOT.JS.ORG

### ISSUE THREAD

**Issue by wilderbeast19** [paritytech/polkadot#1637]
I open a kasuma , account on polkadot.js.org, i did not back it up, but wrote the 12 seed words and my password. i transferred some ksm tokens to it, later i wanted to move the tokens to the extension wallet, it rejected my password. i then decided to recover the account with the 12 words, it generated a different address, that cannot be verified from or does not exist in the ledger or blockchain. my tokens are still in the address, i informed admin in telegram, still no solution. when i tried imputing in SECRET DERIVATION PATH , it gives me various different addresses.
Please assist in recovering my tokens.

**Comment by Stefie** [comment]
Hi @wilderbeast19 ,
when you say "i wanted to move the tokens to the extension wallet", do you mean the PolkadotJS extension?
If so, please try the following syntax when importing your with the 12-word seed phrase & your password, notice the three slashes between the seed phrase and the password.:

<img width="482" alt="Screenshot 2020-08-25 at 17 36 34" src="https://user-images.githubusercontent.com/125398/91195921-cb489c00-e6f9-11ea-86b4-fda556d123d2.png">

If you want your address displayed in the Kusama format, you should switch to it in the settings:

<img width="312" alt="Screenshot 2020-08-25 at 17 40 27" src="https://user-images.githubusercontent.com/125398/91196230-2b3f4280-e6fa-11ea-9a98-1930a7f3fef7.png">

**Comment by wilderbeast19** [comment]
It's still not generating my address that has my tokens, as i imput the
password after the 12 word seed, the address begins to change with each
letter i add.
I believe, there should be a way out to recover my tokens.

Efe

**Comment by wilderbeast19** [comment]
And the addresses generated can not be verified on the blockchain,
Can i send the real address to you and one or two of other addresses
generated.

**Comment by wilderbeast19** [comment]
i can not recover the account in polkadot.js.org, it keeps giving various
addresses, t

**Comment by wilderbeast19** [comment]
DTNZvMfdhZAiN6yBD69S6JX4pq17FGBd4VVisfmbkTJq694





polkastats does not have record of the addresses generated.

**Comment by wilderbeast19** [comment]
DTNZvMfdhZAiN6yBD69S6JX4pq17FGBd4VVisfmbkTJq694

**Comment by Stefie** [comment]
> as I input the password after the 12 word seed, the address begins to change with each letter I add

I just verified that importing accounts in the PolkadotJS extension is working as expected. As you can see in my screenshot above, the address is not getting displayed there while typing, so I’m not sure which wallet / UI you’re referring to.

Since this is neither a technical Issue with Polkadot itself nor with the PolkadotJS Extension, I’m afraid we can’t provide individual support at this moment.

**Comment by wilderbeast19** [comment]
Yesterday, Someone said he encountered this same issue, but fortunately he
had no funds in the address,  so he just abandoned it.
My question is the 12 seed is generating various addresses but only one is
valid in polkastat, that's the one with my funds..
There must be a way for me to get my funds out.
From the developers, there must be a way to recover the address.

**Comment by hanwencheng** [comment]
> It's still not generating my address that has my tokens, as i imput the
password after the 12 word seed, the address begins to change with each
letter i add.

@wilderbeast19 I think you have misunderstand the password in (Polkadot.js and extensions) with (the derivation password start with `///`).

On extension you can use any new password you like. do not need to use the old one or `///`

**Comment by wilderbeast19** [comment]
My 12 seed is not generating the address, i did not save json file, only
the Lord can help me recover my tokens. I am trying to forget them.

**Comment by wilderbeast19** [comment]
Saw my json file, by chance today, but still cannot locate the exact
password used in opening the account, if i open the json file, how can i
get the RAW SEED?

**Comment by dursunal** [comment]
I update my polkawallet. I try to sign in my wallet. I use my mnomenic words or raw seed word but I can not see my wallet. it adds a different wallet with each new venture. I want to helps from acala. But they did not help me. 

Ea9YVo9Nw4khz96WvLjhGAAxLGFYuzJr8K3pd3rdtaDPcef Wallet dont be seen. ı lost all my investment. 
-- | --
Ea9YVo9Nw4khz96WvLjhGAAxLGFYuzJr8K3pd3rdtaDPcef Wallet dont be seen.

**Comment by NukeManDan** [comment]
Note that issues on this repository are for reporting bugs related to Polkadot's node code base itself, not applications that connect to a Polkadot node. This is not the Polkadot apps UI repo or extention that many are talking about. If you have a bug to report for those apps specifically, please place that on the appropriate repo here: https://github.com/polkadot-js/

### For those looking for **user support** please look through the official searchable support website: 
## https://support.polkadot.network/support/home

The support site also lists an email to contact as well with these issues if you can't find a guide to your problem.

**Comment by alyosha7** [comment]
> I open a kasuma , account on polkadot.js.org, i did not back it up, but wrote the 12 seed words and my password. i transferred some ksm tokens to it, later i wanted to move the tokens to the extension wallet, it rejected my password. i then decided to recover the account with the 12 words, it generated a different address, that cannot be verified from or does not exist in the ledger or blockchain. my tokens are still in the address, i informed admin in telegram, still no solution. when i tried imputing in SECRET DERIVATION PATH , it gives me various different addresses. Please assist in recovering my tokens.

I see this issue is closed now. Has this been resolved? I have the same issue. 
Thanks!

**Comment by NukeManDan** [comment]
Please seek user related support here: 

## https://support.polkadot.network

issues are for the software development process, not account management issues :pray:
