### ISSUE TITLE
Guide: Use regular maps if they support iteration

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1640]
> `frame` maps support iteration already, i believe.

_Originally posted by @rphmeier in https://github.com/paritytech/polkadot/pull/1591#discussion_r471624151_

Research if we the FRAME iterable maps are appropriate there

**Comment by drahnr** [comment]
https://substrate.dev/docs/en/knowledgebase/runtime/storage#storage-maps says that it's more costly to iterate over maps, but with the current approach we do both - iterate over a vec and a map.

**Comment by shawntabrizi** [comment]
iterating over a map will be very costly compared to iterating over a vec.

Do look at each value in a map, you will need to read from storage that value individually, which can be extremely heavy. We treat each of these operations as ~25 microseconds at the moment.

https://github.com/paritytech/substrate/blob/master/frame/support/src/weights.rs#L167

The downside of using a vec is that if you ever want to access only 1 item, you would need to read and decode the whole vector just to access that one item. However, if you will always be iterating over the whole list, using a vector is most certainly cheaper.

If you will do a combination of both reading 1 value and iterating over all values, consider storing both a map and a vec (which may be overall less cost to your chain). But this stuff also depends on the number of values.

**Comment by burdges** [comment]
These are BTreeMap-like constructs organized into their own (sub)trees, not separate storage items spread all over some larger tree, right?  It's obviously expensive to read all over a tree, so I'll assume organized subtrees.

If properly optimized, then merkle tree hashing should cost only twice-ish what linear hashing costs, so even if you want the whole vec then the vec should only double your speed.

We might lack some optimizations here, like omitting intermediate copath layers when both children get revisited, or not optimizing the merkle tree hashing.

**Comment by drahnr** [comment]
@pepyakin @rphmeier imho the guide can then stay as is, and we keep the duplicate storage entries for sake of perf. It does not hurt much to already have that in the guide and have the invariants specified explicitly.
