### ISSUE TITLE
Implementer's Guide: HRMP/XCMP channel limits

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1641]
XCMP tries it's best on delivering messages. However, that requires some degree of effort applied by the recipient parachain. Specifically, XCMP relies on the availability system as a fallback to obtain the message preimages. But availability data is only stored for only so much time and pruned within a day or less. Therefore, a parachain must consume the messages lest let them slip beyond the availability window and lose them forever.

That might be problematic for parathreads, since they don't produce a lot of blocks. However, if one of the parachains start spamming messages, the para will have to process them under a risk of losing other messages.

It seems a good idea to give control of how many messages a parathread is willing to process at most. Similarly, it seems a good idea to allow to control the maximum size of any message put into the recipient's channel. 

That would allow the recipient to tune the settings so that it can definitely handle the sudden surge of messages, won't allow to send unexpectedly large messages, would allow to correctly prioritise some channels over others (or the opposite, for suspicious paras it could set lower limits).

## Approach

This concern was already raised in the original research draft: [Opening/closing XCMP Channel](https://github.com/w3f/research/commit/a52335510de4e4b3d453e5f32613287ae418a055#diff-3a27e98dcdaf0fdab2577d7d5ce867cbR26).

My current vision is similar to that. The sender proposes the parameters of the channel in the open channel request and then the recipient confirms them by accepting that request. That requires the sender to know the appropriate parameters of the request, but that's fine: after all the sender is required to know the protocol the recipient understands.

**Comment by pepyakin** [comment]
Similarly to #1644 I think it makes sense to impose a limit controlled by a configuration parameter that prevents ridiculous capacities and the message size limits.

The parameters should always be specified explicitly and there should not be reliance on the defaults provided by the configuration. The motivation is the configuration values might increase suddenly so high that would make some recipients to choke. Thus, explicit negotiation of the higher limits, should the configuration allow those, is preferred.

**Comment by xlc** [comment]
How does transaction fee & weights plays with this?
Also the dest parachain may choose to ignore some messages due to fee / weight requirement, and in that case how does the sender know the message is been dropped?
