### ISSUE TITLE
Router's Drop implementation is wrong

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#165]
Router unconditionally clears gossip and the consensus instance on `drop`, but Router is `Clone` and the individual clones can be short-lived. This cleanup should only be done when all `Router` instances on a consensus hash have dropped.

Backport to v0.3

**Comment by rphmeier** [comment]
This is fixed in #149 but needs some kind of backport to v0.3.

**Comment by DemiMarie-parity** [comment]
@rphmeier should I take this?

**Comment by rphmeier** [comment]
sure, if you like

**Comment by DemiMarie-parity** [comment]
@rphmeier which hash is relevant here?

**Comment by DemiMarie-parity** [comment]
#149 is rather large and tricky to backport.  Is there a simpler way?

**Comment by rphmeier** [comment]
The whole thing doesn't need to be backported, and actually shouldn't be. This piece of code in particular has changed a lot from v0.3. It's not particularly urgent that it be fixed in v0.3 anyway (it's a bug which doesn't get triggered in practice), so if it turns out to be substantial effort we should not spend time on it.

**Comment by DemiMarie-parity** [comment]
Since it doesn’t get triggered in practice, I don’t think we should backport it, unless there would be a major problem if it did get triggered.

**Comment by rphmeier** [comment]
No, it wouldn't be a major issue. It would just fail to reach agreement on parachain candidates sometimes, because it's overeagerly collecting garbage.
