### ISSUE TITLE
No token name on dev chains

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/polkadot#1684]
If I run `polkadot --dev=kusama --no-telemetry --rpc-methods=unsafe --unsafe-ws-external` in one terminal and run `curl --data-raw '{"jsonrpc":"2.0","id":1,"method":"system_properties","params":null}' -H 'Content-Type: application/json' -- http://localhost:9933` in another, the response is `{"jsonrpc":"2.0","result":{},"id":1}`, which I think is wrong.  A working chain must have at least a token name.

This exposed what I assume to be a bug in `jsonrpsee`: it behaves unpredictably when decoding a response fails.

**Comment by bkchr** [comment]
Dev chains don't have system properties set and there is also no real requirement for this.
