### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by meltaus** [paritytech/polkadot#170]
after upgrading to version 0.3.15 I don't see the node on https://telemetry.polkadot.io/#/Alexander But on logs I see that it is necessary works. And there was a message
"src/lib.rs
274
1"

**Comment by meltausorion** [comment]
![alexander](https://user-images.githubusercontent.com/13775964/54107080-b6475280-440a-11e9-9f54-63877e2ebd01.png)

Same error if I install a new node

**Comment by meltausorion** [comment]
https://pastebin.com/WCScuVnM

**Comment by gavofyork** [comment]
stale
