### ISSUE TITLE
CI is not building wasm

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#173]
The CI is not building the wasm blob and so we probably miss errors.

CC: @gabreal

**Comment by gabreal** [comment]
do you have a link to the site where you saw this problem?

**Comment by bkchr** [comment]
We don't call `./scripts/build.sh` here: https://github.com/paritytech/polkadot/blob/222c6c23bbf9460f1a4993e5a25baf34ef2a0c24/.gitlab-ci.yml#L97
You can just look into a CI build of polkadot and see that only native is compiled.

**Comment by gabreal** [comment]
https://gitlab.parity.io/parity/polkadot/-/jobs/127652

thanks for reporting wasm blobs are included now
