### ISSUE TITLE
Backport tracing to older wasm releases

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/polkadot#1730]
Once https://github.com/paritytech/substrate/pull/6916 is in and https://github.com/paritytech/substrate/issues/6572 adds traces to the runtime, our client provides `tracing`-support for wasm runtimes with the `with-tracing` feature is enabled. To allow  for tracing all the way back to genesis, we therefor must **backport these changes to each polkadot runtime at the time and build it with `with-tracing` enabled**, and then release the wasm binaries here for download.

**Comment by rphmeier** [comment]
outdated
