### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13

### ISSUE THREAD

**Issue by Black52** [paritytech/polkadot#1742]
> Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

Hash: given=d3a331ad9c54603ef83e23a7cf0779a03bf2b092fd97bd90f936c31b28406154, expected=c1773a85faa78f0d4220d0779cf570f05434512080d131be73e8bdab8087441c

====================

Version: 0.8.24-5cbc418a-x86_64-linux-gnu

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: start_thread
  37: clone

Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
Which Polkadot version are you running?

**Comment by Black52** [comment]
0.8.24-5cbc418a-x86_64-linux-gnu

**Comment by Black52** [comment]
> Which Polkadot version are you running?

0.8.24-5cbc418a-x86_64-linux-gnu
========================
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: start_thread
  38: clone


Thread 'tokio-runtime-worker' panicked at 'Signature verification has not been called before `SignatureBatching::drop`', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/647ad15/primitives/runtime/src/lib.rs:799

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

thread panicked while panicking. aborting.
2020-09-23 17:00:51.841 main INFO sc_cli::runner  Parity Polkadot
2020-09-23 17:00:51.842 main INFO sc_cli::runner  ✌️  version 0.8.24-5cbc418a-x86_64-linux-gnu
2020-09-23 17:00:51.843 main INFO sc_cli::runner  ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-09-23 17:00:51.843 main INFO sc_cli::runner  📋 Chain specification: Westend
2020-09-23 17:00:51.843 main INFO sc_cli::runner  🏷  Node name: PolkaDocker727
2020-09-23 17:00:51.843 main INFO sc_cli::runner  👤 Role: FULL
2020-09-23 17:00:51.843 main INFO sc_cli::runner  💾 Database: RocksDb at /root/.local/share/polkadot/chains/westend2/db
2020-09-23 17:00:51.843 main INFO sc_cli::runner  ⛓  Native runtime: westend-43 (parity-westend-1.tx3.au2)
2020-09-23 17:00:57.661 main INFO sub-libp2p  🏷  Local node identity is: 12D3KooWReFPfivnXVn2wC6iyVtxegu7fbR7DotUxUrEB8snJhkq (legacy representation: 12D3KooWReFPfivnXVn2wC6iyVtxegu7fbR7DotUxUrEB8snJhkq)
2020-09-23 17:00:57.711 main INFO sc_service::builder  📦 Highest known block at #2143450
2020-09-23 17:00:57.721 tokio-runtime-worker INFO substrate_prometheus_endpoint::known_os  〽️ Prometheus server started at 127.0.0.1:9615

**Comment by bkchr** [comment]
This will be solved with 0.8.25

**Comment by Black52** [comment]
> This will be solved with 0.8.25
Is there a problem with the current version?   I'm syncing to 1280777 now，I can't download the next one。
My node：westend

**Comment by ethernomad** [comment]
v0.8.25 has been tagged, but this issue still exists

**Comment by bkchr** [comment]
@ethernomad you still get a storage root mismatch with the tagged release?

**Comment by ethernomad** [comment]
The error does not occur for me with master HEAD.

Which commit fixed this issue?

**Comment by bkchr** [comment]
@ethernomad With westend? Which block?

**Comment by ethernomad** [comment]
Sorry - it doesn't occur with Polkadot. My Westend node is currently catching up. I'll post again once the problem occurs or it catches up with the network.

**Comment by ethernomad** [comment]
I was able to sync westend with latest polkadot binary without issue.

**Comment by bkchr** [comment]
Good

**Comment by bkchr** [comment]
I think this can be closed now.

**Comment by lucamarrocco** [comment]
I've a similar error, please see https://github.com/paritytech/polkadot/issues/3286
