### ISSUE TITLE
9944 connecttion fail

### ISSUE THREAD

**Issue by satonz** [paritytech/polkadot#1748]
After the node is started, port 9944 cannot be connected
node: 
![image](https://user-images.githubusercontent.com/38401802/94096593-1370f080-fe57-11ea-92ca-e366a65b8902.png)

**Comment by satonz** [comment]
Is there a problem with my start command?

**Comment by bkchr** [comment]
You need to expose the ws and http rpc interfaces. Check the cli docs of `rpc-external`

**Comment by bkchr** [comment]
@laboon the wiki should be updated with a working example

**Comment by satonz** [comment]
this is my command
![image](https://user-images.githubusercontent.com/38401802/94121445-e8e95c80-fe83-11ea-83dc-15e23a83f5d9.png)


![image](https://user-images.githubusercontent.com/38401802/94121465-ee46a700-fe83-11ea-9a80-dbf66d7fd270.png)

**Comment by satonz** [comment]
The port has been leaked to the outside

**Comment by bkchr** [comment]
What does that mean?

**Comment by satonz** [comment]
we use substrate-api-sidecar  cant connection  polkadot           
Is there a problem with my start command?

**Comment by satonz** [comment]
![image](https://user-images.githubusercontent.com/38401802/94122060-a8d6a980-fe84-11ea-9064-6abc8bfe5000.png)

**Comment by bkchr** [comment]
@joepetrowski any ideas?

**Comment by joepetrowski** [comment]
I'm not familiar with that `w3f` docker image for Sidecar, do you know what version it's running? 

@emostov knows the Sidecar WebSocket stuff well and @chevdor helped a lot with Sidecar's docker setup - one of you know?

**Comment by satonz** [comment]
hello  What should I do

**Comment by laboon** [comment]
@bkchr opened an issue to update wiki, thanks

**Comment by emostov** [comment]
Closed [this issue here](https://github.com/paritytech/substrate-api-sidecar/issues/304). I think it was specific to docker. From my limited docker knowledge, my understanding is that you need the host set to 0.0.0.0 in order to expose ports outside of a containers own virtual network. We implicitly mention that in [Sidecar's readme docker section.](https://github.com/paritytech/substrate-api-sidecar#run)
