### ISSUE TITLE
WARN Block prepare storage changes error

### ISSUE THREAD

**Issue by guijun** [paritytech/polkadot#1756]
commit 507b9cbca5a662a1221be43992c6d19b3c78881e (HEAD -> master, origin/master, origin/HEAD)

Sep 27 01:35:26 u64 polkadot[42288]: This is a bug. Please report it at:
Sep 27 01:35:26 u64 polkadot[42288]:         https://github.com/paritytech/polkadot/issues/new
Sep 27 01:35:26 u64 polkadot[42288]: Sep 27 01:35:26.852  WARN Block prepare storage changes error:
Sep 27 01:35:26 u64 polkadot[42288]: Execution(Other("Wasm execut Error importing block 0x063b1e12ca5fc17e7a1d65a14dce635f1fd5ee7abb345b14b31e3c043a792034: Err(Other(ClientImport("Import failed: Execution: Wasm execution trapped: Failed to register required extension: `VerificationExt`: ExtensionAlreadyRegistered\nwasm backtrace:\n  0: 0x25754 - <unknown>!sp_io::crypto::extern_host_function_impls::start_batch_verify::ha3a2d8c956d98dee\n  1: 0xfcde5 - <unknown>!Core_execute_block\n")))7 01:35:26 u64 polkadot[42288]: Sep 27 01:35:26.852  WARN 

Sep 27 01:35:27 u64 polkadot[42288]: ====================
Sep 27 01:35:27 u64 polkadot[42288]: Version: 0.8.24-507b9cbc-x86_64-linux-gnu
Sep 27 01:35:27 u64 polkadot[42288]:    0: sp_panic_handler::set::{{closure}}
Sep 27 01:35:27 u64 polkadot[42288]:    1: std::panicking::rust_panic_with_hook
Sep 27 01:35:27 u64 polkadot[42288]:              at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
Sep 27 01:35:27 u64 polkadot[42288]:    2: std::panicking::begin_panic
Sep 27 01:35:27 u64 polkadot[42288]:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_extrinsics_with_book_keeping
Sep 27 01:35:27 u64 polkadot[42288]:    4: tracing::span::Span::in_scope
Sep 27 01:35:27 u64 polkadot[42288]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
Sep 27 01:35:27 u64 polkadot[42288]:    6: <westend_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,westend_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<westend_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<westend_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<westend_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<westend_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<westend_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<westend_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<westend_runtime::Runtime>)>>>>::execute_block
Sep 27 01:35:27 u64 polkadot[42288]:    7: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Sep 27 01:35:27 u64 polkadot[42288]:    8: std::thread::local::LocalKey<T>::with
Sep 27 01:35:27 u64 polkadot[42288]:    9: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Sep 27 01:35:27 u64 polkadot[42288]:   10: sc_executor::wasm_runtime::RuntimeCache::with_instance
Sep 27 01:35:27 u64 polkadot[42288]:   11: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Sep 27 01:35:27 u64 polkadot[42288]:   12: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Sep 27 01:35:27 u64 polkadot[42288]:   13: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Sep 27 01:35:27 u64 polkadot[42288]:   14: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Sep 27 01:35:27 u64 polkadot[42288]:   15: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Sep 27 01:35:27 u64 polkadot[42288]:   16: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Sep 27 01:35:27 u64 polkadot[42288]:   17: sp_api::Core::execute_block_with_context
Sep 27 01:35:27 u64 polkadot[42288]:   18: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
Sep 27 01:35:27 u64 polkadot[42288]:   19: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
Sep 27 01:35:27 u64 polkadot[42288]:   20: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
Sep 27 01:35:27 u64 polkadot[42288]:   21: sp_consensus::import_queue::import_single_block_metered
Sep 27 01:35:27 u64 polkadot[42288]:   22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   23: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   24: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   25: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   26: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   27: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   29: std::thread::local::LocalKey<T>::with
Sep 27 01:35:27 u64 polkadot[42288]:   30: futures_executor::local_pool::block_on
Sep 27 01:35:27 u64 polkadot[42288]:   31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Sep 27 01:35:27 u64 polkadot[42288]:   32: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Sep 27 01:35:27 u64 polkadot[42288]:   33: tokio::runtime::task::harness::Harness<T,S>::poll
Sep 27 01:35:27 u64 polkadot[42288]:   34: tokio::runtime::blocking::pool::Inner::run
Sep 27 01:35:27 u64 polkadot[42288]:   35: tokio::runtime::context::enter
Sep 27 01:35:27 u64 polkadot[42288]:   36: std::sys_common::backtrace::__rust_begin_short_backtrace
Sep 27 01:35:27 u64 polkadot[42288]:   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
Sep 27 01:35:27 u64 polkadot[42288]:   38: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Sep 27 01:35:27 u64 polkadot[42288]:              at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
Sep 27 01:35:27 u64 polkadot[42288]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Sep 27 01:35:27 u64 polkadot[42288]:              at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
Sep 27 01:35:27 u64 polkadot[42288]:       std::sys::unix::thread::Thread::new::thread_start
Sep 27 01:35:27 u64 polkadot[42288]:              at rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/sys/unix/thread.rs:87
Sep 27 01:35:27 u64 polkadot[42288]:   39: start_thread
Sep 27 01:35:27 u64 polkadot[42288]:   40: clone

**Comment by bkchr** [comment]
What are you running? Polkadot or Westend?
