### ISSUE TITLE
polkadot_proposer_block_constructed_count not incrementing in branch prgn-remove-old-service-second-try

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1757]
Sequence of events this morning:

- requested instructions in `#polkadot-devops:matrix.parity.io` for checking whether [that branch](https://github.com/paritytech/polkadot/pull/1732) was burning in properly
- got a "looks good"
- requested bot merge for that branch
- followup in matrix: looks like `polkadot_proposer_block_constructed_count` is either broken or not increasing on the polkadot validator `polkadot-validator-ae2-1`
  - however, it seemed to be ok on `kusama-validator-ue1-0`

**Comment by tomaka** [comment]
> however, it seemed to be ok on kusama-validator-ue1-0

The metric wasn't working there either, but it also wasn't working before the testing started, so I didn't attribute this problem to the PR itself.

**Comment by ordian** [comment]
I was told the public of `polkadot-validator-ae2-1` and it seems to have produced the blocks: [polkascan link](https://polkascan.io/polkadot/account/1KPfsQbEQzetjYbQFPAmJ5XXN8G4Jh3toBQW41H4x7wTczu#authoredblocks).

**Comment by ordian** [comment]
Hmm, was that metrics introduced 5 month ago?
https://github.com/paritytech/substrate/pull/6030

**Comment by coriolinus** [comment]
Git blame seems to think so, but I haven't been following closely the details about which substrate is paired up with which polkadot right now, other than to notice that upgrades seem to be a fairly big deal. A few months' delay wouldn't surprise me.

**Comment by bkchr** [comment]
Polkadot is always using Substrate master, there is no months in delays.

Did you tried to run a local network with your branch?

**Comment by coriolinus** [comment]
Did I try? Yes. Did I succeed? Not sure. It looked like it worked, but it is possible that I misread things. I am at best an inexperienced node operator.

If we always use substrate master, it is not clear why I often see PRs with titles like "update Substrate and bump version", the most recent of which is #1720. That implies a more stepped upgrade process.

**Comment by bkchr** [comment]
> If we always use substrate master, it is not clear why I often see PRs with titles like "update Substrate and bump version", the most recent of which is #1720. That implies a more stepped upgrade process.

If I say you that we use latest Substrate master, you can trust me.

> Did I try? Yes. Did I succeed? Not sure. It looked like it worked, but it is possible that I misread things. I am at best an inexperienced node operator.

Did it produced blocks or not?

**Comment by coriolinus** [comment]
> Did it produce blocks or not?

Yes--but when there are only two nodes, both running in dev mode (Alice and Bob), and I have to mess around with the command line to get them to talk to each other at all, then I begin to suspect that I am running things outside of normal parameters.
