### ISSUE TITLE
Land XCM v0 onto master

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1783]
In https://github.com/paritytech/polkadot/pull/1657 the initial prototype version of XCM was introduced. However, it was coded against the v0 parachains, which at the time of writing this was already eradicated. 

Note that this issue doesn't require complete polishness of XCM. The goal of this issue is to land XCM on master adapting it to the parachains v1 code to ultimately achieving feature parity with the v0 version - i.e. launch rococo v1 with XCM and demonstrate the same functionality.

**Comment by h4x3rotab** [comment]
Do we need to wait for this to test the XCM handlers on a rococo-template parachain?

**Comment by shawntabrizi** [comment]
Follow up maybe for another issue:

 - [ ] TODOs from this PR: https://github.com/paritytech/polkadot/pull/1771/

**Comment by shawntabrizi** [comment]
Follow up:

- [ ] Bring in the `Sibiling` struct which is not yet used

```
#[derive(Clone, Copy, Default, Encode, Decode, Eq, PartialEq, Ord, PartialOrd, RuntimeDebug)]
pub struct Sibling(pub Id);

impl From<Id> for Sibling {
	fn from(i: Id) -> Self {
		Self(i)
	}
}
impl From<Sibling> for Id {
	fn from(i: Sibling) -> Self {
		i.0
	}
}
impl AsRef<Id> for Sibling {
	fn as_ref(&self) -> &Id {
		&self.0
	}
}
impl TypeId for Sibling {
	const TYPE_ID: [u8; 4] = *b"sibl";
}
impl From<Sibling> for u32 {
	fn from(x: Sibling) -> Self { x.0.into() }
}

impl From<u32> for Sibling {
	fn from(x: u32) -> Self { Sibling(x.into()) }
}

impl IsSystem for Sibling {
	fn is_system(&self) -> bool {
		IsSystem::is_system(&self.0)
	}
}

**Comment by rphmeier** [comment]
@pepyakin triage? should this be bethesda?

**Comment by pepyakin** [comment]
Yep, this is a priority now.

**Comment by pepyakin** [comment]
I think this issue is not longer relevant as all parts were landed.
