### ISSUE TITLE
v0.8.25 build fail

### ISSUE THREAD

**Issue by BomaxChen** [paritytech/polkadot#1814]
node is on macOS
i can build 0.8.24 but 0.8.25 will fail
====================================
error[E0282]: type annotations needed
      --> /Users/bomaxchen/.cargo/git/checkouts/substrate-7e08433d4c370a21/2f3b20b/primitives/arithmetic/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1614 | / implement_fixed!(
  1615 | |     FixedU128,
  1616 | |     test_fixed_u128,
  1617 | |     u128,
  ...    |
  1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
  1622 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to 3 previous errors

  For more information about this error, try `rustc --explain E0282`.
  error: could not compile `sp-arithmetic`

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bkchr** [comment]
Please downgrade your nightly: https://substrate.dev/docs/en/knowledgebase/getting-started/#downgrading-rust-nightly

You can always find the latest working nightly for a release in the release announcement here on github.
