### ISSUE TITLE
Balance not matching

### ISSUE THREAD

**Issue by thanlok** [paritytech/polkadot#1815]
I am using docker to start the DOT node on `westend` testnet. 
Image: `parity/polkadot:master-0.8.24-9d6cd80-2f48441d`
Command:
 `--chain westend --rpc-external --ws-external --pruning archive --rpc-port 9933 --ws-port 9944 --rpc-cors all --rpc-methods Unsafe --wasm-execution Compiled --port 30333 --base-path /opt/data --force-westend`.

When I query my balance through the node. I got a different balance from the on chain balance.

Address: `5E7Sb4cUMkh4VAdpc4yX56bjWxGXrbNTpB8KRaJ4nxaV8Vbr`
On chain balance: 1 WND https://westend.subscan.io/account/5E7Sb4cUMkh4VAdpc4yX56bjWxGXrbNTpB8KRaJ4nxaV8Vbr
Query Node Balance: 
```
{ nonce: '0',
  refcount: '0',
  data:
   { free: '16.777M WND',
     reserved: '0',
     miscFrozen: '0',
     feeFrozen: '0' } }
```

How come the node query balance is different from the on chain balance?

I am using polkadot js lib https://polkadot.js.org/docs/api/examples/promise/listen-to-balance-change. Here is my code.

```
import { ApiPromise } from "@polkadot/api";
import { WsProvider } from "@polkadot/rpc-provider";

const wsProvider = new WsProvider("ws://127.0.0.1:9944");
const api = await ApiPromise.create({ provider: wsProvider });
let data:any  = await api.query.system.account("5E7Sb4cUMkh4VAdpc4yX56bjWxGXrbNTpB8KRaJ4nxaV8Vbr");
console.log(data.toHuman())
```

**Comment by bkchr** [comment]
@jacogr any idea?

**Comment by thanlok** [comment]
@bkchr @jacogr sorry, i just figure out it's the js lib version problem. Thank you

**Comment by shawntabrizi** [comment]
FYI this is likely due to the fact that the refcount of a user changed from u8 to u32 causing the entire account data (including balance) to be parsed wrong.

**Comment by jacogr** [comment]
Here is the FAQ entry - https://polkadot.js.org/docs/api/FAQ#on-a-non-current-non-substrate-20-branch-my-balances-are-wrong
