### ISSUE TITLE
DMP design is broken as presented in impl-guide w.r.t. contextual execution 

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1824]
The acceptance criteria for DMP is presented as follows:

```
* `check_processed_downward_messages(P: ParaId, processed_downward_messages)`:
    1. Checks that `DownwardMessageQueues` for `P` is at least `processed_downward_messages` long.
    1. Checks that `processed_downward_messages` is at least 1 if `DownwardMessageQueues` for `P` is not empty.
```

the first rule depends on a variable parameter, specifically the length of `DownwardMessageQueues` for `P`. It is variable w.r.t. to contextual execution, meaning that the parameter can change in between two blocks within one session. 

However, in this case it is safe. If we assume 

1. a DMQ for a para can be only appended to by the relay-chain (using `queue_downward_message`)
1. a DMQ can only be emptied by an enacted candidate

therefore the length of the DMQ cannot become less than a candidate's `processed_downward_messages` in successive blocks. Therefore, the candidate cannot be invalidated until the next session, which is what we need for sound contextual execution.

The second rule IS problematic though.

> Checks that `processed_downward_messages` is at least 1 if `DownwardMessageQueues` for `P` is not empty.

or more formally, the candidate passes the acceptance criteria rule if:

`len(DownwardMessageQueues(P)) = 0 || processed_downward_messages ≥ 1`

at the backing time, having `len(DownwardMessageQueues(P)) = 0` and `processed_downward_messages = 0` would pass the validation. However, let's assume that a downward message was enqueued for `P` just before inclusion. Therefore, at inclusion we will have 

`len(DownwardMessageQueues(P)) = 1` and `processed_downward_messages = 0` which results in invalidation of a candidate, making contextual execution unsound.

**Comment by pepyakin** [comment]
Assuming we still want to preserve the requirement of dequeuing at least one message per parablock we could do the following.

One obvious solution here is to move watermarks. Indeed, we explored this direction earlier and even had a PR. We've [decided](https://github.com/paritytech/polkadot/pull/1629#issuecomment-683780372) to go away from it: in order to make the mechanism safe from overwhelming the para with downward messages, we would've needed to introduce a compound watermark, i.e. comprised of `(blocknumber, message in that block)`. That would make annoying to keep track of (e.g. you'd need to know the number of messages sent in a block).

Another solution is to mark each message with a sequence number within that queue, starting with 1. A para candidate would carry the sequence number of the last message received, with 0 meaning no message read. Enacting such a candidate would prune all messages up to and including the sequence number to that number found in the candidate. The acceptance rule would say that the sequence number found in the candidate should be greater the one found in the DMQ. 

We could augment it with adding a block number, so that would get us a more bearable watermark and provide the block number when the message was sent.

**Comment by bkchr** [comment]
> The acceptance rule would say that the sequence number found in the candidate should be greater the one found in the DMQ.

Should be greater than which one in the DMQ? Couldn't it still happen that there wasn't a DMQ at the point of time the parachain candidate was created, but at inclusion there is now a message. However, the acceptance rule would require that the sequence number of the candidate is greater than the one found in the DMQ?

**Comment by pepyakin** [comment]
Right, good catch. Apparently my mental model was broken. The problem as I see it now boils down to answering the question:

If during inclusion a candidate doesn't read a message when a queue is not empty, is it because it wants to circumvent the requirement of reading a message or because there were no messages at the relay-parent?

well, it's good that we have a backup with the watermarks solution, but I really think it's clumsy. I'd give some more thought to it.

**Comment by bkchr** [comment]
> well, it's good that we have a backup with the watermarks solution, but I really think it's clumsy. 

Sorry to ask again, what you mean by this?

**Comment by pepyakin** [comment]
By "backup" I meant the first possible solution that starts with "One obvious solution here is to move watermarks" in [my message](https://github.com/paritytech/polkadot/issues/1824#issuecomment-710075617).

**Comment by pepyakin** [comment]
This addendum actually might work.

> We could augment it with adding a block number, so that would get us a more bearable watermark and provide the block number when the message was sent.

Let me expand this idea.

- Each message is attributed with the block number it was sent and a running sequence number within the DMQ for that para, starting with 1.
- A para candidate would carry the DMP watermark, i.e. the block number and the sequence number of the last message received. Similar to HRMP, with no messages to receive, the block number in the watermark would be set to the block number of the relay-parent. 
- The acceptance criteria rule would say that the block number `B` in the watermark from the candidate should satisfy: the last watermark > B ≥ the relay-parent block number. Apart from that, `B` should land either on the relay-parent or on a block where there were at least one message was sent (in HRMP we keep those in a structure called digest. Perhaps we could merge them?). Additionally, the sequence number should point on an existing message (again, should be handled by a digest)
- Enacting a candidate would prune all messages up to and including the sequence number to that number found in the candidate. 

So it is really similar to watermark with the exception of a better individual message differentiation.

Right now, I think there is a possible way how we could make the original `processed_downward_messages` mechanism work.  I think I am a bit confused on how would contextual execution work and a unsure atm if that can possibly work. I'll share it here if when it gets more digested in my head.

**Comment by pepyakin** [comment]
Ok, I think I can conclude that this is a false alarm and I just got confused.

For contextual execution, we would need to be able to validate a candidate the relay-parent of which is `k` block back. There is a requirement for this even, `ValidationData` should be reconstructable for past `k` blocks. (See [here](https://github.com/paritytech/polkadot/pull/1576/files#diff-496968b27c9bf5b89a74bc1325ea63eeb595efd7deebb18ca918beb0bf13a8b8R104)).

So we should be able to get the length of the DMQ at the specific block.

**Comment by pepyakin** [comment]
I think we can close this for now
