### ISSUE TITLE
Invalid value for '--telemetry-url <URL VERBOSITY>...': Verbosity level missing

### ISSUE THREAD

**Issue by SarahKay99** [paritytech/polkadot#1828]
https://github.com/paritytech/polkadot/issues/1020 I'm using Windows. I tried this solution, and it didn't work. Each of the following commands has spawned the same error:

`--telemetry-url 'wss://telemetry.polkadot.io/submit 0`
`--telemetry-url 'wss://telemetry.polkadot.io/submit/' 0`
`--telemetry-url 0 'wss://telemetry.polkadot.io/submit/'`
`--telemetry-url wss://telemetry.polkadot.io/submit/ 0`
`--telemetry-url 0 wss://telemetry.polkadot.io/submit/`

Any advice?

**Comment by bkchr** [comment]
Please try:
`--telemetry-url "wss://telemetry.polkadot.io/submit 0"`

**Comment by ander7agar** [comment]
Same issue running with `--telemetry-url 'ws://telemetry_backend:2000/submit 0'`.

**Comment by bkchr** [comment]
@ander7agar what is the error?

**Comment by ander7agar** [comment]
The error is this output: `error: Invalid value for '--telemetry-url <URL VERBOSITY>...': Verbosity level missing`

**Comment by bkchr** [comment]
What shell are you using?

**Comment by ander7agar** [comment]
I'm using Docker, running Polkadot binary on Ubuntu 20.04 LTS  container

**Comment by bkchr** [comment]
https://stackoverflow.com/a/57812982 this should solve your problem.

**Comment by Kalanamith** [comment]
Use double quotes for telemetry  url value `"ws://telemetry_url:2000/submit 0"`
