### ISSUE TITLE
State Tracing Backports Tracking

### ISSUE THREAD

**Issue by insipx** [paritytech/polkadot#1839]
This issue is for tracking backports for state-tracing into Kusama/Polkadot runtimes.

# **Context**
Tracing allows for external sources (exchanges/archive nodes) to follow changes being done to the state by specific extrinsics. Tracing has been available in substrate and therefore Polkadot since Polkadot/Kusama version 0.8.23. However, historical runtimes do not include tracing, and so the entire history may not yet be tracked. In order to do so, tracing functionality must be backported into older runtimes, and the WASM blobs made available locally to overwrite the on-chain WASM if tracing is enabled.

## Relevant PR's:
[Tracing with bridging to WASM](https://github.com/paritytech/substrate/pull/6916)
[Overwrite on-chain WASM with local wasm](https://github.com/paritytech/substrate/pull/7317)
[Backport Older Runtimes](https://github.com/paritytech/polkadot/issues/1730)

### Disclaimer
Full state-tracing may only support Polkadot, or from a specific version as to reduce the amount of versions needed to be backported.

# Backports

<details><summary> Version Checklist </summary>

- [ ] v0.8.22
- [ ] v0.8.21
- [ ] v0.8.19
- [ ] v0.8.18
- [ ] v0.8.17
- [ ] v0.8.16
- [ ] v0.8.15
- [ ] v0.8.14
- [ ] v0.8.13
- [ ] v0.8.12
- [ ] v0.8.11
- [ ] v0.8.10
- [ ] v0.8.9
- [ ] v0.8.8
- [ ] v0.8.7
- [ ] v0.8.6
- [ ] v0.8.5
- [ ] v0.8.4 - v0.8.1
- [ ] v0.8.0 (Polkadot Release)
**End Polkadot Versions, the rest is only Kusama**
- [ ] v0.7.33
- [ ] v0.7.32
- [ ] v0.7.30
- [ ] v0.7.29
- [ ] v0.7.28
- [ ] v0.7.27
- [ ] v0.7.26
- [ ] v0.7.25
- [ ] v0.7.24
- [ ] v0.7.23
- [ ] v0.7.22
- [ ] v0.7.21
- [ ] v0.7.20
- [ ] v0.7.19
- [ ] v0.7.18
- [ ] v0.7.17
- [ ] v0.7.16 - v0.7.11 ? ( No native version in release notes, hotfixes)
- [ ] v0.7.9
- [ ] v0.7.8
- [ ] v0.7.7
- [ ] v0.7.6
- [ ] v0.7.5
- [ ] v0.7.4
- [ ] v0.7.3
- [ ] v0.7.2
- [ ] v0.7.1
- [ ] v0.7.0
- [ ] v0.6.18
- [ ] v0.6.17
- [ ] v0.6.16
- [ ] v0.6.15 - v0.5.0
</details>

Summary: v0.8.22 - v0.8.0 for full-tracing support in Polkadot (19 total versions)

**Comment by rphmeier** [comment]
stale
