### ISSUE TITLE
Remove flag which disables authority discovery

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1848]
> @mxinden what is the reason authority discovery is still "optional"?

The authority discovery module was not mandatory thus far. The flag would allow a smoother feature roll out. I.e. first put it behind a feature flag then enable it by default but allow to disable it and eventually remove the possibility of disabling it.

Given that with the introduction of the _overseer_ the authority discovery module becomes mandatory on authority nodes, I would suggest removing the flag entirely, always starting the authority discovery module on validator and sentry nodes. (The latter being deprecated https://github.com/paritytech/substrate/issues/6845.)

Would that solve the issue at hand?

_Originally posted by @mxinden in https://github.com/paritytech/polkadot/pull/1795#discussion_r504445370_

**Comment by rphmeier** [comment]
I still believe that authority-discovery should be opt-in for your typical full node. We don't need the thousands of full nodes on the network all attempting to speak to authorities directly.

**Comment by rphmeier** [comment]
So I propose _either_ a `--enable-authority-discovery` which `--validator` and Cumulus `--collator` imply, _or_ for it to be an internal configuration that we enable only for validators and collators.

**Comment by mxinden** [comment]
> We don't need the thousands of full nodes on the network all attempting to speak to authorities directly.

I agree.

> or for it to be an internal configuration that we enable only for validators and collators.

This is my preference. As a side effect it would reduce the configuration surface and thus the operational complexity.

**Comment by bkchr** [comment]
> or for it to be an internal configuration that we enable only for validators and collators.

I would also propose that we go this way.
