### ISSUE TITLE
Merging 1795 breaks metric collection regarding block production

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#1861]
Post #1795:

Block production: [it appears](https://0e5bbbe14f8e4118879f32bb65d57e30.europe-west3.gcp.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(message),filters:!(),index:'1f0d42a0-51b3-11ea-9dc7-693a2e5aea74',interval:auto,query:(language:kuery,query:'host:%20%22kusama-validator-ew4-0%22%20and%20message:%20%22Prepared%22'),sort:!())) that the burnin node is in fact producing blocks. We have not broken block production; we have broken metrics collection related to block production.

_Originally posted by @coriolinus in https://github.com/paritytech/polkadot/pull/1795#issuecomment-717327361_

**Comment by bkchr** [comment]
This was introduced earlier and is a bug on master: https://github.com/paritytech/polkadot/pull/1862
