### ISSUE TITLE
Sync block problem

### ISSUE THREAD

**Issue by 90hacker** [paritytech/polkadot#1882]
The node has been unsuccessful in synchronizing the block。
![image](https://user-images.githubusercontent.com/15024497/97526546-5ab54880-19e4-11eb-9c0a-c8c56ab7e6e8.png)

Need to shut down the process.
Re-run the software to succeed.

version：v0.8.25
system：Ubuntu 18.04.4 LTS

**Comment by bkchr** [comment]
Thank you for the report, but without any logs we can not do anything.
