### ISSUE TITLE
Implement SessionInfo module

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1891]
This module will store historical session info

Described in #1601

**Comment by jonasW3F** [comment]
That would be amazing! I rely with some statistical analysis on session data and being able to restore them (in the case our handler has a downtime and did not extract the session data on time) will help a lot!

**Comment by rphmeier** [comment]
I'm glad to hear that!

**Comment by ordian** [comment]
Closed by #2009.

**Comment by jonasW3F** [comment]
It seems the implementation is done? How can this be leveraged with polkadot.js/api? The idea would be to make queries that accepts sessionIndex as param to fetch session historical data.

**Comment by rphmeier** [comment]
@jonasW3F you can query the storage directly using Polkadot-JS

**Comment by mariopino** [comment]
@rphmeier Can you please provide a example? I can't see related queries in https://polkadot.js.org/docs/substrate/storage

**Comment by ordian** [comment]
you can find it on rococo with https://polkadot.js.org/apps/#/chainstate
![Screenshot from 2021-01-19 16-41-27](https://user-images.githubusercontent.com/4211399/105057255-55144f80-5a75-11eb-95aa-5eb306700f48.png)
