### ISSUE TITLE
`ValidatorIndex` is context-dependent but the docs don't explain that.

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#1899]
We have a type `ValidatorIndex` which is an alias to a u32 which represents a validator, as the docs say, in a lightweight manner. As far as I understand, the `ValidatorIndex` implicitly depends on the current validator set. The problem is the notion of current.

While we could update the `ValidatorIndex`'s docs,  I think there is a bigger problem. It is not immediately obvious what does "current" means. 

For example, let's take the AV subsystem (note that the issue is not limited to this particular area). It has the following message

```
/// Query an `ErasureChunk` from the AV store by the candidate hash and validator index.
QueryChunk(Hash, ValidatorIndex, oneshot::Sender<Option<ErasureChunk>>),
```

as far as I understand, this index is the index of a validator from the set of all active validators in the session when this candidate got backed, but that requires a bit of knowledge and requires some guess work. That seems to be inviting for some subtle issues.

**Comment by coriolinus** [comment]
Would it be better if `ValidatorIndex` were `(Era, u32)`? That would avoid ambiguity about what we mean when the validator set changes.

**Comment by pepyakin** [comment]
If it works, even better!

**Comment by rphmeier** [comment]
Obsoleted by #2403
