### ISSUE TITLE
Proxy Filter for governance calls that cannot result in a slash.

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#1910]
> Would be nice to have a filter for governance calls that cannot result in a slash.

https://github.com/paritytech/polkadot/pull/1890

Basically we just need to figure out which calls **could** result in a slash, and then create a filter which does not include those :)

A fun and easy research project!

**Comment by joepetrowski** [comment]
I'm going to mentor @midegdugarova and @CurlyBracketEffect on creating lists of "non-slashable", "fixed slashable", and "unbounded slashable". Then it would be a great task for one of the new devs to implement and benchmark if necessary.

**Comment by rphmeier** [comment]
stale?

**Comment by joepetrowski** [comment]
It's still possible, but probably less relevant to gov2, and time delay proxies introduce other protection mechanism that are less prone to going out of date with new calls/changes.
