### ISSUE TITLE
rs:160 using  substrate-alexander:v0.3.20

### ISSUE THREAD

**Issue by dave4you** [paritytech/polkadot#192]
Received the following message from the console:

.rs:160                                                                                                                                                      
This is a bug. Please report it at:                                                                                                                          
        https://github.com/paritytech/polkadot/issues/new 

Implementation Details:
Parity Polkadot                                                                                                                          
version 0.3.20-06fe5cc-x86_64-linux-gnu                                                                                                
by Parity Team <admin@parity.io>, 2017-2019                                                                                            
Chain specification: Alexander                                                                                                           
Roles: FULL

**Comment by rphmeier** [comment]
This is not the full error message, is it?

**Comment by rphmeier** [comment]
Closing pending further information.

**Comment by dave4you** [comment]
[Log.txt](https://github.com/paritytech/polkadot/files/3045122/Log.txt)
Hi Robert, 
I had to finish some work before I could attent to this issue.
Attached you find the details requested.
Kind regards,
Dave

**Comment by bkchr** [comment]
Please purge your db and use 0.4.3. This should hopefully fix your problems.

**Comment by dave4you** [comment]
Already done off course. 
Just didn't wat to give the impression I was leaving you hanging ;-)
Cheers

**Comment by bkchr** [comment]
So everything works now?

**Comment by dave4you** [comment]
No problems for some time. 0.3.19 was quickly followed by 0.3.20 so switched the new version right away. Running 0.4.3 since a few minutes.
