### ISSUE TITLE
Ledger support staking with only one account. 2nd one seems to fail

### ISSUE THREAD

**Issue by derfredy** [paritytech/polkadot#1927]
Various users at the Spanish telegram channel seems to have the same issue when staking with their ledgers.

The 1st account goes well, the 2nd fails.

This is the error message from polkadot.js.org/app

![image](https://user-images.githubusercontent.com/23276270/98442214-b037d680-2103-11eb-98c0-e55372b587de.png)

**Comment by shawntabrizi** [comment]
@derfredy can you open this in the https://github.com/polkadot-js/apps

Not much can be done here on Polkadot it seems.
