### ISSUE TITLE
fix polkadot path to follow linux convensions

### ISSUE THREAD

**Issue by pampatzoglou** [paritytech/polkadot#1931]
Polkadot binary should be moved back to its original path under `/usr/local/bin/polkadot` which is the correct location for binaries not installed via the distribution's package manager. The path `/usr/bin/polkadot` implies that Polkadot is installed via the package manager. For more details regarding the standard Linux hierarchy please visit https://www.pathname.com/fhs/pub/fhs-2.3.html.

The issue was introduced at https://github.com/paritytech/polkadot/pull/1799/files#diff-9dc5c8499f2e8713a11f92e74201b84919c98ab2085e9037a351a570878be0ccR40

**Comment by bkchr** [comment]
CC @s3krit

**Comment by ordian** [comment]
but it *is* installed via the `apt` package manager (line 31):
> apt install polkadot
