### ISSUE TITLE
Could you label the runtime migration PR?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot#1938]
Something like this https://github.com/paritytech/polkadot/pull/1914

I don't want to miss any migration, even the custom runtime upgrade.

Thanks.

**Comment by bkchr** [comment]
Why?

**Comment by AurevoirXavier** [comment]
Our chain is following Polkadot's upgrade. There're a lot benifits. And I think other teams would though like us. Polkadot is a good role model, we can always find a solution here if something wrong after a runtime upgrade.

Once there's a unexpected epoch change happened on Kusama, and you make a timewrap. That's awesome and we follow that part to fix our chain.

---

So our migration are almost same with Polkadot. I want to find them easily and perform it on out chain.

**Comment by bkchr** [comment]
Sounds more like this should be improved on the Substrate side, not from Polkadot.

Polkadot is just an implementation that uses Substrate and no reference for runtime upgrade.

@apopiak is taking care to improve the runtime upgrade experience.

**Comment by AurevoirXavier** [comment]
Yes, some optional or custom runtime upgrade doesn't labeled in substrate. I've to find its usage in Polkadot.

**Comment by apopiak** [comment]
> Sounds more like this should be improved on the Substrate side, not from Polkadot. 

It's difficult to improve the from the Substrate side, I'd say, because it is about examples of production runtime migrations. 

> Polkadot is just an implementation that uses Substrate and no reference for runtime upgrade.

In theory™ Polkadot is *just* an implementation, but in practice it will be a reference for runtime migrations as it's just the most mature Substrate chain. The question is how much we are willing to "give in" to that. ;-)

**Comment by bkchr** [comment]
Migrations that are done from the Polkadot side are most often Polkadot specific, this means you will need to write them different for another chain. 

Maybe we should have some side where we link these runtime upgrades and a potential link to how it was done in Polkadot.

**Comment by bkchr** [comment]
> Yes. But some optional or custom runtime upgrade doesn't labeled in substrate. I've to find their usage in Polkadot.

Okay, that sounds like we missed this in Substrate and that shouldn't happen ;)

**Comment by AurevoirXavier** [comment]
> Migrations that are done from the Polkadot side are most often Polkadot specific, this means you will need to write them different for another chain.
> 
> Maybe we should have some side where we link these runtime upgrades and a potential link to how it was done in Polkadot.

Sounds good. An example linking.

**Comment by apopiak** [comment]
> > Yes. But some optional or custom runtime upgrade doesn't labeled in substrate. I've to find their usage in Polkadot.
> 
> Okay, that sounds like we missed this in Substrate and that shouldn't happen ;)

Well https://github.com/paritytech/substrate/pull/6969 is not labeled with `D1-runtime-migration` because it does not contain a migration. But it does contain code to perform a migration. Not sure how we should label that. :thinking:

**Comment by bkchr** [comment]
We should probably label it, because people will need to run a migration for it.

**Comment by AurevoirXavier** [comment]
> Well [paritytech/substrate#6969](https://github.com/paritytech/substrate/pull/6969) is not labeled with `D1-runtime-migration` because it does not contain a migration. But it does contain code to perform a migration. Not sure how we should label that.
 
[D2-optional-runtime-migration]?

**Comment by apopiak** [comment]
I labeled it with `D1` and changed the description of the label.

**Comment by AurevoirXavier** [comment]
> I labeled it with `D1` and changed the description of the label.

Thanks.

**Comment by apopiak** [comment]
The Substrate PR has a link to the companion PR that includes the migration.

Also, created a repo to collect the migrations and notes on them here:
https://github.com/apopiak/substrate-migrations
