### ISSUE TITLE
How to withdraw my proposal?

### ISSUE THREAD

**Issue by zhouziyan** [paritytech/polkadot#1943]
I submitted a proposal in page:
https://polkadot.js.org/apps/#/democracy

The number is 8.

Could anybody share me the method to withdraw a proposal I submitted? I'd like to test if the reversed token can be unfrozen.

**Comment by bkchr** [comment]
CC @rrtti

**Comment by zhouziyan** [comment]
@rrtti zhouziyan

**Comment by rrtti** [comment]
Motion 41 on Polkadot aims to cancel the proposal, as requested by the submitter. More info on the motion can be found here.
