### ISSUE TITLE
Guide: Disputes Subsystems

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1977]
#2424 added a high-level description of disputes, some basic types, and the disputes runtime.

## Goals

This issue is for the node-side subsystems that lead to participation in these disputes. There are five major roles that validator nodes must participate in when it comes to disputes
  1. Detection. Detect bad parablocks, either during candidate backing or approval checking, and initiate a dispute.
  1. Participation. Participate in active disputes. When a node becomes aware of a dispute, it should recover the data for the disputed block, check the validity of the parablock, and issue a statement regarding the validity of the parablock.
  1. Distribution. Validators should notify each other of active disputes and relevant statements over the network.
  1. Submission. When authoring a block, a validator should inspect the state of the parent block and provide any information about disputes that the chain needs as part of the `ParaInherent`. This should initialize new disputes on-chain as necessary.
  1. Fork-choice and Finality. When observing a block issuing a `DisputeRollback` digest in the header, that branch of the relay chain should be abandoned all the way back to the indicated block. When voting on chains in GRANDPA, no chains that contain blocks that are or have been disputed should be voted on.

## Dispute Coordinator

This component is responsible for coordinating other subsystems around disputes.

This component should track all statements received from all validators over some window of sessions. This includes backing statements, approval votes, and statements made specifically for disputes. This will be used to identify disagreements or instances where validators conflict with themselves.

This is responsible for tracking and initiating disputes. Disputes will be initiated either externally by another subsystem which has identified an issue with a parablock or internally upon observing two statements which conflict with each other on the validity of a parablock.

No more than one statement by each validator on each side of the dispute needs to be stored. That is, validators are allowed to participate on both sides of the dispute, although we won't write code to do so. Such behavior has negative EV in the runtime.

This will notify the dispute participation subsystem of a new dispute if the local validator has not issued any statements on the disputed candidate already.

Locally authored statements related to disputes will be forwarded to the dispute distribution subsystem.

## Dispute Participation

This subsystem ties together the dispute tracker, availability recovery, candidate validation, and dispute distribution subsystems. When notified of a new dispute by the Dispute Tracker, the data should be recovered, the validation code loaded from the relay chain, and the candidate is executed. 

A statement depending on the outcome of the execution is produced, signed, and imported to the dispute tracker.

## Dispute Distribution

This is a networking component by which validators notify each other of live disputes and statements on those disputes.

Validators gossip dispute votes to each other

## Dispute Chain Activity

This component has 3 roles:
1. Providing data to a chain while authoring. Given a block hash, returns a set of dispute votes to be submitted to the chain. This is based on the `known_disputes` runtime API and draws data from the Dispute Coordinator.
2. Enhancing the finality voting rule. Given a set of `(CandidateHash, BlockNumber, BlockHash)`, it returns the `BlockHash` corresponding to the highest `BlockNumber` that there are no disputes before. I expect that we will slightly change `ApprovalVoting::ApprovedAncestor` to return this set and then the target block to vote on will be further constrained by this function.
3. Chain roll-backs. Whenever importing new blocks, the header should be scanned for a roll-back digest. If there is one, the chain should be rolled back according to the digest. I expect this would be implemented with a `ChainApi` function and possibly an `ApprovalVoting` function to clean up the approval voting DB.

**Comment by rphmeier** [comment]
For the dispute distribution subsystem, I don't see any immediate need for it to actually be a networking component. Instead I'll introduce a runtime API for drawing dispute votes from the chain. Validators will learn about disputes a little slower this way, presumably after the first validator aware of the dispute initiates the vote on-chain. This will pose a problem in the future if there are long runs of malicious validators who refuse to initiate on-chain disputes, but we can reasonably defer defense against such highly collusive attack vectors for the initial implementation and add an actual networking component in a couple of months.

**Comment by burdges** [comment]
We'd still copy disputes from one chain to another though, right?

**Comment by rphmeier** [comment]
Yeah, as blocks are authored on those chains.
