### ISSUE TITLE
guide: GRANDPA voting rule

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#1980]
We want a GRANDPA voting rule that:
  * does not vote on blocks which haven't been approved. we can determine this with a call to `ApprovalVoting::ApprovedAncestor`
  * does not vote on blocks where there are any live disputes which would trigger a rollback to before that point. It's likely easiest to just abstract over that in this point and do the implementation of that message in the dispute participation subsystem (#1977)

**Comment by burdges** [comment]
We de facto lock disputed parachains because we lock backed parachain cores until they become available and get included.  We might ensure core rotation leaves the disputed parachain locked though.  We do not afaik actually lock the parachain until its dispute concludes, although mabye we should do so, not sure..

**Comment by rphmeier** [comment]
> We de facto lock disputed parachains because we lock backed parachain cores until they become available and get included. 

I was not aware of this - neither of the guide and code mention this. My feeling was that we'd accept disputes on included blocks only, anyway, as there isn't much use disputing something pre-availability.

**Comment by burdges** [comment]
A priori, we'd accept remote disputes on anything I'd think.  Yes, if it never gets included anyplace then sure maybe it's less risky, but actually understanding remote inclusion kinda sucks.  I'd envisioned accepting local or remote disputes without inclusions evidence, but if the disputed candidates were not yet availabile then we continue its availability run off-chain.  We time out eventually but could be restarted manually I guess.

Imagine we've a parachain P and relay chain forks X and Y with X1 backing U on P and Y1 backing V on P.  If we then dispute V on Y then we'll dispute V on X but should we lock P on X?  I think no..

**Comment by rphmeier** [comment]
Closed by #2112
