### ISSUE TITLE
Improve integration testing by rust harness code

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#1991]
Adding re-usable harness code, for improved testing caps, that would yield an improved test experience and assertiveness over the current shell based test runs.

**Comment by bkchr** [comment]
What is this issue about?

Can you please explain it.

**Comment by drahnr** [comment]
This is issue is about creating additional infrastructure/harness code to validate execution flow based on expected prometheus metrics emitted for given input transactions.
As you already pointed out, the input side is covered. The output side afaiu is not.

**Comment by sandreim** [comment]
obsoleted by Zombienet
