### ISSUE TITLE
api.query.sudo is undefined

### ISSUE THREAD

**Issue by fwh1990** [paritytech/polkadot#2007]
I have setup a server by docker image `parity/polkadot` in --dev mode, and then I want to set balance to local address. However, when I invoke `await api.query.sudo.key()`, the terminal just report error: 
```
TypeError: Cannot read property 'key' of undefined
```
It means sudo is undefined. What should I do to make sudo available?

My code looks like:
```typescript
await waitReady();
const api = await ApiPromise.create({ provider: new WsProvider('ws://127.0.0.1:9944') });
await api.isReady;
const sudoKey = await api.query.sudo.key();
```

**Comment by bkchr** [comment]
Neither Polkadot nor Kusama runtimes contain sudo anymore.

**Comment by fwh1990** [comment]
Is any way to make it work?

**Comment by bkchr** [comment]
You can use Westend

**Comment by fwh1990** [comment]
Well, it works again. Maybe the document is out of date : https://polkadot.js.org/docs/api/start/api.tx.wrap#sudo-use

**Comment by fwh1990** [comment]
Thank you
