### ISSUE TITLE
chill() does not take effect

### ISSUE THREAD

**Issue by derfredy** [paritytech/polkadot#203]
It appears to be a bug in the validator selection algorithm, specifically when there are more slots than validators.

parity-polkadot v0.3.21
Testnet Alexander

Gui: https://polkadot.js.org/apps/#/explorer

How did I reproduce the error:

 I sent 1DOT more to that account in order to ensure there is enougth to pay fees. Then I went to extrinsics -> staking -> chill() I submited the TX. It said Success. Waited for new era but my account seems locked.

The locked account in this case is: 5GoFreeEQLTr7ACQ9PuX9g9ZP6en9DmV3U3v8GzBwVLBkqty

![chill-error](https://user-images.githubusercontent.com/23276270/55324070-42d0b800-5481-11e9-80a6-29f5a353d19d.png)

**Comment by rphmeier** [comment]
`chill` removes you from the list of validators -- can you clarify what you mean by `locked`? you have to unbond if you want to move the funds, and this takes some time to take effect (1 day on the testnet, AFAIK).
