### ISSUE TITLE
A question about the length of polkadot's address, sometimes it would be 47. 

### ISSUE THREAD

**Issue by bruce1ee** [paritytech/polkadot#2032]
On polkadot's main network, the address length is 48. I used ed25519 algorithm, the address length sometimes would be 47. When it would be 47 or when it would be 48?

I generated 100 addresses. The length of 78 addresses is 48, and the other is 47.

**Comment by bruce1ee** [comment]
I found it would be base58 encoding. I tested 10000 encoding cases, their length was always to be 47 or 48.

**Comment by rphmeier** [comment]
https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)
