### ISSUE TITLE
Ws connection failed!

### ISSUE THREAD

**Issue by jaslin-W** [paritytech/polkadot#2063]
hello, polkadot teams.
The polkadot version is v0.8.26-1
OS: debian
I have encountered a strange problem. Sometimes When i start polkadot with this blew command, i get a ws connection error.I have try to figure out this, but no idea. Now the solution i found is to restart
```
exec /usr/bin/polkadot --chain=polkadot-local \
--alice -d /tmp/alice \
--rpc-external \
--ws-external \
--node-key 0000000000000000000000000000000000000000000000000000000000000001 &
exec /usr/bin/polkadot --chain=polkadot-local --bob -d /tmp/bob --port 30334 \
--bootnodes '/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
```
![polk](https://user-images.githubusercontent.com/65018397/100962219-dfa0fe00-355e-11eb-9127-dc94b34ba14a.png)

**This is log. I don't see any error**

**[dot_daemon.log](https://github.com/paritytech/polkadot/files/5633610/dot_daemon.log)**

**Comment by shawntabrizi** [comment]
@jaslin-W Are there any errors in your browser terminal?

**Comment by jaslin-W** [comment]
it always shows it is Initializing connection.  And i run this command.
`polkadot-js-api tx.balances.transfer 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty 12345 --seed "//Alice"`

it shows

```
2020-12-03 14:18:21          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
_Event {
  type: 'error',
  isTrusted: false,
  _yaeti: true,
  target: W3CWebSocket {
    _listeners: {},
    addEventListener: [Function: _addEventListener],
    removeEventListener: [Function: _removeEventListener],
    dispatchEvent: [Function: _dispatchEvent],
    _url: 'ws://127.0.0.1:9944',
    _readyState: 3,
    _protocol: undefined,
    _extensions: '',
    _bufferedAmount: 0,
    _binaryType: 'arraybuffer',
    _connection: undefined,
    _client: WebSocketClient {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      config: [Object],
      _req: null,
      protocols: [],
      origin: undefined,
      url: [Url],
      secure: false,
      base64nonce: 'nlSBrTeffkoc98M+y6P6/w==',
      [Symbol(kCapture)]: false
    },
    onclose: [Function: value],
    onerror: [Function: value],
    onmessage: [Function: value],
    onopen: [Function: value]
  },
  cancelable: true,
  stopImmediatePropagation: [Function (anonymous)]
}
```

this is ports info in my mac. I run polkadot node in docker.
![ports](https://user-images.githubusercontent.com/65018397/100971954-e0438f80-3572-11eb-826e-fe45ab7f5967.png)

**Comment by jaslin-W** [comment]
![Uploading polkadot.png…]()

**Comment by jaslin-W** [comment]
@shawntabrizi

**Comment by shawntabrizi** [comment]
If you run your node in docker, you cannot directly access it from that port. There are some tricks you need to do in order to interact with a docker node (which should be pretty standard for any service running inside docker), but i do not know those steps, sorry.

**Comment by jaslin-W** [comment]
I have expose this 8080, 9944 and 9933 port. And i also add substrate-api-sidecar into docker image. And it is ok to connect. 8080 is for add substrate-api-sidecar.
 <img width="1231" alt="docker" src="https://user-images.githubusercontent.com/65018397/101119428-4a693c80-3626-11eb-847f-3af0737cd126.png">

![image](https://user-images.githubusercontent.com/65018397/101119375-2b6aaa80-3626-11eb-84d9-33a3876a1eda.png)

**Comment by kaichaosun** [comment]
Can you try debug the connection first in docker, then outside of docker with plain http connection and websocket connection?
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_localPeerId", "params":[]}' http://localhost:9933
```
WebSocket use 9944 by default, http use 9933 by default.

**Comment by jaslin-W** [comment]
execute in docker

![image](https://user-images.githubusercontent.com/65018397/101120778-75a15b00-3629-11eb-81e3-fb71c360d45d.png)

**Comment by kaichaosun** [comment]
Ping me on riot `@kaichao:matrix.parity.io`, I will help you on the debug.

**Comment by jaslin-W** [comment]
log show:
```
2020-12-03 03:36:28  👶 Starting BABE Authorship worker    
2020-12-03 03:36:28  Unable to listen on 0.0.0.0:9944    
2020-12-03 03:36:28  Unable to bind RPC server to 0.0.0.0:9944. Trying random port.   
```
so sometime 9944 connect fail. I think it is not the problem of polkadot.
Thanks for all.

**Comment by jaslin-W** [comment]
i start two nodes. both they want to use 9944. But only alice expose 9944 to docker outside. So when she doesn't bind to 9944. the outside can't connect to 9944. without` --ws-external`, the node also open ws

**Comment by Stefie** [comment]
> i start two nodes. both they want to use 9944. 

You should be able to re-assign the port of the second node from 9944 to 9945 (on anything else) by passing 
`--port 9945:9944` to it

**Comment by Floxter** [comment]
Same problem here (running on vps without docker).

![image](https://user-images.githubusercontent.com/83981055/125867428-7f6a58c7-b501-4dc2-9c0c-66f6517e6ebf.png)
