### ISSUE TITLE
Ran out of free WASM instances

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot#2070]
When starting recent Polkadot builds (compiled with `--features=real-overseer`; not sure whether that matters) I get several ocurences of the warning `Ran out of free WASM instances` It seems to be harmless, but I'm not sure wht it means or why it is caused.

**Comment by bkchr** [comment]
Will be fixed by https://github.com/paritytech/polkadot/pull/2069

**Comment by autocatalytic** [comment]
Getting this in logs for Kusama validator node (waiting state).
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
PRETTY_NAME="Ubuntu 20.04.2 LTS"

$ ./target/release/polkadot --version
polkadot 0.8.30-4b86755c3-x86_64-linux-gnu
