### ISSUE TITLE
How to query information from relay chain through the `VMP` ?

### ISSUE THREAD

**Issue by JNhua** [paritytech/polkadot#2074]
# Question
For example, parachain nodes need to query Alice's balance and Bob's identity of the relay chain. We need vertical message passing for trustful messages, rather than using the `OCW`. How to query information from relay chain through the `VMP` ?
# Opinion
We need a unified fixed interface to initiate query requests through the `UMP`.  And then relay chain delivers the information to the parachain through the `DMP`.

**Comment by pepyakin** [comment]
While having an unified interface sounds good, I think that burdening the relay-chain with this requests is a bit too much. On the bright side, one can extract the required information using storage proofs.
