### ISSUE TITLE
Guide: Relax slashing on pre-backing disputes 

### ISSUE THREAD

**Issue by burdges** [paritytech/polkadot#2078]
We expect parachain validator groups should be larger than one validator to improve liveness.  It maybe improves availability distribution too, although this remains dubious since reconstruction should work symmetrically with only one validator receiving.

If parachain validator groups have size n=3 (resp. n=5) then we'd demand k=2 (resp. k=3) backing votes before proceeding into availability.  We're currently worried that requiring either n=4 and k=3 or else n=5 and k=4 harms liveness too much, but we'd consider these later if liveness turned out really good in practice, group rotate between parachains fast, and we feel more nervous about wasm timing.  

We believe an incorrect invalid dispute vote could be slashed much less than 100%, maybe 10% or even 1%, whatever pays for the escalation.  We'll do these slashes with our fancy slashing system https://github.com/w3f/research/blob/master/docs/polkadot/slashing/npos.md which makes them start like 5% or 0.5% respectively.  

Anytime a candidate actually gets backed by k-of-n parachain validators, then if that candidate later turns out invalid then we have a soundness violation that requires we slash a full 100% and kick them permanently.  We expect governance should usually uncover bugs and revert these slashes, but soundness violations are very bad.

If however a candidate only gets backed by less than k parachain validators, and someone disputes it, then we do not have a soundness violation per se.  We still escalate so we require at least the same slashing as incorrect invalid dispute vote, so 10% or 1% via the normal fancy slashing system.

Implementing this gives us near perfect protection against extremely rare bugs like CPU failures and many rowhammer attacks.  It improves our resilience against WASM timing bugs since frequently the bug gets discovered in a 1-of-3 situation.  

It also requires patience from hackers who can only compromise a few machines because now they should wait until those machines land within the same parachain validator group.  We rotate group composition only every few hours, so this could require a considerable wait.

**Comment by rphmeier** [comment]
> If however a candidate only gets backed by less than k parachain validators, and someone disputes it, then we do not have a soundness violation per se. We still escalate so we require at least the same slashing as incorrect invalid dispute vote, so 10% or 1% via the normal fancy slashing system.

@burdges There is a lot of hidden complexity here. Local disputes can fairly easily determine who the backing validators were for a given parachain candidate and see how many backing votes have been submitted to the dispute. Remote disputes don't have an easy way of determining this in full accuracy, because they don't know at what block number the session started on the remote chain.

**Comment by burdges** [comment]
Yes, we cannot do this if we risk not seeing all the backers, which really then requires consensus among the backers.  Ick!  

I'd judge this not worth the effort for the foreseeable future then.  We've far more important matters than reducing a slash that should be reverted anyways from 100% to 10%.

**Comment by burdges** [comment]
I'd almost suggested we close this, except actually.. 

There is a simple consensus protocol for 2-of-3 backers, first one backer signs the candidate receipt and second another signs their signed message.  If they both sign the candidate receipt, but neither signs the other's signature, then we do not consider the candidate backed yet. 

We could therefore leave this open as a future defense against weak hackers, cosmic rays, weak rowhammer attacks, etc.  We must settle the k-of-n required for backers before implementing this though, which pushes this off until past 1000 validators, and maybe based hierarchical really chains.  Fine.

**Comment by rphmeier** [comment]
Closing but could reopen and move to a "distant future" milestone

**Comment by burdges** [comment]
We'll file this under some future issue for tuning the parachain backing checker group size, because this makes sense only if group sizes stay about one.
