### ISSUE TITLE
Grandpa Voting suddenly fails and nodes crash.

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot#2086]
I was running a local (to my laptop) rococo-local test network with two validators (using custom keys, not Alice/Bob). The netwrok ran as expected for several thousand blocks. Then, suddenly, both validators crashed with this error:

```
2020-12-07 13:59:17  GRANDPA voter error: Signing("Failed to sign GRANDPA vote for round 4186 targetting 0xb1afb6c17e799771303da1e31a005e1382af043973a5a1adc8dc26e2645578e6")    
2020-12-07 13:59:17  Essential task `grandpa-voter` failed. Shutting down service.    
```

The complete steps I'm using to setup this network are written in detail here https://github.com/PureStake/moonbeam/blob/joshy-parachains-v1/launch-notes.md

In case it helps, I've collected about 6 minutes of logs from each validator before the crash. https://gist.github.com/JoshOrndorff/9775f34f4f709fddef8e4a9740dc5f02

**Comment by bkchr** [comment]
Cc @andresilva

**Comment by andresilva** [comment]
Can you confirm if anything changed on your local keystore? This seems like an error related to keys.

**Comment by JoshOrndorff** [comment]
I've been launching the network several times today, so there is a good chance I accidentally deleted my keystore while working on something else and didn't notice the crash until later.

If it happens again with the keys intact I'll reopen this issue.

Thanks for the help.
