### ISSUE TITLE
Prepare `SessionInfo` module to be used in practice

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2093]
After #2092 all runtimes will be aware of `Assignment` keys.

We have two issues right now:
  1. No way exists currently for the `AssignmentId`s to make their way into the `SessionChangeNotification`s issued by the `Initializer`. We'll need to find a way to wire both keys into the initializer, which Substrate's APIs haven't quite been designed for. Then it should be trivial to pull the `AssignmentId`s out of the `SessionChangeNotification` in `SessionInfo`.
  2. The `SessionInfo` module will initially have `EarliestSession` be `0`, but when introduced on a live chain that's been around for several thousand sessions (Kusama, Polkadot), it'll end up in a potentially heavy loop trying to prune all session info from `0..some_high_session_number`. We should work around this so enabling the `SessionInfo` module on existing chains is light.

**Comment by ordian** [comment]
For 1, an alternative would be to have a runtime module storing those keys for the current session and session info module fetching those keys as we do with the authority discovery keys. This works because of 1 block delay in the session change notification.

**Comment by rphmeier** [comment]
We could even have the `Initializer` be that module. We'd just have to implement the `OneSessionHandler` for some wrapper around `Initializer` like `AssignmentKeyHandler<Initializer>`
