### ISSUE TITLE
panic error while running a private network or connecting to a live testnet

### ISSUE THREAD

**Issue by telostia** [paritytech/polkadot#2114]
hi, I've tried many vps and different nightly versions.
I got it to build successful and can load up a solo chain but when i tried to run a private network , it gives me the following panic errors.. please help!!

this is one of the testnet i tried, it gives me the same error whether its from substrate-template or polkadot substrate.

Dec 12 22:50:01.766  INFO Substrate Node
Dec 12 22:50:01.766  INFO ✌️  version 2.0.0-37f7720-x86_64-linux-gnu
Dec 12 22:50:01.766  INFO ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
Dec 12 22:50:01.766  INFO 📋 Chain specification: DOT Mog Testnet
Dec 12 22:50:01.767  INFO 🏷  Node name: node01
Dec 12 22:50:01.767  INFO 👤 Role: AUTHORITY
Dec 12 22:50:01.767  INFO 💾 Database: RocksDb at ./tmp/validator-chain/chains/alpha_testnet/db
Dec 12 22:50:01.767  INFO ⛓  Native runtime: node-259 (substrate-node-0.tx1.au10)
Dec 12 22:50:02.156  INFO 👶 Creating empty BABE epoch changes on what appears to be first startup.
Dec 12 22:50:02.165  WARN Using default protocol ID "sup" because none is configured in the chain specs
Dec 12 22:50:02.173  INFO 🏷  Local node identity is: 12D3KooWBpzYzoeRrSYNzNAxRen9se45AbXNQWKHJ9ZvahykMNNQ (legacy representation: 12D3KooWBpzYzoeRrSYNzNAxRen9se45AbXNQWKHJ9ZvahykMNNQ)
Dec 12 22:50:02.434  INFO 📦 Highest known block at #0
Dec 12 22:50:02.475  INFO 〽️ Prometheus server started at 127.0.0.1:9615
Dec 12 22:50:02.494  INFO Listening for new connections on 127.0.0.1:9944.
Dec 12 22:50:02.495  INFO 👶 Starting BABE Authorship worker

====================

Version: 2.0.0-37f7720-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/core/src/option.rs:1234
   7: <libp2p_mdns::behaviour::Mdns as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   8: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,TConnInfo>::poll_next_event
  10: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  11: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: futures_executor::local_pool::block_on
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  19: tokio::runtime::task::raw::poll
  20: tokio::runtime::blocking::pool::Inner::run
  21: tokio::runtime::context::enter
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: core::ops::function::FnOnce::call_once{{vtable.shim}}
  24: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/sys/unix/thread.rs:87
  25: start_thread
  26: clone

**Comment by telostia** [comment]
this is the rustup show info:

~/substrate# rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2020-10-01-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2020-10-01-x86_64-unknown-linux-gnu (directory override for '/root/substrate')
rustc 1.48.0-nightly (ef663a8a4 2020-09-30)

**Comment by bkchr** [comment]
Did you tried Master?

**Comment by telostia** [comment]
yes, both master and nightly

**Comment by telostia** [comment]
hm. seems it worked when vps was reset after installation.. dunno why. some kinda of loose cache was running? If anyone has the same issue, please try resetting vps.. worked for me. cheers

**Comment by telostia** [comment]
no good... the problem reappears when service is stopped. When manually started it, it will just panic again.

**Comment by bkchr** [comment]
Can you please give a better description on how to reproduce this?

**Comment by telostia** [comment]
i made a bug report below which also appeared in node-template, i'll close this thread.

https://github.com/substrate-developer-hub/substrate-node-template/issues/121
