### ISSUE TITLE
benchmark the inclusion inherent

### ISSUE THREAD

**Issue by coriolinus** [paritytech/polkadot#2124]
Right now the inclusion inherent uses an essentially arbitrary SWAG for its weight calculations. Someone with appropriate knowhow should properly [benchmark it](https://github.com/paritytech/polkadot/pull/2060#discussion_r544216629_).

**Comment by coriolinus** [comment]
Attn: @thiolliere @athei: I believe that you two are likely to have the right knowhow.

**Comment by athei** [comment]
Given that I don't even know what the inclusion inherent is I wouldn't be too sure of that. That said, there is surely I way I can help.

**Comment by rphmeier** [comment]
@athei Generally we need some help benchmarking and profiling the parachains runtime. The inclusion inherent is the inherent by which all data about parachain candidates and their availability enters the runtime, so it's important for us to understand how heavy this is in practice, and how this grows with the number of parachains and the number of validators.

**Comment by rphmeier** [comment]
This is done
