### ISSUE TITLE
Parachain upgrades within contextual execution

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#2158]
When a parachain candidate signals of an upgrade, this change is not enacted immediately, but rather with a delay. 

Currently, this delay countdown begins at the relay parent block (in contrast to inclusion or enactment). This is convenient since in that case the parachain/parathread can predict the relay parent number at which the code change has an effect.

However, with contextual execution, the candidates can be included with relay parent block that is older than one. Equally, that means that collators are free to collate a block with a relay parent of any age as long as it is within the session, therefore circumventing the `delay`.

Moreover, the upgrades are bookkept only based only on relay parent. Therefore, one can execute an upgrade sweep: multiple upgrades going back to back (from PoV of inclusion).

Example:

1. a candidate that carries an upgrade built at relay parent `R` is included at relay chain block `B`. The acceptance check passes because there were no prior upgrades. The upgrade is scheduled at `R + delay`.
2. a candidate that carries an upgrade built at relay parent `R+max(delay, freq)` is included at relay chain block `B+1`. The acceptance check passes since from it's PoV the upgrade is already activated and `freq` has passed. The upgrade is scheduled at `R+max(delay, freq)+delay`.
3. and so on

**Comment by bkchr** [comment]
> However, with contextual execution, the candidates can be included with relay parent block that is older than one. Equally, that means that collators are free to collate a block with a relay parent of any age as long as it is within the session, therefore circumventing the `delay`.

But don't we prevent to include a candidate that was build on a relay block with a lower number of the last relay block of the last included candidate?

And all this assumes that we have delays that are shorter than a session? I think the delay on main net was planed to be 1 day or similar.

**Comment by burdges** [comment]
> But don't we prevent to include a candidate that was build on a relay block with a lower number of the last relay block of the last included candidate?

I'd expect so and this data should exist in the parachain's state on the relay chain.

**Comment by pepyakin** [comment]
> But don't we prevent to include a candidate that was build on a relay block with a lower number than the last relay block of the last included candidate?

No, or at least I haven't found the place where we do that.

> And all this assumes that we have delays that are shorter than a session? I think the delay on main net was planed to be 1 day or similar.

yup, I indeed assumed that more than one upgrade can fit in a session. I didn't know about the planned value, but I assumed it may be important for hot fixes or anything alike. If the delay or frequency is longer than a session, then I'd be happy since because I find the current construction really convenient from the PoV of cumulus.

**Comment by bkchr** [comment]
> No, or at least I haven't found the place where we do that.

We should clearly add such a check.



> yup, I indeed assumed that more than one upgrade can fit in a session. I didn't know about the planned value, but I assumed it may be important for hot fixes or anything alike. If the delay or frequency is longer than a session, then I'd be happy since because I find the current construction really convenient from the PoV of cumulus.

Let's wait for @rphmeier, however I think the delay was rather "big". If you need a fast hotfix, you probably need to use the council.

**Comment by bkchr** [comment]
Here in the original issue, you can find the proposed timings: https://github.com/paritytech/polkadot/issues/825

**Comment by rphmeier** [comment]
If you include a candidate in block `B` with `relay_parent_number = R`, the delay window will always go from `R..R+D` regardless of where `number(B)` falls in that window. That's the only way parachains can predict when the upgrade will happen.

Contextual execution windows will be small, because the goal is to include stuff that's narrowly missed the block authorship window. Not to include stuff that's even minutes old.
