### ISSUE TITLE
Log statement of candidate invalidity should contain the reason

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#2179]
Right now, if candidate is invalid and was rejected a log statement saying something like

```
2020-12-29 18:11:12  received invalidity note for candidate candidate_receipt=
CandidateReceipt 
{ 
    descriptor: 
        CandidateDescriptor 
        { 
            para_id: Id(600), 
            relay_parent: 0x24a4043c6626e60ba08c3399a78d421164265617e895318caefb3dfc1eb1f0cd, 
            collator: Public(2849e28115022f7c990ee3e64a17542cc38d9539c80cfeca55032f6196023469 (1ups6faP...)), 
            persisted_validation_data_hash: 0xf84c53edf4b12448b5fcc2f1e2039eb0e3b345abd4cdb6ce3230189ec4cdbd4a, 
            pov_hash: 0x2dbc6278e3b1c5f41c04f6481e0da3974ab0510e9be9d1165d84cdb300977de6, 
            erasure_root: 0x64a49122d87d0057718fa98bfc89bad6348858d1bdbb2ceaada8f8ecc4d9161b, 
            signature: Signature(9e568dcf7eefed48b91a7d40338dacebbbac5d6660926a7f1e5ccdd1b8fadf5713bd170b3a358181ec75ca034a95346a6c9fbcdfa76a8c919681a2a643134a85) 
        }, 
        commitments_hash: 0xae44e15b15e5205328e010c54fbfa99f62c67d088334bd3e2dfedece6c5b54ea 
}
```

will be printed.

This statement is of limited usability though, since it doesn't provide any details on why this candidate is invalid.

It would help quite a lot if we printed the reason.

**Comment by coriolinus** [comment]
We'd need to extend `CandidateSelectionMessage::Invalid` to contain the information about why a particular candidate was invalid, probably as a small enum. Maybe use `thiserror` to derive one with nice human-readable messages.

Possible reasons for invalidity:

- [wrong collator sent it](https://github.com/paritytech/polkadot/blob/0df0195a2e0c9eff76657cc51058394bca2d44a2/node/core/backing/src/lib.rs#L595-L599)
- [commitments mismatch](https://github.com/paritytech/polkadot/blob/0df0195a2e0c9eff76657cc51058394bca2d44a2/node/core/backing/src/lib.rs#L424)
- [erasure root mismatch](https://github.com/paritytech/polkadot/blob/0df0195a2e0c9eff76657cc51058394bca2d44a2/node/core/backing/src/lib.rs#L452)
- [core assumption was falsified](https://github.com/paritytech/polkadot/blob/0df0195a2e0c9eff76657cc51058394bca2d44a2/node/core/candidate-validation/src/lib.rs#L284-L287)
- [runtime didn't like the validation outputs](https://github.com/paritytech/polkadot/blob/0df0195a2e0c9eff76657cc51058394bca2d44a2/node/core/candidate-validation/src/lib.rs#L317-L321)
- `polkadot_node_primitives::InvalidCandidate` variants
- several various internal failures to communicate; those could probably be grouped into a single variant

**Comment by rphmeier** [comment]
we seem to get these now
