### ISSUE TITLE
Thread '<unnamed>' panicked at 'explicit panic'

### ISSUE THREAD

**Issue by dbpatty** [paritytech/polkadot#22]
Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)
Polkadot Version: parity-polkadot v0.2.16

 49:     0x562bfafcc7f4 - std::panicking::try::do_call::h14ad9761133d2f27
  50:     0x562bfb4ce079 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  51:     0x562bfaf80050 - <F as alloc::boxed::FnBox<A>>::call_box::h2fd6834e137777b8
  52:     0x562bfb4ad35a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h940efee7335c8f36
                        at /checkout/src/liballoc/boxed.rs:652
                         - std::sys_common::thread::start_thread::hac18b9ed82bd359d
                        at libstd/sys_common/thread.rs:24
  53:     0x562bfb4ab7c5 - std::sys::unix::thread::Thread::new::thread_start::ha15fdd35f58285a3
                        at libstd/sys/unix/thread.rs:90
  54:     0x7f87e8e6c6b9 - start_thread
  55:     0x7f87e898c41c - clone
  56:                0x0 - <unknown>

Thread '<unnamed>' panicked at 'explicit panic', /home/polkadot/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/304e9c7/protocols/secio/src/handshake.rs:465

**Comment by tomaka** [comment]
Thanks for the report. As you guessed, this is the same problem as #18. Therefore I'm closing as duplicate.
