### ISSUE TITLE
Balance downloads and uploads for parachain validation

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#220]
- [ ] https://github.com/paritytech/polkadot/blob/master/parachain/src/lib.rs#L82
- [ ] https://github.com/paritytech/polkadot/blob/master/parachain/src/lib.rs#L95

**Comment by rphmeier** [comment]
completed via XCM

**Comment by m-cat** [comment]
Can this comment be removed?

https://github.com/paritytech/polkadot/blob/master/parachain/src/primitives.rs#L357

```rs
// TODO: balance downloads (https://github.com/paritytech/polkadot/issues/220)
```
