### ISSUE TITLE
Docker images build with --features=real-overseer

### ISSUE THREAD

**Issue by whalelephant** [paritytech/polkadot#2238]
Any chance the docker image on https://hub.docker.com/r/parity/polkadot can be built with real-overseer feature for easy deployment of parachain testnets? 

Thanks!

**Comment by bkchr** [comment]
CC @TriplEight

**Comment by TriplEight** [comment]
Yeah, it's almost ready https://github.com/paritytech/polkadot/pull/2217/files

**Comment by whalelephant** [comment]
@TriplEight  thanks!

**Comment by whalelephant** [comment]
Hi, is there any update on this? Thanks!

**Comment by TriplEight** [comment]
Thanks for pinging, completelyy forgot to report here.
Yeah, it's around for a while and regularly updated. Can be found here: https://hub.docker.com/r/parity/rococo/tags?page=1&ordering=last_updated

**Comment by TriplEight** [comment]
`rococo-v1` being instead of the `latest`.
