### ISSUE TITLE
Consider cleaning up `PersistedValidationData`

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#2244]
With shifting of the way how we obtain required information in cumulus to merkle proofs, some things became redundant in `PersistedValidationData`.

It looks right now like this:

```rust
pub struct PersistedValidationData<N = BlockNumber> {
	/// The parent head-data.
	pub parent_head: HeadData,
	/// The relay-chain block number this is in the context of.
	pub block_number: N,
	/// The relay-chain block storage root this is in the context of.
	pub relay_storage_root: Hash,
	/// The list of MQC heads for the inbound channels paired with the sender para ids. This
	/// vector is sorted ascending by the para id and doesn't contain multiple entries with the same
	/// sender.
	pub hrmp_mqc_heads: Vec<(Id, Hash)>,
	/// The MQC head for the DMQ.
	///
	/// The DMQ MQC head will be used by the validation function to authorize the downward messages
	/// passed by the collator.
	pub dmq_mqc_head: Hash,
	/// The maximum legal size of a POV block, in bytes.
	pub max_pov_size: u32,
}
```

Having only the `relay_storage_root` we can reach to every other field, including `block_number` since we now have that in the storage.

**Comment by bkchr** [comment]
Just as a remark, changing this will make all parachains fail to validate and will require some upgrade/re-registration.

**Comment by rphmeier** [comment]
Yes, I think if we will do this we should do it soon

**Comment by pepyakin** [comment]
I am not sure if I follow: both block_number and relay_storage_root should refer to the same relay-chain block - the relay parent. Why do we need plus 1 and why don't we do it now?

**Comment by rphmeier** [comment]
@pepyakin Another bug introduced by #2123, I think :). It used to be that `persisted_validation_data` would deal with the child block number.

**Comment by pepyakin** [comment]
I guess that's a sign that we should rename `block_number` → `relay_parent_number`

**Comment by rphmeier** [comment]
I agree
