### ISSUE TITLE
Compiling libsecp256k1 error for polkadot v0.4.3

### ISSUE THREAD

**Issue by cool007zqw** [paritytech/polkadot#226]
Oddly, this error only occurred on VPS of Vultr.
I tried Debian 9.8 and Ubuntu 18.04 on the same instance and they all encountered the same error below.

I tried Windows Subsystem Linux Ubuntu 18.04 on my Desktop and it worked perfectly. So did an Ubuntu 18.04 VPS of Aliyun.

```

Compiling libsecp256k1 v0.2.2
error: failed to compile `polkadot v0.4.3 (/root/polkadot)`, intermediate artifacts can be found at `/root/polkadot/target`

Caused by:
Could not compile `libsecp256k1`.

Caused by:
  process didn't exit successfully: `rustc --crate-name secp256k1 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libsecp256k1-0.2.2/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=unwind -C metadata=5988480a32f4dde9 -C extra-filename=-5988480a32f4dde9 --out-dir /root/polkadot/target/release/deps -L dependency=/root/polkadot/target/release/deps --extern arrayref=/root/polkadot/target/release/deps/libarrayref-773d39469cbf75ea.rlib --extern digest=/root/polkadot/target/release/deps/libdigest-9e7e60a4e24b8be2.rlib --extern hmac_drbg=/root/polkadot/target/release/deps/libhmac_drbg-8224f96825ba6959.rlib --extern rand=/root/polkadot/target/release/deps/librand-8cceafe6485e5163.rlib --extern sha2=/root/polkadot/target/release/deps/libsha2-da57bba50420205d.rlib --extern typenum=/root/polkadot/target/release/deps/libtypenum-06d08f4c81e4ab65.rlib --cap-lints allow` (signal: 9, SIGKILL: kill)

```

**Comment by pepyakin** [comment]
My first guess would be that OOM killer kicked in and killed the compiler process because the system has ran out of physical memory and the system doesn't have enough virtual memory.

How much physical memory does VPS on Vultr have? Is swap configured?

**Comment by cool007zqw** [comment]
> 
> 
> My first guess would be that OOM killer kicked in and killed the compiler process because the system has ran out of physical memory and the system doesn't have enough virtual memory.
> 
> How much physical memory does VPS on Vultr have? Is swap configured?

512MB physical and very likely no swap (that VPS has been cancelled)

I think you are probably right since the other two machines that successfully compiles both have 16GB RAM.

Thank you!

**Comment by flyq** [comment]
> > My first guess would be that OOM killer kicked in and killed the compiler process because the system has ran out of physical memory and the system doesn't have enough virtual memory.
> > How much physical memory does VPS on Vultr have? Is swap configured?
> 
> 512MB physical and very likely no swap (the Vultr VPS has been cancelled so I can only speculate from my other Vultr instance)
> 
> I think you are probably right as the Aliyun VPS which successfully compiles has swap configured, even it only has 512MB physical RAM as well.
> 
> Thank you!

Yes, I get the same failed log when building libsecp256k1 of libp2p-rust, and I find [this](https://stackoverflow.com/a/34885004/5067875), and I build again, it succeed. the memory of  My aliyun ECS is 512 M.

**Comment by bkchr** [comment]
For anyone landing here, you probably need more swap :)
