### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at ...

### ISSUE THREAD

**Issue by base1217** [paritytech/polkadot#2275]
Node fault untypically. Faced first time with issues like this. 

 
====================

Version: 0.8.27-2f845699-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   5: std::panicking::begin_panic_fmt
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   6: tokio::time::wheel::Wheel<T>::poll
   7: tokio::time::driver::Driver<T>::process
   8: <tokio::park::either::Either<A,B> as tokio::park::Park>::park
   9: <tokio::runtime::park::Parker as tokio::park::Park>::park
  10: tokio::runtime::thread_pool::worker::Context::park_timeout
  11: tokio::runtime::thread_pool::worker::Context::run
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
  13: tokio::runtime::thread_pool::worker::run
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
  19: tokio::runtime::context::enter
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  23: start_thread
  24: clone

Thread 'tokio-runtime-worker' panicked at 'elapsed=146098222; when=146098216', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/time/wheel/mod.rs:223

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
How often does this occur?

**Comment by base1217** [comment]
It happened only once. Three days after upgrade to 0.8.27

**Comment by bkchr** [comment]
Okay, as this is not happening that often and it should probably fixed by this upstream fix:
https://github.com/tokio-rs/tokio/issues/2789

I will close this! There isn't that much more when can do, however ty for reporting it!
