### ISSUE TITLE
Finish implementing the collation protocol

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot#2283]
Two things still need to be done in order for the collation protocol to be considered production-ready:

- [x] Switch the collation protocol in Polkadot to use a request-response protocol.
- [ ] https://github.com/libp2p/rust-libp2p/issues/1849
- [x] address TODO introduced in https://github.com/paritytech/polkadot/pull/2287/files

cc @eskimor

**Comment by tomaka** [comment]
I'd add this to a milestone, but I have no idea what they mean.

**Comment by coriolinus** [comment]
Milestones are DC area subway stations (red line, possibly?) IIRC.

**Comment by eskimor** [comment]
Looks done to me.
