### ISSUE TITLE
Parachain Configuration and Parachain Registration must wait at least 1 full session

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2300]
Due to BABE, the validators and randomness of a session are already fixed in advance by one session.
We would like the validator groups to obey the same constraint, as it simplifies the process of tracking the state of parachain consensus of many forks across session changes, as done in the Approval Voting subsystem or in networking code that seeks to connect to the validators of the current and next session. Having consistency across sessions in small forks is desirable for simplicity, as we can expect a single longest chain to prevail within one session's time, as is assumed within BABE.

For this to work, we need to have fixed the number of Availability Cores in the scheduler, as this dictates the splitting of validators into groups. This is determined by the combination of the amount of registered parachains and configuration values - the number of parathread multiplexers, the maximum number of validators per core, and the maximum number of validators to be used in parachain consensus as a whole. We do not want any of these values, or indeed other values within `SessionInfo` to vary across forks.

To more clearly restate the problem, we would like to have the property that two blocks `B_a` and `B_b`, which each initiate a session `S + 1`, both descending from a block `B_s` which initiates session `S`, have the same parachain consensus state for `S + 1` - specifically, the validator groups, the validators' keys themselves, the number of cores, the parachains assigned to each core, among others.

This is clearly not the case under the status quo. Imagine that `B_a` and `B_b` differ in their chain only by their parent block `B_k` and `B_k'`, respectively. In `B_k'` if a new parachain is registered or a configuration change is made, it may affect the number of cores or the number of validators selected for each core, leading to an inconsistency that complicates the node-side code more than it is already.

```
          /--- B_k  -|- B_a
B_s .....
          \--- B_k' -|- B_b
                     |
                 session change
```

The solution is to have parachain registration and configuration updates take at least one full session. More specifically, it means that if the changes are submitted at any time during session `S`, then the changes will take effect at the start of session `S + 2`. The actual duration is somewhere between 1 and 2 full sessions, depending on at what point the change is submitted.

Some notes on parathreads:
  * Registering a parathread is OK at any time, as long as it's at least a full session before the parathread can submit any claims. In practice, it would be unwieldy to try and track this at the level of the `Scheduler` module where claims are submitted instead of the level of the `Paras` module where parathreads are submitted for registration.
  * Upgrading a parathread to a parachain would have to undergo the same "at least one session", as a parachain gets a reserved core.
  * De-registering a parachain would require the same.

In practice, this does mean a several-hours delay after an auction concludes in order to onboard. Viewed through the lens of slots which are months or even years long, this seems an acceptable trade-off to avoid an easy source of consensus bugs.

The actual concrete changes that need to be made to the codebase at the time of writing:
  * Parachain and Parathread onboarding should be delayed by 1 extra session
  * `HostConfiguration` updates should be modified similarly.

**Comment by shawntabrizi** [comment]
CC me

**Comment by burdges** [comment]
>   Registering a parathread is OK at any time, as long as it's at least a full session before the parathread can submit any claims. 

We might want code registered in advance, although maybe doing so creates problems for emergency fixes, rescue upgrades, etc.  If a parathread's code already exited by some mechanism then maybe registering need not wait a full session, not sure this matters.

>    Upgrading a parathread to a parachain would have to undergo the same "at least one session", as a parachain gets a reserved core.
>    De-registering a parachain would require the same.

Yes presumably.

**Comment by rphmeier** [comment]
We probably want something like a FIFO "actions queue" where any action (registration, upgrade, swap, deregister) takes at least 1 full session. Any code has to be present for that entire duration.

**Comment by burdges** [comment]
That sounds simplest and safest, but if anything looks particularly annoying then we can just think through the consequences.
