### ISSUE TITLE
Identity Judgement

### ISSUE THREAD

**Issue by AmazingBeerBelly** [paritytech/polkadot#2340]
Why my address is still Fee Paid after I passed the W3F Registrar verification?

![37501611727514_ pic](https://user-images.githubusercontent.com/25864116/106077664-ea39d700-614c-11eb-9b46-f3df5d29f292.jpg)

https://kusama.subscan.io/account/DJnHuVHDNefFoF71xKrGhxzA3Q6Rtkhh1PkY72RzybQKyhC?tab=extrinsic

And I have received the verified success message:

![37581611727794_ pic](https://user-images.githubusercontent.com/25864116/106077696-f887f300-614c-11eb-80af-519d1154bb09.jpg)
![37651611727907_ pic](https://user-images.githubusercontent.com/25864116/106077701-faea4d00-614c-11eb-815d-09048e7542e5.jpg)

Thanks a lot!

**Comment by lamafab** [comment]
@AmazingBeerBelly 
> https://kusama.subscan.io/account/DJnHuVHDNefFoF71xKrGhxzA3Q6Rtkhh1PkY72RzybQKyhC?tab=extrinsic

The registrar will not judge identities which contain Legal Name (or Web). The service is waiting for you to remove it, so please do that. Note that you **don't** have to clear the identity or request new judgement, just remove the field and update. Maybe also choose another Display Name, currently it publicly states "My Account 1". For example the value from Legal Name, "amazingbeerbelly"?

Also note that the service is unrelated to Polkadot itself. Ask question like those in our community channels on Element or similar. Thanks a lot.

**Comment by AmazingBeerBelly** [comment]
My address is "Reasonable" now! Thanks a lot!
