### ISSUE TITLE
Parachain Dot Accounting

### ISSUE THREAD

**Issue by nczhu** [paritytech/polkadot#235]
Enable parachains to be able to hold and handle Dots. 

This issue is related to parachain auctioning: #234  . This is a high priority item.

### Motivation
- To participate in an auction for obtaining a slot, a parachain needs to deposit DOTs. 
- A parachain candidate can issue additional native tokens in order to acquire DOTs. 
- If a parachain fails to obtain the slot, the returned DOTs can be used to buy back the native token and burn it.

More background available from @gavofyork. 

cc: @0x7CFE @FatemeShirazi

_Pls let me know if the above motivation for this issue is incorrect :)_

**Comment by gavofyork** [comment]
Should be done now.
