### ISSUE TITLE
Compilation failure 

### ISSUE THREAD

**Issue by donank** [paritytech/polkadot#235]
I am trying to setup a node in a google cloud VM instance with these specifications -
 
- 1 vCPU,
- RAM - 0.6 GB memory
- HDD - 100GB
- OS - Ubuntu 18.04

The error copied from terminal - 

> error: failed to compile `polkadot v0.1.0 (https://github.com/paritytech/polkadot.git?branch=v0.1#692a2cc0)`, intermediate artifacts can be found at `/tmp/cargo-install
> dnOehS`
> 
> Caused by:
>   Could not compile `ethereum-types`.
> 

I am not sure what am i supposed to do here? I came accros one more error previously 

> Could not compile `rayon-core`,

 it occured because the gcc package was missing. What package do i need for this? Or do i need to compile on a better system?

**Comment by 5chdn** [comment]
Please share the full log of the build log. What's your rust version?

**Comment by donank** [comment]
Rust Version - 1.27.0 

Verbose Build Output - [https://pastebin.com/52XvqeGu](url)

**Comment by tomaka** [comment]
The compiler stops with SIGKILL, which indicates out of memory.
Indeed, 0.6 GB of memory is really too low to compile any big Rust project.

You could try adding the `-j 1` flag, but the more reliable solution is to increase the amount of memory in the VM.

**Comment by 5chdn** [comment]
Or just create a 1GB swap. Will be slow but usually does the trick.
