### ISSUE TITLE
Rococo should be able to send XCM

### ISSUE THREAD

**Issue by shaunxw** [paritytech/polkadot#2405]
I was trying to do a cross-chain DOT transfer on rococo local network, but it failed and the dest parachain cannot receive `Xcm::ReserveAssetDeposit` message. It looks like to me the reason is Rococo V1 has [no XCM sender](https://github.com/paritytech/polkadot/blob/57eb9d10d874a27f2661523ce4b533aa690589c3/runtime/rococo/src/lib.rs#L550).

Rococo should be able to send XCM to help parachains on cross-chain DOT transfer.

**Comment by bkchr** [comment]
https://github.com/paritytech/cumulus/pull/322 does this fixes your problem?

**Comment by vgeddes** [comment]
@bkchr I think @shaunxw is correct. I was having the same issue even with https://github.com/paritytech/cumulus/pull/322. The  latter PR just fixes sending from the source chain. In my case the destination parachain chain never received the message, and it probably got stuck somewhere in the relay chain.

**Comment by shaunxw** [comment]
paritytech/cumulus#322 updated HRMP path. But to do a cross-chain DOT transfer(from parachain A to parachain B), Rococo needs to send downward XCM to children parachains.

Message passing in cross-chain DOT transfer(between two parachains) should work like this:
1. Source parachain sends XCM via UMP to Rococo.
2. Rococo updates source and dest chain reserve accounts.
3. Rococo sends XCM via DMP to dest chain, to notify reserve asset deposit.

Step 1 & 2 works perfectly fine, but step 3 never happen.

I'll try to make a pull request to fix this.
