### ISSUE TITLE
Error when run in dev mode

### ISSUE THREAD

**Issue by FilipLaurentiu** [paritytech/polkadot#241]
filip-vm@ubuntu-16:~$ polkadot --dev
2019-05-01 20:26:18 Parity Polkadot
2019-05-01 20:26:18   version 0.3.21-84917945-x86_64-linux-gnu
2019-05-01 20:26:18   by Parity Team <admin@parity.io>, 2017-2019
2019-05-01 20:26:18 Chain specification: Development
2019-05-01 20:26:18 Node name: living-driving-9787
2019-05-01 20:26:18 Roles: AUTHORITY

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h8421a7f2ddc9bf3a (0x5624728a10bf)
   1: rust_panic_with_hook (0x562472a67358)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::h8e929b2c1921f12e (0x5624720ceb24)
   3: <std::thread::local::LocalKey<T>>::with::h2248c1a41c46b6a6 (0x562472161b76)
   4: sr_io::with_storage::h446e583ff22db6d1 (0x562472126151)
   5: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::h044e77190f3fb8bc (0x5624720ec73f)
   6: <polkadot_runtime::GenesisConfig as sr_primitives::BuildStorage>::assimilate_storage::h69dd288fb71f5b34 (0x5624720c7421)
   7: sr_primitives::BuildStorage::build_storage::h58845fbbd50d8c57 (0x562471b8124e)
   8: <&'a substrate_service::chain_spec::ChainSpec<G> as sr_primitives::BuildStorage>::build_storage::h873aa0d154960241 (0x562471ec7679)
   9: <substrate_client::client::Client<B, E, Block, RA>>::new::h3368d434dd41c30c (0x562471e6b133)
  10: substrate_client_db::new_client::hcfca5ae5b3039358 (0x562471b3da9c)
  11: <substrate_service::components::FullComponents<Factory> as substrate_service::components::Components>::build_client::hdf2bab353a6626c1 (0x562471cf44ff)
  12: <substrate_service::Service<Components>>::new::hd14109f1db2aa94e (0x562471c69124)
  13: <polkadot_service::Factory as substrate_service::components::ServiceFactory>::new_full::h88e0be6a897f3849 (0x562471b0e153)
  14: substrate_cli::run_node::h50428385d61576a2 (0x5624719f4912)
  15: substrate_cli::parse_and_execute::h300c50bbc6fe1c70 (0x5624719ef1c7)
  16: polkadot::main::hda13f4050809a4c0 (0x562471a64e20)
  17: std::rt::lang_start::{{closure}}::hc42c1dfeb3ef75b1 (0x562471a5d922)
  18: {{closure}} (0x562472a66c72)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:297
  19: __rust_maybe_catch_panic (0x562472a6d139)
             at src/libpanic_unwind/lib.rs:87
  20: try<i32,closure> (0x562472a6783c)
             at src/libstd/panicking.rs:276
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  21: main (0x562471a64fb1)
  22: __libc_start_main (0x7fc14041c82f)
  23: _start (0x5624719531f8)
  24: <unknown> (0x0)

Thread 'main' panicked at 'assertion failed: T::Currency::free_balance(&stash) >= balance', /home/filip-vm/.cargo/git/checkouts/substrate-7e08433d4c370a21/8b92a59/srml/staking/src/lib.rs:488

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
This should be fixed in master/0.4, please update to one of these versions.

**Comment by FilipLaurentiu** [comment]
> This should be fixed in master/0.4, please update to one of these versions.

I will try, thx
