### ISSUE TITLE
"Trying to canonicalize invalid block" error after restart

### ISSUE THREAD

**Issue by nicolasochem** [paritytech/polkadot#2410]
After upgrading from 0.8.28.to 0.8.28-1 my database got corrupted. Node would consistently fail immediately upon restart with the following message:

```
│ 2021-02-09 17:04:42  GRANDPA voter error: Client(StateDatabase("Trying to canonicalize invalid block"))
│ 2021-02-09 17:04:42  Essential task `grandpa-voter` failed. Shutting down service.
│ Error:  
│    0: Other: Essential task failed.
│ Location:  
│    src/main.rs:25  
│   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
│    1: __libc_start_main<unknown>                                                     
│       at <unknown source file>:<unknown line>   
│ Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
│ Run with RUST_BACKTRACE=full to include source snippets.         
│ stream closed  
```

I am using the official docker container.

My node is not currently validating.

It is running in `pruning` mode with following args:

`--validator --wasm-execution Compiled --unsafe-pruning --out-peers=40 --pruning=1000 `

I could only solve it by deleting all storage and restoring from a snapshot.

I then updated another node, and there was no issue. So it is not a consistent problem. It may also have nothing to do with the upgrade from 0.8.28 to 0.8.28-1.

Unfortunately I no longer have access to the node in this state. I am opening a bug for tracking purposes, maybe other people see the issue as well.

**Comment by bkchr** [comment]
> After upgrading from 0.8.28.to 0.8.28-1 my database got corrupted.

Do you mean there was an actual db error before you got this grandpa error?

**Comment by nicolasochem** [comment]
No, sorry, what I refer to as "database error" is this grandpa error above. This happens immediately after starting the node.

**Comment by bkchr** [comment]
Did you force close the process before?

**Comment by nicolasochem** [comment]
Maybe yes. I killed the pod with kubernetes, which force closes the process if sigterm does not terminate it after some time (a few seconds).

**Comment by bkchr** [comment]
Yeah, this is probably the problem. I assume that this corrupted the db.

As this is nothing we can prevent from our side, I'm gonna close this.
