### ISSUE TITLE
kusama node keeps restarting

### ISSUE THREAD

**Issue by andreisid** [paritytech/polkadot#2428]
My kusama validator keeps restarting a couple of times / day
here is what i could find in my log:

Feb 12 17:24:39 kusama-st polkadot[13076]: 2021-02-12 17:24:39  💤 Idle (47 peers), best: #6179600 (0x8383…e3d0), finalized #6179598 (0x869d…32c1), ⬇ 2.0MiB/s ⬆ 2.4MiB/s
Feb 12 17:24:42 kusama-st polkadot[13076]: 2021-02-12 17:24:42  ✨ Imported #6179601 (0xca33…200a)
Feb 12 17:24:43 kusama-st polkadot[13076]: ====================
Feb 12 17:24:43 kusama-st polkadot[13076]: Version: 0.8.28-1-99043f78-x86_64-linux-gnu
Feb 12 17:24:43 kusama-st polkadot[13076]:    0: sp_panic_handler::set::{{closure}}
Feb 12 17:24:43 kusama-st polkadot[13076]:    1: std::panicking::rust_panic_with_hook
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
Feb 12 17:24:43 kusama-st polkadot[13076]:    2: std::panicking::begin_panic_handler::{{closure}}
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499
Feb 12 17:24:43 kusama-st polkadot[13076]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
Feb 12 17:24:43 kusama-st polkadot[13076]:    4: rust_begin_unwind
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
Feb 12 17:24:43 kusama-st polkadot[13076]:    5: std::panicking::begin_panic_fmt
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437
Feb 12 17:24:43 kusama-st polkadot[13076]:    6: libp2p_core::connection::manager::Manager<I,O,H,TE,HE>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:    7: libp2p_core::connection::pool::Pool<TInEvent,TOutEvent,THandler,TTransErr,THandlerErr>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:    8: libp2p_core::network::Network<TTrans,TInEvent,TOutEvent,THandler>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:    9: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
Feb 12 17:24:43 kusama-st polkadot[13076]:   10: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   11: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
Feb 12 17:24:43 kusama-st polkadot[13076]:   12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   17: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   18: std::thread::local::LocalKey<T>::with
Feb 12 17:24:43 kusama-st polkadot[13076]:   19: futures_executor::local_pool::block_on
Feb 12 17:24:43 kusama-st polkadot[13076]:   20: tokio::runtime::task::core::Core<T,S>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Feb 12 17:24:43 kusama-st polkadot[13076]:   22: tokio::runtime::task::harness::Harness<T,S>::poll
Feb 12 17:24:43 kusama-st polkadot[13076]:   23: tokio::runtime::blocking::pool::Inner::run
Feb 12 17:24:43 kusama-st polkadot[13076]:   24: tokio::runtime::context::enter
Feb 12 17:24:43 kusama-st polkadot[13076]:   25: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 12 17:24:43 kusama-st polkadot[13076]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 12 17:24:43 kusama-st polkadot[13076]:   27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
Feb 12 17:24:43 kusama-st polkadot[13076]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
Feb 12 17:24:43 kusama-st polkadot[13076]:       std::sys::unix::thread::Thread::new::thread_start
Feb 12 17:24:43 kusama-st polkadot[13076]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
Feb 12 17:24:43 kusama-st polkadot[13076]:   28: start_thread
Feb 12 17:24:43 kusama-st polkadot[13076]:   29: __clone
Feb 12 17:24:43 kusama-st polkadot[13076]: Thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: By (1)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.27.0/src/connection/manager.rs:408
Feb 12 17:24:43 kusama-st polkadot[13076]: This is a bug. Please report it at:
Feb 12 17:24:43 kusama-st polkadot[13076]:         https://github.com/paritytech/polkadot/issues/new
Feb 12 17:24:43 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=exited, status=1/FAILURE
Feb 12 17:24:43 kusama-st systemd[1]: polkadot-validator.service: Failed with result 'exit-code'.
Feb 12 17:25:43 kusama-st systemd[1]: polkadot-validator.service: Service hold-off time over, scheduling restart.
Feb 12 17:25:43 kusama-st systemd[1]: polkadot-validator.service: Scheduled restart job, restart counter is at 33.
Feb 12 17:25:43 kusama-st systemd[1]: Stopped Polkadot Validator.

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
cc @romanb do you have any opinion? :pray: 
There might be some race condition with a connection task closing.

**Comment by romanb** [comment]
> There might be some race condition with a connection task closing.

Could you elaborate on that suspicion? I'm currently puzzled to the point that I think I must be missing something very obvious. What I see is that [the code in question](https://github.com/libp2p/rust-libp2p/blob/master/core/src/connection/manager.rs#L348-L360) holds a mutable borrow to a `HashMap`, checks if `contains_key(id)` yields true for some key that is just a [newtype over a `usize`](https://github.com/libp2p/rust-libp2p/blob/master/core/src/connection/manager/task.rs#L42), and if true uses that same id immediately thereafter in a `HashMap::entry(id)` call. How could the former return `true` while the latter returns an `AbsentEntry` immediately after? :thinking:

**Comment by tomaka** [comment]
Sorry you're right, I only quickly glanced at the code and misread.
I'm also very confused.

**Comment by arkpar** [comment]
@andreisid Is that a physical machine? If so, could you try running [memtest](https://www.memtest.org/)?

**Comment by andreisid** [comment]
@arkpar it is a VPS, 6CPU/16G RAM. Unfortunately i don't have any memtest option in my cloud provider.

**Comment by andreisid** [comment]
journalctl -u polkadot-validator --since "72 hour ago"|grep "Main process exited"
Feb 16 20:12:34 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 16 22:37:37 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 16 23:03:36 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 02:01:03 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 02:28:26 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 13:16:17 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 14:24:20 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 14:46:28 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 15:03:47 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 15:19:24 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 17 16:13:06 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 03:15:49 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 03:38:03 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 04:49:27 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 10:46:59 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 11:07:13 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 15:01:27 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 17:45:15 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 18:04:19 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 19:26:22 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 18 19:35:07 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 19 05:08:55 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 19 07:47:43 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 19 11:55:02 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 19 12:28:11 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV
Feb 19 14:45:55 kusama-st systemd[1]: polkadot-validator.service: Main process exited, code=killed, status=11/SEGV

It looks like my validator restarts a couple of times/day . status=1/FAILURE means it restarted with the bug I posted, status=11/SEGV just crashes and restarts with no other info
