### ISSUE TITLE
Collator protocol should decrease peer reputation

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#2433]
The collator protocol collator side currently doesn't decrease peer reputation when someone sends us junk data that isn't expected.

**Comment by rphmeier** [comment]
Maybe can be done with the reputation refactoring https://github.com/paritytech/polkadot/issues/2184

**Comment by eskimor** [comment]
Apart from decreasing peer reputation on garbage, I think we should set [`in_peers`](https://github.com/paritytech/polkadot/blob/4377176446c17e46cb306d398cc21e435a8d0d0e/node/network/protocol/src/peer_set.rs#L59) to 0, as collators don't expect incoming connections right now, but just connect to the validators of its assigned group. This would mean that only staked validators we our selves connected to can send us garbage.

**Comment by xlc** [comment]
Not sure if I understanding correctly, but why collator should not allow incoming connections? We want it to receive transactions broadcasted by other nodes right?

**Comment by eskimor** [comment]
I am only talking about the collation peer set. The collator would still be able to accept connections on any other peer set. The collation peer set is only used for communicating with validators and there connections are opened by collators, as validators don't need to know what collators actually exist.

**Comment by bkchr** [comment]
> Uh, we use the same config for both validators and collators - so that does not work. Although it is kinda stupid to allow incoming connections for collators if we actually don't want them.

We should be able to pass some parameter that says if the node is a collator

**Comment by eskimor** [comment]
> We should be able to pass some parameter that says if the node is a collator

Yeah, currently looking into how to do this in a non hacky way.

**Comment by eskimor** [comment]
Given that we are now only connected to validators of the current backing group and that groups rotate anyway, I think this can be closed.
