### ISSUE TITLE
Reed-Solomon Erasure Optimization

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2442]

**Comment by drahnr** [comment]
The current implementation is really slow. We need to replace it with an algorithm that is faster and scales better.

* [x] Eval various papers to reduce the `O(...)` complexity
* [x] Choose a algorithm to implement in rust
* [ ] Implement a benchable first draft impl
* [ ] Understand algorithm better by simplification where possible
* [ ] Move `parity-erasure-encoding` to the new algorithm
* [ ] Refactor the implementation while maintaining performance
