### ISSUE TITLE
Integration tests for subsystems passing messages

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2443]
@drahnr Can you add some examples of tests here?

**Comment by drahnr** [comment]
The idea is to have chunks of the whole system covered, this implies `net -> Mod1 -> Mod2 -> Mod3 -> net` while the transported messages might differ and characteristic ones must be selected manually @coriolinus overview slides might come in handy to pick viable candidates to cover a lot of subsets.

Implementation steps:

* [ ] reduce the block time to as little as a couple of 100ms
* [ ] replace the bridge subsystem with a configurable mock
* [ ] create a macro to spawn those "strain" integration tests more easily

At this stage, the majority of the work is already done.

* [ ] run `coz` for individual tests to find lock congestions and bottlenecks

**Comment by drahnr** [comment]
This one has fallen a bit behind, it's essentially the integration of zombienet as cargo test runner with a pretty macro. It's on @pepoviola 's agenda (eventually)

**Comment by drahnr** [comment]
Closing, since the value of adding such a thing at this point is questionable compared to the effort required, given that we can anneal the use cases from both ends already.
