### ISSUE TITLE
Report error on Validator Kusama

### ISSUE THREAD

**Issue by dembuongactro** [paritytech/polkadot#2446]
Hello dev team,

I am Tien, I make Validator node for Kusama, I setup the second node and syncing database from the network. Today I check the service is not running and I check the log, they said that this is bug please report at there.

sudo systemctl status kusama.service
● kusama.service - Kusama Validator
     Loaded: loaded (/etc/systemd/system/kusama.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-02-16 20:46:16 +07; 3s ago
    Process: 12658 ExecStart=/home/kusama/polkadot/target/release/polkadot --validator --name=EMMANUEL --chain=kusama --max-parallel-downloads=250 --db-cache=10240 --in-peers=150 --out-peers=100 --telemetry-url wss://telemetr>
   Main PID: 12658 (code=exited, status=1/FAILURE)

Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:       std::sys::unix::thread::Thread::new::thread_start
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:              at rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:   50: start_thread
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:   51: clone
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]: Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x5f1d47dc7fab7bf13b2b8>
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]: This is a bug. Please report it at:
Feb 16 20:46:16 kusama.contaboserver.net polkadot[12658]:         https://github.com/paritytech/polkadot/issues/new
Feb 16 20:46:16 kusama.contaboserver.net systemd[1]: kusama.service: Main process exited, code=exited, status=1/FAILURE
Feb 16 20:46:16 kusama.contaboserver.net systemd[1]: kusama.service: Failed with result 'exit-code'.
lines 1-16/16 (END)

My VPS: CPU: 8 cores, RAM: 30GB, SSD: 800GB

What should I do in this case?

Thank you so much.

Tien.

**Comment by bkchr** [comment]
Your database is broken. There is nothing we can do. But still ty for the report.
