### ISSUE TITLE
[Docker] Can't mount folder /data

### ISSUE THREAD

**Issue by anhcao142** [paritytech/polkadot#2482]
It seems there is something wrong with the Dockerfile since no data is in `\data` after mounted. This happens in v0.8.28-1. I use docker-compose to run but you can test it with this command

```
docker run -d -p 30333:30333 -p 9933:9933 -v ~/polkadot-data:/data parity/polkadot:v0.8.28-1 --chain polkadot
```

If I do this, it works:
```
docker run -d -p 30333:30333 -p 9933:9933 -v ~/polkadot-data:/polkadot/.local/share parity/polkadot:v0.8.28-1 --chain polkadot
```

**Comment by bkchr** [comment]
CC @s3krit

**Comment by s3krit** [comment]
Hi @anhcao142 - this is due to a discrepancy between the Dockerfile in the `/docker` directory of our repo (which creates a symbolic link between /data and /polkadot/.local/share), and the Dockerfile used to create our release images (which currently doesn't). For the time being, your solution should work but I'll update our release Dockerfile to also create this link.

cheers

**Comment by anhcao142** [comment]
So that's why the linking is not working. When you are done updating, can you notify me?

**Comment by s3krit** [comment]
When we fix it, this issue will be closed as a result so that should notify you :)

**Comment by anhcao142** [comment]
Sorry to bother you but I see there is a newer version in DockerHub. Did you update the dockerfile?

**Comment by anhcao142** [comment]
Hi, It seems the symlink is not working as intended. When I try to run the docker with

```
docker run -d -p 30333:30333 -p 9933:9933 -v ~/polkadot-data:/data parity/polkadot:v0.8.28-1 --chain polkadot
```

it didn't find the old data and sync it from start, thus overwrite my old data. Now my data is corrupted and I have to sync from the start.

**Comment by anhcao142** [comment]
Sorry, nevermind, It's actually my fault. I migrate from the `chevdor` version and it has a different mounting path as `parity/polkadot`. Changing from `~/polkadot-data:/data` to `~/polkadot-data:/data/polkadot` solves the problem. No data was overwritten.
