### ISSUE TITLE
Please give me a recommended configuration for a full node, thank you

### ISSUE THREAD

**Issue by vae520283995** [paritytech/polkadot#2501]

**Comment by bkchr** [comment]
Please use google or whatever search engine you want to use

https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot

**Comment by vae520283995** [comment]
> Please use google or whatever search engine you want to use
> 
> https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot

Thank you, but I don't need to be a validator, I am an exchange, I only need to connect to the polkadot network and be able to synchronize block data.

**Comment by bkchr** [comment]
CC @joepetrowski

**Comment by joepetrowski** [comment]
There is no one configuration that will meet everyone's needs. Please read the integration guide: https://wiki.polkadot.network/docs/en/build-integration
