### ISSUE TITLE
Implement routing and fetching protocols for ICMP egress

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#253]
Every parachain candidate may produce egress to any other parachain. Collators of receiving parachains need to fetch all unrouted egress from all other parachains and combine them into an ingress queue which is used during creation and validation of new parachain candidates.

**Comment by GrapeBaBa** [comment]
@rphmeier I have a question about this. How collators of receiving parachains knows other parachains? It seems right now the collator pool only maintained by validators.

**Comment by rphmeier** [comment]
stale
