### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime

### ISSUE THREAD

**Issue by edag94** [paritytech/polkadot#2540]
Command ran: ./polkadot --chain=kusama --database=RocksDb --unsafe-pruning --pruning=1000 -d /datadrive

datadrive is an external SSD

Command line output:

2021-02-28 08:41:05  ----------------------------    
2021-02-28 08:41:05  This chain is not in any way    
2021-02-28 08:41:05        endorsed by the           
2021-02-28 08:41:05       KUSAMA FOUNDATION          
2021-02-28 08:41:05  ----------------------------    
2021-02-28 08:41:05  Parity Polkadot    
2021-02-28 08:41:05  ✌️  version 0.8.28-1-99043f78-x86_64-linux-gnu    
2021-02-28 08:41:05  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021    
2021-02-28 08:41:05  📋 Chain specification: Kusama    
2021-02-28 08:41:05  🏷 Node name: hesitant-car-3740    
2021-02-28 08:41:05  👤 Role: FULL    
2021-02-28 08:41:05  💾 Database: RocksDb at /datadrive/chains/ksmcc3/db    
2021-02-28 08:41:05  ⛓  Native runtime: kusama-2028 (parity-kusama-1.tx4.au2)    
2021-02-28 08:41:06  🏷 Local node identity is: 12D3KooWM9D59XU9saSQ6jECLY8awdghBDxMjnXgDZRm3dK6Ugv3    
2021-02-28 08:41:06  📦 Highest known block at #6396535    
2021-02-28 08:41:06  〽️ Prometheus server started at 127.0.0.1:9615    
2021-02-28 08:41:06  Listening for new connections on 127.0.0.1:9944.    
2021-02-28 08:41:06  🔍 Discovered new external address for our node: /ip4/52.250.109.215/tcp/30333/p2p/12D3KooWM9D59XU9saSQ6jECLY8awdghBDxMjnXgDZRm3dK6Ugv3    
2021-02-28 08:41:07  🔍 Discovered new external address for our node: /ip4/10.25.14.1/tcp/30333/p2p/12D3KooWM9D59XU9saSQ6jECLY8awdghBDxMjnXgDZRm3dK6Ugv3    

====================

Version: 0.8.28-1-99043f78-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268
   7: <sp_state_machine::ext::Ext<H,N,B> as sp_externalities::Externalities>::storage
   8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
   9: std::thread::local::LocalKey<T>::with
  10: sp_io::storage::get_version_1
  11: sp_io::storage::get
  12: frame_support::storage::unhashed::get
  13: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  14: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  15: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  16: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  17: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  18: <(TupleElement0,TupleElement1) as frame_support::traits::OnFinalize<BlockNumber>>::on_finalize
  19: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_extrinsics_with_book_keeping
  20: tracing::span::Span::in_scope
  21: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
  22: <kusama_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,kusama_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<kusama_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<kusama_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<kusama_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<kusama_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<kusama_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<kusama_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<kusama_runtime::Runtime>)>>>>::execute_block
  23: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
  24: std::thread::local::LocalKey<T>::with
  25: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  26: sc_executor::wasm_runtime::RuntimeCache::with_instance
  27: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  28: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  29: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  30: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  31: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  32: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  33: sp_api::Core::execute_block_with_context
  34: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  35: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  36: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  37: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Sync+core::marker::Send> as sp_consensus::block_import::BlockImport<B>>::import_block
  38: sp_consensus::import_queue::import_single_block_metered
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  41: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  42: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  44: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  45: std::thread::local::LocalKey<T>::with
  46: futures_executor::local_pool::block_on
  47: tokio::runtime::task::core::Core<T,S>::poll
  48: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  49: tokio::runtime::task::harness::Harness<T,S>::poll
  50: tokio::runtime::blocking::pool::Inner::run
  51: tokio::runtime::context::enter
  52: std::sys_common::backtrace::__rust_begin_short_backtrace
  53: core::ops::function::FnOnce::call_once{{vtable.shim}}
  54: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
  55: start_thread
  56: __clone

Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x40d9cc0a49e07b83c314b4b7be9e0b481d1b5cdaf0f4ff26dd152aa9c434d6d3"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/466ac62/primitives/state-machine/src/ext.rs:203

I report this as the command line output told me to

**Comment by edag94** [comment]
Duplicate of #2529

**Comment by edag94** [comment]
Except I'm using RocksDb here. I was able to run it from an older snapshot 2 days ago. I am using a new snapshot as I wanted to setup a new node for testing. I'm guessing the snapshot is broken.

**Comment by bkchr** [comment]
@edag94 from where did you get this snapshot?

**Comment by edag94** [comment]
https://ksm-rocksdb.polkashots.io/

**Comment by edag94** [comment]
kusama-6396526.RocksDb.7z

6396526 is the block height of the snapshot that failed

**Comment by edag94** [comment]
But now that I have looked a little more, I'm assuming using snapshots from this website is not officially supported by parity, and maybe not have a place in the issues section here. Are there snapshots that are officially hosted by parity?

**Comment by bkchr** [comment]
We don't provide any snapshots. Sorry.

Did you checked that the checksum of the downloaded file was correct? Can you reproduce this problem?
