### ISSUE TITLE
XCM simulator

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#2544]
It will be helpful to have some tool to simulate the interaction of XCM related code without having us to run multiple relaychain nodes and parachain nodes.

**Comment by bkchr** [comment]
By XCM related code you mean your pallets?

**Comment by xlc** [comment]
Our pallets, other parachain's pallets, but most importantly xcm-executor/builder from Polkadot and maybe xcm-handler from Cumulus.

Right now to run a XCM message, it starts from our pallet, uses xcm-builder in Polkadot, call into xcm-handler from Cumulus, which calls xcm-executor from Polkadot, and to go relaychain, routed to dest parachain, call into xcm-handler, call into xcm-executor, call into custom pallet code.

Too many moving parts over multiple process. Will be helpful to be able to run the whole thing in a single integration test.

**Comment by bkchr** [comment]
CC @shawntabrizi @pepyakin

**Comment by jak-pan** [comment]
We're trying to do integration tests and will also probably do these with https://github.com/halva-suite/halva but it needs some upgrades since it's little bit outdated. cc @martinfridrich but this is interesting :) Would be faster for preliminary tests.

**Comment by shawntabrizi** [comment]
closed by https://github.com/paritytech/polkadot/pull/3538

**Comment by MBANKm** [comment]
,😉
