### ISSUE TITLE
Print enabled feature: real-overseer / approval-checking

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#2546]
For some reason our docker build script failed to build with real-overseer despite we have updated our Dockerfile to include it.

It is currently very hard to tell if real-overseer is enabled or not. It will be helpful there is a way to easily detect it without checking debug logs of validator.

**Comment by bkchr** [comment]
`approval-checking` feature doesn't exist anymore.

**Comment by rphmeier** [comment]
@xlc I would gladly accept a PR `info!` log in `node/service` which is gated on `#[cfg(features = "real-overseer)]`. Although I hope this is not an issue for long.
