### ISSUE TITLE
Add back Jaeger spans to availability distribution

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#2551]
Follow up for #2423 .

**Comment by dvdplm** [comment]
cc @insipx

**Comment by eskimor** [comment]
Any particular wishes with regards to spans? Shall I try maintaining names from the old implementation, where it makes sense?

**Comment by insipx** [comment]
> Any particular wishes with regards to spans? Shall I try maintaining names from the old implementation, where it makes sense?

Most important for me are having a `candidate-hash` and `candidate-stage` available. Other than that, it's free to change I think
