### ISSUE TITLE
Replace XCM `Error::Undefined` usage with more explict errors

### ISSUE THREAD

**Issue by shaunxw** [paritytech/polkadot#2577]
`Error::Undefined` is used in different places. It's hard to tell the exact reason of execution failure with this error returned. It should be replaced with explicit ones.

In currency adapter, I think it could be replaced with a `Error::FailedToTransactAsset(&'static str)` error, to represent all asset transact failures. As parachains are likely to have their own `TransactAsset` implementation, the `&'static str` could be helpful to provide details of parachain specific errors.

I've started [some work](https://github.com/shaunxw/polkadot/blob/sw%2Freplace-xcm-undefined/xcm/xcm-builder/src/currency_adapter.rs) to replace the `Undefined` error in currency adapter. If this direction makes sense, I'm happy to polish it and open a PR.

**Comment by shawntabrizi** [comment]
@shaunxw would be happy to review and accept a PR here.
