### ISSUE TITLE
ForceApprove digest for approval checking finality rule

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#2582]
If parachain approval-checking fails, for some reason, and finality stalls, we want to give governance the ability to issue a consensus digest in the header of a block, which will force-approve every parachain candidate up to some `BlockNumber` in the chain that the candidate appears within. This will allow governance to intervene and get relay-chain consensus back on track, even if parachain consensus has failed.

**Comment by burdges** [comment]
Yup.  We'd the oppose force dispute and/or buy dispute too, but I guess that's another matter.

**Comment by rphmeier** [comment]
I'd want a separate method for manually creating disputes on-chain which validators would then detect and initiate.

**Comment by burdges** [comment]
> What do you mean by "buy dispute"?

We'll postpone that 2021 I think ;) but basically fishermen.
