### ISSUE TITLE
Crownloan module issue with numeric values

### ISSUE THREAD

**Issue by ppoliani** [paritytech/polkadot#2592]
I have recently forked the Polkadot repo and integrated the Crowdloan module into the Kusama runtime. I have then used polkadot-launch to run a local network and test the module.

I have also shared the issue on the Polkadot.js repo.

https://github.com/polkadot-js/apps/issues/4780#issue-823644313

Basically, all I did is simply integrate the existing crowdloan module into the Kusama runtime. This is pretty much what I did:

https://github.com/Apocentre/polkadot/pull/1/files

Probably I'm doing something wrong; however I can't get my head around what the issue might be.

**Comment by shawntabrizi** [comment]
@ppoliani are you going to share what your error even is?

**Comment by ppoliani** [comment]
Hey @shawntabrizi, I shared a link to the polkadot.js issue I created.

I will try the branch you suggested

**Comment by shawntabrizi** [comment]
@ppoliani what Jaco mentions in the issue is likely correct. The issue is not in the runtime, but a mismatch in the types between Polkadot JS and Substrate.

You should look to manually add the Crowdloan types into Polkadot JS, or wait a bit longer for us to better integrate the two together.
