### ISSUE TITLE
Audit Para Onboarding Pallets

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#2624]
https://github.com/paritytech/polkadot/pull/2294 was merged without completion of audit so that users may be able to play around and try out the pallets.

These audits still need to be completed before they get used in a production blockchain.

- [ ] Registrar
- [ ] Slots
- [ ] Crowdloan
- [ ] Auctions
- [ ] Paras (parachain_runtime)

**Comment by shawntabrizi** [comment]
Crowdloan

- [ ] Check no Extra Contributions Allowed After Winning
- [ ] Check No extent with data

Other

- [ ] Metadata for paras?
- [ ] Crowdloan Owner in UI

**Comment by thiolliere** [comment]
AFAICT it is audited https://github.com/paritytech/srlabs_findings/wiki/Pull-request-review-overview
