### ISSUE TITLE
[Request] Improve confusing console output

### ISSUE THREAD

**Issue by asmodat** [paritytech/polkadot#263]
I had very odd experience with running validator node for the first time. Setup it exactly like this: https://github.com/BitySA/KnowledgeBase/blob/master/Validation-Services/Polkadot/Testnet/validator-setup.md

I waited half a day for it to sync, then once I was on the latest block and started validating my node instantly got "reported offline" once entering validator set even tho I was on the latest block.

My console output looked like follows:

![image](https://user-images.githubusercontent.com/10515811/58017967-d9c10480-7b01-11e9-9f92-015b958003b1.png)

Through the weekend I did absolutely nothing with my node, to come today in the morning and submit another validate tx in order to enter set after previously getting slashed and unbounded.

Surprisingly all is fine! with 0 issue, 0 reported offline, my problem is that there was no indication whatsoever what was wrong.

My console output looks like follows now:

![image](https://user-images.githubusercontent.com/10515811/58018077-2278bd80-7b02-11e9-997e-e080d5c63a96.png)

I understand I was probably out of sync, but the console output did not provide me a single clue what is going on, making it a horrible experience to debug it. 

I think there should be some more explicit information in the console informing that node is not validating and it will get slashed etc because X, Y, Z

PS
Monitor-rpc was showing exact same block height as polkascan...

**Comment by bkchr** [comment]
I think if your own nodes know that it is being slashed, it would not being slashed (as it would follow the rest of the network).

I'm not quite sure what you really want here. Looking at all the console output, I don't really know what to do here. So, I will close this issue.
