### ISSUE TITLE
[Request] Add sentry node configuration

### ISSUE THREAD

**Issue by asmodat** [paritytech/polkadot#264]
Enable sentry node configuration of polkadot service in order not to expose validator node directly to the hostile environment.

That is provide a way to mitigate DDOS, and disallow external connections to be made directly to validator node.

**Comment by lsaether** [comment]
As I understand sentry nodes, they are nodes which are connected to the gossip network and provide a layer of separation to the validator. That way in case of DDOS attacks, it would only take down the sentries and hopefully a validator is running a few of them to be resilient.

Would it be possible to mimic this function by passing flags to the cli? Something like this:
```
$ polkadot  --no-mdns --validator  --out-peers 1 --in-peers 0 --bootnodes <URL_of_your_sentry>
```

**Comment by xlc** [comment]
there is [`reserved-nodes`](https://github.com/paritytech/substrate/blob/43164e24f23fe71d82906b4379e043bfdf9beba3/core/cli/src/params.rs#L102) flag that can be used for this purpose.

**Comment by dbpatty** [comment]
so is it now possible in Alexander to configure a sentry?

**Comment by lsaether** [comment]
It should be possible if you're willing to do some tinkering :) 

Otherwise, there is currently a bounty being worked on https://github.com/w3f/Web3-collaboration/issues/122 that will deliver a configuration and guide for setting up sentry nodes.

**Comment by gavofyork** [comment]
@mxinden is working on this.

**Comment by mxinden** [comment]
**Current status**: Sentry node setup can be simulated via [substrate/blob/master/scripts/sentry-node/docker-compose.yml](https://github.com/paritytech/substrate/blob/master/scripts/sentry-node/docker-compose.yml) with blocks being produced and finalized.

**Next up**: A way to authenticate a sentry node as a valid sentry node for a given validator. This enables validators to keep long living connections to other validators even when only accessible through sentry nodes.

**Comment by dbpatty** [comment]
Ty I'll study it

**Comment by agutsal** [comment]
@xlc I need some help from you it seems. I'm the guy working on [this](https://github.com/w3f/Web3-collaboration/issues/122). 
Basically I've to run validator behind sentry using docker-compose

my question is, did I got it right that sentry should be run with something like that:
`docker run -ti parity/polkadot:v0.4.4  --chain=local --alice`
while validator should be run like that:
`docker run -ti parity/polkadot:v0.4.4  --chain=local --validator --reserved-nodes //Alice`

of course real chain and URL would be configurable.

**Comment by gilescope** [comment]
closing as sentry nodes are not needed any more.
