### ISSUE TITLE
Cannot withdraw some funds from Crowdloan in retire phase

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/polkadot#2747]
We are trying to withdraw users funds in our retiring Crowdloan campaign. We use polkadotjs to dump the list, and send tx.crowdloan.withdraw to withdraw. At first we have dumped 180+ addresses, and we successfully withdraw 100+. However there are 80 remaining failed with `crowdloan.NoContributions`.

These failed txs can be found here:
<https://polkadot.js.org/apps/#/explorer/query/0x214abc9f2eb056443d14993f7c6fb5959e5e2dfd0305b5f2dbe46c110b2b6d9d>

I'm confused because these are dumped from the child-trie. One of the account is our own account. How can it be NoContributions?

Maybe related (we submitted the contribution on 26th):

> Jaco:  It could very well be that the ones that you cannot withdraw were made before the memo change. There were no migrations done.

## Links

- The failed accounts: <https://pastebin.com/sL3AgqaL>
- Dump script: <https://github.com/Phala-Network/phala-blockchain/blob/master/scripts/js/dumpCrowdloan.js>
- Withdraw script: <https://github.com/Phala-Network/phala-blockchain/blob/master/scripts/js/crowdloanWithdraw.js>

## Sample account

The sample account is controlled 

- User: 5GjDHxVoRp59ttbxUVJQYXEuQVUEX5US7JvR7qMNCNrdEjZo
- ParaId: 30
- TrieIndex: 21

```json
  {
    "from": "5GjDHxVoRp59ttbxUVJQYXEuQVUEX5US7JvR7qMNCNrdEjZo",
    "data": [
      "0x0000000000000000007aec84453a8000",
      "0x"
    ]
  },
```

On polkadotjs-apps UI, it showed my contribution was recognized. But when I called `crowdloan.withdraw` I only got the error.

**Comment by shawntabrizi** [comment]
@h4x3rotab Could be corrupted state because of the breaking upgrade I did. I can help you dissolve your crowdloan, but probably funds dont get returned.

The next crowdloan you make should not have this issue.

**Comment by h4x3rotab** [comment]
Thanks. Closing the issue
