### ISSUE TITLE
tokio-runtime-worker

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/polkadot#2748]
2021-03-29 11:00:12  ✨ Imported #20 (0x08c2… a8a9)    
2021-03-29 11:00:12  Moving approval window from session 0..=0 to 0..=3
2021-03-29 11:00:12  [index: 1] Reporting im-online at block: 20 (session: 4): heartbeat(Heartbeat { block_number: 20, network_state: OpaqueNetworkState { peer_id: OpaquePeerId([152, 0, 36, 8, 1, 18, 32, 190, 121, 61, 218, 27, 159, 36, 166, 79, 55, 52, 186, 175, 246, 235, 243, 159, 66, 110, 122, 56, 15, 157, 164, 34, 170, 125, 176, 80, 23, 79, 93]), external_addresses: [OpaqueMultiaddr([116, 47, 105, 112, 52, 47, 49, 55, 50, 46, 49, 48, 53, 46, 49, 50, 54, 46, 56, 49, 47, 116, 99, 112, 47, 51, 48, 51, 51, 52])] }, session_index: 4, authority_index: 1, validators_len: 4 }, Signature(e409493f23778f49bd1647689e473413e0011e17fe07d605ab98d47f0b629f100fa59c7acc75de8a951ad26b9d4877e661146f08e300fe3933088ecb66709a83))    
2021-03-29 11:00:12  (offchain call) Error submitting a transaction to the pool: Pool(InvalidTransaction(InvalidTransaction::Stale))    

====================

Version: 0.8.30-36af7c96-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  6: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   7: pallet_babe::<impl pallet_babe::pallet::Pallet<T>>::current_epoch
   8: <rococo_runtime::Runtime as sp_consensus_babe::runtime_decl_for_BabeApi::BabeApi<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,rococo_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<rococo_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<rococo_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<rococo_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<rococo_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<rococo_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<rococo_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<rococo_runtime::Runtime>)>>>>::current_epoch
   9: std::thread::local::LocalKey<T>::with
  10: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  11: sc_executor::wasm_runtime::RuntimeCache::with_instance
  12: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  13: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  15: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  16: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  17: sp_consensus_babe::runtime_decl_for_BabeApi::current_epoch_call_api_at
  18: sp_consensus_babe::BabeApi::current_epoch
  19: polkadot_node_core_runtime_api::make_runtime_api_request
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  24: std::thread::local::LocalKey<T>::with
  25: futures_executor::local_pool::block_on  
  26: tokio::runtime::task::core::Core<T,S>::poll
  27: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  28: tokio::runtime::task::harness::Harness<T,S>::poll
  29: tokio::runtime::blocking::pool::Inner::run
  30: tokio::runtime::context::enter
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
  32: core::ops::function::FnOnce::call_once{{vtable.shim}}
  33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17
  34: start_thread
  35: clone

Thread 'tokio-runtime-worker' panicked at 'EpochConfig is initialized in genesis; we never `take` or `kill` it; qed', /home/simrococo/.cargo/git/checkouts/substrate-7e08433d4c370a21/2f69b2d/frame/babe/src/lib.rs:580

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

2021-03-29 11:00:12  Unable to gather info about imported block (0x08c22f18630cebaa313c51b73dc9b01b0cee7ff912e39337d75b182330c9a8a9, 20). Skipping chain.

**Comment by master-davidlee** [comment]
I try to build my own relay chain,  and this happens when I try to connect bob to Alice, Alice is the boot node. 
The command is`./target/release/polkadot   --chain ~/rococo-4.json   --tmp   --ws-port 9955   --port 30334   --bob   --bootnodes /ip4/ipaddress/tcp/30333/p2p/alice node id`
I don't know why?

**Comment by andresilva** [comment]
How did you generate the chainspec? Can you replicate with `--chain rococo-local`?

**Comment by master-davidlee** [comment]
I use the cumulus-workshop provides rococo chain spec, the link is https://substrate.dev/cumulus-workshop/#/en/1-prep/2-chain-spec. I use the rococo-4.json

**Comment by andresilva** [comment]
Sorry those need to be updated, I created an issue for this https://github.com/substrate-developer-hub/cumulus-workshop/issues/46. In the meantime feel free to continue the tutorial with `--chain rococo-local`.

**Comment by master-davidlee** [comment]
I tried the rococo-local and every thing looks fine

**Comment by master-davidlee** [comment]
I build my own rococo-4.json by adding charlie and dave as validators in rococo-local.json
