### ISSUE TITLE
Something about the parathread

### ISSUE THREAD

**Issue by master-davidlee** [paritytech/polkadot#2753]
I build my own rococo with 4 validators, and everything is fine. I registered 2 parathreads, but I am a little confused because I read Shawn's guide it says  
![image](https://user-images.githubusercontent.com/49427668/112847719-f1904900-90d9-11eb-94e1-4aba3406f58d.png)
But after I broadcast the transaction only after about 3-5 minutes the status changed from onboarding to Parathread. 
So I use the `sudocall>slots>force_lease`, and it succeeded.
![image](https://user-images.githubusercontent.com/49427668/112848126-4fbd2c00-90da-11eb-95f0-7f83531b0320.png)
But after about 20 minutes the parathread 300 still a parathread, So I want to why Parathread to Parachain change does not as fast as the Onboarding to Parathread?

**Comment by master-davidlee** [comment]
Oh, I think I found the reason because I set the reserve from 0-100, which means it won't start until lease 1. So I have to wait for 14400 blocks

**Comment by bkchr** [comment]
So, this issue can be closed?

**Comment by shawntabrizi** [comment]
@master-davidlee it should be that force lease now immediately starts the onboarding process, so make sure you have the latest code and you shouldnt have to wait 1 day

**Comment by master-davidlee** [comment]
![image](https://user-images.githubusercontent.com/49427668/112980752-d6324600-918c-11eb-9f3d-a89eb84129a7.png)

so what do you mean wait until lease 1?

**Comment by master-davidlee** [comment]
> @master-davidlee it should be that force lease now immediately starts the onboarding process, so make sure you have the latest code and you shouldnt have to wait 1 day

after one day the parathread which onboarding by forcelease had become the parachain. Where can I get how many slots can be auctioned and how to increase it?

**Comment by shawntabrizi** [comment]
> so what do you mean wait until lease 1?

That is out of date. I updated it now, thanks!
