### ISSUE TITLE
Trie: Extension Node Removal

### ISSUE THREAD

**Issue by nczhu** [paritytech/polkadot#279]
_Wanted to put up an issue for this as it’s important for Kusama, please CRUD as needed._

Polkadot RE spec include changes to substrate patricia trie. Some slight codec changes and the removal of trie extension node.

Related issue for additional context: https://github.com/paritytech/trie/pull/11

Currently owned by @cheme

**Comment by gavofyork** [comment]
Duplicate of https://github.com/paritytech/substrate/pull/2815

**Comment by rphmeier** [comment]
outdated/more of a cumulus concern
