### ISSUE TITLE
Add `poke` to Crowdloan

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#2801]
A crowdloan won't bid in an auction unless it is part of the `NewRaise` Vec by the ending period of the auction.

For it to be in that `NewRaise` vec, someone needs to contribute to that fund. But it is possible that no one else wants to contribute or that the cap for the fund was reached.

In this case, we should have a simple function `fn poke(fund_id)`, which will check if the fund has non-zero raised, and then put it in the `NewRaise` vec if it is not already there.

This way, a fund can make sure that it will get its bid in, even if a contribution does not occur.

- [ ] Write `poke` function
- [ ] Tests
- [ ] Benchmarks

**Comment by stanly-johnson** [comment]
> will check if the fund has non-zero raised

@shawntabrizi I can work on this, quick question, how can a fund have non-zero raise with no contributions?

**Comment by shawntabrizi** [comment]
@stanly-johnson it will have contributors, but not during the current auction cycle.

A crowdloan can span multiple auctions, and this issue is trying to resolve situations like that.
