### ISSUE TITLE
Parachain validation terminatable (infinite-loop-proof)

### ISSUE THREAD

**Issue by nczhu** [paritytech/polkadot#281]
Hey @arkpar, we wanted to put up an issue for this as it’s important for Kusama, please CRUD as needed. Let us know if you need any context around this!

**Comment by arkpar** [comment]
The initial implementation will use a separate process for executing validation function. The process can be terminated after a timeout. There will be no metering of any kind.

**Comment by gavofyork** [comment]
Duplicate of #147
