### ISSUE TITLE
2.2 "./target/release/polkadot" results in "no such file or directory"

### ISSUE THREAD

**Issue by JonHill24** [paritytech/polkadot#283]
../polkadot$ ./target/release/polkadot

 bash: ./target/release/polkadot: No such file or directory

**Comment by bkchr** [comment]
What did you do? And what do you want to do?

**Comment by shawntabrizi** [comment]
@JonHill24 you need to call:
```
./scripts/build.sh
cargo build --release
```

This will build the Wasm runtime, which then allows you to build the `release` binary which is probably what you are trying to do here.
