### ISSUE TITLE
Query parachain code hash from runtime, computing hash offchain on parachain candidate validtion

### ISSUE THREAD

**Issue by thiolliere** [paritytech/polkadot#2879]
follow up from https://github.com/paritytech/polkadot/pull/2593

instead of recompute the hash when validating a candidate, we should be able to query the code hash from the runtime.

https://github.com/paritytech/polkadot/blob/a9af2c334913b15598a31c596e08a5ca1408a174/node/core/candidate-validation/src/lib.rs#L481

step1: add runtime api to query the code hash
step2: make use of it to get the hash in candidate validation.

**Comment by pepyakin** [comment]
subsumed by https://github.com/paritytech/polkadot/issues/4524
