### ISSUE TITLE
Potential council issue

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#288]
I am reporting this as a potential issue because I saw the issue on a local chain but I am using this local chain atm and I would like to avoid resetting it until I am done since I did pass a few referendums on it.

Details to come but based on a discussion in Riot. 

I started a local chain running polkadot 0.4.4 and connected the UI from https://polkadot.js.org/apps/#/staking

Initially it showed:
![image](https://user-images.githubusercontent.com/738724/59215951-d7127600-8bba-11e9-9a12-9c5cb458d681.png)

I did not check the council state at the point.

From an empty local chain, I did:
- add accounts (session and stash for Alice´s family)
- reduce the number of session per era
- reduce the session length (I am testing, things need to go fast :))
- add one validator (from 2 to 3)
- bring the 3rd validator in

I did nothing related to the council beside querying storage.

- `acitveCouncil` 6 accounts
- `desiredSeats` : 4
- `carryCount`: 4

**Comment by chevdor** [comment]
After a little while, my validators look like:
![image](https://user-images.githubusercontent.com/738724/59216112-3cfefd80-8bbb-11e9-9dac-b18404b6bff8.png)

and the council shows:
![image](https://user-images.githubusercontent.com/738724/59216131-47b99280-8bbb-11e9-9dc5-c0c3bfdf4456.png)

**Comment by Kianenigma** [comment]
This could be an issue in the council. I'll try to run a similar setup and see what's the outcome.

**Comment by chevdor** [comment]
If that helps you, I am using a version closed to that for the network:
https://gist.github.com/chevdor/be461d11c56baecb0e7bbcb920e964fb#file-dcp-polkadot-5nodes-ui-yml

I say close because the UI seems to be broken when using master so I am running 0.4.4.
I did however a change to run 0.4.4, here it is: (I removed the --cors flag that was not available back then)
[dcp-polkadot-5nodes-ui-044.yml.zip](https://github.com/paritytech/polkadot/files/3273397/dcp-polkadot-5nodes-ui-044.yml.zip)

`TAG:0.4.4 docker-compose -f thefile.yml up --force-recreate`

**Comment by gavofyork** [comment]
@Kianenigma did you ever find anything wrong here? Unit tests are pretty comprehensive and UI has a lot of logic...

**Comment by gavofyork** [comment]
Closing - reopen if there is anything here.
