### ISSUE TITLE
Upgrade Pallets to FRAME v2

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#2882]
There are a number of custom Polkadot pallets in this repo, and we could use help to migrate them to the new v2 macro.

The pallets which are already live need to check that they won't break, but new pallets like the onboarding systems should get migrated before they are put live on the network.

- [x] auctions (#3031)
- [x] claims (#3032)
- [x] crowdloans (#3036)
- [x] mmr (#3061)
- [x] registrar (#3063)
- [x] sudo wrapper (#3074)
- [x] purchase (#3075)
- [x] slots (#3218)
- [x] runtime > parachains (a lot in here)

**Comment by shaunxw** [comment]
XCM sender doesn't need migration as it's not a pallet. Migrations in `runtime > common` are done.

**Comment by ferrell-code** [comment]
Once the last three are merged all the parachains pallets will have been migrated.

With a quick grep I see that there is one small validator_manager.rs pallet in rococo and a few pallets in bridges. Not sure if these are going to be used in the long term, but most are now using the attribute macro :dragon_face:

**Comment by shawntabrizi** [comment]
thanks @ferrell-code !

probably we want to migrate the bridge pallet stuff, but we can open a new issue for that and have the bridge team track it cc @HCastano @tomusdrw

**Comment by HCastano** [comment]
Yeah, @ferrell-code feel free to open an issue and/or PRs in the [`parity-bridges-common`](https://github.com/paritytech/parity-bridges-common) repo
