### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [paritytech/polkadot#2909]
Hi I have some questions regarding this project:
1. Is it workable right now? Am I able to generate hashes to earn money?
2. Can I control how much processing power to take to generate hashes?
3. Am I able to change the output or not even display a console session for situations I may not want a console to open and for it to run in the background?
4. Say if I have the crypto wallet stored on my computer A and it is off, and I am doing cryptomining (using this crate) on Computer B and Computer B does NOT store the wallet and I wanted to send it off. Do I need to store the wallet on a server? Does the crypto wallet have a server where I can chose to create a wallet and where all my money can go over there?
5. Is this library capable of sending generated hashes via the Internet?
6. Am I able to use The [Rust](https://www.rust-lang.org/) Programming Language to script and control mining? If so how difficult would it be to code it up?
7. If 6 is applicable, then how efficiently can I generate the code?
8. Is it as private and secure as [Monera](https://www.getmonero.org/)?
9. If 6 is applicable, do I have to disclose my source code under GPL?

**Comment by laboon** [comment]
Before filing issues on the repo, I would recommend reading the Polkadot wiki. https://wiki.polkadot.network/

As Polkadot does not have mining, most of your questions don't make a whole lot of sense.
