### ISSUE TITLE
Can I upgrade polkadot from 0.8.27 to 0.8.30?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot#2931]
Hi guys! Can I upgrade polkadot from 0.8.27 to 0.8.30?
Seems I shouldn't skip the 0.8.28.
Both 0.8.28 and 0.8.30 contain a DB migration.

Sorry to open an issue here.
I've ask this on element many times, but nobody answered. But this is important to me.

**Comment by eskimor** [comment]
I got the following info from @wpank :

```
I would say probably not. Usually db migrations we do are only tested from one version to the next. Jumping versions might be a bit weird. The safest way to upgrade in that case would be going from v0.8.27, to v0.8.28, to v0.8.29, to v0.8.30
Or going straight to v0.8.30 and downloading a new db snapshot
```

**Comment by bkchr** [comment]
Yes you can https://github.com/paritytech/substrate/blob/0856e0729c5f9cd5d398b93680ab154fe486e588/client/db/src/upgrade.rs#L41
