### ISSUE TITLE
Different denomination granularities of Polkadot

### ISSUE THREAD

**Issue by savudani8** [paritytech/polkadot#2935]
I ran a [dev Polkadot node](https://github.com/paritytech/polkadot/releases/tag/v0.8.30) today (`polkadot --dev`) and needed to submit a value of `1000000000000`  (10^12) for it to be considered 1 DOT in the `polkadot/apps` explorer. 
However, the docs [here](https://wiki.polkadot.network/docs/en/learn-DOT) specify a granularity of 10^10 for DOT.

Is there a difference between the denomination on `polkadot --dev` and that on mainnet? If so, it would be useful to outline it in the docs. Thanks!

**Comment by bkchr** [comment]
I assume polkadot-js defaults to 12 token decimals when there are no specified. Am I right @jacogr?

**Comment by jacogr** [comment]
Yes. The UI (& API) applies a default of 12 decimals along with "Uinit" symbol when none are retrieved via the properties RPCs. (not specified in the chainspec)

**Comment by savudani8** [comment]
Thank you!
