### ISSUE TITLE
staking.staker got wrong 'total' & 'value'

### ISSUE THREAD

**Issue by xfylsj** [paritytech/polkadot#294]
Hi, I am having issues on `staking.staker` when retrieving the 'total' bond amount and each nominator's bond value.

Say 1M bonded on staker, and 1M bonded on its nominator, so total bond amount should be 2M, but using `staking.staker`, the `total` bond is `1999960` and the `value` of nominator is `999960`.

Bond `1M` for nominator:
![image](https://user-images.githubusercontent.com/31326993/59643957-f1ea7900-91be-11e9-9818-a2817f5bb0f5.png)

Issues: 

On 'Staking Overview' page, the nominator's bond value is `999.960K`.
![image](https://user-images.githubusercontent.com/31326993/59643982-0d558400-91bf-11e9-94a0-7b84e28aee29.png)

 Use `staking.stakers` to query, the `total` and `value` are also wrong.
![image](https://user-images.githubusercontent.com/31326993/59644828-c79aba80-91c2-11e9-98bf-0b7a4868b631.png)

Node
```
version 1.0.0-98a733fa-x86_64-macos
```

**Comment by gavofyork** [comment]
As a nominator, you are not guaranteed to have all stake placed behind validators of your choice. There is an distribution and optimisation algorithm which does this for you, and in some cases it may be slightly suboptimal (like here it's 99.996% "correct").

Another possibility is just that the nominator balance got reduced somehow, perhaps by transaction fees?

Maybe check to see what the account's balance is to determine what's going on.
