### ISSUE TITLE
Archive full node CPU usage spikes at around 11:30am UTC everyday.

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/polkadot#2955]
```
image: parity/polkadot:v0.8.30 
node type: archive full node
cpu: 4000m                                                                              
memory: 12800Mi
FLAGS and OPTIONS:
    --base-path=/chain-data
    --rpc-cors=all
    --port=30333
    --rpc-port=9933
    --ws-port=9944
    --chain=polkadot
    --ws-external
    --rpc-external
    --rpc-methods=Unsafe
    --pruning=archive
    --ws-max-connections=250
```

Hi, I am running an archive full node using the `parity/polkadot:v0.8.30` image, my node had CPU spikes every day at around 11:30 am UTC. Also, the node syncing was impacted during the spikes. 

I am creating this issue to check whether I can do anything to stop the CPU spikes.

![image](https://user-images.githubusercontent.com/14008461/116493765-85308180-a8f3-11eb-993d-2b9ca695a09c.png)

I checked the chain status at that time, seems like there is an `electionprovidermultiphase(submit_unsigned)` extrinsic at that time every day.  [ `electionprovidermultiphase(submit_unsigned)` extrinsic details](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.onfinality.io%2Fpublic-ws#/explorer/query/0xd006ffefad5075da4a96a4eeb96191f980a6bc5037bd9ee03cedbe472dba90ed)

Any clue what causes the high CPU usage? If the CPU usage is caused by `election`, as a full node, does my node need to compute for the election? I have tried to add `--offchain-worker=Never` to prevent executing offchain workers but it didn't help.

Any suggestions would be greatly appreciated!

**Comment by bkchr** [comment]
Cc @kianenigma

**Comment by kianenigma** [comment]
This is expected and if it happens once a day around the same block where we `submit_unsigned`, then there's nothing to be done about it. 

> I have tried to add --offchain-worker=Never

Indeed, you don't need this since you already don't run OCW if you are not a validator. 

Also if you are validators, I have heard about spikes every 4 hours as well when we change a session for im-online messages. do you also see this? If so, then this just makes the situation worse as the two computationally heavy operations overlap.

**Comment by AlexZhenWang** [comment]
Thank you for the response @kianenigma!

I just checked the validator node I am running, the spikes every 4 hours are not obvious on my side, I can only see the spikes every 24 hours with `submit_unsigned`.
CPU usage of my validator node:
![image](https://user-images.githubusercontent.com/14008461/116841698-15413480-ac2e-11eb-898b-6a930ffdab52.png)

Overwise, if the CPU spikes are caused by the `electionprovidermultiphase(submit_unsigned)` extrinsic, will the CPU usage during the spike increase in the future when the network has more nodes?

**Comment by kianenigma** [comment]
The spike, if it is indeed caused by `submit_unsigned ` is related to the size of the npos system in general. A part of that is how many active validators we have. But the number of waiting ones and nominators is also important.

**Comment by AlexZhenWang** [comment]
Got it, thank you for the explanation, @kianenigma !
