### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Daelon02** [paritytech/polkadot#2976]
Hi, we trying use polkadot pallets from github, like
 ```xcm = { git = "https://github.com/paritytech//polkadot", rev = "127eb17a25bbe2a9f2731ff11a65d7f8170f2373" }```
and we have this errors
[logs.txt](https://github.com/paritytech/polkadot/files/6421573/logs.txt)

**Comment by bkchr** [comment]
Run `cargo update -p parity-scale-codec-derive`
