### ISSUE TITLE
Connecting to next group in advance in collator protocol does not work at session boundaries

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#2985]
The collator side of the collation protocol tries to connect to the current responsible backing group and the next one. This is done by just incrementing the group index (modulo group count), which will obviously not work at session boundaries.

Consequences should be minor: Collating at session boundaries will be slightly slower. Nevertheless it is kind of ugly that collators will try to connect to totally unconcerned validators.

**Comment by ordian** [comment]
As a best of both words, we could check if group is about to rotate and only then use the next group preconnection.

**Comment by eskimor** [comment]
That's a good point as well. Prematurely connecting to the next group is pointless, as validators will kill idle connections. So connecting to the next group should only happen right before rotation.

We might want to remove this optimization all together as it is broken right now anyway. We can add it back later, if it is deemed necessary.

**Comment by rphmeier** [comment]
cc @lldenaurois
