### ISSUE TITLE
Low number of peers in Australia

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/polkadot#2996]
- System: Debian 10 / 4.19.0-16-amd64 / 64GB memory / Xeon E-2236
- Polkadot: running with default options
- Networks: tried both with the Polkadot and Kusama networks with similar results. 
- Location: Australian datacenter

When starting the node, peers quickly get to 50 but then over 24 hours lowers to 5-15 peers and remain that way.

I am assuming this issue is due to the low number of nodes in this region, which is then an issue with the network and not my setup. If I remove this node and place it closer to the other ones then it's going against the decentralization goals of the network.

I have done this experiment about six months ago and terminated it for the same issue I'm experiencing on my second attempt today. It was a completely different server.

**Comment by bkchr** [comment]
Cc @tomaka

**Comment by tomaka** [comment]
It's very unlikely that this is related to being in Australia.

Please make sure that the timeclock on your machine is accurate. It is a possible reason.

If it doesn't solve the problem, please run your node with `-l sync=debug -l sub-libp2p=debug` until the number of peers gets low and upload the logs somewhere.

**Comment by LukeWheeldon** [comment]
Here it is. Thanks for your help @tomaka.

[debug.log.tar.gz](https://github.com/paritytech/polkadot/files/6450950/debug.log.tar.gz)

**Comment by tomaka** [comment]
Everything seems to time out. Event the identification requests (a small request to gather the remote's version) time out, which I had never seen before.

You probably have a lot of packet loss, or not enough bandwidth available for the node.

**Comment by LukeWheeldon** [comment]
1 Gbps in NEXTDC datacenter, ping is fine.
