### ISSUE TITLE
Validator node crash

### ISSUE THREAD

**Issue by ZhongweiZhang** [paritytech/polkadot#30]
I deployed a Local Two-node Testnet with 2 validators and a adder-collater. The first Alice validator crashed not long after the collater joined. logs are attached.
[polkadot_test.txt](https://github.com/paritytech/polkadot/files/2423050/polkadot_test.txt)

**Comment by arkpar** [comment]
@tomaka

**Comment by tomaka** [comment]
Yes this has been fixed in substrate.

**Comment by tomaka** [comment]
Closing as duplicate of #18
