### ISSUE TITLE
Thread 'main' panicked at 'assertion failed: 

### ISSUE THREAD

**Issue by ZhangWei-KUMO** [paritytech/polkadot#303]
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hfe242bd60c2e8de7 (0x10fd70c50)
   1: std::panicking::rust_panic_with_hook::hfcf2d0777bc6c409 (0x10ff51250)
   2: std::panicking::begin_panic::hc769b4ccceaafada (0x10f2c8284)
   3: std::thread::local::LocalKey<T>::with::he936736f48b2d634 (0x10f2b7a5d)
   4: sr_io::with_storage::h03448e04a3b04fc6 (0x10f31cc23)
   5: <srml_staking::GenesisConfig<T> as sr_primitives::BuildStorage>::assimilate_storage::haa4372f729b152cd (0x10f2e6608)
   6: <polkadot_runtime::GenesisConfig as sr_primitives::BuildStorage>::assimilate_storage::h9477fc7a85ef4571 (0x10f2c03b4)
   7: sr_primitives::BuildStorage::build_storage::ha222a131e7c0f467 (0x10ef19099)
   8: <&substrate_service::chain_spec::ChainSpec<G> as sr_primitives::BuildStorage>::build_storage::h7fb40ce0efdcf24b (0x10ec85c9e)
   9: substrate_client::client::Client<B,E,Block,RA>::new::hca98c610320e0a93 (0x10f1a7f12)
  10: substrate_client_db::new_client::h3a69b1996868033b (0x10eede9a3)
  11: <substrate_service::components::FullComponents<Factory> as substrate_service::components::Components>::build_client::h2844409a03c35462 (0x10f08ef80)
  12: substrate_service::Service<Components>::new::h2a3807784a492b1c (0x10efeebdb)
  13: <polkadot_service::Factory as substrate_service::components::ServiceFactory>::new_full::hddfd0006099e7961 (0x10ede61be)
  14: substrate_cli::run_node::h743fc6bc06fcdcd1 (0x10ebc16fe)
  15: substrate_cli::parse_and_execute::he61bf40e6fd1e926 (0x10ebbc3c5)
  16: polkadot::main::h01d684af4464f07e (0x10ec34add)
  17: std::rt::lang_start::{{closure}}::hce5611c565900161 (0x10ebe7615)
  18: std::panicking::try::do_call::h1252fc9a2ff235eb (0x10ff50b07)
  19: ___rust_maybe_catch_panic (0x10ff59aee)
  20: std::rt::lang_start_internal::h4c054360e442146c (0x10ff515ed)
  21: _main (0x10ec34c68)

Thread 'main' panicked at 'assertion failed: T::Currency::free_balance(&stash) >= balance', /Users/zhangwei/.cargo/git/checkouts/substrate-7e08433d4c370a21/8b92a59/srml/staking/src/lib.rs:488

**Comment by bkchr** [comment]
What did you run? Which version?

**Comment by xlc** [comment]
https://github.com/paritytech/substrate/blob/8b92a59/srml/staking/src/lib.rs#L488

Bad chain spec

**Comment by bkchr** [comment]
So probably an old version, please update.
