### ISSUE TITLE
getMetadata might stall the node's rpc

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/polkadot#3053]
When using states_getMetadata rpc to retrieve metadata for a specific block of kusama like block#6137912 or block#7100891, it will take more than 1min before the websocket connection be closed by the node. (I also tested other endpoints listed in polkadot-ui, if using parity's endpoint i will get a response eventually, for other endpoints my ws connections were all disconnected)
The problematic blocks are usually block that contains code update, but not all these kind of blocks will trigger this issue.

The other consequences are 
1. 1 core of cpu will be 100% occupied for 5-10min before becoming to idle again.
2. no new ws connection can be established
3. some of the connected ws connections will be closed, some won't but they stop receiving subscriptions (like new headers) neither they can perform new rpc calls.

## Platform:
cpu: 4 cores, 16G mem
node version: v0.9.1
network: kusama 
archive node

## test scripts
```
// node --experimental-repl-await

const { ApiPromise, WsProvider } = require('@polkadot/api');
const provider = new WsProvider(endpoint)

api = await ApiPromise.create({ provider });
let b7100891 = '0x0c3743f02f149d2513784ee48648c6e2b5be2b0cf2c477c34de4c7b2b74eb285';
b6137912 = '0x6f3f5cf507a83d05cb6339273d57517972d5e7482f192f107eacd0356f286a87';
console.time('getMetadata')
await api.rpc.state.getMetadata(b7100891)
console.timeEnd('getMetadata')

```

**Comment by bkchr** [comment]
> block#6137912 or block#7100891,

and any block in between doesn't have this problem?

**Comment by ianhe8x** [comment]
I'm not sure, because the strategy of my app is to build and catch registry at the block contains new runtime upgrade so the following blocks won't trigger getMetadata

**Comment by bkchr** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/0x0c3743f02f149d2513784ee48648c6e2b5be2b0cf2c477c34de4c7b2b74eb285

Just tried and it responded in seconds?

**Comment by ianhe8x** [comment]
Try this link https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/0x5d8a24b3edf87f1f9fe28372d802f63197f1a3fab278f1b7d5e7f65d9a36bc42
This is the block after 7100891. 

7100891 itself uses metadata of 7100890 to decode

**Comment by ianhe8x** [comment]
@bkchr Just follow up here, can you confirm this do be an issue?

**Comment by bkchr** [comment]
@arkpar is that maybe related to the trie and we run into some performance problems when we fetch a block that enacted a new runtime?

**Comment by chevdor** [comment]
I tested the 2 hashes mentioned and one in between and I don't see the issue with my first tests.
I usually get responses within ~200ms.

```
 time subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b 0x6f3f5cf507a83d05cb6339273d57517972d5e7482f192f107eacd0356f286a87 && ll /tmp/test.wasm
subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b   0.21s user 0.04s system 33% cpu 0.759 total
-rw-r--r--  1 will  wheel  2301867 May 26 15:44 /tmp/test.wasm
```

```
 $ time subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b 0x0c3743f02f149d2513784ee48648c6e2b5be2b0cf2c477c34de4c7b2b74eb285 && ll /tmp/test.wasm
subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b   0.22s user 0.05s system 32% cpu 0.821 total
-rw-r--r--  1 will  wheel  2008974 May 26 15:44 /tmp/test.wasm
```

```
$ time subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b 0x46e88dbe1ab021ce8a30b30e7fbb7e397ba68a6cf9866ef9fbd890742ac0d4a5 && ll /tmp/test.wasm
subwasm get -o /tmp/test.wasm wss://kusama-rpc.polkadot.io -b   0.21s user 0.04s system 33% cpu 0.746 total
-rw-r--r--  1 will  wheel  2371624 May 26 15:46 /tmp/test.wasm
```

That being said, I did not use the JS API and I probably did not use the same rpc endpoint than you (I used wss://kusama-rpc.polkadot.io as you can see above).

Testing the following could be helpful:
- could you test your snippet against `wss://kusama-rpc.polkadot.io`
- is your endpoint accessible to the public? If so, I could test against it on my end

That would help us figure out whether what you see is due to your client or to the node.

I did also test from https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/js using the snippet below and that indeed takes MUCH longer (16-20s).


<details>
<summary>Snippet</summary>

```
let b7100891 = '0x0c3743f02f149d2513784ee48648c6e2b5be2b0cf2c477c34de4c7b2b74eb285';
b6137912 = '0x6f3f5cf507a83d05cb6339273d57517972d5e7482f192f107eacd0356f286a87';
var before = Date.now();
let res = await api.rpc.state.getMetadata(b7100891)
var after = Date.now()
console.log('elapsed (ms)', after-before)
console.log(res)
```
</details>

<details>
<summary>Output</summary>

```
elapsed (ms) 16701
{magicNumber: 1635018093, met....
```

</details>

**Comment by chevdor** [comment]
Wait... I take back my tests... I am fetching the **runtime** not the **metadata**.

**Comment by jacogr** [comment]
At the blockhash -

![image](https://user-images.githubusercontent.com/1424473/119684178-93b37f80-be44-11eb-8775-a514d6bfe5fe.png)

`11:39:00.735` request sent, `11:39:19.715` response received so `19.715s` to retrieve (take this with a grain of salt, I don't have the speediest connection ever)

The time between `1:39:19.715` and `11:39.29.329` (when the next request for getStorage goes) is the parsing time of that data into the JS objects. (Certainly not speedy in itself, generally I see between 1.5 and 2s for that in my tests)

**Comment by arkpar** [comment]
I'll look into profiling this, one I get my archive node synced.

**Comment by arkpar** [comment]
@basti It is busy doing trie iteration in `sp_io::storage::next_key_version_1` indeed. Is it supposed to iterate over a lot of keys?

**Comment by arkpar** [comment]
@ianhe8x As a workaround, try running with `--db-cache=8192`

**Comment by ianhe8x** [comment]
do it right away. will report back.
