### ISSUE TITLE
Fees and Tips are incorrectly split between Treasury and Block producer

### ISSUE THREAD

**Issue by xx-labs** [paritytech/polkadot#3054]
This issue is related to substrate issue #8854
https://github.com/paritytech/substrate/issues/8854

This issue also directly affects Polkadot, since the DealWithFees implementation assumes the fees are the first element.
https://github.com/paritytech/polkadot/blob/bb2ac8a7d40e5e722084ba0ec3b54cca6f18db19/runtime/common/src/impls.rs#L39-L61

This bug can be found in the Polkadot Mainnet.
Here is an example of a transfer without tips:
https://polkadot.js.org/apps/#/explorer/query/0x0218a64f98f808d654f9113cd1feeb70d66e1fb02742b2ee43df33d3b88922e7
The totality of the transaction fee is deposited in the block producer's account.

Here is an example of a transfer with a tip:
https://polkadot.js.org/apps/#/explorer/query/0xf0d74cc96794b6ef3ff3836ff115bff18fefb9132790ae033d5d5014a24cb102
The totality of the transaction fee + 20% of the tip is deposited in the block producer's account.
80% of the tip is deposited into the Treasury account.

**Comment by bkchr** [comment]
Cc @kianenigma

**Comment by thiolliere** [comment]
This is fixed on substrate master, should be automatically fix on polkadot master on its next substrate update https://github.com/paritytech/substrate/issues/8854

**Comment by shawntabrizi** [comment]
cc @kirushik @kirushik-parity

**Comment by thiolliere** [comment]
This should have been fixed through https://github.com/paritytech/polkadot/pull/3062
