### ISSUE TITLE
Import failed for block 5205486

### ISSUE THREAD

**Issue by aaadipop** [paritytech/polkadot#3094]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
- linux / 32Gb
- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
- https://gist.github.com/aaadipop/e112aeb71a3f7b1af17a96789898e930
- Describe the role your node plays, e.g. validator, full node or light client.
- full node
- Any command-line options were passed?
- --pruning archive

hey, after yesterday's err with memory, I downgraded the node to v8.30 them back to v9.2 

with v8.30 this issue doesn't occur

**Comment by Neurone** [comment]
Looking at the log the error is with block **5205487** (hash 0xdadc3cd2f3aad410f6a12894b1b42fe75b67c0c1d230e2194e587b50e940ee0c) not 5205486.

**Comment by bkchr** [comment]
This is fixed with the 0.9.3 release
