### ISSUE TITLE
Feature: chain spec extension to indicate which runtime is expected

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot#3110]
The Polkadot node can run many runtimes (kusama, westend, rococo, ...). When starting a node from a chain spec json file, the node needs to determine which runtime to use. There are currently two approaches available to users:

1. use a cli flag such as `--force-westend`
2. name your spec file starting with a magic string such as `westend-custom-local.json`.

This issue proposes a third option (and possibly the removal of the second option). Add a chain spec extension field to indicate which runtime is expected. The syntax in the json file would be like
```json
"runtime": "westend",
```

This is similar to the approach in cumulus where the parachain spec indicates which relay chain is backing this parachain ([code](https://github.com/paritytech/cumulus/blob/36c6da180a43f2decaa4d5f7c8147fcbf1a6d20e/polkadot-parachains/src/chain_spec.rs#L43-L44)).

**Comment by crystalin** [comment]
According to https://github.com/paritytech/polkadot/blob/master/cli/src/command.rs#L106, the `--force-westend` flag is only use to specify which network to load the specs for, not the runtime (which is retrieved using the prefix of `id` from the specs)

**Comment by JoshOrndorff** [comment]
You're right @crystalin Thanks for explaining.

I was briefly thinking it would still be nice to use a field rather than the `starts_with` technique, but now I realize you can't even look at the fields until after you have opened the spec.
