### ISSUE TITLE
crowdloan.Onboarded event is never emitted

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#3127]
https://github.com/paritytech/polkadot/blob/8879b79f3c2396c0c152e0face02402305be245c/runtime/common/src/crowdloan.rs#L241-L242

Cannot find any code that emit Onboarded event. Is this intentional?

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by xlc** [comment]
Closed by #3174
