### ISSUE TITLE
Westend and Kusama local are not working properly with parachains.

### ISSUE THREAD

**Issue by riusricardo** [paritytech/polkadot#3145]
Parachains aren't producing blocks on westend local. Shell started working after PR https://github.com/paritytech/polkadot/pull/3130 but Aura parachains aren't working.

Here are the logs of rococo-local and westend-local using the same binary. I changed Westend's epoch time to make it faster for testing and creating this logs. The parachain should be producing blocks around block 40.

Cumulus commit: master#540e74d33c09f27253f0f1c0671315fc035c371f
Collators and validators logs for Rococo and Westend local: [westmint-westend-local.zip](https://github.com/paritytech/polkadot/files/6571890/westmint-westend-local.zip)

**Comment by riusricardo** [comment]
This error can be reproduced manually or with polkadot launch with the cumulus rococo-runtime parachain.
Manual test:
```
polkadot build-spec --chain westend-local --disable-default-bootnode > westend-local.json

polkadot --execution wasm --chain ./westend-local.json --tmp --ws-port 9944 --port 30333 --alice
polkadot --execution wasm --chain ./westend-local.json --tmp --ws-port 9945 --port 30334 --bob

polkadot-collator export-genesis-state --parachain-id 1000 > para-1000-genesis
polkadot-collator export-genesis-wasm > para-1000-wasm

polkadot-collator \
--collator \
--alice \
--tmp \
--parachain-id 1000 \
--port 40333 \
--ws-port 9844 \
-- \
--execution wasm \
--chain ./westend-local.json \
--port 30377 \
--ws-port 9977
```

Polkadot Launch:
```
{
	"relaychain": {
		"bin": "polkadot",
		"chain": "westend-local",
		"nodes": [
			{
				"name": "alice",
				"wsPort": 9944,
				"port": 30444
			},
			{
				"name": "bob",
				"wsPort": 9955,
				"port": 30555
			}
		],
		"runtime_genesis_config": {
			"parachainsConfiguration": {
				"config": {
					"validation_upgrade_frequency": 1,
					"validation_upgrade_delay": 1
				}
			}
		}
	},
	"parachains": [
		{
			"bin": "polkadot-collator",
			"id": "1000",
			"balance": "1000000000000000000000",
			"nodes": [
				{
					"name": "alice",
					"wsPort": 9988,
					"port": 31200,
					"flags": ["-laura=debug", "--", "--execution=wasm"]
				}
			]
		}
	],
	"simpleParachains": [
	],
	"hrmpChannels": [],
	"types": {
		"BridgedBlockHash": "H256"
	},
	"finalization": false
}
```

**Comment by bkchr** [comment]
While polkadot launch did not registered the chain automatically for me, after registering the parachain manually it worked :shrug:

**Comment by riusricardo** [comment]
Closing now because I can't reproduce anymore with master. Only the polkadot issue is still present
