### ISSUE TITLE
Typesafe MultiAsset Wildcards 

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#3168]
Right now, wildcard `MultiAsset` values (which are entirely indefinite and dependent on some context) are expressed by the same type as definite `MultiAsset` values. This leads to issues where items are accidentally not handled since indefinite wildcard values are unresolved at the time of handling and erroneously ignored.

To combat this, there should a new type `WildMultiAsset` which alone can express indefinite wildcard values. This is what would be typically used in XCM, but most internal functions would continue to operate on `MultiAsset` values (which will be altered so that it can only express definite assets). A `WildMultiAsset::resolve` function would convert one to the other, given a _context_, which would typically be the holding account.

This would probably be best combined with the move to the new `MultiAsset` (https://github.com/paritytech/polkadot/pull/2815).

**Comment by apopiak** [comment]
Is this fully addressed by #2815 ?

**Comment by KiChjang** [comment]
I believe this is fully resolved as of XCM v3.
