### ISSUE TITLE
parachain validation function and linear memory

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#317]
For now it seems that the parachain validation function host environment provides and the parachain wasm imports a linear memory instance.

On the other hand, substrate does it the other way around: the host just imports the memory exported by the wasm runtime. 

In substrate this is not much important since the wasm binary is always trusted. However, this is not the case for the parachain wasm. If we were to make the wasm parachain to export a linear memory then it could declare that that the memory instance requires huge amount of memory and as part of instantiation the wasm engine would happiliy allocate up to 4GB of memory. This is fixable but requires either deserialization of a wasm module and checking its memories or implementing configurable limits in the wasm engine.

I wonder if we should reconsider these design decisions. Also I wonder there are any  implications for cumulus

**Comment by gavofyork** [comment]
So... what? We should alter Substrate to make sure the node provides the memory rather than the Wasm blob? Or is it no trouble to keep them different? CC @arkpar @bkchr

**Comment by arkpar** [comment]
I'd just set a hard limit for parachain validation. 256MiB perhaps.

**Comment by pepyakin** [comment]
I think it might be end up being no trouble! I just didn't think about that at all and have no idea of implications of this difference.

Setting a hard limit sounds OK for me. Although as I have said, we would need to alter either wasmi or deserialize a module and check the limit set by the module manually.
