### ISSUE TITLE
Polkadot Node Errors

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/polkadot#3182]
Hi I'm running the Polkadot Node on my Mac and I'm getting the following errors in my terminal. I'm not sure why this is happening, so I'm just dropping in to hopefully get some support. Thanks!
<img width="1146" alt="polkadotnode" src="https://user-images.githubusercontent.com/62865359/120852271-fba24e00-c547-11eb-9eba-20e90c30e9d5.png">

**Comment by bkchr** [comment]
use `purge-db` and also use release mode.

**Comment by J-Cook-jr** [comment]
Ok, I will do that. If I'm wishing to run in dev mode, is release and dev mode the same?

**Comment by Swader** [comment]
Dev mode is the type of running the chain. Release mode is how it's compiled.
