### ISSUE TITLE
use `purge-db` and also use release mode.

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/polkadot#3183]
use `purge-db` and also use release mode.

_Originally posted by @bkchr in https://github.com/paritytech/polkadot/issues/3182#issuecomment-854969135_

How do I update the node I'm using?

**Comment by bkchr** [comment]
Can you please stop to create new issues.

This issue tracker is not for explaining how git or github works. 

Not sure which version you want to update. You can checkout the relevant tag for example.

**Comment by J-Cook-jr** [comment]
I just created a new issue for it https://github.com/paritytech/polkadot/issues/3185#issue-911833124
