### ISSUE TITLE
validation host is too eager to deem a candidate invalid

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3192]
Recently we observed that the validation host may fail to communicate with the child process that is responsible for compiling the PVF. This now leads to validation host thinking that the PVF that is broken. Therefore, all following execution requests will fail with "invalid candidate".

The logic there is wrong because failing to communicate with the child process should not lead to claiming that the candidate is invalid. 

Besides that, it is not clear to me if we should deem the candidate invalid if the PVF itself is invalid.

**Comment by rphmeier** [comment]
I think that from the perspective of the high-level code the 'validate candidate' API should make a best effort to validate the candidate and if that fails then to be clear that there has been an internal failure. We must make sure that malicious code cannot cause issues presenting as an internal failure. When internal issues are encountered the candidate validation subsystem might retry a few times to present an API which the high level code can use simply to answer the question of validity

**Comment by burdges** [comment]
Yes exactly, we should report how we fail though when starting a dispute.  We should relevant logs related to disputes too.

**Comment by pepyakin** [comment]
I was thinking about this and I am not sure if I agree.

Imagine a malicious PVF crafted so that it would OOM on 50% of machines during compilation. This would make one side of the chasm to think the candidates for that PVF are valid and the other side would think it is invalid. 

Is that really worse than if the second side thought that this is an internal failure?

**Comment by rphmeier** [comment]
> Imagine a malicious PVF crafted so that it would OOM on 50% of machines during compilation. This would make one side of the chasm to think the candidates for that PVF are valid and the other side would think it is invalid.

Can't this be averted somehow? We must have some kind of threat model for parachains where the compilation can succeed on all machines
