### ISSUE TITLE
Disputes via approval-checking

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3222]
1. Introduce a new type of approval vote which is a disapproval vote
2. In the presence of even a single disapproval vote,  the candidate is escalated to be checked by all validators
3. The `approved_ancestor` logic can avoid finalizing anything which has even one disapproval which has not been approved by at least f+1 nodes. We may want to wait for 2f+1 so the candidate doesn't get finalized before there are enough votes to slash the offender.
4. The dispute participation subsystem is no longer necessary
5. The dispute distribution subsystem is no longer necessary

If a candidate is in fact valid and a validator disputes its validity, then the majority of validators will approve it and the approval voting subsystem will eventually finalize it.

If a candidate is not valid and a validator disputes its validity, then the majority of validators will disapprove it and the dispute coordinator system will eventually abandon the chain.

**Comment by burdges** [comment]
If we escalate then we'll want 2f+1 approvals before finality, not just f+1.  It's true if we have f+1 approvals then we'll never slash anyone, but if we get f+1 disapprovals too, then we'll revert the chain without slashing.

**Comment by rphmeier** [comment]
There's a bit too much complexity in doing that in the approval-voting subsystem, due to needing the 2f+1 in the union of backing and approval votes, but we can do that using the dispute coordinator.
