### ISSUE TITLE
Add dispute_period and random_seed to SessionInfo

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3227]
This will let us refactor the rolling session window based on `dispute_period` of the highest session, and change its uses in approval voting and the dispute coordinator to avoid hardcoded window sizes.

Alternatively, expose `dispute_period` by some other runtime API. However, the cleanest would be to use `SessionInfo`.

cc @ordian

**Comment by ordian** [comment]
We could also add `random_seed` from initializer to SessionInfo, that would be useful #3270.

**Comment by rphmeier** [comment]
I also recommend a new type for `SessionInfo` within the `session_info` runtime module so that changes in primitives don't silently invalidate runtime storage. I expect an `Into<primitives::SessionInfo> for runtime::session_info::SessionInfo>` would make the implementation of the runtime API easy.
