### ISSUE TITLE
Windows build failure on 0.9.4

### ISSUE THREAD

**Issue by akru** [paritytech/polkadot#3231]
While building Polkadot for windows target https://github.com/airalab/robonomics/runs/2813205199?check_suite_focus=true 

I get an error of using hardcoded os::unix in polkadot-node-core-pvf.

**Comment by bkchr** [comment]
Yeah, we don't support windows. 

You can maybe try it with the unix subsystem, but that's it.

**Comment by bkchr** [comment]
CC @pepyakin

**Comment by akru** [comment]
I see, Polkadot builds without issues in past, anyway thank you!

**Comment by pepyakin** [comment]
Yes, with the recent emerge of WSL we didn't think it is worth of hassle to make it work on Windows/MSVC. That said, when everything settles and/or we get a little bit less crunching on delivering the base functionality of polkadot we may reconsider this.
