### ISSUE TITLE
Reserved KSM by `nicks` pallet can't be released

### ISSUE THREAD

**Issue by michalisFr** [paritytech/polkadot#3243]
A user has a reserved amount of 10 KSM due to using the `nicks.set_name` extrinsic a long time ago. Now they don't have a way to remove that reserve because the `nicks` pallet is no longer part of the runtime.

Is there a workaround they can use to release that reserve? And if there isn't, how can this be resolved for them and other users who may face this issue?

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by shawntabrizi** [comment]
@michalisFr I dont see any on-chain data which has the information about the users who used nicks. Do you have some kind of transaction data or block explorer where we can get the list?

Ultimately if we can collect an accurate list of users who this affects, we can make a simple governance proposal.

**Comment by michalisFr** [comment]
I don't have any @shawntabrizi. We only know of this one user that wrote in support with this issue. I'll ping Jake who's working on a script to finds other users in the same position.

So, I gather there's no way for them to release these funds themselves, right?

**Comment by xlc** [comment]
Here are all the Nicks events https://kusama.subscan.io/event?address=&module=nicks&event=all&startDate=&endDate=
Latest one is a NameSet so this guy likely have some extra reserved balance if the upgrade that removes nicks pallet didn't correctly clean up the state https://kusama.subscan.io/extrinsic/0x121d10050dc3a5d73014432c0f6014d4c5bef79bbe0ec8d1e0ff32a402d51ba2?event=563794-4

**Comment by jakehemmerle** [comment]
fwiw @michalisFr finished a script finding accounts that:

- Have issued at least one successful set_name extrinsic
- Haven't issued a successful clear_name extrinsic after that
- Have at least 10 KSM reserved balance

corrosponding accounts:
[accounts.json.txt](https://github.com/paritytech/polkadot/files/6658750/accounts.json.txt)

Maybe include the script here for ref @michalisFr ?

**Comment by shawntabrizi** [comment]
Yeah, and I would be interested to know how many accounts which satisfy the first two points dont satisfy the third point

**Comment by michalisFr** [comment]
@shawntabrizi I did a little refactoring to get you the output you wanted:
```
Accounts with `set_name`: 153
Accounts that didn't issue a `clear_name`: 115
Accounts without a `clear_name` but less than 10 KSM reserved: 84
Accounts with reserved KSM: 31
```

Here's the script (it's in python): 
[accounts_extrinsics.py.zip](https://github.com/paritytech/polkadot/files/6661708/accounts_extrinsics.py.zip)

Now, from my understanding from @xlc's comment, when the nicks pallet was removed the names should have been cleared? So, that perhaps explains these 84 accounts. Although, if that's the case, it obviously didn't happen for all accounts.

However, there are two pieces of information this output doesn't provide:
1. If my understanding above is correct, we can't be sure the reserved amount for these 31 accounts is from `set_name` or other sources
2. There was one account:
CmD9vaMYoiKe7HiFnfkftwvhKbxN9bhyjcDrfFRGbifJEG8
that issued a successful `clear_name` without a previous `set_name`. 
It seems in some cases `set_name` was issued by `sudo` for some accounts, so there may be accounts with reserved amounts because of this that never issued a `set_name` or `clear_name`.

To answer these more digging is required. The first one could be done manually too.

**Comment by michalisFr** [comment]
I took an in-depth look at these accounts I found, although from the 31 only 21 had a reserved amount larger than 10 KSM after all (not sure why the other 10 were included in the results).

- From these 21, I found 6 that `almost certainly` and 6 that `probably` have a reserve due to `nicks`.
- I also found a recurring 0.01 KSM reserved amount in 7 of them that I can't explain
- Almost all of them have an Account Index, but I don't know if it's relevant. 
- "Chevdor" has a total reserve that's less than the sum of its parts, for some reason
- @shawntabrizi Your account is on that list too, but I didn't look into it cause you have almost 8000 extrinsics! But it doesn't look likely.

Here are my findings:
[nicks investigation.xlsx](https://github.com/paritytech/polkadot/files/6718035/nicks.investigation.xlsx)

**Comment by michalisFr** [comment]
Hey @shawntabrizi! 

I wanted to revive this issue and see what we can do about these accounts that have reserved balance from `nicks`. If there's no technical solution to this we should create a governance proposal to release these reserves.

But I don't want us to miss any accounts that might have the same problem or, even worse, accidentally release funds that are supposed to be reserved. So it'd be good if someone more technically oriented than me can look into this and see if they can verify my findings.

**Comment by shawntabrizi** [comment]
using governance is the right way here. The only other way of fixing this issue would be to introduce the nicks pallet back into the runtime or something.

You can start a chat with me, raul, and yourself in Element to work out the proper proposal to submit.

**Comment by KiChjang** [comment]
I suppose this has been fixed? If so, I'm closing for now, feel free to reopen if I'm mistaken.
