### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Allocator ran out of space"'

### ISSUE THREAD

**Issue by dave4you** [paritytech/polkadot#3280]
2021-06-17 11:05:59  ⚙️  Syncing  0.0 bps, target=#5545134 (28 peers), best: #5202215 (0xa1ef…ee60), finalized #5202213 (0x23a2…d92d), ⬇ 1.8kiB/s ⬆ 1.2kiB/s    

2021-06-17 11:06:04  ⚙️  Syncing  0.0 bps, target=#5545134 (27 peers), best: #5202215 (0xa1ef…ee60), finalized #5202213 (0x23a2…d92d), ⬇ 1.9kiB/s ⬆ 1.7kiB/s    

====================

**Version: 0.8.29-72ce1c82-x86_64-linux-gnu**

   0: sp_panic_handler::set::{{closure}}

   1: std::panicking::rust_panic_with_hook

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17

   2: std::panicking::begin_panic_handler::{{closure}}

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13

   3: std::sys_common::backtrace::__rust_end_short_backtrace

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18

   4: rust_begin_unwind

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5

   5: core::panicking::panic_fmt

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14

   6: core::option::expect_none_failed

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5

   7: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute

   8: wasmtime::func::Func::new::{{closure}}

   9: wasmtime::trampoline::func::stub_fn

  10: <unknown>

  11: <unknown>

  12: <unknown>

  13: <unknown>

  14: <unknown>

  15: <unknown>

  16: <unknown>

  17: <unknown>

  18: <unknown>

  19: <unknown>

  20: RegisterSetjmp

  21: wasmtime_runtime::traphandlers::catch_traps

  22: wasmtime::func::Func::call

  23: sc_executor_wasmtime::instance_wrapper::EntryPoint::call

  24: scoped_tls::ScopedKey<T>::set

  25: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call

  26: sc_executor_common::wasm_runtime::WasmInstance::call_export

  27: std::panicking::try

  28: std::thread::local::LocalKey<T>::with

  29: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}

  30: sc_executor::wasm_runtime::RuntimeCache::with_instance

  31: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call

  32: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux

  33: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler

  34: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call

  35: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at

  36: sp_api::runtime_decl_for_Core::execute_block_call_api_at

  37: sp_api::Core::execute_block_with_context

  38: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block

  39: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block

  40: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Sync+core::marker::Send> as sp_consensus::block_import::BlockImport<B>>::import_block

  41: sp_consensus::import_queue::import_single_block_metered

  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

  44: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll

  45: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll

  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

  47: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll

  48: std::thread::local::LocalKey<T>::with

  49: futures_executor::local_pool::block_on

  50: tokio::runtime::task::core::Core<T,S>::poll

  51: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once

  52: tokio::runtime::task::harness::Harness<T,S>::poll

  53: tokio::runtime::blocking::pool::Inner::run

  54: tokio::runtime::context::enter

  55: std::sys_common::backtrace::__rust_begin_short_backtrace

  56: core::ops::function::FnOnce::call_once{{vtable.shim}}

  57: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9

      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9

      std::sys::unix::thread::Thread::new::thread_start

             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17

  58: start_thread

  59: __clone

Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Allocator ran out of space"', /rustbuilder/.cargo/git/checkouts/substrate-7e08433d4c370a21/61b1eb8/primitives/io/src/lib.rs:1048

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

2021-06-17 11:06:05  Block prepare storage changes error:

RuntimeApiError(Application(Execution(Other("Wasm execution trapped: Failed to allocate memory: \"Allocator ran out of space\"\nwasm backtrace:\n    0: 0x1601 - <unknown>!sp_io::allocator::extern_host_function_impls::malloc::h3ba50d5b2de26c25\n    1: 0xcf604 - <unknown>!core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::he3692847e41b46cc\n    2: 0xcf1c2 - <unknown>!sp_npos_elections::setup_inputs::hd89ca1e0feeaabd9\n    3: 0x90707 - <unknown>!sp_npos_elections::phragmen::seq_phragmen::hd129027c03c0249a\n    4: 0xa1161 - <unknown>!pallet_staking::Module<T>::new_era::hf7fe25e8949425a7\n    5: 0x9930e - <unknown>!<(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize::h398bc3af78c339e8\n    6: 0x1576c3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block::h975d2a527ce51f82\n    7: 0x15082b - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))    

2021-06-17 11:06:05  💔 Error importing block 0xd79f21595fb10471ab2b0d9427dffa8de4001c351a53f408995cf2dda309e43a: Err(Other(ClientImport("Import failed: Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: Failed to allocate memory: \\\"Allocator ran out of space\\\"\\nwasm backtrace:\\n    0: 0x1601 - <unknown>!sp_io::allocator::extern_host_function_impls::malloc::h3ba50d5b2de26c25\\n    1: 0xcf604 - <unknown>!core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::he3692847e41b46cc\\n    2: 0xcf1c2 - <unknown>!sp_npos_elections::setup_inputs::hd89ca1e0feeaabd9\\n    3: 0x90707 - <unknown>!sp_npos_elections::phragmen::seq_phragmen::hd129027c03c0249a\\n    4: 0xa1161 - <unknown>!pallet_staking::Module<T>::new_era::hf7fe25e8949425a7\\n    5: 0x9930e - <unknown>!<(TupleElement0,TupleElement1) as frame_support::traits::OnInitialize<BlockNumber>>::on_initialize::h398bc3af78c339e8\\n    6: 0x1576c3 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block::h975d2a527ce51f82\\n    7: 0x15082b - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))    

2021-06-17 11:06:05  💔 Error importing block 0x5921b7b1b5269c96e91421f5b55d37c70db36d99fa3a207ce50429b3a20d7939: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0x4e2825636313cb034d0673571065869921a1aed0d088fe781134bce12a2c44df: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0x40a62de11bffe2af4a0ee6368554e133b9ffde3ef44b5e755b091fbf3185f776: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0xa1c3ac904935bfbae42d6402df189392efda3d89c59737741bd92d30f09f63d4: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0xf120666f47cc30b6403d0154df21b58e9093977afbe9fe9e180feea74f70a5b8: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0x1eabcf8103e4e51e85c489478b71731aaec43b6865019b758133cea3619f1e0f: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0x2e67be84d6efd4ff84ebbb94881d27e02fda4bbf5c600fa41b404bfd9d296ba9: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0xb3b7289b39d9b19cf2227aef66ab76212f51f78814c9b45a1eb846c351d435ae: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0x7da7eb7064ea0ea8d9d0bceaf9717fb4f416f4db5ffe1d4f54579e596afbfbd3: Err(UnknownParent)    

2021-06-17 11:06:05  💔 Error importing block 0xa6399c700db507d3ae6885dc4ed53f8b786ade74f3bbc827a8aa379d0dd5f1d3: Err(UnknownParent)    

2021-06-17 11:06:09  ⚙️  Syncing  0.0 bps, target=#5545134 (20 peers), best: #5202215 (0xa1ef…ee60), finalized #5202213 (0x23a2…d92d), ⬇ 539.7kiB/s ⬆ 3.1kiB/s

**Comment by mnguyen-io** [comment]
Getting the same error here

```
Jun 17 11:32:12 localhost polkadot-v0.9.3[18719]: 2021-06-17 11:32:12  💤 Idle (49 peers), best: #5545120 (0x02ea…94a2), finalized #5545118 (0x3a85…b719), ⬇ 261.1kiB/s ⬆ 211.7kiB/s
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: ====================
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: Version: 0.9.3-aa3867609-x86_64-linux-gnu
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    0: sp_panic_handler::set::{{closure}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    1: std::panicking::rust_panic_with_hook
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    2: std::panicking::begin_panic_handler::{{closure}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    4: rust_begin_unwind
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    5: core::panicking::panic_fmt
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    6: core::option::expect_none_failed
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    7: tracing::span::Span::in_scope
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    8: <<sp_io::allocator::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtAllocatorMallocVersion1 as sp_wasm_interface::Function>::execute
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:    9: scoped_tls::ScopedKey<T>::with
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   10: sc_executor_wasmtime::state_holder::with_context
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   11: sc_executor_wasmtime::imports::call_static
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   12: wasmtime::func::Func::new::{{closure}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   13: wasmtime::trampoline::func::stub_fn
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   14: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   15: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   16: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   17: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   18: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   19: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   20: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   21: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   22: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   23: <unknown>
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   24: RegisterSetjmp
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   25: wasmtime_runtime::traphandlers::catch_traps
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   26: wasmtime::func::Func::_call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   27: wasmtime::func::Func::call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   28: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   29: scoped_tls::ScopedKey<T>::set
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   30: sc_executor_wasmtime::runtime::perform_call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   31: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   32: sc_executor_common::wasm_runtime::WasmInstance::call_export
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   33: std::panicking::try
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   34: std::thread::local::LocalKey<T>::with
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   35: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   36: sc_executor::wasm_runtime::RuntimeCache::with_instance
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   37: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   38: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   39: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   40: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   41: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   42: sp_api::runtime_decl_for_Core::initialize_block_call_api_at
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   43: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_initialize_block_runtime_api_impl
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   44: sp_api::Core::initialize_block
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   45: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   46: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   47: sp_authority_discovery::runtime_decl_for_AuthorityDiscoveryApi::authorities_call_api_at
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   48: sp_authority_discovery::AuthorityDiscoveryApi::authorities
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   49: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   50: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   52: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   53: tokio::runtime::task::core::Core<T,S>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   54: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   55: tokio::runtime::task::harness::Harness<T,S>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   56: std::thread::local::LocalKey<T>::with
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   57: tokio::runtime::thread_pool::worker::Context::run_task
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   58: tokio::runtime::thread_pool::worker::Context::run
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   59: tokio::macros::scoped_tls::ScopedKey<T>::set
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   60: tokio::runtime::thread_pool::worker::run
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   61: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   62: tokio::runtime::task::core::Core<T,S>::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   63: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   64: std::panicking::try
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   65: tokio::runtime::task::raw::poll
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   66: tokio::runtime::blocking::pool::Inner::run
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   67: tokio::runtime::context::enter
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   68: std::sys_common::backtrace::__rust_begin_short_backtrace
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   69: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   70: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:       std::sys::unix::thread::Thread::new::thread_start
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   71: start_thread
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]:   72: __clone
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/85fa0ab/primitives/io/src/lib.rs:1068
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: This is a bug. Please report it at:
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: #011https://github.com/paritytech/polkadot/issues/new
Jun 17 11:32:13 localhost polkadot-v0.9.3[18719]: 2021-06-17 11:32:13  Failed to publish external addresses: CallingRuntime(RuntimeApiError(Application(Execution(Other("Wasm execution trapped: Failed to allocate memory: \"Requested allocation size is too large\"\nwasm backtrace:\n    0: 0x1a33e2 - <unknown>!sp_io::allocator::extern_host_function_impls::malloc::h98aee1dfcd9b68c4\n    1: 0x1525 - <unknown>!__rg_realloc\n    2: 0x151a - <unknown>!__rust_realloc\n    3: 0x12e27 - <unknown>!alloc::raw_vec::finish_grow::h26986712646e2a6f\n    4: 0x11c7c - <unknown>!<sp_std::Writer as core::fmt::Write>::write_str::h3cc6a45a5103153c\n    5: 0x3719c - <unknown>!<X as parity_scale_codec::codec::Encode>::encode_to::h15cf7a276aeb60d9\n    6: 0x174d46 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::initialize_block::h43e8bad2af7de2d8\n    7: 0x17a353 - <unknown>!Core_initialize_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n")))))
```

**Comment by past2017** [comment]
same issue

**Comment by mnguyen-io** [comment]
Just a heads up to those seeing this issue - they've asked to downgrade to 0.8.30 and run with the following added: --execution native --wasm-execution Compiled

**Comment by AlexZhenWang** [comment]
> Just a heads up to those seeing this issue - they've asked to downgrade to 0.8.30 and run with the following added: --execution native --wasm-execution Compiled

Hi may I ask where did they post this?

**Comment by mnguyen-io** [comment]
They use a chat/SMS program called element/matrix/riot or whatever its called now:

https://wiki.polkadot.network/docs/en/community

Usually theres a bot that echo's messages to/from there onto Discord but it seems like it's not working .

**Comment by AlexZhenWang** [comment]
> They use a chat/SMS program called element/matrix/riot or whatever its called now:
> 
> https://wiki.polkadot.network/docs/en/community
> 
> Usually theres a bot that echo's messages to/from there onto Discord but it seems like it's not working .
> 
> FYI - I've downgraded and the errors have stopped, but blocks probably won't move much until more Validators have downgraded.

Thanks @mnguyen-io

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼
