### ISSUE TITLE
sync panic

### ISSUE THREAD

**Issue by CryptoDavChen** [paritytech/polkadot#3287]
Thread 'tokio-runtime-worker' panicked at 'Failed to allocate memory: "Requested allocation size is too large"', /Users/xxx/.cargo/git/checkouts/substrate-7e08433d4c370a21/2c84b31/primitives/io/src/lib.rs:1100

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼
