### ISSUE TITLE
pallet-xcm: XcmExecuteFilter usage is a bit confusing

### ISSUE THREAD

**Issue by shaunxw** [paritytech/polkadot#3295]
In `pallet-xcm`, `XcmExecuteFilter` is applied to `execute` dispatchable call, but not to other calls like `teleport_assets` and `reserve_transfer_assets`.

With the configuration in Kusama: https://github.com/paritytech/polkadot/blob/8475048a65982a29b3d7fa3935a5897abb3cd6c3/runtime/kusama/src/lib.rs#L1350-L1351

Users can:
- Teleport via `teleport_assets` call
- Reserve transfer via `reserve_transfer_assets`
- Teleport via `execute` call.

But they cannot do:
- Reserve transfer via `execute` call.

The inconsistency is a bit confusing. If `XcmExecuteFilter` is mean to filter all XCM executions in `pallet-xcm`, it should be applied to all calls. Or if it's mean to only filter `execute` call, then the config in Kusama shouldn't filter out reserve transfer.

**Comment by KiChjang** [comment]
I think this has been fixed in the latest master. The `XcmExecuteFilter` is now set to deny all calls.
