### ISSUE TITLE
KSM teleport should filter dest chain

### ISSUE THREAD

**Issue by shaunxw** [paritytech/polkadot#3296]
Currently KSM teleport is only for between Kusama and Statemine, while the config in Kusama runtime allows to teleport to any parachain. https://github.com/paritytech/polkadot/blob/8475048a65982a29b3d7fa3935a5897abb3cd6c3/runtime/kusama/src/lib.rs#L1326

IMO we should limited the teleport dest so that users are less likely to make mistakes.

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by KiChjang** [comment]
The `OnlyWithdrawTeleportForAccounts` configuration is removed nowadays, and teleportation destinations are now controlled with the `IsTeleporter` config item in `xcm_executor::Config`.
