### ISSUE TITLE
v0.9.3 rust_panic_with_hook tokio-runtime-worker

### ISSUE THREAD

**Issue by TrustVeriCor** [paritytech/polkadot#3303]
[v093tokio-runtime-worker.txt](https://github.com/paritytech/polkadot/files/6675790/v093tokio-runtime-worker.txt)

**Comment by TrustVeriCor** [comment]
@cryptogolunar:matrix.org 

lmk if more info is needed.

**Comment by NukeManDan** [comment]
To solve this, please downgrade to Polkadot 0.8.30 and run with the following flags added or changed to the correct option:
```
polkadot --execution native --wasm-execution Compiled`
```

The easiest path is to download (and verify) the `polkadot` binary and run it:
- https://github.com/paritytech/polkadot/releases/tag/v0.8.30

If you choose to build from source, you must [use the rust 1.51.0 release](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions) of the stable and nightly toolchain: 
```bash
# Run in the top level of the Polkadot source working directory
git checkout v0.8.30
rustup override set 1.51.0
cargo build --release
```

## NOTE: There will be a 0.9.5 release very soon

You will be encouraged to use when available. Please join [Polkadot Validator Lounge](https://matrix.to/#/#polkadotvalidatorlounge:web3.foundation)  and monitor for the latest information and questions. 🙏🏼
