### ISSUE TITLE
Detected prevote equivocation in the finality worker

### ISSUE THREAD

**Issue by johnwstanford** [paritytech/polkadot#3322]
Not completely sure what this means, but it tells me to report it and I'm happy to help.  I'm running Ubuntu 21.04 with Rust 1.52.  I had my node completely synced with a build from a commit that was a few weeks old (not sure exactly which one), then I fast-forwarded to `59e9480b`, rebuilt, reran, and got this message after a few minutes.

`
2021-06-20 14:10:03 Detected prevote equivocation in the finality worker: Equivocation { round_number: 7146, identity: Public(41ef4a31eb7dc1e01f4630604e1908e644d7cdee3f66a60f98d6d59605326f8b (12VTCPo8...)), first: (Prevote { target_hash: 0x69d58870f763a9faa3ee61230f3ba8ce5e2d043b64bbcdb8c5aa9ecde596c6f1, target_number: 5545149 }, Signature(f7b3682ed175611a5a51ed80dfd91a66d7d8bcb47234159ce35156ff368b5bbe661c1478ee869f0482ad9e79e3c4c8369400fb13f685f5a9d170139ddbef4a0a)), second: (Prevote { target_hash: 0x746dbc5007833143af4762dd25d4793a2aafbca2eec472d6145ea7506074d2bb, target_number: 5545142 }, Signature(8a23a27266cd5a5510b807267b5f434d916c2897059b657b7ea3e0449d6539cc9c1014353671971db527c084cca57c89fa2c30227c7bc16ebaa8baa498be3a0c)) }    

====================

Version: 0.9.5-59e9480bc-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   7: futures_executor::local_pool::block_on
   8: sc_finality_grandpa::environment::Environment<BE,Block,C,N,SC,VR>::report_equivocation
   9: <sc_finality_grandpa::environment::Environment<B,Block,C,N,SC,VR> as finality_grandpa::voter::Environment<<Block as sp_runtime::traits::Block>::Hash,<<Block as sp_runtime::traits::Block>::Header as sp_runtime::traits::Header>::Number>>::prevote_equivocation
  10: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::handle_vote
  11: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::process_incoming
  12: finality_grandpa::voter::voting_round::VotingRound<H,N,E>::poll
  13: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  14: <finality_grandpa::voter::Voter<H,N,E,GlobalIn,GlobalOut> as core::future::future::Future>::poll
  15: <sc_finality_grandpa::VoterWork<B,Block,C,N,SC,VR> as core::future::future::Future>::poll
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  17: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  18: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  19: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  20: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  24: futures_executor::local_pool::block_on
  25: tokio::runtime::task::core::Core<T,S>::poll
  26: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  27: tokio::runtime::task::harness::Harness<T,S>::poll
  28: tokio::runtime::blocking::pool::Inner::run
  29: tokio::runtime::context::enter
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  33: start_thread
  34: clone

Thread 'tokio-runtime-worker' panicked at 'cannot execute `LocalPool` executor from within another executor: EnterError', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/local_pool.rs:81

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new
`

**Comment by andresilva** [comment]
Thanks for the report, this should be fixed with https://github.com/paritytech/substrate/pull/9154/.

**Comment by rphmeier** [comment]
Hello @johnwstanford I'd like to open a tip for you on Polkadot for finding this issue. Could you post a Polkadot address here?

**Comment by johnwstanford** [comment]
Thanks!  Glad to help.  Polkadot address is `13398FNhb9c52wdzFtkZTCXxvaS2WL1CnNZ4biYC5iURE1CD`

**Comment by andresvsm-old** [comment]
Hi, I'm encountering the same issue now. Is there any problem using --alice flag and --validator flag at the same time? I'm running a node on k8 and two nodes on a virtual machine (both in the same machine) and if I stop a node a restart it, this problem appears. I'm running the nodes using --alice, --bob and --charlie respectively and each one of them with their node-keys, so I think its not a problem about duplicated keys. Besides that, I'm running the k8 node as the boot node and connecting the other two nodes to it using the --bootnodes flag.

2022-07-06 07:00:48 Detected prevote equivocation in the finality worker: Equivocation { round_number: 2276, identity: Public(88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee (5FA9nQDV...)), first: (Prevote { target_hash: 0x4fc41711706f0ae5e7a2e79c2d235d9da18f500c6ede2aa9ed4fa1e8acf2ab02, target_number: 514 }, Signature(57cb7e704aa781c66ea8c09af189bbd7716c1ad18da989dc8f1848cf6883e3065ba6fdeb0d7f7c73f1c5635df4dd18f789f06118630932a66102b2776b0a4609)), second: (Prevote { target_hash: 0x17c4b23d640a6b976a7f8b94f7e919893066d66747f329ac430c394b14758461, target_number: 524 }, Signature(b31752a74d025ca0134d2f0b9bbcaa75d5dd2cfeb79c9d1ae66da9299668caba1e7857b7685b65730095ce703ce900b6abaca6516187b4e1f7d76aa98065e307)) }
2022-07-06 07:00:48 Error reporting prevote equivocation: safety invariant has been violated: Refraining from sending equivocation report for our own equivocation.
