### ISSUE TITLE
Trie lookup error: Database missing expected key

### ISSUE THREAD

**Issue by carumusan** [paritytech/polkadot#3323]
2021-06-20 19:38:41  ----------------------------
2021-06-20 19:38:41  This chain is not in any way
2021-06-20 19:38:41        endorsed by the
2021-06-20 19:38:41       KUSAMA FOUNDATION
2021-06-20 19:38:41  ----------------------------
2021-06-20 19:38:41  Parity Polkadot
2021-06-20 19:38:41  ✌️  version 0.9.3-aa3867609-x86_64-linux-gnu
2021-06-20 19:38:41  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-06-20 19:38:41  📋 Chain specification: Kusama
2021-06-20 19:38:41  🏷 Node name: tsuki-validator-0
2021-06-20 19:38:41  👤 Role: AUTHORITY
2021-06-20 19:38:41  💾 Database: ParityDb at /data/chains/ksmcc3/paritydb
2021-06-20 19:38:41  ⛓  Native runtime: kusama-9030 (parity-kusama-0.tx5.au2)
2021-06-20 19:38:47  🏷 Local node identity is: 12D3KooWKybRZHUVDMqQKLdgMFYu586Myo5ZPGBmhVMaKUMgxrC8
2021-06-20 19:38:47  🔍 Discovered new external address for our node: /dns/validator-0.kusama.tsukistaking.com/tcp/30333/p2p/12D3KooWKybRZHUVDMqQKLdgMFYu586Myo5ZPGBmhVMaKUMgxrC8
2021-06-20 19:38:47  📦 Highest known block at #7903560
2021-06-20 19:38:47  〽️ Prometheus server started at 127.0.0.1:9615
2021-06-20 19:38:47  Listening for new connections on 127.0.0.1:9944.
2021-06-20 19:38:47  👶 Starting BABE Authorship worker
2021-06-20 19:38:48  🔍 Discovered new external address for our node: /ip4/174.138.6.49/tcp/30333/p2p/12D3KooWKybRZHUVDMqQKLdgMFYu586Myo5ZPGBmhVMaKUMgxrC8
2021-06-20 19:38:49  🔍 Discovered new external address for our node: /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWKybRZHUVDMqQKLdgMFYu586Myo5ZPGBmhVMaKUMgxrC8

====================

Version: 0.9.3-aa3867609-x86_64-linux-gnu

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: start_thread
  57: clone

Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xbe124b46e060e833ac4ea322b41821b508cf872e236fafef71bf9bcc989b3baf"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/85fa0ab/primitives/state-machine/src/ext.rs:203

**Comment by carumusan** [comment]
Also occurs on v0.9.5. Downgrading gave the same error.

**Comment by pepyakin** [comment]
cc @cheme @arkpar

**Comment by cheme** [comment]
@carumusan , thanks for reporting the issue.

What was your launch command ? (mainly to know if you were using pruning but other parameter are interesting too).

Also any other error messages after this one?

**Comment by carumusan** [comment]
```
        args:
        - --chain=kusama
        - --validator
        - --base-path=/data
        - --name=tsuki-$(HOSTNAME)
        - --telemetry-url
        - 'wss://telemetry-backend.w3f.community/submit 1'
        - --database=paritydb-experimental
        - --public-addr=/dns/$(HOSTNAME).kusama.tsukistaking.com/tcp/30333
```

**Comment by carumusan** [comment]
No other messages.

**Comment by bakhtin** [comment]
Still happening to me on version 0.9.41-e203bfb396e

```
   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::exists_storage
   8: sp_io::storage::exists_version_1
   9: sp_io::storage::ExtStorageExistsVersion1::call
  10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: wasmtime_runtime::traphandlers::catch_traps::call_closure
  21: wasmtime_setjmp
  22: sc_executor_wasmtime::runtime::perform_call
  23: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  24: sc_executor_common::wasm_runtime::WasmInstance::call_export
  25: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  26: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  27: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  28: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  29: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  30: <kusama_runtime::RuntimeApiImpl<__SrApiBlock__,RuntimeApiImplCall> as sp_api::Core<__SrApiBlock__>>::__runtime_api_internal_call_api_at
  31: <&sc_service::client::client::Client<B,E,Block,RA> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  32: <sc_consensus_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  33: <sc_consensus_beefy::import::BeefyBlockImport<Block,BE,Runtime,I> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  34: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  35: <alloc::boxed::Box<dyn sc_consensus::block_import::BlockImport<B>+Transaction = Transaction+Error = sp_consensus::error::Error+core::marker::Sync+core::marker::Send> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  36: sc_consensus::import_queue::basic_queue::BlockImportWorker<B>::new::{{closure}}
  37: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  38: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  39: tokio::runtime::task::raw::poll
  40: std::sys_common::backtrace::__rust_begin_short_backtrace
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
  43: start_thread
  44: clone


Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xa00e1dd6362a14f185b5d46789568c63371bb7dcd528473e2edd89adfa833213"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/980eb16/primitives/state-machine/src/ext.rs:278
```

Running the node like this:
`polkadot  --base-path=/data/ --database=paritydb --pruning=archive --rpc-external --ws-external --rpc-methods=safe --rpc-cors=all`

**Comment by bkchr** [comment]
@bakhtin there is a newer issue for this. However, TLDR, it will be fixed with the next release.
