### ISSUE TITLE
Enable `ApprovalCheckingVotingRule` on Polkadot

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#3326]
Before we deploy enable parachains runtime on Polkadot
https://github.com/paritytech/polkadot/blob/59e9480bcdb9fd0b9f071f236063f54c4d2377e5/runtime/polkadot/src/lib.rs#L1185-L1242

we need to revert #3321.

**Comment by ordian** [comment]
after #3815 is merged, but before it's enacted, we'd need a client release with this fix

**Comment by rphmeier** [comment]
I think even after it's enacted is OK. Because there won't be any parachains, the voting rule will still effectively be longest-chain until relay-chain governance actually adds a parachain.
