### ISSUE TITLE
Approval Voting: Start work again on start-up

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3330]
If the node concluded without finishing approval work, the node should attempt to conclude the approval work when it starts up.

In practice, this should be done on the first activated leaf it handles, because `SessionInfo` is required to know the authorities in a given `BlockEntry`'s session.

A couple of facts worth being aware of:
  - The node gives all subsystems its current leaves on startup. This means that the first active leaf notification will be instantaneous on startup.
  - A candidate can only exist in 1 session. That means that if it appears in a block for one session, it can't appear in any other blocks that aren't in the same session.

What this consists of, in practice, is iterating over all `CandidateEntry`s stored by the approval DB, and finding those for which we've issued assignments but not approvals. [`KeyValueDB::iter_with_prefix`](https://docs.rs/kvdb/0.9.0/kvdb/trait.KeyValueDB.html#tymethod.iter_with_prefix) will likely be useful for this.

For each candidate, fetch the session info from the `RollingSessionInfo`. Find out if we control assignament and validation keys for the session. If not, ignore everything in that session. If so, ignore any `CandidateEntry`s that have our validator index in the `approvals` bitfield. For all remaining `CandidateEntry`s, find any `ApprovalEntry`s we're in the `assignments` bitfield of. These are the `(candidate, block)` pairs we need to launch approval work for.

Launch approval for all these candidates under these blocks, applying the same rules as #3254.

**Comment by rphmeier** [comment]
Note that after https://github.com/paritytech/substrate/issues/7715 is done and we can gracefully exit the node, the only situation this will be useful in is when the node crashes.

**Comment by burdges** [comment]
We do this for the case of nodes being crashed intentionally as a mechanism to prevent checking back blocks.

**Comment by rphmeier** [comment]
What do you mean by back blocks?

**Comment by burdges** [comment]
err.. bad blocks.

**Comment by Lldenaurois** [comment]
This issue can be closed. @ordian and I came to the conclusion that it is sufficient to wait a little bit on startup to see if we can determine the last_finalized_block and then prune our startup work to remove all approvals work for finalized block.

In addition, @ordian confirmed that on the receiving end, the validator will only reduce the peer's reputation, meaning that if we don't finalize a block before we handle the startup, the validator *may* get disconnected as they are distributing those approvals.
