### ISSUE TITLE
Replace StreamsUnordered with futures::stream::select_all

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#3331]
https://docs.rs/futures/0.3.15/futures/stream/select_all/index.html is relatively new, I think. It seems far better than the `StreamsUnordered` API and probably more reliable.

**Comment by ordian** [comment]
What's `StreamsUnordered`? Do you mean `FuturesUnordered` or `select!` macro? I don't think `select_all` replaces that.

**Comment by rphmeier** [comment]
Oh, it's a crate we used to use. But I suppose we got rid of it already.
