### ISSUE TITLE
Invalid block justification

### ISSUE THREAD

**Issue by fgimenez** [paritytech/polkadot#334]
One of the nodes of a network using a binary built from https://github.com/paritytech/polkadot/commit/9b66efa7b693a4b5bc33cbb018ecda923c79e152 started complaining about invalid justifications:
```
2019-07-22 12:32:57 Invalid justification provided by QmW45D6YLfctkSnsjyoqcSxw9qoiXUmAFGn5ea99L6SC7X for #0x9919…1a1b
```
This message is repeated continuously in the logs for several peer ids. The node still produces blocks, but takes much longer and it reports 0 or a small number of peers.

**Comment by andresilva** [comment]
Closing as stale. We already fixed some bugs around this area over time.
