### ISSUE TITLE
Wiki Page is off-line.

### ISSUE THREAD

**Issue by howardpen9** [paritytech/polkadot#3367]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
- Describe the role your node plays, e.g. validator, full node or light client.
- Any command-line options were passed?

Hello, https://wiki.polkadot.network/docs/en/ page is off-line right now. 

Anyone can trouble shooting? Thanks.

**Comment by Swader** [comment]
Hi, the wiki is fine but you need to start tat the root: wiki.polkadot.network. We'll fix the other links

**Comment by bkchr** [comment]
Should be posted here: https://github.com/w3f/polkadot-wiki/issues

So, I'm going to close this. Ty
