### ISSUE TITLE
Approval Voting ops.rs - Handling forks of length 0

### ISSUE THREAD

**Issue by Lldenaurois** [paritytech/polkadot#3389]
@drahnr: I don't quite get this line? Should we not error out if the fork is of 0 length or store None instead?

Referring to the line that defined `new_range` in the `canonicalize` function. Possibly may make sense to move to tristate enum in the Overlayedbackend to indicate whether initialized, removed or overwritten.

**Comment by rphmeier** [comment]
https://github.com/paritytech/polkadot/pull/3366#discussion_r664241546 explains the original comment this is extracted from. I don't really understand the statement of this issue nor what action is meant to be taken for it.
