### ISSUE TITLE
--bootnodes should be able to accept just IP:port

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#339]
... rather than requiring the public node key.

**Comment by tomaka** [comment]
I would suggest `/ip4/x.x.x.x/tcp/x` instead of `ip:port`, so that we can be generic over the multiaddress.

I also think a warning should be printed if the user doesn't specify the public key, because when doing so you can get man-in-the-middled.

**Comment by gavofyork** [comment]
for the purposes of UI, ip:port is still king and not supporting it would just lead to more support burden.

**Comment by gavofyork** [comment]
in other words, users don't care about multiaddress. they just want to Get Things Working.

**Comment by gavofyork** [comment]
support both though, if you like.
