### ISSUE TITLE
Conflating Filtering and Identifying in XCM v0 `NetworkId` and `MultiAsset`

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#3409]
I would like to raise an issue I see with XCM v0:
I see a difference between `NetworkId` and `MultiAsset` on the one hand and other enums/"identifiers" like `MultiLocation` or `BodyPart`. The latter separate the identifying and filtering parts. Identifying is done by the enum instance (e.g. a multilocation might be `X2(Parachain(1), GeneralIndex(42))`) while filtering is done in the XCM implementation (e.g.  the `IsTeleporter` filter). This IMO is a good pattern.
`NetworkId` and `MultiAsset` combine an identifying function with a filter function within the enum which leads to non-filtering code having to manage the case when we get `MultiAsset::AllFungible` even though that is not its purpose. I think we should avoid this in v1 and separate filtering and identifying completely.

**Comment by apopiak** [comment]
related to https://github.com/paritytech/polkadot/issues/3168

**Comment by gavofyork** [comment]
Consider creating an XCM v1 tracking issue so when the time comes to move from v0 we have a single place with all the gripes.

**Comment by KiChjang** [comment]
With the introduction of `MultiAssetFilter`, I think this is fixed in v1 and later.
