### ISSUE TITLE
Design and implement Pre-Validation function but also proceed when it's not present

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3428]
(created automatically from https://github.com/paritytech/polkadot/issues/2888)

More details [here](https://github.com/paritytech/polkadot/issues/1348) - quite a few things are outdated, some still relevant. When getting to this issue, we should walk through 1348 and create tickets for parts that are still relevant, then close that old ticket.

**Comment by m-cat** [comment]
Is this still relevant? Looks like 1348 has been closed as "outdated".

**Comment by eskimor** [comment]
Maybe. I think it is incompatible with the idea of making PoV providers distinct from PoV producers. As this would mean that block producers would need to reveal themselves ahead of time. Until we have not fully committed to that approach, I think it is too early to close, but still nothing to work on right now.

**Comment by burdges** [comment]
We could likely write down a list of "enough" block production mechanisms, including some that provide pre-validation functions even when block producers stay anonymous.  

Aura+Praos=Babe of course, as well as Sassafras and some shuffle SSLE that assumes small-ish list of producers.   All have flavors without and with post-production anonymity, well except pure Aura.  I suppose fantomette works too, but like PoW cannot produce blocks at fixed time increments.  It's plausible parathread add some new interesting things though.

**Comment by eskimor** [comment]
In the end I don't think this will gain us much: Collators can still provide the header, but then sending garbage data and we would only know after the fact.

If we assume collators are keeping the block header a secret, then it would be useful, but breaks the idea of separating PoV producers from block providers.

I am going to close this for now, as I don't think it will be necessary/useful. We can revive if need be.
