### ISSUE TITLE
`AllowTopLevelPaidExecutionFrom` is Named Confusingly

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#3429]
`AllowTopLevelPaidExecutionFrom` filters the types of XCMs it accepts:

https://github.com/paritytech/polkadot/blob/2bad8079a73dc92d83bc3c0e5d81de388d36cf24/xcm/xcm-builder/src/barriers.rs#L42-L56

A more apt name would be `AllowAssetXcmExecutionFrom`.

**Comment by KiChjang** [comment]
The naming here actually makes sense, "top-level paid execution" here means payment occurs at the very top level of recursion, i.e. not via a `Transact` or an instruction that can contain additional XCM, such as a `SetAppendix`.

Closing as a won't fix.
