### ISSUE TITLE
Error importing block #6379314

### ISSUE THREAD

**Issue by dlalstjd** [paritytech/polkadot#3435]
Hi,
I'm running Westend node and my node stoped sync.

<img width="1230" alt="스크린샷 2021-07-08 오전 11 50 52" src="https://user-images.githubusercontent.com/50138250/124854763-cd9aa880-dfe2-11eb-966d-387b34126d04.png">

my node version is 0.9.6 and error messages are showing above.

how do i fix this..?

**Comment by xlc** [comment]
upgrade to 0.9.8

**Comment by dlalstjd** [comment]
Thanks! After upgrading, it works
