### ISSUE TITLE
Get rid of timeouts for open channel requests

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3451]
We had a discussion with @shawntabrizi where he suggested that timeouts for pending open channel requests are superfluous.

First off, timing introduces unneeded churn. It makes the recipient to act quickly to accept the request. Alternatively, the sender and recipient may have to agree between each other to coordinate opening the channel so that it happens at the same time.

Then we also are doing some work on each session to check what pending requests are expired. We could avoid that.

While we don't have parathreads there is a very limited venue for spamming the requests given that they are required to point to existing para ids and no duplicates are permitted. Moreover, the spamming can be limited economically by the already existing deposit mechanism.

We may hold off with changing this for two reasons:

- we can increase the open timeout to be very long, so that it won't be bothersome anymore
- XCMP module can take this into account when implemented and start with non expiring requests from the start.

**Comment by xlc** [comment]
Current TTL on Kusama is 2 sessions which are just 2 hours. That's no way enough for any governance to vote & accept an open channel request.

**Comment by pepyakin** [comment]
That sounds we should increase the TTL in the meantime anyway
