### ISSUE TITLE
XCM Executor ignores errors while dispatching Transact messages

### ISSUE THREAD

**Issue by vitvakatu** [paritytech/polkadot#3458]
Hello

I've played with Transact messages a bit, and it is unclear, how to get an actual Call execution status. Comments in XcmExecutor code explicitly state that any errors are ignored (see https://github.com/paritytech/polkadot/blob/1d4783291168a18dab7d5fb05ceac98a07389aad/xcm/xcm-executor/src/lib.rs#L198).

Is it deliberate decision? How could I verify if transaction was actually successful?

**Comment by xlc** [comment]
https://github.com/paritytech/xcm-format/pull/22

**Comment by vitvakatu** [comment]
Thank you!
