### ISSUE TITLE
How to get balance?

### ISSUE THREAD

**Issue by ruanqunfeng** [paritytech/polkadot#348]

**Comment by kianenigma** [comment]
Please describe more. From where? the UI? the code?

**Comment by ruanqunfeng** [comment]
> Please describe more. From where? the UI? the code?

Can i get balance by rpc?

**Comment by kianenigma** [comment]
The `GetStorage` can help you read not just balance but _any data_. But if you use the JS api (see the same doc on the Api section) you can get more high-level abstraction.

https://polkadot.js.org/api/METHODS_RPC.html#json-rpc

**Comment by ruanqunfeng** [comment]
> The `GetStorage` can help you read not just balance but _any data_. But if you use the JS api (see the same doc on the Api section) you can get more high-level abstraction.
> 
> https://polkadot.js.org/api/METHODS_RPC.html#json-rpc

OK，thanks

**Comment by ruanqunfeng** [comment]
> The `GetStorage` can help you read not just balance but _any data_. But if you use the JS api (see the same doc on the Api section) you can get more high-level abstraction.
> 
> https://polkadot.js.org/api/METHODS_RPC.html#json-rpc

OK，thanks
