### ISSUE TITLE
Project compiles, but cannot launch/run it - Apple M1 ARM stable-aarch64-apple-darwin

### ISSUE THREAD

**Issue by mbouzas** [paritytech/polkadot#3482]
Hi,
I just compiled polkadot project:
`cargo build --release
`
everything was ok:
```
 polkadot % cargo build --release
    Finished release [optimized] target(s) in 23m 41s

```
Check if the help page prints to ensure the node is built correctly
`./target/release/polkadot --help`

I receive this error:
`zsh: illegal hardware instruction  ./target/release/polkadot --help
`

so I can not launch it.
I am using Mac m1, on rosetta terminal:
```
polkadot % arch
arm64
```
Thanks for the support.
Manu

**Comment by s3krit** [comment]
Hey. Is there a reason you're attempting to launch it using Rosetta? I was able to build polkadot v0.9.8 on my M1 Air with no issues. What is your default target? Can you run `rustup default` and post the output, as well as `cargo version` and `cargo +nightly version`. Cheers. My output below, for example:

```
~/code/polkadot on  3a10ee63c ⌚ 12:05:35
$ rustup default
stable-aarch64-apple-darwin (default)

~/code/polkadot on  3a10ee63c ⌚ 12:05:38
$ cargo version
cargo 1.52.0 (69767412a 2021-04-21)

~/code/polkadot on  3a10ee63c ⌚ 12:05:44
$ cargo +nightly version
cargo 1.54.0-nightly (0cecbd673 2021-06-01
```

**Comment by mbouzas** [comment]
the building is ok, the issue it is to run it.
```
Projects % rustup default
stable-x86_64-apple-darwin (default)
```
```
Projects % cargo version
cargo 1.53.0 (4369396ce 2021-04-27)
```
```
Projects % cargo +nightly version
1.55.0-nightly (66a6737a0 2021-07-14)
```

Basically, I am following cumulus workshop

https://substrate.dev/cumulus-workshop/#/

**Comment by s3krit** [comment]
You should be able to build + run polkadot on your M1 after running the following 2 commands:

```
rustup install stable-aarch64-apple-darwin
rustup default stable-aarch64-apple-darwin
```

Then go to your polkadot directory, run `cargo clean` and attempt to build & run again with `cargo build --release`. That being said, I'm not sure why the version you've built with the `stable-x86_64-apple-darwin` target fails to run. I'll do some digging...

**Comment by rphmeier** [comment]
@mbouzas Any success?

**Comment by mbouzas** [comment]
Yes!!! you saved me!
Thanks a lot!
