### ISSUE TITLE
how to transfer native assets between two relaychain account from parachain side?

### ISSUE THREAD

**Issue by yrong** [paritytech/polkadot#3500]
the requirement here is just to transfer some ksm from relaychain accountA to accountB, but instead of straightforwardly using polkadot js I would like to invoke from parachain, currently I'm using  [cumlulus ParentAsUmp route] (https://github.com/yrong/bifrost/blob/167d8eadd0c5de6cd9d5b2e38f3483a987b6557a/runtime/asgard/src/lib.rs#L767) to send message but the problem is that origin contains only parachain account and the source accountId part missing. 

Then I notice that there is [RelayedFrom xcm format](https://github.com/paritytech/xcm-format#relayedfrom) which will keep the original accountId so I wrap a [xcmp call with `TransferAsset` embed in `RelayedFrom` message](https://github.com/yrong/bifrost/blob/167d8eadd0c5de6cd9d5b2e38f3483a987b6557a/xcm-support/src/lib.rs#L167-L176)

And then another issue comes is that current polkadot xcm executor can not extract accountId in RelayedFrom message with the default accountId convertor so do some hack in [extension of SovereignAccountOf types](https://github.com/yrong/polkadot/blob/166239e326df7091879c089ca6be8139e97d170b/runtime/rococo/src/lib.rs#L610) to achieve that.

The whole hack is in this [commit](https://github.com/yrong/polkadot/commit/1b5c9b6f924afc46e6d2021373a26af4e4d5d7c6#diff-913ae0b4a6608e2af7b0141218c195418841c4fd46afd33f4d83a862e3777d25) and after all above steps I can transfer assets from parachain side but I would like to know is this the proper way or is there any way without hacking the current polkadot implementation?

**Comment by bkchr** [comment]
CC @apopiak

**Comment by apopiak** [comment]
I don't expect the relaychain to trust a community chain enough to give it control over its accounts directly like this.
If I understand what you want to do correctly, a parachain could take control of e.g. the treasury account which we would want to avoid ;-)
The scenario that will be supported will likely be the following:
There could be a deterministic account id generated (e.g. sth like `hash(parachain id, parachain account)`) for origins coming from parachains. You could then send funds to that generated id and remote control it from the parachain.

**Comment by yrong** [comment]
@apopiak  thanks for the reply. Let me explain the background a little bit, we are [bifrost](https://bifrost.finance) and one of our service is to help other parachains to participant crowdloan with assets locked while still provide liquidity in the form of Staking derivatives.  Currently we're using multi-signer to achieve it and you can check [description here](https://wiki.bifrost.finance/publicity/crowdloan-multi-signer)  

     In next step we would like to replace the multi-signer with xcmp which require 2 steps.  First a xcm transfer call to transfer some ksm directly from personal account to the parachain account in relaychain side. Then a [transact call](https://github.com/paritytech/xcm-format#transact) to contribute to fund with the parachain account. You may check [some code snippet](https://github.com/yrong/bifrost/blob/167d8eadd0c5de6cd9d5b2e38f3483a987b6557a/pallets/salp/src/lib.rs#L758-L785) for detail.

    Since we act only as a crowdloan contribute proxy here we do not want to ask people to send their native ksm assets to our parachain first which maybe is what you suggest here if I understand correctly.
 
   The current hacks we made are just some temporarily workrounds but from what @gavofyork last time clarified my understanding is that such restrictions will be relaxed sooner or later so our solution is technically feasible.

https://matrix.to/#/!WuksvCDImqYSxvNmua:matrix.parity.io/$htj-o9ILEZi2Jz-eB-_7zemk6vUJij_JLTH6X_BvIEI?via=matrix.parity.io&via=matrix.org&via=web3.foundation

![image (6)](https://user-images.githubusercontent.com/4383920/126315063-ae601b63-783c-431d-895d-b8d0f94924b9.png)

 So I would like to know is their any other way to achieve it without sacrificing the security?

**Comment by apopiak** [comment]
> [...] First a xcm transfer call to transfer some ksm directly from personal account to the parachain account in relaychain side. [...]

As mentioned above: This will not be possible. AFAICT parachains will not be able to transact as arbitrary accounts on the relaychain.

> Since we act only as a crowdloan contribute proxy here we do not want to ask people to send their native ksm assets to our parachain first which maybe is what you suggest here if I understand correctly.

I suggest they send it to an account id that does not have an associated private key and can only be controlled via XCM from your parachain, thus opting in to your parachain controlling these funds.

> The current hacks we made are just some temporarily workrounds but from what @gavofyork last time clarified my understanding is that such restrictions will be relaxed sooner or later so our solution is technically feasible.
> 
> ![image](https://user-images.githubusercontent.com/4383920/126319293-041b2106-1bbf-481f-b4c3-e5b5707c80c8.png)
> 
> ![image (6)](https://user-images.githubusercontent.com/4383920/126315063-ae601b63-783c-431d-895d-b8d0f94924b9.png)

Note that this only says that you can lift theses kinds of limitations earlier on a parachain instead of the relaychain.

> So I would like to know is their any other way to achieve it without sacrificing the security?

Well I gave a sketch of my suggested solution above. I'll try to sketch something in a PR to give you a better idea.

**Comment by yrong** [comment]
@apopiak appreciate for your clarification and now I understand the relaychain asset transfer from parachain is not doable.  
 
  For the derivated account you provided in #3505 since we've already stored the contribution in [child trie](https://github.com/yrong/bifrost/blob/167d8eadd0/pallets/salp/src/lib.rs#L696-L703)  same as what crowdloan module does so all contribution origin from the same parachain account  is ok to us and we may not need such kind of derivated account which contains each contributor's accountId.

But to act as a crowdloan contribute proxy chain we do need the ability of ump contribution call and the ability to extract the parachain account from ump transact origin,  so I would like to know are these Lift restrictions I can still look forward to?

**Comment by apopiak** [comment]
I talked more with Gav about this usecase and want to clarify that we don't plan on adding derived accounts, so my suggested strategy would not work.

**Comment by yrong** [comment]
@apopiak Thanks for your effort and hope parity can lift the current limations in xcmp as soon as possible which we believe will  promote our polka ecology a lot

**Comment by apopiak** [comment]
:+1: It will definitely be opened some, but generic relaychain accounts will not be able to be controlled from parachains.
Feel free to open an issue for the particular calls you would like to be able to call via `Transact` and the data you want to be able to read out.

Closing this.
