### ISSUE TITLE
Add transfer events to `CurrencyAdapter`?

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#3508]
Functions implemented for `Currency` do not emit events currently. E.g. [`deposit_creating` here](https://github.com/paritytech/substrate/blob/03d4d0d7c129eec3d3ab2876bddbe5d6dfa1f178/frame/balances/src/lib.rs#L1515-L1537)

This makes it difficult to trace transfers when these functions are called e.g. via XCM. (As surfaced by https://github.com/paritytech/polkadot/issues/3489)

Should we address this in the underlying implementation or do we expect the callers to generate the events?
We could adjust the `CurrencyAdapter` to add events. (Similar question arises for the `FungiblesAdapter`, of course, though the fungibles implementation in the `assets` pallet does emit events for mint, burn and transfer.)

**Comment by gavofyork** [comment]
Should happen either as part of the `CurrencyAdapter` implementation or, better I think, inside `XcmExecutor`. Low-level utilities (such as `deposit_creating`) should not be emitting events.

**Comment by apopiak** [comment]
adressed by https://github.com/paritytech/substrate/pull/9425
