### ISSUE TITLE
Memory leak in `StatementDistribution::handle_subsystem_message`

### ISSUE THREAD

**Issue by koute** [paritytech/polkadot#3514]
As far as I can see there's a memory leak here:

```
#14 [kusama] tokio::runtime::thread_pool::worker::Context::run
#15 [kusama] tokio::runtime::thread_pool::worker::Context::run_task
#16 [kusama] std::thread::local::LocalKey<T>::with
#17 [kusama] tokio::runtime::task::harness::Harness<T,S>::poll
#18 [kusama] <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
#19 [kusama] tokio::runtime::task::core::Core<T,S>::poll
#20 [kusama] <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
#21 [kusama] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
#22 [kusama] <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
#23 [kusama] <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
#24 [kusama] <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
#25 [kusama] <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
#26 [kusama] <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
#27 [kusama] polkadot_statement_distribution::StatementDistribution::run::{{closure}}
#28 [kusama] polkadot_statement_distribution::StatementDistribution::handle_subsystem_message::{{closure}}
#29 [kusama] <alloc::vec::Vec<T,A> as core::clone::Clone>::clone
```

Here's a memory graph after over 9 days of profiling:

![memory](https://user-images.githubusercontent.com/246574/126770493-2759dcbf-90c7-47a2-b0bf-0c8c18b8ba51.png)

The growth here is linear and is around ~1MB/h. Every minute at least one allocation is getting leaked; usually multiple are leaked. All of this is from a non-validator Kusama node.

I'll investigate this in more detail and try to fix it next week, so this issue's mostly just for tracking and/or in case someone already knows why this happens from the top of their head.

**Comment by ordian** [comment]
Interesting, so the allocation is coming from
> #28 [kusama] polkadot_statement_distribution::StatementDistribution::handle_subsystem_message::{{closure}}
#29 [kusama] <alloc::vec::Vec<T,A> as core::clone::Clone>::clone

`Vec::clone()`? I don't see anything obviously wrong from a quick glance at the code. `active_heads` should be limited to unfinalized blocks. `RuntimeInfo` is limited to 2 lru entries (unless there is an `lru` bug).

Would be nice to confirm if this is also observable on a validator node.
