### ISSUE TITLE
Sent two identical transactions

### ISSUE THREAD

**Issue by hzccc** [paritytech/polkadot#3518]
Kusama sent two identical transactions, one successful and one unsuccessful. I only broadcast the one deal that worked. Version 0.9.8

tx:https://kusama.subscan.io/extrinsic/0xeef956cf4be3a26511e4a49aa0a8320d63671c650a37485a55311851883e74e1
address: https://kusama.subscan.io/account/CajXAnA1Nt7JH52rzWcFzmY35zWhzrLJ87e3vV5hKHpbyFu?tab=transfer

**Comment by bkchr** [comment]
What is this issue about?

**Comment by hzccc** [comment]
> What is this issue about?

this extrinsic “0xeef956cf4be3a26511e4a49aa0a8320d63671c650a37485a55311851883e74e1”  repeat broadcast

**Comment by bkchr** [comment]
You send an immortal transaction. That can be applied as often as wanted. Especially as you used `nonce=0`. Nothing special here.

**Comment by bkchr** [comment]
Use mortal transactions.
