### ISSUE TITLE
Referendum always passes if any stake votes for it

### ISSUE THREAD

**Issue by laboon** [paritytech/polkadot#352]
DESCRIPTION:
I was able to get any referendum to pass on the Alexander testnet (Polkadot 0.4.4) if any amount of stake votes for it, no matter how small.  I tried this with Balances -> setBalance and was able to arbitrarily change different accounts' balances.

I was also able to reproduce this problem running locally with a --dev chain.

<img width="569" alt="Screen Shot 2019-08-02 at 4 23 22 PM" src="https://user-images.githubusercontent.com/1417717/62423552-cb5da000-b68f-11e9-8b87-fada87c7313e.png">
<img width="261" alt="Screen Shot 2019-08-02 at 4 23 41 PM" src="https://user-images.githubusercontent.com/1417717/62423553-cb5da000-b68f-11e9-99b4-3ee92dc1e99a.png">
<img width="524" alt="Screen Shot 2019-08-02 at 4 34 44 PM" src="https://user-images.githubusercontent.com/1417717/62423554-cb5da000-b68f-11e9-8ef1-c6e2cc3a2280.png">

TO REPRODUCE:
1. Submit a new proposal using setBalance to modify a target account's balance, and wait for it to be voted upon.
2. Have a small amount of stake for it ("aye").
3. Have a larger amount of stake vote against it ("nay").  

EXPECTED BEHAVIOR:
Referendum fails; no change in target account's balance

OBSERVED BEHAVIOR:
Referendum passes; target account's balance is set to the value

NOTES:
I was able to replicate this with both the current Alexander testnet and locally on the dev chain.

**Comment by laboon** [comment]
Note: I could not replicate this in the w3f/polkadot k4a branch.

**Comment by gavofyork** [comment]
Good!
