### ISSUE TITLE
Add Docs to XCM-Simulator Macros

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#3542]
See comments here https://github.com/paritytech/polkadot/pull/3538

**Comment by bizzyvinci** [comment]
Hi @shawntabrizi. What are the steps to get this done?

**Comment by shawntabrizi** [comment]
@bizzyvinci the macros in this file have no usability documents:

https://github.com/paritytech/polkadot/blob/master/xcm/xcm-simulator/src/lib.rs

There are some examples, but the macros themselves should have docs saying how to use them and what kinds of things that may work or break them.

**Comment by bizzyvinci** [comment]
This is my first time writing docs. Are there guidelines and good samples?
