### ISSUE TITLE
`DepositAsset` and `DepositReserveAsset` should have an extra parameter limiting the number of distinct assets to deposit.

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#3547]

**Comment by KiChjang** [comment]
Should this limit be passed onto the `AssetTransactor`, so that anyone implementing the `AssetTransactor` trait can decide what to do with the max distinct asset limit?

**Comment by gavofyork** [comment]
It will be managed prior to that level, in the executor.

**Comment by KiChjang** [comment]
This is done in #2815.
