### ISSUE TITLE
Wallet improvement for HDX platform

### ISSUE THREAD

**Issue by FredZarco** [paritytech/polkadot#3582]
The thread on people staking all their HDX ties up admin and each tip sent has to come from somewhere.
seems to be a common problem, which could be solved with a common solution andsave you HDX in the long run.

Staking in wallet/bonding wallet improvement so that its not possible to stake all tokens, it leaves all but one HDX token.
When selecting bonding, you cannot select all to bond, it leaves out 1 X HDX token in users wallet.
When selecting staking, you must have 1 x HDX in your wallet.
Wallet cannot have 0 HDX in it, on selection, making it impossible to bond or stake with nothing left in wallet for fees.
Benefits are.

Less users doing the same thing, im one of them, but willing to suggest an improvement.
Admin get a little more time back.
More HDX is retained as each tip has to come from somewhere
Users wallet will always contain 1 X HDX for fees.

https://commonwealth.im/hydradx/proposal/discussion/1503-wallet-improvement-for-hdx-platform

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by kianenigma** [comment]
> When selecting bonding, you cannot select all to bond, it leaves out 1 X HDX token in users wallet.

This is a UI help feature. If you bond everything, you can never unbond yourself, since you cannot pay fees. You can actually bond everything in the `developer -> extrinsics` tab, but the default staking UI prevents you from shooting yourself in the foot.

**Comment by FredZarco** [comment]
Hi, i could be wrong here but many people have the same issue and shot themselves in the foot.
Just take a look at tip request posts https://commonwealth.im/hydradx/
Many people have the same problem, or wouldnt be asking for a TIP to get out of the situation.
