### ISSUE TITLE
Staking miner: Should stop submitting if one submission in each round fails

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot#3622]
A common scenario is that we don't have enough funds to cover the deposit + fee of a transaction. If this is the case, don't submit. 

Current behaviour is that we crash upon all errors, including lack of fees, but the deployment configuration is such that it restarts immediately, so we keep falling for the same trap.

My suggestion is this: 
The failure to submit should not cause the miner to crash. Instead it should remember the round number (https://github.com/paritytech/substrate/blob/5a07b982e9832fe42de2429c1932b4e06bcb7fe7/frame/election-provider-multi-phase/src/lib.rs#L1137), and simply stop working for that round.

**Comment by kianenigma** [comment]
@niklasad1 is this done?

**Comment by niklasad1** [comment]
No, we talked about this on the last call whether it's needed or not.
