### ISSUE TITLE
Balance mismatch for account in Rococo

### ISSUE THREAD

**Issue by prasannayasan** [paritytech/polkadot#3630]
For account 5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9 in Rococo network,

balance at block:
[375](https://rococo.subscan.io/block/375) : 1000000000000000000
[376](https://rococo.subscan.io/block/376) :  999569735523517888

At block 376:
- [43 instances](https://rococo.subscan.io/extrinsic/376-2) of balance transfer from 5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9 of 10000000000000
- Total transfer : 430000000000000
- Fee incurred for this block by 5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9
    - As displayed by [Subscan](https://rococo.subscan.io/extrinsic/376-2) : 264475954744

Total deductions for account: 5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9
- 430000000000000 + 264475954744
- 430264475954744

Final computed balance for account 5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9
- 1000000000000000000 - 430264475954744
- 999569735524045256

Difference between computed balance and live balance is 
- 999569735524045256(computed) - 999569735523517888(live)
- 527368 is the difference. 

Any idea why there is a difference in value ?

**Comment by shawntabrizi** [comment]
The tx fee number you have above is not accurate it seems. look at the first event emitted:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1860335/129194048-97337219-85c7-4877-886f-f761d55344ab.png">

**Comment by shawntabrizi** [comment]
430000000000000 + 264476482112  = 430264476482112

1000000000000000000 - 430264476482112 = 999569735523517888

This seems to match what is live on chain.

So maybe make a report to Subscan that their fee reporting is wrong.

**Comment by AbhijitSinha1** [comment]
@shawntabrizi 

This is what I see in [subscan](https://rococo.subscan.io/extrinsic/376-2):

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/2098830/129207620-959622e0-f32c-482a-af0b-35750e44a658.png">

I used the SDK to fetch the fees for that extrinsic:

```
const queryInfo = await api.rpc.payment.queryInfo(ex.toHex(), blockHash);

console.log("fee:", queryInfo.partialFee);
```

And that too gives the same fee number which is shown in subscan. 

Which tool are you using to view the transactions, can you please share the link to the first event?

Thank you

**Comment by shawntabrizi** [comment]
If you click this link that you have posted: https://rococo.subscan.io/extrinsic/376-2

And then scroll to the very bottom to the first event, you will see the correct fee amount.

As mentioned, the fee being displayed by subscan, for whatever reason, is wrong.
