### ISSUE TITLE
Polkadot 0.9.9 Release - Failed to update session cache for disputes

### ISSUE THREAD

**Issue by mnguyen-io** [paritytech/polkadot#3660]
As of 0.9.9 on polkadot with the following parameters: --ws-port=9944 --unsafe-ws-external --rpc-cors=all --no-telemetry --rpc-port 9922 --pruning=archive --validator

We're seeing the following message in syslog for all blocks it seems:

 Failed to update session cache for disputes err=SessionsUnavailable { kind: Missing, info: Some(SessionsUnavailableInfo { window_start: 0, window_end: 0, block_hash: 0x45182bd7bc7c14f4f07fd96647b7e5ba2e94f5dd5d272dee0366f42d241f3e41 }) }
Failed to update session cache for disputes err=SessionsUnavailable { kind: Missing, info: Some(SessionsUnavailableInfo { window_start: 0, window_end: 0, block_hash: 0x33decb4ec9e2bc610ecd8693e8ee33b3584e9f0ee490dfd080d04520e20fb4ea }) }

Is this expected?

On a non-validator node running the following parameters we are not seeing the failed message:

--ws-external --rpc-external --rpc-cors all --chain=polkadot --pruning=archive --rpc-port 9933 --ws-port 9944

**Comment by bert2002** [comment]
We are seeing the same errors. Is that breaking anything?

**Comment by ssssaaamm** [comment]
I can confirm the above. Do we need to downgrade to the previous version?

**Comment by mnguyen-io** [comment]
They released 0.9.9-1 earlier today. This should  fix the issue you're seeing
