### ISSUE TITLE
"Module doesn't have export xxx" error with a strange fix

### ISSUE THREAD

**Issue by lsaether** [paritytech/polkadot#367]
Testing on Polkadot master at [this commit](https://github.com/paritytech/polkadot/commit/eba3eeae646809f0a51fd592e0bc25320bab6dae) a chain spec I was using with the `id` field set to `kusama` broke with an error from the Wasm interpreter:

```
Error: Input("Client(Execution(Wasmi(Function(\"Module doesn\\\'t have export BabeApi_startup_data\"))))")
```

After changing the `id` field to something else like `kusama2`, the chain started perfectly fine. As far as I could tell the only `id` that caused this error in the Wasm interpreter was `kusama`. My suspicion is that the [runtime string that was set in the commit](https://github.com/paritytech/polkadot/commit/eba3eeae646809f0a51fd592e0bc25320bab6dae#diff-11f21b7f145f98241270cf825e0aaab5R97) to `polkadot` somehow created a collision that caused the interpreter to malfunction. If this is the case, there should be better error handling here if possible since this was a very cryptic error. I was only able to fix it by trial and error. 

Why does the `id` field in a chain specification have the ability to modify how an identical Wasm blob is interpreted? 

Let me know if this is better asked on the `polkadot` repository.

**Comment by pepyakin** [comment]
Yep, I think polkadot is way better choice for now since at the moment I am rather unconvienced that the problem is in wasmi.

What is the `id` field you are referring to? Can you point me to it?

**Comment by bkchr** [comment]
Did you purge your db?

**Comment by lsaether** [comment]
Ok it looks like purging the db does resolve the issue. I assume the issue was then we had a prior version of the runtime code cached?

**Comment by bkchr** [comment]
The wasm code is stored on chain and that was the problem here.
