### ISSUE TITLE
error: failed to run custom build run for 'kusama-runtime v0.9.9'

### ISSUE THREAD

**Issue by yasindce1998** [paritytech/polkadot#3686]
***OS Information***
OS: Manjaro Linux x86_64 
Host: 81FS Lenovo E41-25 
Kernel: 5.10.26-1-MANJARO 
Uptime: 10 hours, 11 mins 
Packages: 6174 (pacman), 4 (flatpak), 17 (snap) 
Shell: bash 5.1.0 
Resolution: 1366x768 
DE: Plasma 5.21.3 
Terminal Font: Noto Mono 10 
CPU: AMD PRO A4-4350B R4 2C+3G (2) @ 2.500GHz 
GPU: AMD ATI Radeon R2/R3/R4/R5 Graphics 
Memory: 1878MiB / 3774MiB 

```
error: failed to run custom build command for `kusama-runtime v0.9.9 (/home/user/polkadot/runtime/kusama)`

Caused by:
  process didn't exit successfully: `/home/user/polkadot/target/debug/build/kusama-runtime-664a9a4f011a079d/build-script-build` (exit code: 1)
  --- stderr
  Rust nightly not installed, please install it!
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by yasindce1998** [comment]
already solved!!!

**Comment by tifecool** [comment]
What was your solution?
@yasindce1998
