### ISSUE TITLE
Council elections: ordered or unordered voter input?

### ISSUE THREAD

**Issue by yussefsoudan** [paritytech/polkadot#3689]
Hello! 

Very exciting to see the tremendously innovative work happening in Polkadot. I have an inquiry with regards to the input taken from voters when electing councillors.

In the [JS interface](https://polkadot.js.org/apps/#/council), the input from the voter is given as an ordered list of candidates. However, in the papers describing the [Phragmén](https://arxiv.org/pdf/1611.08826.pdf) and [BalPhragmms](https://arxiv.org/pdf/2004.12990.pdf) algorithms, there is no mention of an ordered input from the voter (instead it is described as an approval set). The Polkadot [documentation](https://wiki.polkadot.network/docs/learn-phragmen#basic-phragm%C3%A9n) does not mention an ordered input either. Have I missed something in the description of the algorithms?

Thanks for taking the time!

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by kianenigma** [comment]
Only the prime's election is dependent on the order of votes. Else, the answer to "who is are the councillors" are independent of order. 

https://wiki.polkadot.network/docs/learn-governance#prime-members
