### ISSUE TITLE
PVF validation host: Do not conflate different errors by child worker

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3754]
Right now, the preparation worker conflates different errors into a single `DidntMakeIt` artifact status. Worse, this is reported by the execution worker as "preparation timeout" which is extremely confusing. Untangling this would be the result of completion of this issue.

At the moment of writing, that error can be reported on the following conditions:

1. the response from the worker is received, but the file cannot be renamed (moved) to the final destination location
2. the response from the worker is received, but it is not what we expected
3. an IO error occurred while receiving the result from the worker process
4. the worker took too much time to finish preparation

All these issues should be properly reported separately. This means we should probably list those conditions in the `ArtifactState` enum.

**Comment by m-cat** [comment]
I noticed this too. Glad there is already an issue for it, I can take this up in the near future. Maybe after https://github.com/paritytech/polkadot/pull/6282 is done to prevent merge conflicts.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-36/1529/1
