### ISSUE TITLE
Candidate Validation/PVF validation host: more fidelity of error metrics

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3755]
Currently we are only sending metrics about candidate validation that basically has 3 buckets: valid, invalid, validation failure. There is no way to see the breakdown of those failures and the reasons why candidates are invalid.

It seems to be a good idea to introduce metrics that are broken down by the reasons of errors. 

Perhaps, this could use the statuses would-be introduced by https://github.com/paritytech/polkadot/issues/3754

**Comment by mrcnski** [comment]
Closing; see https://github.com/paritytech/polkadot/pull/6479#discussion_r1063980221.
