### ISSUE TITLE
Rococo stops producing blocks

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/polkadot#3792]
Hi, the Rococo network seems to stop producing blocks. 
(Please forgive me if this is not the correct place to report the Rococo issue, I didn't find a better place to report)
https://telemetry.polkadot.io/#list/0xe7c3d5edde7db964317cd9b51a3a059d7cd99f81bdbce14990047354334c9779
![image](https://user-images.githubusercontent.com/14008461/132143990-d2373ccc-e3df-40cc-a387-875bdd7164a5.png)

**Comment by pepyakin** [comment]
Rococo seems to be up and running according to [this](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer). It was recently restarted so I guess that may be the issue. The telemetry indeed seems stuck.

**Comment by lovelaced** [comment]
There is a new chainspec as the chain was reset: https://github.com/paritytech/polkadot/pull/3785/files#diff-0c308d253f9e0d8f257bbe0fe485e32be7bdd079e3c44f3643707fb8a89b6dc0

all existing nodes will have to switch to the new genesis.
