### ISSUE TITLE
Local Two-node Testnet: Error

### ISSUE THREAD

**Issue by csknk** [paritytech/polkadot#3804]
On master branch. Follow instructions in README for setup of a two node local development testnet:

```bash
# Terminal 1
./polkadot --chain=polkadot-local --alice -d /tmp/alice
```
Node starts up and shows `Local node identity is: 12D3KooWFHDTrK8NmHSmDPgZqi8jqdKEMVy2quc9kXPedHNbikTS`

Attempt to start a second node in the network in a separate terminal, as per README instructions:

```bash
# Terminal 2
./polkadot --chain=polkadot-local --bob -d /tmp/bob --port 30334 --bootnodes '/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWFHDTrK8NmHSmDPgZqi8jqdKEMVy2quc9kXPedHNbikTS'
```
This node fails to start. Final log output:

```bash
2021-09-07 09:35:18 Unable to listen on 127.0.0.1:9944
```
I have tried specifying a custom `rpc-port` for node `bob` but this makes no difference.

It looks like the specified custom port is not being applied.

The second node panics after the "Unable to listen..." message.

If I shutdown `alice` and attempt to run `bob` with custom ports it starts normally, but it looks like the custom port is not being applied:

```
./polkadot --chain=polkadot-local --bob -d /tmp/bob --port 30334 --rpc-port 9945

# Log output
2021-09-07 10:12:23 Listening for new connections on 127.0.0.1:9944.
```

**Comment by bkchr** [comment]
This should be `--ws-port`

**Comment by csknk** [comment]
Thank you.
