### ISSUE TITLE
Dev network has 0 balance for all accounts

### ISSUE THREAD

**Issue by mrihn** [paritytech/polkadot#3810]
I started a local testnet with the following command:

polkadot --alice -d /tmp/alice --ws-external --rpc-external --rpc-cors all --dev

The node came up and is running without errors. I am able to connect to it with the browser UI, but all of the accounts (ALICE, ALICE_STASH, BOB, etc.) have a balance of 0.

The same thing happened when I brought up a "Local Two-node Testnet" as described in the README.

Is there a separate command (or command line option) to start the accounts with a certain amount of funds?

I am running with Polkadot version 0.9.9

**Comment by NukeManDan** [comment]
This is likely due to a type mapping issue. you can do a sanity check. Go into the Settings > Developer and clear any custom types. Still not working? Please let me know

**Comment by mrihn** [comment]
I did not have any custom types set in the Developer settings.
