### ISSUE TITLE
authority lookup  issue

### ISSUE THREAD

**Issue by zhex** [paritytech/polkadot#3832]
Hi, 

I created a rococo based custom chain with replaced validator addresses. The image I used is `parity/polkadot:v0.9.9-1` and launched 3 validator nodes.

I can see the chain is producing blocks and finalised blocks. but I get the error log:
```
Low connectivity - authority lookup failed for too many validators. connected=2 target=3
```

why does this happen? anything I might do wrong?

**Comment by ordian** [comment]
We have a warning if authority discovery resolution fails for >= 1/3 of validators, which is the case for 1 validator out of 3.
If this happens only on startup (even if a few times), but doesn't appear later, it's safe to ignore.

**Comment by zhex** [comment]
@ordian thank you for your answer. the warning message stuck there for 1 day until I restarted all the 3 nodes at the same time.
