### ISSUE TITLE
Size limit for chunk requests should depend on the number of validators

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#3856]
Right now it is [assumed](https://github.com/paritytech/polkadot/blob/8fab1d8f3039ce79215f2f1adefa769260d9228c/node/network/protocol/src/request_response/mod.rs#L136) that the size of a chunk should be smaller than 1/10th of the original payload, which should hold for production networks, but not for test networks.

We could either fix this, by drastically increasing the limit to like 1 times the original payload, but that sounds bad or change the number at runtime based on the actual number of validators, which is going to be a bit cumbersome.

See https://github.com/paritytech/cumulus/issues/587

**Comment by dt665m** [comment]
If I understand correctly,  you are saying that production networks like kusama and polkadot have many more validator nodes and thus, smaller chunks... so the 1/10th assumption should hold.  However, with testnets using a smaller validator set, the chunks aren't small enough... correct?

Would it be easier to introduce a temporary hack such that the protocol configuration could be relaxed if a genesis file is not classified as "Live"?  If this is acceptable for now, I could take a crack at it.

**Comment by eskimor** [comment]
Correct. As long as we can be reasonably sure that such a relaxed config won't hit any live networks, that would be good!

**Comment by burdges** [comment]
Should the Reed-Solomn crate export any relevant function?

**Comment by eskimor** [comment]
No no, everything is there. What makes it not straight forward is that the limits are set at node startup on initialization and a correct solution would monitor the number of validators as currently set in the runtime and set parameters accordingly.

**Comment by drahnr** [comment]
Divide by 2 is reasonable, there is no chunk fetching with 1 node :upside_down_face:
