### ISSUE TITLE
Not able to generate chain_spec 

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/polkadot#3879]
I am getting below error after following https://substrate.dev/cumulus-workshop/#/en/1-prep/2-chain-spec?id=generate-a-plain-chain-spec. I am using Mac M1.

```
ayushkumarmishra@Ayushs-MacBook-Pro polkadot % ./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode > rococo-custom-2-plain.json
zsh: illegal hardware instruction  ./target/release/polkadot build-spec --chain rococo-local  > 

```
Can someone help me to fix this?

**Comment by ordian** [comment]
Make sure to compile the binary using the native toolchain: #3482

**Comment by NukeManDan** [comment]
@ayushmishra2005 I see that the linked issue should solve your problem, yes? If not, please let's reopen this issue.
