### ISSUE TITLE
Re-opening faulty, unsolved extrinsics errors and inability to withdraw.

### ISSUE THREAD

**Issue by polkadotbabe** [paritytech/polkadot#3917]
Since it's scrolled off and doesn't come back up to the top with updates:

https://github.com/paritytech/polkadot/issues/2654

In addition to my second controller still being locked, my third controller/stash is unable to unlock and withdraw.

Given that there's a (relatively) decent amount that's been locked for six months, I'd appreciate a team member helping solve this.

Thanks in advance!

--Anna

**Comment by bkchr** [comment]
Please don't open duplicate issues.
