### ISSUE TITLE
sudo apt install make clang pkg-config libssl-dev (APT issue with MACOS)

### ISSUE THREAD

**Issue by insight07** [paritytech/polkadot#392]
sudo apt install make clang pkg-config libssl-dev

gave me following error 

Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/apt"

I have Java version 1.8.0.91 installed on my iMac

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by sqwilso** [comment]
Hi - I've a similar problem. "Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/apt" (-1)"

What was the solution that you found?

Appreciate any help that you can provide.

Thanks, Stuart

**Comment by insight07** [comment]
install latest Xcode.. and skip this command. It works.

**Comment by PaulRBerg** [comment]
In my case, this error occurred after installing Mojave. Make sure to have the latest Xcode and Xcode tools installed.

**Comment by PaulRBerg** [comment]
Apt is not an OSX specific command. You probably want to use Homebrew.
