### ISSUE TITLE
build-spec fail to build genesis.json if the account is for Polkadot mainnet

### ISSUE THREAD

**Issue by iammelea** [paritytech/polkadot#394]
```
polkadot --version
polkadot 0.5.0-5e1f3f12-x86_64-linux-gnu
```

when = 
```
build-spec
```
and the chainspec.json has a account like this to Polkadot mainnet

Address (SS58): 16h4UDmApKc7yzobkmnox6eKAkB3BACJDJVc1BaarK2fxRMM

generated in this way
```
subkey --network polkadot generate
```
CMD fail this error
```
Error: Service(Other("Error parsing spec file: UnknownVersion at line 28 column 11"))
```

test with substrate default accounts works fine

**Comment by soc1c** [comment]
Just ran into this too. Changing the address type does not seem to allow substrate to parse the actual key.

```json
      "babe": {
        "authorities": [
          [
            "31VGz261j1xA2Ym4YaymG1MxSTM6p5Yi3jsBA5kpPCCehMnE",
            1
          ],
          [
            "36HRqqRfrk8bu12qMRdrZFFsyxNxtfwrSLsnzaRDRjV4LE2f",
            1
          ]
        ]
      },
      "grandpa": {
        "authorities": [
          [
            "31aJzwWMD8G3oHMEpruJykTfhU64D1ZCvt1N55Zz3X6XD7ip",
            1
          ],
          [
            "31nq3pcnYvaPpo9yQGnK5rgF21Jpnvr6wvN2CHzSEYZkZhTP",
            1
          ]
        ]
      },
```


I tried modifying the `1` to something else but without any success. What's a valid version here?

**Comment by soc1c** [comment]
Not only a polkadot issue, moving to substrate https://github.com/paritytech/substrate/issues/3641

**Comment by soc1c** [comment]
@iammelea this should work for Polkadot with Substrate's latest `master`
