### ISSUE TITLE
User's pre-genesis claim on Ethereum doesn't show on Polkadot

### ISSUE THREAD

**Issue by michalisFr** [paritytech/polkadot#3968]
The user with ETH address:
0x00554019bc1d942aef1cbf7ee6becdab99ca91d7
claimed pre-genesis in this tx:
https://etherscan.io/tx/0x9fd76b7759b6523c0e8425a6db51540f36f511d58c1fc73562c6cda78625347e
to the account:
145VGavE2sK4sxxx3nNWaKvZdp8Qf7mDHhh63JFCvvMysYSy

This is also confirmed through the `preclaim` chain state:
![aVEJGMGeB_GN-Z294L7hJB1H16fSyJaecw](https://user-images.githubusercontent.com/45905709/135281438-09cfa569-074a-401d-8146-ca9cf289e427.png)
and the fact that the account exists with no ED:
https://polkadot.subscan.io/account/145VGavE2sK4sxxx3nNWaKvZdp8Qf7mDHhh63JFCvvMysYSy

However, when he tries to attest he gets an error that there's no claim for that account:
![-nyhSCXFJ7Biw_KABwqt0FWgUj3qUagveA](https://user-images.githubusercontent.com/45905709/135281985-69a88cbf-cecf-4c26-8198-5594e3d885ce.png)
and the chain state shows the same, as mentioned here:
https://github.com/polkadot-js/apps/issues/6158#issuecomment-925540455

One thing worth mentioning is that he attempted the claim again, to the same account, but the tx was reverted with `Account has already claimed` error:
https://etherscan.io/tx/0x1aba5fe215078e5eb2fa7e8b7fb85fef3e2876a57466a31dd92a4d16f45e48c3

**Comment by shawntabrizi** [comment]
This was resolved, the user claimed this not using his `preclaim` but claiming via another account:

https://polkadot.subscan.io/extrinsic/1089513-2?event=1089513-4
