### ISSUE TITLE
`UpgradeRestrictionSignal` is one block off

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#3971]
Assume `UpgradeRestrictionSignal` is set. If `UpgradeRestrictionSignal` is unset at the relay-block `B`, then a parablock that signals an upgrade built with the relay-parent `B-1` can be accepted. However, the post-state at `B-1` forbids an upgrade since `UpgradeRestrictionSignal` is set. That means a non-🤠 parachain will not risk upgrading until it builds a parablock at `B` where the upgrade restriction is lifted.

A potential solution is to unset `UpgradeRestrictionSignal` at `on_finalize` not in `on_initialize`.

**Comment by rphmeier** [comment]
Nice catch, should be an easy fix too.
