### ISSUE TITLE
rococo-local failed to upgrade to 0.9.10

### ISSUE THREAD

**Issue by zhex** [paritytech/polkadot#3979]
Hi,

I use version v0.9.9-1 to ran rococo-local with 3 nodes and try to upgrade the runtime to 0.9.10 but seems something goes wrong after the upgrade, the chain stops producing blocks.

<img width="765" alt="a0122a5185ba6c11092bdad43164ea8" src="https://user-images.githubusercontent.com/144652/135540224-da7610fc-cbf8-46d6-8283-b31481c4a507.png">

upgrade steps:
- create a chain from v0.9.9-1
- upgrade chain node client to v0.9.10 one by one
- generate new runtime wasm with the command `WASM_TARGET_DIRECTORY=$(pwd) cargo build -p rococo-runtime`
- call `system.setCode` via sudo

**Comment by bkchr** [comment]
This was fixed on master. Please compile a rococo wasm binary there.
