### ISSUE TITLE
Only building a subset of runtimes does not work with `runtime-benchmarks` feature enabled

### ISSUE THREAD

**Issue by hirschenberger** [paritytech/polkadot#4022]
Building the runtimes takes a long time. I tried to build just one runtime for benchmark development, but couldn't figure out how to build only the runtime I wanted to benchmark.

I tried `cargo build --release  --no-default-features --features="runtime-benchmarks","polkadot-cli/kusama-native"` but this still builds all runtimes. Maybe they are opted in by the `runtime-benchmarks` feature?

Related matrix [discussion](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$163346790761752dgUbc:matrix.org?via=matrix.parity.io&via=corepaper.org&via=matrix.org)

**Comment by hirschenberger** [comment]
It seems as if the building of all runtimes is added here https://github.com/paritytech/polkadot/blob/c4ee9d463adccfa3bf436433e3e26d0de5a4abbc/node/service/Cargo.toml#L160

This can in the future be solved with Cargo's [weak dependency feature](https://doc.rust-lang.org/cargo/reference/unstable.html#weak-dependency-features) that is currently only available in nightly.

**Comment by gilescope** [comment]
Weak dependency features has been stabilized in the 1.60 release.
