### ISSUE TITLE
Have alerts on frequent network errors

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#4029]
Since https://github.com/paritytech/polkadot/pull/3946 we silenced networking errors as they can happen under normal operation - but if they become more frequent, then there is likely some issue. We should have corresponding metrics and alerts on them once their rate surpasses some threshold.

**Comment by sandreim** [comment]
This is currently done by using catch all error/warning for anything  under`parachain` log target. We should specialize further for network errors only if this still makes sense.

**Comment by eskimor** [comment]
The goal would be to make warnings and errors that can appear under normal conditions `DEBUG` by default, so we get clean logs. But still be able to understand when something is off. Ideally we would have support for this in the logging framework - like an adaptive logging level. Report once - debug within `x` seconds -> debug, Report twice -> debug -> Report `y` times -> Warn with hint that a similar error/warning was logged under debug already `z` times (maybe even re-stating them at that level).

Something like:

```
gum::warn_if_frequent(
   target: LOG_TARGET,
   "Peer was disconnected"
);
```
