### ISSUE TITLE
Warn in case on chain scraping does not work

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#4033]
Once the runtime is upgraded and fetch on chain votes is supposed to work, we should get a warning once it stops (e.g. due to a runtime upgrade). So [this](https://github.com/paritytech/polkadot/blob/50b0658c1da5c1833dc20bb4fee2c9461fcd5dd9/node/core/dispute-coordinator/src/real/mod.rs#L542) should become `warn` once we upgraded the runtime.

This is a follow up for #3924.

**Comment by bkchr** [comment]
Runtime api supports versioning for exactly these kind of use cases. A proper fix would be to bump the runtime api version and check if the required one is already on chain and otherwise inform the caller that the method isn't yet available.

**Comment by sandreim** [comment]
@eskimor looks like we can close this one, wdyt ?
