### ISSUE TITLE
Failed to open peer storage 

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#404]
This issue is more to document the problem and the solution. I don´t think a fix is worth it.
Feel free to comment/close the issue once read.
CC @gavofyork (I think you changed things on the topic recently).

<details>
  <summary>Details</summary>

nodes.json new format:
```
{"QmRMGcQh69t8a8YwzHkofVo9SFr7ffggUwhAYjVSTChmrd":{"addrs":[["/ip4/104.211.54.233/tcp/30333",3155132328031937]]},"QmSz8qCADMmi92QB8dTqMPu56JYQQKZBAHz7y8KXjvqcvW":{"addrs":[["/ip4/40.117.153.33/tcp/30333",3155132328031937]]},"QmWCnXrhM1in1qPqVT3rDXQEJHedAzbPDMimdjqy2P9fGn":{"addrs":[["/ip4/104.211.48.51/tcp/30333",3155132328031937]]},"QmWzYU5X1NpFrprD1YZF5Lcj9aE5WF4QEg5FpvQx5XGWG7":{"addrs":[["/ip4/40.114.120.164/tcp/30333",3155132328031937]]},"QmYPx99i3H8EKXrvYHTBwqz3jjFC1kBfkvmSKd2h9zwQFr":{"addrs":[["/ip4/104.211.48.247/
```

Older format:
```{
  "nodes": [
    {
      "url": "enode://690f4c344d25273eba0fa95463be214cf7c1720120cdad32d46a52483441107167720cd53b072240649d3ae6a6a42969871df983e14b7ec3327acc94195aeb23@10.5.0.184:30300",
      "last_contact": {
        "failure": 1531810202
      }
    },
    {
      "url": "enode://373ad6196df2322a931e396642c38932c85e8f481e4e3bfbff63f20700a67c17a4a700f3e101ef151e3de2bd5da647719619fdbb5820b4fc39aec7f1414ec46c@188.15.33.41:30303",
      "last_contact": {
        "failure": 1531810202
      }
    },
    ...
```

</details>

When a node starts and `nodes.json` contains old data, it reports `Failed to open peer storage` and say the peer data will not be saved.

Either we do a fix that wipes the old file and move on, or we document that users need to delete the file (which I kinda do in this issue :))

**Comment by tomaka** [comment]
Still needs a fix so that the code automatically deletes the invalid peer storage.
