### ISSUE TITLE
Backward incompatibility between XCM v0 and v1

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#4056]
https://github.com/paritytech/polkadot/blob/aeea9b7bd81919e014f7621f6c4b2eb9709d918f/xcm/src/v1/order.rs#L149

This is `v1::MultiAsset` which is no compatible with `v0::MultiAsset`.

On Karura 1011 (The current live runtime), we are using `v0::MultiAsset::All` and it failed to be decoded on Kusama 9100.

https://github.com/open-web3-stack/open-runtime-module-library/blob/4bd9eed87814e74aa94720f38af0b7328aed2771/xtokens/src/lib.rs#L217

**Comment by gavofyork** [comment]
See https://github.com/paritytech/polkadot/pull/2815 for information on incompatibilities and https://github.com/paritytech/polkadot/pull/3578 for the fix in Polkadot.
