### ISSUE TITLE
Kusama validator stopped with the below error

### ISSUE THREAD

**Issue by blackhatzw** [paritytech/polkadot#406]
My validator stopped automatically then I checked the log and find the below error:

2019-08-27 01:06:47 Idle (50 peers), best: #52385 (0x936c…5335), finalized #52384 (0x9b54…98ec), ⬇ 67.6kiB/s ⬆ 60.5kiB/s
2019-08-27 01:06:48 Imported #52386 (0x5c90…2c9c)
2019-08-27 01:06:48 Error running offchain workers at Number(52386): UnknownBlock("Unknown state for block Number(52386)")

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h74fc0ce542015ca1 (0x563d98b5b400)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x563d98c94d09)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x563d98c947a2)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x563d98c94686)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x563d98cb653d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h287370aa51833ba0 (0x563d97e799ae)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage::hebfb603b706804c5 (0x563d97c76ee0)
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::hff29821f9e7a295e (0x563d97b655fd)
   8: wasmi::func::FuncInstance::invoke::h48737de52080e00f (0x563d97a0cf0a)
   9: wasmi::runner::Interpreter::start_execution::hcf42baf6164f9c9c (0x563d97d7763a)
  10: wasmi::func::FuncInstance::invoke::h48737de52080e00f (0x563d97a0cf9c)
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::hf3b258b653b2ba9b (0x563d97b75edb)
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h980f1bf295730437 (0x563d97df2fab)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::hb5dc2a70c174a42b (0x563d97f2a290)
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::hf41df3a259c3610b (0x563d97f84512)
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hb6ee62da768c2701 (0x563d97e2739b)
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h3f7e3aecf9b6025a (0x563d97bead70)
  17: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::hbef71fbaf582805b (0x563d97d056b5)
  18: substrate_client::runtime_api::Core::initialize_block::h7a64873171547623 (0x563d979ae17a)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h135e6d1787d654e9 (0x563d97e16de8)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hb47b4e45db48769e (0x563d97beccb7)
  21: polkadot_primitives::parachain::runtime_decl_for_ParachainHost::validators_call_api_at::h1ba17a421bf6c7ea (0x563d97f0abac)
  22: polkadot_primitives::parachain::ParachainHost::validators::h50edda0e08a06cb4 (0x563d979c44af)
  23: polkadot_validation::ParachainValidation<C,N,P>::get_or_instantiate::h03062f99ba95a6c2 (0x563d97a960c2)
  24: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::h1285764a84cd8bda (0x563d97fb70e6)
  25: <futures::future::select::Select<A,B> as futures::future::Future>::poll::hd8dbf9175f9110f9 (0x563d97d9dc25)
  26: futures::future::chain::Chain<A,B,C>::poll::h3a4d7e09f966ddfa (0x563d980fb4b9)
  27: futures::task_impl::std::set::hd673d21627d39e78 (0x563d9817b852)
  28: tokio_current_thread::CurrentRunner::set_spawn::h4150e72017b9360c (0x563d979d416b)
  29: tokio_current_thread::scheduler::Scheduler<U>::tick::hf8d1d070382aa5ea (0x563d980bf359)
  30: tokio_current_thread::Entered<P>::block_on::h2948deeeb292ddae (0x563d979d4366)
  31: std::thread::local::LocalKey<T>::with::h8c905f40ba5bf329 (0x563d97e50754)
  32: std::thread::local::LocalKey<T>::with::h9381601243224b22 (0x563d97e50e0b)
  33: std::thread::local::LocalKey<T>::with::hac17cd602a593c9f (0x563d97e52e3b)
  34: std::thread::local::LocalKey<T>::with::h89797832172d5614 (0x563d97e4f6a1)
  35: tokio::runtime::current_thread::runtime::Runtime::block_on::hd708dc927dca4614 (0x563d97c49f65)
  36: std::sys_common::backtrace::__rust_begin_short_backtrace::hfe49e6f04e871514 (0x563d98159734)
  37: std::panicking::try::do_call::h1f14f5300bf31260 (0x563d98030e79)
  38: __rust_maybe_catch_panic (0x563d98c9dc2a)
             at src/libpanic_unwind/lib.rs:82
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}::h5724696c3ef422ff (0x563d97ac33b4)
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x563d98c82def)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x563d98c9cfb0)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  42: start_thread (0x7fa348f8b6db)
  43: __clone (0x7fa348a9c88f)
  44: <unknown> (0x0)

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x93b4bf27f0e31d303ef9955821c35c3a779e28aeeb35c6ecc0f1064cbceba27b"', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

**Comment by iammelea** [comment]
What is the Polkadot --version?

**Comment by blackhatzw** [comment]
Just talked this issue in Riot, my version is v0.5.0, I will close this issue
