### ISSUE TITLE
Make XCM Instructions with `Wild` filter weighable.

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#4069]
XCM Currently supports a `MultiAssetFilter::Wild` filter where:

```
pub enum WildMultiAsset {
	/// All assets in the holding register, up to `usize` individual assets (different instances of non-fungibles could
	/// be separate assets).
	All,
	/// All assets in the holding register of a given fungibility and ID. If operating on non-fungibles, then a limit
	/// is provided for the maximum amount of matching instances.
	AllOf { id: AssetId, fun: WildFungibility },
}
```

In the case that this filter is used, we cannot currently know the worst case scenario for weighing these instructions.

To solve this we need to implement two new features:

1. Add an overall `MAX_HOLDING_ASSETS` constant to the whole XCM Executor configuration which can be used in any situation to provide a pessimistic upper bound on how many assets could be matched from Holding.
2. ~For instructions where a pessimistic upper bound is not good enough (e.g. when there is a storage write for every asset matched such as in `InitiateTeleport`), provide a facility for specifying a more accurate asset-match-count via a `max_assets` field.~ Introduce `AllCounted` and `AllOfCounted` in `Wild` and remove all `max_assets` stuff.

These changes are breaking and should be included in XCM v3

**Comment by gavofyork** [comment]
Closed with #4097
