### ISSUE TITLE
Metadata V14

### ISSUE THREAD

**Issue by shedfull** [paritytech/polkadot#4070]
It seems that the latest version of the polkadot metadata (v14) is in a completely different format to previous versions. This has broken the python substrate-interface and the polkaj java client (and probably others that I don't know about) Some advance notice about this major change would have been appreciated

**Comment by bkchr** [comment]
Everyone was informed about this, the library you are referencing was also updated 20 days ago already: https://github.com/polkascan/py-substrate-interface/commit/2edeaef30d0855656e34caf7b8dcb5a88de8af8a
