### ISSUE TITLE
Telemetry should not be enabled by default for production networks

### ISSUE THREAD

**Issue by soc1c** [paritytech/polkadot#416]
Apparently, with Kusama CC1 nodes reporting to telemetry.polkadot.io by default, the monitoring dashboard gets unusable for various reasons:

- Dashboard freezes after a certain amount of time
- Refreshing 150+ nodes every 6 seconds makes it hard to extract any useful information
- Finding own nodes to pin is kind of difficult

Proposal:

- Default to `--no-telemetry` for Kusama CC1
- Maybe consider exceptions for special purpose nodes, such as `--validator` or `--pruning archive` nodes

**Comment by bkchr** [comment]
Isn't this more a flaw of the telemetry that should support filtering the nodes?

**Comment by joshua-mir** [comment]
I feel `--validator` nodes should definitely *not* be on public telemetry.

**Comment by crsCR** [comment]
There's an issue with public nodes that are on telemetry too. Validator IPs can be leaked to these public nodes even if the validator has --no-telemetry flagged. The nodes include validator IP in network state under knownaddresses...
https://github.com/w3f/polkadot-secure-validator/issues/3

**Comment by rphmeier** [comment]
stale
