### ISSUE TITLE
Extract Runtime Constants into Separate Crates

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#4251]
For Statemint we would like to depend on the constants (e.g. depend on [Kusama's deposit](https://github.com/paritytech/polkadot/blob/f26e523a1335cf2fdb4bae37dd89fa5220b3619e/runtime/kusama/src/constants.rs#L26) for Statemine) without depending on the whole runtime.
Thus it would be great if we could extract them into separate crates. (e.g. `westend-runtime-constants`, `polkadot-runtime-constants`, `kusama-runtime-constants`)
Would be great to include the existential deposit (and potentially some other constants) in it.

**Comment by Doordashcon** [comment]
Hello @apopiak, for clarity. Constants defined in various runtimes(i.e `westend/src/constant.rs`, `test-runtime/src/constant.rs` e.t.c.) should become one crate because they are repeated with the same values?

**Comment by apopiak** [comment]
> Hello @apopiak, for clarity. Constants defined in various runtimes(i.e `westend/src/constant.rs`, `test-runtime/src/constant.rs` e.t.c.) should become one crate because they are repeated with the same values?

No, the `constants.rs` modules should each become a crate. So sth like `westend-runtime-constants`, `polkadot-runtime-constants`, `kusama-runtime-constants`.

**Comment by Doordashcon** [comment]
Okay, taking on this issue

**Comment by apopiak** [comment]
addressed via #4456
