### ISSUE TITLE
Orga/Meta Request: Add XCM label

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#4266]
It would be great if we could tag XCM-related PRs (analogously to PRs that are marked `B7-runtimenoteworthy`).
This issue proposes adding a new label for it.

**Comment by chevdor** [comment]
Since we need that in Cumulus and we setlled for `B6-XCM`, I created `B6-XCM`in both repos. Labels will change soon anyway, we can adjust.

**Comment by chevdor** [comment]
Since we could have a PR affecting the runtime AND XCM, this label should not be a `B` label. I moved it to `T6-XCM`.

**Comment by KiChjang** [comment]
Looks like this is already done.
