### ISSUE TITLE
[zombienet] migrate branch based malicious code to malus framework

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#4271]
Currently a function changeset is present in a branch, but the malus behavior is not equivalent and doesn't quite work.

Moving the functionality is a requirement to move on with integration tests 0002 and 0003 in #4131 / #3639

**Comment by drahnr** [comment]
#4377 is imported, porting is now pending impl

**Comment by drahnr** [comment]
@sandreim to my understanding, with you current open PRs this is covered, or are there any further tests missing?

**Comment by sandreim** [comment]
AFAIK this is ca be closed.
