### ISSUE TITLE
Ran out of free WASM instances   

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/polkadot#4275]
Network: Polkadot
Version: 0.9.12

Hi, I am running a node to provide WS endpoint for my Dapp, and it gets `Ran out of free WASM instances` error, any idea how I should do to fix it?

**Comment by bkchr** [comment]
This is no bug, it just means that you are using more wasm instances as we can cache. It will just be more costly to create more instances, but nothing breaks. 

You can configure the maximum number using `--max-runtime-instaces`

**Comment by igorbarinov** [comment]
what is a default value for `--max-runtime-instaces`? @bkchr

**Comment by AlexZhenWang** [comment]
> what is a default value for `--max-runtime-instances`? @bkchr
> 
> p.s. there is a typo in your reply `--max-runtime-instances` should be

The default is 8 and the max is 256
