### ISSUE TITLE
Consider a declarative API to describe XCM barrier conditions

### ISSUE THREAD

**Issue by KiChjang** [paritytech/polkadot#4276]
Currently, the way we set up XCM barriers is done in a very procedural and imperative manner:

https://github.com/paritytech/polkadot/blob/903c6f2f014bcedb9d6be0cae86e6a4a922f692b/xcm/xcm-builder/src/barriers.rs#L53-L92

Since we've already have cases where a misconfigured barrier condition has led to privilege escalation attacks, it is therefore prudent to consider whether this should be the way in which we manage the complexity involved in configuring the barrier.

Due to the security implications, we can even begin to think of the barrier as the firewall, the first line of defense against malicious actors, and so barrier conditions should:

- be easily maintainable and auditable;
- hide complexity when it is not necessary to be surfaced;
- simple to use and configure

One of the suggestions made by @apopiak was to have an API that resembles something like the following:

```rust
message
	.match_next_inst(|inst| matches!(inst, WithdrawAsset(..))
	.match_while(|inst| matches!(inst, ClearOrigin))
	.match_next_inst( /* ... */ )
```

Files: `xcm/xcm-builder/src/barriers.rs`, `xcm/src/v3/mod.rs`

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-40/2468/1
