### ISSUE TITLE
Investigate avoiding disputes in case of PVF preparation transient errors

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#4293]
A validator that cannot validate a candidate due to a preparation error should strive to not cast an invalid vote, so that disputes are not initiated due to transient errors.

The caveat here is that we do not always know if an error is transient or it is a deliberate attack. However, after we land https://github.com/paritytech/polkadot/issues/3211 this will become much more easier: if the supermajority voted for a PVF then we can be reasonable sure that the is indeed transient.

**Comment by burdges** [comment]
We'll just compile the PVFs an earlier though, no?  We could finalize that 2/3rd of validators compiled the PVF correctly even.  We'd then have overlapping 2/3rds that do not work out, but ignoring that likely works fine.
