### ISSUE TITLE
Reintroduce custom polkadot CLI commands

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#43]
I think this is only `collating_for` for now.

**Comment by gnunicorn** [comment]
`collating_for` never was a CLI argument - see [the commit in which it was removed](https://github.com/paritytech/polkadot/commit/1fb72bf331aa4bf347b096be34e81b068cfaac55#diff-4a0ebb58ae5c66b498d949b3702d9953L1) - looks like we moved all cli args over to substrate. No need to be done here. closing.
