### ISSUE TITLE
Chainstate is not the same on different nodes

### ISSUE THREAD

**Issue by GopherJ** [paritytech/polkadot#4307]
Hi, we discovered a strange and serious bug on our nodes. The chainstate of them are different.

The storage that I'm talking about is:

```
system.account(hJL2mJF9qhnQitjAXq8QJB5suYFYMySc1kwGnYDy49EAxqVcv)
```

The endpoints that I'm using:

- Parallel Heiko: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fheiko-rpc.parallel.fi#/explorer
- OnFinality: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparallel-heiko.api.onfinality.io%2Fpublic-ws#/explorer
- Heiko Collator 0: https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer (not public)

### Query 1 - OnFinality rpc node:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/33961674/142132081-401b7b1c-9ae4-42ef-8cc8-95604c3a2208.png">

### Query 2 - Parallel Heiko rpc node:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/33961674/142132129-6ef5a995-0311-4ac1-ac66-2c4579d88410.png">

### Query 3 - Parallel Heiko Collator 0:

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/33961674/142132162-c9c16f3e-b89c-49c0-aa73-5a45ef2d35ac.png">

As you can see, our rpc nodes have different chainstate with bootnodes, but it shouldn't, at the same time, our rpc node is still syncing. If the chainstate is not the same or block is missing, shall it stop syncing and wait?  How should we fix this difference?

**Comment by GopherJ** [comment]
Maybe: https://github.com/paritytech/substrate/issues/10130 is related

**Comment by yz89** [comment]
By the way, the vesting transaction was a success.
https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer/query/0x3d7f9c048367d65da447c16fc99677574f6d7e37cac92fe27a43bd336fc3db10

to: hJL2mJF9qhnQitjAXq8QJB5suYFYMySc1kwGnYDy49EAxqVcv

**Comment by bkchr** [comment]
> our rpc node is still syncing

What is synching? The relay chain?

**Comment by GopherJ** [comment]
@bkchr relaychain & parachain

**Comment by bkchr** [comment]
How should we test this without being able to connect to the collator?

As you can see in your screenshot, you can insert a block hash you want to query on. Please query the data on all nodes based on the same block.

**Comment by yz89** [comment]
I queried on all the nodes based on the block 218830. (hash 0x3d7f9c048367d65da447c16fc99677574f6d7e37cac92fe27a43bd336fc3db10)

### Query 1 - OnFinality rpc node:
![image](https://user-images.githubusercontent.com/12026976/142167450-b06b2baa-0e8d-4843-8d01-4eef4e09bf8c.png)

### Query 2 - Parallel Heiko rpc node:
![image](https://user-images.githubusercontent.com/12026976/142167544-5798a5f8-1e12-432e-ba0f-102f2c9404d4.png)

### Query 3 - Parallel Heiko Collator 0:
![image](https://user-images.githubusercontent.com/12026976/142167605-431f378e-5785-4bf3-9c83-bfd1de10d7d4.png)

They are same now. But why are their states different when checking the latest status?

**Comment by bkchr** [comment]
What is your rpc seeing as best block?

**Comment by yz89** [comment]
They are all 266080 fow now.

**Comment by yz89** [comment]
After another restart, the RPC node is restored. This one's weird.

**Comment by GopherJ** [comment]
@bkchr is this caused by some kind of `cache`?

**Comment by bkchr** [comment]
If it would have been the state-cache, it should have been solved with a simple restart.

**Comment by GopherJ** [comment]
@bkchr yes we fixed it by restarting nodes, what's the best settings of `--state-cache-size` for preventing such issue?

**Comment by bkchr** [comment]
You said you needed to restart it multiple times, so that could not have been a cache issue. A cache issue would have been fixed after the first restart.

**Comment by GopherJ** [comment]
@bkchr No, we only restarted them one time

**Comment by bkchr** [comment]
Then run with `--stache-cache-size 0` for now please.

**Comment by GopherJ** [comment]
@bkchr let me try it, since this can be very hard to reproduce again, I think this issue can be closed for now. We will try to use `--state-cache-size 0` and let you know if it happens again.

Thanks for your help
