### ISSUE TITLE
Improve Integration Testing Support

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#4333]
As a parachain developer I want to be able to run local relay chains for integration testing.
Rococo can be great for prototyping features/changes, but cannot function as a full substitution for testing against the relay chain that the parachain is intended to run on. E.g. the XCM config between Rococo and Kusama differs.

For this reason we should investigate how to improve testing support with something that's close to the production runtimes.

**Comment by apopiak** [comment]
Some approaches to investigate:
+ allow configuring of time periods of production runtimes, e.g. block times, session times, voting periods
  + see #4332 for a first try
+ adjust Westend to be more in line with Polkadot, e.g. adjust existential deposit/decimals to Polkadot's
+ add a feature to Substrate to fake time (or similar) so everything can be sped up

**Comment by xlc** [comment]
> add a feature to Substrate to fake time (or similar) so everything can be sped up

This will be very helpful to all other teams

**Comment by drahnr** [comment]
CC @pepoviola

**Comment by pepoviola** [comment]
Hi @apopiak, I'm currently working in a project called `zombienet` which primary goal is provide an integration test framework (allowing to spawn a new network from a provided config and run assertions agains it). At this moment the project is in early state but we can check your use case to check if the already implemented features cover it.

Thanks!

**Comment by sandreim** [comment]
We have coverage in current zombienet integration suite: https://github.com/paritytech/polkadot/tree/master/zombienet_tests
