### ISSUE TITLE
Test false positive dispute spam

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#4354]
If the chain gets flood with lots of invalid candidates, lot's of chain reversions will happen. We need to make sure, that no matter how hard we push here, the chain will always continue to make progress - at least slowly.

Risks for Rococo: Chain might cease to make progress. Stopping malicious validators should bring it back, if we can do that before hitting an unexpected epoch change. => We should make sure to be able to remove malicious validators within a few minutes.

**Comment by rphmeier** [comment]
It depends what you mean by 'make progress' - we would probably have to make mathematical arguments based on the number of local disputes, the number of malicious validators, and the backing group size. A hyper-geometric distribution tells us that with 33% malicious, we'd have around 20% of groups of size 5 being majority-malicious as N->INF. In this case, we'd be looking at reversions every block and therefore we'd need to improve our 'disabling' code to ignore backing statements. Then we'd always be able to make progress in blocks authored by non-byzantine nodes, so 66+e% of the time.

**Comment by eskimor** [comment]
My understanding is that on chain reversion we clean out backed candidates and thus we will have at least one block without any candidates included, thus it cannot get disputed and thus the chain should make progress even if every single candidate on every block gets disputed.

**Comment by eskimor** [comment]
Has been tested.
