### ISSUE TITLE
#1 Real IP gossiped inclusive with the flag `--listen-addr=` , #2 If --listen-addr= if cant find the assigned IP, error and connect using another IP. same for the ports.

### ISSUE THREAD

**Issue by iammelea** [paritytech/polkadot#437]
When start the node like this

```
~/.local/share/polkadot/chains/ksma$ polkadot --name melea-◮👁◭-W3F-I-Trust --listen-addr=/ip4/10.0.0.2/tcp/30333
```
Then 

```

2019-09-17 07:05:29 Parity Polkadot
2019-09-17 07:05:29   version 0.5.1-645baf1-x86_64-linux-gnu
2019-09-17 07:05:29   by Parity Team <admin@parity.io>, 2017-2019
2019-09-17 07:05:29 Chain specification: Kusama CC1
2019-09-17 07:05:29 Node name: melea-◮👁◭-W3F-I-Trust
2019-09-17 07:05:29 Roles: FULL
2019-09-17 07:05:33 Highest known block at #349201
2019-09-17 07:05:33 Local node identity is: QmSmt
2019-09-17 07:05:34 Discovered new external address for our node: /ip4/10.0.1.252/tcp/30333/p2p/QmSmti75b7R
```
After the Discovered new external address, the gossip the Real IP
```
2019-09-17 07:05:34 Discovered new external address for our node: /ip4/REAL-IP-HERE/tcp/30333/p2p/QmSmti7
```
If using this flag ```--listen-addr=/ip4/10.0.0.2/tcp/30333``` when start why shows anothers IP or my real IP always after start.

Also if the node or the server for any reason restart the node and for any reason, the IP is not available, I hoped that it would not connect while the IP assigned in the flag ```--listen-addr=``` was available or failed to find the IP and stopped but instead it is connected by another IP, Also the ports, if the ports are busy, no error Stop, simply say in the logo that  IP is not available and will connect to another IP / ports.
This can cause problems for the validators working with nodes in private connection for my understanding and test.

when checking the logs in the private node running reserves nodes 2 and listen address too.
![Screenshot from 2019-09-17 07-39-11](https://user-images.githubusercontent.com/38863192/65014301-81b6d500-d91e-11e9-96c8-e45ab523d501.png)
after stop and start get 2 peers again ok.
![Screenshot from 2019-09-17 07-41-45](https://user-images.githubusercontent.com/38863192/65014337-aca12900-d91e-11e9-96b6-d465343dd7a9.png)

Thank you

**Comment by bkchr** [comment]
@tomaka sounds like he is right and we should make this an hard error? If the binding to the address fails, we should not just switch to listening on a different address.

**Comment by tomaka** [comment]
For #1, the real IP address it show you is what we call the external IP address. I thought there was a CLI option to configure the external addresses that are advertised (like is the case in parity-ethereum), but I can't find it and I guess it doesn't exist.

For #2, I don't see what you mean. If listening on an IP:port fails (according to the Linux kernel), you're supposed to see a warning and nothing more happens: https://github.com/paritytech/substrate/blob/7fc21ceafbd01f3fadff7d1ebd51b7c6ba9f86ac/core/network/src/service.rs#L212-L216
Most notably, we don't automatically listen on something else.

**Comment by iammelea** [comment]
Ok, some pic better.
![Screenshot from 2019-09-18 00-15-05](https://user-images.githubusercontent.com/38863192/65083955-33e7ae80-d9aa-11e9-8869-c5ebea5885a5.png)

stop node, stop VPN, node start cant use the IP, the connect using another, cant peer to my nodes.
![Screenshot from 2019-09-18 00-17-53](https://user-images.githubusercontent.com/38863192/65084034-672a3d80-d9aa-11e9-838f-d0df62443689.png)

more pic
![Screenshot from 2019-09-18 00-18-51](https://user-images.githubusercontent.com/38863192/65084095-83c67580-d9aa-11e9-9886-80cf85bad699.png)

here without reserves nodes connect and peer. 

My question is, does this not bring connectivity problems? It is best if the node does not connect if the external IP is not available and stop some panic msg? instead of using another IP?

**Comment by gavofyork** [comment]
Is this still a problem?

**Comment by iammelea** [comment]
Today review and update

**Comment by LukeWheeldon** [comment]
I am observing this here too, where while I assign a specific interface and port through --listen-addr, polkadot is still displaying "Discovered new external address for our node: /ip4/1.2.3.4/tcp/30334/p2p/12D3KooWXXX" on interfaces that are not specified on --listen-addr.

**Comment by heisler98** [comment]
On v0.9.0, I experience this as well. Not necessarily an issue for me - just consistently throws up all my local interfaces in the log.

**Comment by LukeWheeldon** [comment]
Two points:
1. It should be a user choice whether an application is "gathering information from all its connections". The vast majority of server applications have an option to bind to a specific IP:PORT and not nose around without permissioin.
2. As can be seen in #2997, polkadot is detecting IPs that are not part of the system it is running on.

**Comment by tomaka** [comment]
You seem mistaken.
The IP addresses that are shown to you in the logs are the IP addresses that *other nodes* think your node has, in order words it is the "source IP address" that other nodes see when your node establishes a TCP connection to them.
The private IP addresses that you see are the ones used by virtual interfaces. They are being filtered out and not used by other nodes to try connect.

**Comment by LukeWheeldon** [comment]
That makes a lot of sense, but then, why do I see those private IP addresses that supposedly belong to me, while I am not under NAT, or PAT? There's just something odd about this.

Furthermore, everything that is in the default log view is there because it is useful to the nodes admins, it enables them to quickly get an understanding of the node's state. As one such admin, what am I to do with those private addresses, how is that helping me understand the current state? Is all of this documented somewhere so I can attempt to wrap my head around what is going on here? Thanks @tomaka!

**Comment by LukeWheeldon** [comment]
I understand, thank you for clarifying. It's still unclear to me why those private IP addresses are showing up while they are not part of my system nor part of the routing to my node, which is not leveraging NAT, or PAT for that matter. Although I would like to understand, I don't want to make this about me. I raise this point in case it would be helpful to OP's issue.

If not useful, then no problem we can move on. If useful, I'm happy to provide more details and logs on my end.

**Comment by tomaka** [comment]
If you log `-l sub-libp2p=debug`, you should find log lines that say something like "identified" or "identity", and that will contain the information about which peer has reported seeing which IP address for your node.
