### ISSUE TITLE
runtime: allow span based tracing

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#4382]
On the host side we use span based tracing which are now also available in our metrics backend.

Adding this to the runtime seems reasonable.

*Outline*:

Define something along:

```
#[runtime_interface]
pub trait SpanTrace {
 fn enter(tag: &'static str) -> SpanId {}
  fn child_enter(parent: SpanId, tag: &'static str) -> SpanId{}
 fn leave(SpanId) {}
}
```

which could be conveniently used similarly to the node side `jaeger::Span`s.

**Comment by bkchr** [comment]
We already have this: https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs#L1202

And this feature should also be turned off by default or should be turned off when we build the on chain wasm file, as we do it for logging. We can then have special nodes that run with a wasm file that has this feature enabled.

**Comment by bkchr** [comment]
We already have this: https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs#L1202

And this feature should also be turned off by default or should be turned off when we build the on chain wasm file, as we do it for logging. We can then have special nodes that run with a wasm file that has this feature enabled.

**Comment by drahnr** [comment]
So I was right and this existed :) I just didn't manage to find it. CC @sandreim
