### ISSUE TITLE
Json RCP access fails through Docker container

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#439]
While http and ws connections work with polkadot running locally, the same requests fail with a Docker container despite the ports being open.

tested with:
```
docker run --rm -it -p 9944:9944 -p 30333:30333 -p 9933:9933 -v ~/Library/Application\ Support/Polkadot/:/data chevdor/polkadot polkadot
```

```
curl -H "Content-Type: Application/json" -d "{}" http://localhost:9933
```

**Comment by tomusdrw** [comment]
Are the ports exposed in Docker? What error are you getting?

**Comment by chevdor** [comment]
Using `polkadot` sending an (invalid) request such as `curl -H "Content-Type: Application/json" -d "{}" http://localhost:9933`, I do get an answer: `{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":null}`

Using `docker run --rm -it -p 9944:9944 -p 30333:30333 -p 9933:9933 -v ~/Library/Application\ Support/Polkadot/:/data chevdor/polkadot polkadot` (you see with `-p 9933:9933` that the port is open and exposed) and the same curl request, I get:
```
curl: (52) Empty reply from server
```

I did `nmap`in both cases and the port *is* open:
```
$ nmap localhost -p 9933
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-30 11:21 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00034s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE
9933/tcp open  unknown
```

**Comment by tomaka** [comment]
I would guess that polkadot only listens on `127.0.0.1` by default, so it would only accept connections from inside the container.

**Comment by chevdor** [comment]
Indeed @tomaka. But mapping the ports as as I did should work.
It works for nginx for instance: `docker run -it --rm -p 82:80 nginx` will show you a nice welcome from nginx at http://localhost:82

Should not polkadot listen on all interfaces => 0.0.0.0 ?

**Comment by chevdor** [comment]
Note to self: test a change at https://github.com/paritytech/polkadot/blob/master/substrate/cli/src/lib.rs#L296 from `127.0.0.1` to `0.0.0.0`

**Comment by chevdor** [comment]
See #495
