### ISSUE TITLE
Construct a batch operation with two transfer_all calls, which will be replayed from time to time after the broadcast.

### ISSUE THREAD

**Issue by scrawld** [paritytech/polkadot#4433]
I sent a batch operation with two transfer_all in the batch operation.
I thought it was supposed to be a failure, but it worked.
After transferring money to the sending account, the last batch method was called again after half an hour, and the transaction hash was the same.
Send account number `12LEEihCXEUmdc35CpiDA4nuaif3vmX7weCsWELj9KBwZeB3`
```
[
  {
    name: "calls",
    type: "Vec<Call>",
    type_name: "Vec<<T as Config>::Call>",
    value: [
      {
        call_index: "0504",
        call_module: "Balances",
        call_name: "transfer_all",
        params: [
          {
            name: "dest",
            type: "sp_runtime:multiaddress:MultiAddress",
            value: {
              Id: "0x065ffd17df6c27f34ecc91313a9ee924b4b18557ec29c7a2f63970fab7a2a44d"
            }
          },
          {
            name: "keep_alive",
            type: "Bool",
            value: false
          }
        ]
      },
      {
        call_index: "0504",
        call_module: "Balances",
        call_name: "transfer_all",
        params: [
          {
            name: "dest",
            type: "sp_runtime:multiaddress:MultiAddress",
            value: {
              Id: "0x8a51dd9ab9ca5391c3406f5b32343697351043c41dd180abe2265c22bb847757"
            }
          },
          {
            name: "keep_alive",
            type: "Bool",
            value: false
          }
        ]
      }
    ]
  }
]
```

**Comment by bkchr** [comment]
Transaction hashes are not unique.

**Comment by scrawld** [comment]
The second transfer was self-executing

**Comment by bkchr** [comment]
> The second transfer was self-executing

What you mean?

**Comment by scrawld** [comment]
The txhash will be duplicated, I broadcast the transaction and get the txhash, how do I query the transaction accurately

**Comment by shawntabrizi** [comment]
> last batch method was called again after half an hour

This is not how batch txs work, so there is something else going on.

**Comment by scrawld** [comment]
> > last batch method was called again after half an hour
> 
> This is not how batch txs work, so there is something else going on.
> 
> If you let your account be killed, it txs without a lifetime can be replayed. It is not a good idea to give any tx a large lifetime.

Why doesn't this case return an error?

**Comment by shawntabrizi** [comment]
@scrawld it is just an implementation detail. Currently a transfer of value 0 is considered a simple noop:

https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L1474

**Comment by scrawld** [comment]
@shawntabrizi Why is this batch operation being replayed.

**Comment by scrawld** [comment]
@shawntabrizi I called the utility.batch_all method with two Balances.transfer calls, and after broadcasting I found that my last utility.batch had been replayed again transferring the rest of my balance.

The height of the first transaction is `8023499` The transaction hash is `0x2b8bb7784f8a8ff4fc9dfe93b864df0ab9e4defbe63e9200239d7f8b380a5649`. The first one is operated by me.
The second transaction height is `8023499` and the transaction hash is `0xdc54b92b1377bf0e8854385c49aa6b2debfdcfd135351f719e56dd4ed8d228fb`. The second one is replayed

I would like to know why this is happening and I hope it will be resolved soon, it has caused me damage.

**Comment by scrawld** [comment]
@shawntabrizi I don't know when it will be replayed, but when it happens the balance of my account will be completely transferred, I feel that my account is no longer safe.

**Comment by xlc** [comment]
Why you are making immortal transaction?

**Comment by scrawld** [comment]
> Why you are making immortal transaction?

I was just curious if this would return a failure for me, and this is what happened

**Comment by scrawld** [comment]
The latest replay, this time for me to replay two operations, block `8023820`, the transaction hash are `0x2b8bb7784f8a8ff4fc9dfe93b864df0ab9e4defbe63e9200239d7f8b380a5649`,`0xdc54b92b1377bf0e8854385c49aa6b2debfdcfd135351f719e56dd4ed8d228fb`
Is there a temporary solution, now as long as the account has a balance will be replayed operation to transfer

**Comment by xlc** [comment]
there are no solution other than ensure your account always have ED. this is what happened if you are using immortal transaction.

**Comment by scrawld** [comment]
I think this is a bug that causes the account to no longer be available

**Comment by shawntabrizi** [comment]
@scrawld you should read: https://wiki.polkadot.network/docs/build-protocol-info#transaction-mortality

In summary:

* If your account falls below the existential deposit, your account will be "cleaned up" specifically your nonce will be reset and any other artifacts of your account will be deleted from the chain.
* This could allow a replay attack where you signed a previous transaction with a specific nonce, and when you use this account again after it has been reset, you will go through the same nonces over again, and that transaction could be replayed.
* This problem is solved by also including a lifetime to a transaction which will say that a transaction is only valid if both the nonce and the era match what is expected. So while it may be possible that the nonce will be reached again, certainly the era would not be the same (unless being replayed in a very very short amount of time)
* Your issue here is that you did not set a lifetime to the transaction you created, thus it does not check that transaction is being replayed. This is a mistake on your side, or on the side of whatever tool you use to generate the transaction.
