### ISSUE TITLE
After sending a transaction, how to accurately check the transaction

### ISSUE THREAD

**Issue by scrawld** [paritytech/polkadot#4443]
I will get the txhash after broadcasting the transaction, but the txhash is not unique, so what is the best way to get the transaction information and make sure the transaction is successful?

**Comment by bkchr** [comment]
There is the `author_submitAndWatchExtrinsic` rpc for this.

**Comment by scrawld** [comment]
I'm using substrate-api-sidecar to interact with the node.
`substrate-api-sidecar` This project doesn't seem to support `author_submitAndWatchExtrinsic ` yet.

**Comment by bkchr** [comment]
CC @TarikGul

**Comment by TarikGul** [comment]
Feel free to close this as there is a tracking [issue here](https://github.com/paritytech/substrate-api-sidecar/issues/783) in sidecar now. Will work on giving `author_submitAndWatchExtrinsic ` support.
