### ISSUE TITLE
Migrate monitoring dashboard to rococo

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#4477]
Currently we only have a small number of metrics that are actively monitored.

* [x] migrate all metrics, add them one by one and check their viability
* [ ] define alerts for every single one of them

**Comment by sandreim** [comment]
Except for the alerts part, the dashboards in https://github.com/paritytech/polkadot/pull/4578 can be used for rococo as well.

**Comment by drahnr** [comment]
I think this can be closed?
