### ISSUE TITLE
Log level is not displayed

### ISSUE THREAD

**Issue by nomotobori** [paritytech/polkadot#4495]
Our system runs polkadot downloaded from docker on Aws Ecs.

Current status
We entered to “ — log＝info” to display the log level when starting polkadot. But, the log level is not output.

if you enter “—log ＝ debug” the log level of debug ,info, warn, error will output. But, We want the log of info ,warn error.

Question
What command shoul I enter to output the log level info ,warn,error.

Reference
https://wiki.polkadot.network/docs/build-node-management#monitoring-and-telemetry

**Comment by bkchr** [comment]
Use `--detailed-log-output`, this is available since 0.9.13
