### ISSUE TITLE
parity-common duplicate source version

### ISSUE THREAD

**Issue by akru** [paritytech/polkadot#451]
**Problem**

Cargo vendorization fails on polkadot 0.6 with following error:

```
  found duplicate version of package `kvdb v0.1.0` vendored from two sources:

        source 1: https://github.com/paritytech/parity-common?rev=616b40150ded71f57f650067fcbc5c99d7c343e6#616b4015
        source 2: https://github.com/paritytech/parity-common?rev=b0317f649ab2c665b7987b8475878fc4d2e1f81d#b0317f64
```

**Reproduce steps**

    cargo vendor --locked

**Comment by iammelea** [comment]
The correct branch is v0.6.0

**Comment by akru** [comment]
@iammelea Currently it's the same commit https://github.com/paritytech/polkadot/commit/41db99055c08ab7365263ba9ab1c35966147286b.

**Comment by gavofyork** [comment]
sorted.
