### ISSUE TITLE
Upgrading to polkadot 9140 stalled relay network because of babe epoch

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot#4586]
This happened in 1 of our network (the same process was performed with success on another network with the difference of using a westend-local network instead of polkadot-local):
- polkadot-local based network, using client 0.9.13 with runtime 9122
- 4 validators (in 2 different geo-location)
- (1 parachain with 4 collators assigned, but I doubt this has an impact)

I've perform a system.setCode using the official runtime polkadot 9140. The runtime upgrade went well, block kept being produced.
At some point the block production stopped. The validators reported:
```
validator1 2021-12-23 02:49:18.006  WARN tokio-runtime-worker babe: Error with block built on 0xdadac27ae1cb3e9de4cf3beac16ace4c5160c53f02e2be59982f6121221c4b9a: ClientImport("Expected epoch change to happen at 0x1d1a750610e1ec51691f96ce1569618f1c41721195a645a6a74bc10be964c971, s273371293")    
```
(note that a successful block was produced 6s before)

Here are the full logs of all the validators:
[moonlama-validator.log](https://github.com/paritytech/polkadot/files/7766473/moonlama-validator.log)

**Comment by bkchr** [comment]
@crystalin could you please try this again?

Is this network accessible? Aka some open rpc?

**Comment by crystalin** [comment]
@bkchr we purged the network and will try again the same process.
We have tried the same process on some other networks using different runtime (westend-local) and it worked.
We are also trying the process of doing 9122 -> 9130 -> 9140

**Comment by crystalin** [comment]
This was due to a custom 9122 runtime containing a shorter epoch time :(
Sorry for the false alarm
