### ISSUE TITLE
Skipping index [1] in chain spec vec!s, intentional or bug?

### ISSUE THREAD

**Issue by decentration** [paritytech/polkadot#4591]
Looking at how the the keys in the vec tuple are [cloned](https://github.com/paritytech/polkadot/blob/80dfb926f40114841d3894fd75f39098dff9d5d4/node/service/src/chain_spec.rs#L510) as stash, controller and session keys:

```Rust
session: rococo_runtime::SessionConfig {
			keys: initial_authorities
				.iter()
				.map(|x| {
					(
						x.0.clone(),
						x.0.clone(),
						rococo_session_keys(
							x.2.clone(),
							x.3.clone(),
							x.4.clone(),
							x.5.clone(),
							x.6.clone(),
							x.7.clone(),
```
i see that index [1] is skipped and not used, so if i use this as a template in my chain-spec.json file, index [1] of the tuple is missed out. 

I see this in every chain-spec config, checking whether this is intentional or a bug?

Or is it just done for speed, and then in production the second [0] can be changed to [1]...?

**Comment by bkchr** [comment]
This is done by intention.

This is also not related to production networks.

**Comment by decentration** [comment]
@bkchr what is the intention? and also what is the need for [1] in this instance?

**Comment by bkchr** [comment]
This is just copy and paste error. Nothing else.

**Comment by decentration** [comment]
Oh ok, thanks, happy holidays : ) 

Kind regards

> 
>   
>
