### ISSUE TITLE
zombienet: test parachain upgrades

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#4599]
one common thing that I have to do from time to time locally is testing that upgrading a parachain works. It would be great if that was automated away.

Currently, I am using this script currently to automate the process locally: https://gist.github.com/pepyakin/2583ff3348c0188dc3b25cf3537f5f70

cc @pepoviola

**Comment by pepoviola** [comment]
Hi @pepyakin, Thanks for the `gist`! Let me work in the `upgrade` feature in zombienet and I will ping you to test.

**Comment by pepoviola** [comment]
Hi @pepyakin, I have an initial implementation [here](https://github.com/paritytech/zombienet/pull/51) using the simple `smoke-test` as base. Can you send me an upgrade file to test since I tested locally with one generated by another zombienet instance and I get this error from the `api`

```
  zombie::network-node blockNumber : 10 +2s
2021-12-24 16:27:47        RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Other, \"cannot deserialize module: InvalidMagic\
```

Thanks!

**Comment by pepyakin** [comment]
that's weird. Can you send me the file you are trying to send as an upgrade?

Do you have access to the built version of cumulus? If so, a valid wasm upgrade should be available target/release/wbuild/rococo-runtime/rococo_runtime.compact.compressed.wasm

**Comment by pepyakin** [comment]
Ah perhaps that's a bad idea, we should maybe modify the binary there to avoid having the same code hash, see https://github.com/paritytech/cumulus/issues/863

**Comment by ordian** [comment]
Having same code hash would also make it harder to test upgrade succeeded.

**Comment by pepoviola** [comment]
> that's weird. Can you send me the file you are trying to send as an upgrade?
> 
> Do you have access to the built version of cumulus? If so, a valid wasm upgrade should be available target/release/wbuild/rococo-runtime/rococo_runtime.compact.compressed.wasm

Ah my bad, I was using the `wasm` generated by zombienet and not the one from cumulus. I will try with the right one and post the result here 👍.

**Comment by pepoviola** [comment]
@pepyakin, upgrade test implemented in https://github.com/paritytech/polkadot/pull/4660. 
Thanks!
