### ISSUE TITLE
tests::runtime_can_publish_metrics in polkadot-node-metrics is flakey

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#4609]
I've noticed a couple of times already that the test mentioned in subject fails randomly in PRs with unrelated changes. Here is the last instance of it

https://gitlab.parity.io/parity/polkadot/-/jobs/1308146#L1044

cc @sandreim

**Comment by sandreim** [comment]
Taking a look ... most likely 10s is not enough to author a block so the metric is never incremented and test fails.
