### ISSUE TITLE
zombienet smoke test is flakey

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#4626]
The CI test labelled zombienet-tests-parachains-smoke-test sometimes gives false negative. Here is one of the instances:

https://gitlab.parity.io/parity/polkadot/-/jobs/1309372#L166

@pepoviola

**Comment by pepoviola** [comment]
Hi @pepyakin, thanks for reporting. I'm also tracking this issue [here](https://github.com/paritytech/zombienet/issues/31).

I will try this setup with the latest release of `zombienet`.

Thx!

**Comment by ordian** [comment]
this particular failure might be due to outdated master (doesn't include https://github.com/paritytech/polkadot/blob/3490833b05d1ad97bd2bdaf9b66af72eb101bb32/.gitlab-ci.yml#L30)

**Comment by pepoviola** [comment]
Hi @pepyakin, I updated the `zombienet` in the `pr` branch and now test are green.

https://github.com/paritytech/polkadot/pull/4578/commits/8ebb613a248f25f925d423bba768cd132e15c0f3

Thanks!
