### ISSUE TITLE
Parachain collator trying to connect to wrong validator

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot#4630]
This might be related to #4617 

When a validator (clientv0.9.13, runtime 9140) is getting unassigned, some collators (which seem to be disconnected right after) are trying to connect back to the validator, getting the reputation down: `Declared as collator for unneeded para`

Here are the logs of the given validator:
[alphanet-validator1.log](https://github.com/paritytech/polkadot/files/7786640/alphanet-validator1.log)

(Check for the line `collator-protocol: Unassigned from a parachain para_id=Id(1000)`)

**Comment by crystalin** [comment]
I'm thinking this could also be (I haven't check the code) due to a retry, happening while the set of validator is changing. However this seems to last too long (checking the logs). It would have to be some kind of unbounded retries.

**Comment by ordian** [comment]
This issue is tracked in https://github.com/paritytech/polkadot/issues/4435.

**Comment by ordian** [comment]
@crystalin could you try #4640? it should fix the issue you're describing
