### ISSUE TITLE
Failed to parse transaction

### ISSUE THREAD

**Issue by 3461610003** [paritytech/polkadot#4634]
broadcast returns {"code":500,"error":"Failed to parse transaction.","transaction":"0x4db12a110df4010dc07fb81423a6cd6528cfdb6cf06379f1b1cfd283a6744746bad16ec9c09474d2aae129b944327fd9c08f68d9fd8d2ba40fc9e84fb2a1290a","cause":"Extrinsic: length less than remainder, expected at least 11349, found 64","stack":"Error: Extrinsic: length less than remainder, expected at least 11349, found 64\n at assert (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/util/assert.cjs:34:11)\n at Function._decodeU8a (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:254:22)\n at Function._decodeExtrinsic (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:235:31)\n at new GenericExtrinsic (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:205:38)\n at new Type (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/types/create/registry.cjs:464:16)\n at new Submittable (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/submittable/createClass.cjs:117:7)\n at ApiPromise._extrinsics (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/node_modules/@polkadot/api/submittable/createSubmittable.cjs:18:23)\n at TransactionSubmitService.submitTransaction (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/services/transaction/TransactionSubmitService.js:16:22)\n at TransactionSubmitController.txSubmit (/opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/controllers/transaction/TransactionSubmitController.js:40:41)\n at /opt/node/14.17.0/lib/node_modules/@substrate/api-sidecar/build/src/controllers/AbstractController.js:168:15"}

**Comment by bkchr** [comment]
please report in the appropriate repo.
