### ISSUE TITLE
Runtime debugging not possible due to missing RuntimeDebug implementations

### ISSUE THREAD

**Issue by hirschenberger** [paritytech/polkadot#4651]
I added `sp-debug-derive` with the `force-debug` feature as @al3mart suggested [here](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$16412030812550AMtvS:matrix.parity.io?via=matrix.parity.io&via=corepaper.org&via=matrix.org)

and removed the debug-when-std conditionals when I got an error of missing Debug implementations as @bkchr suggested.

I worked on a PR by removing some more conditionals but got stuck when structs from `finality-grandpa` got involved as it does not have a dependency on `sp_core` or `sp_debug_derive`

I'm not sure how to continue here, should I add that dependency to `finality-grandpa` also?

**Comment by bkchr** [comment]
Not sure, but I didn't run into any problems: https://github.com/paritytech/polkadot/pull/4652

**Comment by hirschenberger** [comment]
Maybe I did sth. wrong I added:

```
sp-debug-derive = { git = "https://github.com/paritytech/substrate", branch = "master", features = ["force-debug"] }
```
to `runtime/parachains/Cargo.toml` to enable using the log-macros for debugging an issue.

**Comment by bkchr** [comment]
Ahh I did not compile with the runtime benchmarks feature.

**Comment by bkchr** [comment]
My branch works for me with `runtime-benchmarks`

**Comment by hirschenberger** [comment]
Can you check: https://github.com/hirschenberger/polkadot/tree/issue-4651?

It's your branch with my changes on top.

It fails with:

```
    Compiling bp-header-chain v0.1.0 (/home/hirschen/devel/git/polkadot/bridges/primitives/header-chain)
  error[E0277]: `finality_grandpa::Commit<<Header as sp_runtime::traits::Header>::Hash, <Header as sp_runtime::traits::Header>::Number, sp_finality_grandpa::app::Signature, sp_finality_grandpa::app::Public>` doesn't implement `core::fmt::Debug`
    --> /home/hirschen/devel/git/polkadot/bridges/primitives/header-chain/src/justification.rs:38:26
     |
  38 | #[derive(Encode, Decode, RuntimeDebug, Clone, PartialEq, Eq, TypeInfo)]
     |                          ^^^^^^^^^^^^ `finality_grandpa::Commit<<Header as sp_runtime::traits::Header>::Hash, <Header as sp_runtime::traits::Header>::Number, sp_finality_grandpa::app::Signature, sp_finality_grandpa::app::Public>` cannot be formatted using `{:?}` because it doesn't implement `core::fmt::Debug`
 ```

**Comment by bkchr** [comment]
Yeah, I always only compiled `polkadot-runtime`. Using `rococo-runtime`, I get the same error.

**Comment by hirschenberger** [comment]
> Yeah, I always only compiled `polkadot-runtime`. Using `rococo-runtime`, I get the same error.

How do you build only one runtime? Searching for this for some time to reduce my turnaround time.

**Comment by bkchr** [comment]
I just build `cargo build --release -p polkadot-runtime`.
