### ISSUE TITLE
XCM: Add support for NFT AssetTransactor

### ISSUE THREAD

**Issue by NunoAlexandre** [paritytech/polkadot#4670]
@NukeManDan invited the opening of this issue after my query on whether there is support transferring NFTs through XCM. 

> NFT via XCM is not currently supported (no NFTAdapter or similar) and would need to be put on the roadmap

Fwiw, our first use case at Centrifuge is to be able to bridge NFTs from/to Statemint.

**Comment by gavofyork** [comment]
Yes indeed.
