### ISSUE TITLE
Implications of Using `AccountId::default()` as parent `AccountId` for Location-Conversion

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/polkadot#4687]
Given a note on the default behaviour of `AccountId32`

Quote:
> We recently discovered that anyone can sign transactions in Substrate with a zero account (AccountId::default()). The reason behind this is that cryptographically a private key of zero makes to an actual complete curve in sr25519 and ed255519. This is coming directly from schnorrkel.

Resolved for substrate via https://github.com/paritytech/substrate/pull/10403

Aren't the following lines a bit dangerous, given that many parachains will most likely plug in the normal `AccountId32` type there?

https://github.com/paritytech/polkadot/blob/5a7004f22b43e46e73ed36c87c9159283e025a56/xcm/xcm-builder/src/location_conversion.rs#L40-L59

**Comment by bkchr** [comment]
CC @KiChjang

**Comment by KiChjang** [comment]
Yeah, we should remove that, I guess this just wasn't done in the polkadot repo yet.
