### ISSUE TITLE
Validator attempting to peer with external nodes

### ISSUE THREAD

**Issue by jack-kearney** [paritytech/polkadot#469]
I have a validator node running in a private network without a publicly addressable network interface. I use the `--reserved-peers` flag to peer with publicly addressable sentry nodes. 

For awhile now I've observed my validator attempting to initiate connections to other external nodes. After bumping to `v0.6.2` and using the `--reserved-only` flag I expected the validator to stop attempting to initiate those connections but am still observing this behavior.

Any idea on why this might be happening?

**Comment by bkchr** [comment]
That is a duplicate of https://github.com/paritytech/substrate/issues/3721, so I close this here.
