### ISSUE TITLE
transaction-BUG:  Long time no block, transaction invalid & less the gas

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/polkadot#470]
When the Long time no block, I send DOTs, but other address didn't recived, and my balance is less the gas.

**Comment by chevdor** [comment]
@jiangfuyao was the sender maybe a validator ?

**Comment by jiangfuyao** [comment]
@chevdor No, is normal user.

**Comment by gavofyork** [comment]
Again, no idea what could have happened and impossible to investigate. If you can find a way to reproduce this "bug", please reopen.
