### ISSUE TITLE
Overseer, Collators and Full nodes

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#4708]
:bulb:  uh right - you do the validation regardless whether or not you find your key in `validators`, but are you sure full nodes don't run the overseer?

I believe checking for  `role.is_authority()` in [this line](https://github.com/paritytech/polkadot/blob/22e5c04008dd85ddd36c4af74e3bdcdb20bb0645/node/service/src/lib.rs#L735) would make sense - I don't see any code that disables the overseer if `is_authority()` is false, only [chain selection](https://github.com/paritytech/polkadot/blob/22e5c04008dd85ddd36c4af74e3bdcdb20bb0645/node/service/src/lib.rs#L737) is different. :thinking:

_Originally posted by @eskimor in https://github.com/paritytech/polkadot/pull/4685#discussion_r783400297_

**Comment by pepyakin** [comment]
@eskimor , I actually did not check that for a fact! I assumed that's the case, i.e. that only `--validator` enables overseer.

However, I must note that the reason why I introduced disabling the pvf-checker subsystem if the node is collator is because I already saw that collators are doing useless work by doing a job of a validator: doing either availability or approvals related work for example. Because PVF pre-checking is solely a validator job I opted in for the check. 

cc @drahnr

**Comment by burdges** [comment]
Yes, collators should never run parachain blocks from other parachains.

I do think eventually collators should observe relay chain finality, including knowing which validators do approval checks for their own ancestors and other parachains that send them messages.  We could do all this via some other interface, but doing so carries risk.  There are not decisions that need to be made right now of course.

**Comment by eskimor** [comment]
> However, I must note that the reason why I introduced disabling the pvf-checker subsystem if the node is collator is because I already saw that collators are doing useless work by doing a job of a validator: doing either availability or approvals related work for example. Because PVF pre-checking is solely a validator job I opted in for the check.

I meant check for role.is_authority() in addition to the check of not being a collator, not instead. so  only enable `!is_collator && !is_authority` ... might be overkill, but that's what I meant.   So the check would be stricter not less strict.

**Comment by drahnr** [comment]
The `overseer` runs for whatever fits the bill of `Role::Authority`.

**Comment by eskimor** [comment]
https://github.com/paritytech/polkadot/blob/22e5c04008dd85ddd36c4af74e3bdcdb20bb0645/node/service/src/lib.rs#L958 ... `maybe_params` will only be `Some` if we are in fact a validator and thus only then we will have an overseer handle and an overseer. Thanks @drahnr !
