### ISSUE TITLE
parity/polkadot in Docker Hub is not being updated since Dec 2, 2021

### ISSUE THREAD

**Issue by Rutrus** [paritytech/polkadot#4717]
I see many images being updated in [parity dockerhub](https://hub.docker.com/u/parity)

But [polkadot](https://hub.docker.com/r/parity/polkadot/tags) node is not being updated since 0.9.13

Should I change my source? Thanks.

**Comment by bkchr** [comment]
CC @chevdor

**Comment by Rutrus** [comment]
Thank you @bkchr. I would like to update to polkadot 0.9.15 as it  prepares for the next runtime upgrade.

**Comment by Rutrus** [comment]
Any update? I would like to update to polkadot 0.9.15 as it prepares for the next runtime upgrade.

**Comment by joe-bowman** [comment]
Another ping here.

**Comment by chevdor** [comment]
You can find the docker image on docker hub.
Please note that the tag is `v0.9.15-1`.

```
docker run --rm -it parity/polkadot:v0.9.15-1 --version 
```
