### ISSUE TITLE
validator BUG: Only can use a STRING a little shorter seed

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/polkadot#473]
Can't use the seed from the UI to be a validator key, it will be differently
![](http://p37d7w3w4.bkt.clouddn.com/UI%20address.png)
![](http://p37d7w3w4.bkt.clouddn.com/running--validator.png)

**Comment by jiangfuyao** [comment]
Use a STRING a little shorter seed. Then it will work.

**Comment by chevdor** [comment]
Dup #474
