### ISSUE TITLE
Check usage of `get_session_index()` and `request_session_index_for_child()`

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot#4733]
The fn `get_session_index()` takes a block hash as parameter and returns the session index of any of it children, rather than itself. Since the session index of the child and parent can differ this could lead to potential unwanted behaviour or errors. 

While most of the time we need the child session index for collating, backing, availability, etc, sometimes, for example in disputes-coordinator, we need the session index for a specific block rather than it's child. We need to ensure we haven't introduced any errors, rename and document things to point out the distinction.

**Comment by bkchr** [comment]
https://github.com/paritytech/polkadot/blob/master/node/network/dispute-distribution/src/sender/mod.rs#L194-L197

This is one of these places that needs to be fixed.
