### ISSUE TITLE
Update `AlwaysRelease` and `AlwaysLatest`

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#4734]
https://github.com/paritytech/polkadot/blob/dee0681cccc650d7b2ba5face7f15eb49bdc9b98/xcm/src/lib.rs#L438-L442

Now that v2 is stable and audited, I would assume that it should be the default for both `AlwaysRelease` and `AlwaysLatest`.

**Comment by KiChjang** [comment]
In v3, `AlwaysLatest` has been updated and `AlwaysRelease` is removed in favour of `AlwaysLts`.
