### ISSUE TITLE
apt repository missing v0.9.15-1

### ISSUE THREAD

**Issue by bert2002** [paritytech/polkadot#4738]
Hi, 
is there a change of plan for the deb repository or will it be updated soon with `v0.9.15-1` ? 

Thanks,
bert

**Comment by bkchr** [comment]
CC @chevdor

**Comment by chevdor** [comment]
@bert2002 there is no plan to change anything and the deb will be published asap, the issue is being worked on.

**Comment by gologo13** [comment]
any ETA to upload v0.9.15 or v0.9.15-1? It seems not published yet. thanks.

**Comment by chevdor** [comment]
You should be able to find and install 0.9.15-1 from the apt repo now.
