### ISSUE TITLE
Client(UnknownBlock("State already disca rded for Hash XXXXX)) 

### ISSUE THREAD

**Issue by freddieee** [paritytech/polkadot#477]
Hi, when I use RPC call  `state_getMetadata` to query the elder blocks, it cannot retrieve the metadata for those blocks, for example,

``
 u'error': {u'message': u'Unknown error occured', u'code': -32603, u'data': u'Client(UnknownBlock("State already discarded for Hash(0x3bdc554e8e9562f205c47ba4609c0604870258807faf80ab1d6ffc079760d8b0)"))'}}
``

is there any configuration that can make the node keeps those data?

**Comment by gavofyork** [comment]
yes: `--pruning=archive`. You'll need to resync from scratch, though.
