### ISSUE TITLE
Extract `MAX_FINALITY_LAG` constant from relay_chain_selection

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot#4788]
This is related to: https://github.com/paritytech/polkadot/pull/4752#discussion_r791975389
We are currently duplicating the `MAX_FINALITY_LAG` constant in dispute-coordinator and approval-voting. We should reuse the existing one. It is also worth noting that we plan to eventually get rid of this forced finality safety net mechanism.

**Comment by Doordashcon** [comment]
Hello @sandreim
Taking on this issue.

**Comment by tifecool** [comment]
I think this is solved.
