### ISSUE TITLE
ImOnline Slashing Not Working

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#479]
Followed these steps to test im-online slashing:

- Start a testnet
- Create controller & stash accounts for 6 validators
- Bond & signal intent to validate for each of these new validators
- Increase the validator count so that they become active validators
- Stop >1 of these new validators

With several of these offline, they should be slashed at the end of the session for which they missed a heartbeat. As in,
```
S1: send heartbeat
go offline
end S1
S2: miss heartbeat
end S2
```
At "End S2", there should be a slash, forced era change, and new election.

Once all 6 of the validators were alive and in the active set, allowed 1 session to pass and then turned 3 of the 6 offline. Another heartbeat wasn't required until several sessions into the next era. At this point, the 3 offline validators no longer have a green checkmark next to them (indicating the heartbeat was not received) but they still have not been removed from the active set and I do not believe a slashing event has occurred.

Modified the v0.6.2 client to:

- Enable transactions
- Change the block time to 1 second
- Change the session length

**Comment by kianenigma** [comment]
> Increase the validator count so that they become active validators
> Stop >1 of these new validators

Are you sure this is enough to make them a validator? I think you have to wait an era until next election. You should push a ForceNewEra with sudo in your test.

**Comment by gavofyork** [comment]
Fixed.
