### ISSUE TITLE
availability-distribution: fix active leaf processing at session boundaries

### ISSUE THREAD

**Issue by slumber** [paritytech/polkadot#4792]
As noticed by @eskimor 
> [Here](https://github.com/paritytech/polkadot/blob/b01fc015b2dae448d8b7ed8d7a928d0bf393297e/node/network/availability-distribution/src/requester/mod.rs#L216) we are not actually using the SessionInfo for the leaf, but the SessionInfo for the leaf's child. Therefore, at session boundaries we will look up the backing group in the wrong session. grimacing

([link](https://github.com/paritytech/polkadot/pull/4735#issuecomment-1017417395) to the comment)

This is not crucial since such candidates are unlikely to be included anyway, but it's best to keep the behavior consistent.
The actual session index for the activated leaf is obtained [here](https://github.com/paritytech/polkadot/blob/master/node/network/availability-distribution/src/requester/mod.rs#L284), so it's sufficient to extract it and refactor requester methods to have it as a parameter.

**Comment by eskimor** [comment]
Thanks @slumber !
