### ISSUE TITLE
Weight Trader Comment Incorrect

### ISSUE THREAD

**Issue by apopiak** [paritytech/polkadot#4815]
https://github.com/paritytech/polkadot/blob/55872676fae63399eb111a60ba27cb735cbaead6/xcm/xcm-builder/src/weight.rs#L241-L243

The doc comment seems incorrect, as the transaction payment pallet is not referenced in the implementation and would not fit into any of the configuration types for `UsingComponents`.

Maybe something like 
```Rust
/// Weight trader which uses the configured `WeightToFee` to set the right price for weight and then 
/// places any weight bought into the right account. 
```
Or depending on what was intended we need to look into how to actually integrate with the transaction payment system.

**Comment by daredevil3435** [comment]
I've corrected it. Please check  #6745 PR

**Comment by daredevil3435** [comment]
@apopiak please check #6745 PR

**Comment by apopiak** [comment]
but you closed the PR?

**Comment by apopiak** [comment]
> @apopiak please check #6745 PR

are you sure? the linked PR talks about something else

**Comment by daredevil3435** [comment]
> > @apopiak please check #6745 PR
> 
> 
> 
> are you sure? the linked PR talks about something else

Hey sorry about that I tagged wrong PR
