### ISSUE TITLE
Do not log seed in the logs

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#482]
![image](https://user-images.githubusercontent.com/738724/43583645-67fc6a3c-9660-11e8-9a09-1474bbc39482.png)

**Comment by chevdor** [comment]
cc @Tbaut since I put his photo here :)

**Comment by jiangfuyao** [comment]
@chevdor Yah, I send My logs, forgot there have seed. Regrettable ' _ '

**Comment by chevdor** [comment]
I sent my logs as well but I kinda expected that so I sent it privately :)

**Comment by chevdor** [comment]
The seed was adding manually to the log in the example above.
I did double check (text search) and the seed does not show up in the logs.
