### ISSUE TITLE
reserveTransferAssets does not work in Westend 0.9.16

### ISSUE THREAD

**Issue by girazoki** [paritytech/polkadot#4915]
the `reserveTransferAssets` in `xcmPallet` does not seem to work in Westend 0.9.16, failing with `UnweighableMessage` error. I tried `limitedReserveTransferAssets` and is working fine, so the reason seems to be the way the destination chain message is weighed locally (https://github.com/paritytech/polkadot/blob/41ab002d7451766324a9f314fee11c9c53314350/xcm/pallet-xcm/src/lib.rs#L801).

I think the issue is the `ReserveAssetDeposited`, which is set to be the maximum weight in Westend (https://github.com/paritytech/polkadot/blob/41ab002d7451766324a9f314fee11c9c53314350/runtime/westend/src/weights/xcm/mod.rs#L74), and makes the message non-weighable.

Is this intended behavior? I know we can use `limitedReserveTransferAssets` but I was just wondering whether this is something that was foreseen before

**Comment by bkchr** [comment]
CC @KiChjang

**Comment by KiChjang** [comment]
Well, on the comment right above `Weight::MAX`, it says that:

https://github.com/paritytech/polkadot/blob/41ab002d7451766324a9f314fee11c9c53314350/runtime/westend/src/weights/xcm/mod.rs#L73

So I'm guessing that plays a factor here?

**Comment by girazoki** [comment]
Yeah absolutely, but it was strange to me because `ReserveAssetDeposited` might be supported in the destination chain (and indeed it has to be if you want to do a `reserveTransferAsset`). Since that part of the function calculates the weight to be used in the destination chain using the local weigher, it was strange to me that it does not work anymore.

As I said wen can still used `limitedReserveTransferAssets`, which does not use the local weigher and therefore bypasses it. I was just wondering whether this was the intended behavior for `reserveTransferAssets` now

**Comment by KiChjang** [comment]
It does use the local weigher, as you can see from the code snippet below:

https://github.com/paritytech/polkadot/blob/8338c23a7d0ffe4f3a83c95437469a74bee0d558/xcm/pallet-xcm/src/lib.rs#L796-L812

But I did some digging and found out that perhaps really should support reserve asset deposits after all, so I'm going to create a PR and re-benchmark it to get some proper weights for it. Thanks for spotting this!

**Comment by KiChjang** [comment]
Oh, it looks like we don't even have a benchmark written for it at all! This will require some coding work.

**Comment by KiChjang** [comment]
@girazoki Note that it will still not work in westend, because it is not configured to recognize any chain as a trusted reserve (not even itself).

**Comment by girazoki** [comment]
No worries. Thank you so much for working on this!
