### ISSUE TITLE
derive Serialize and Deserialize for XCM primitives

### ISSUE THREAD

**Issue by MucTepDayH16** [paritytech/polkadot#4930]
It could be useful for XCM primitives, such as ```MultiLocation``` and ```MultiAsset```, to have ```Serialize``` and ```Deserialize``` impl. This will allow them to be stored in and to be loaded from genesis file.

**Comment by tifecool** [comment]
Hey.
I've been going through both substrate and polkadot for about a week now and would really love to contribute to the projects but don't know where to begin on understanding what's going on in the actual code.

I was hoping I could get a mentor step me through. Someone that would explain to me what were trying to achieve and it's function as I try to solve issues and understand the code at large if that's possible.

Thank you in advance ❤️
Links to onboarding information would be very helpful aswell!

**Comment by bkchr** [comment]
Hey @tifecool, this issue was actually already done with #5036
