### ISSUE TITLE
error: failed to run custom build command for librocksdb-sys v6.20.3

### ISSUE THREAD

**Issue by raojianli** [paritytech/polkadot#4942]
error: failed to run custom build command for `librocksdb-sys v6.20.3`

Caused by:
  process didn't exit successfully: `/home/gdmops/abel/Polkadex/target/release/build/librocksdb-sys-50d890a5c81053f6/build-script-build` (exit status: 127)
  --- stderr
  Inconsistency detected by ld.so: dl-open.c: 678: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: IO failure on output stream: No space left on device
error: build failed

rustc 1.55.0-nightly (e8cb1a4a5 2021-06-27)

os: centos7

**Comment by bkchr** [comment]
Please just read the error message before opening an issue

> LLVM ERROR: IO failure on output stream: No space left on device
