### ISSUE TITLE
Overseer: allow subsystems to instruct the overseer to send signals

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#4961]
We should create a new message from subsystems to the overseer which informs the overseer to send a specific signal. We might introduce a generic type parameter `SubsystemInitiatedSignal` which would allow us to prevent subsystems from sending signals such as `Conclude`, `ActiveLeavesUpdate`, or other stuff that they shouldn't.

cc @drahnr as the overseer expert

**Comment by rphmeier** [comment]
My gut instinct says that this can be done against master and not against the asynchronous backing feature branch, even though this is pre-requisite to async backing. `SubsystemInitiatedSignal` could be `enum Void {}` in `master`.

**Comment by drahnr** [comment]
https://github.com/paritytech/polkadot/blob/e721a5aaafb4c3bba11a51b28d16ed8a67f19504/node/overseer/overseer-gen/proc-macro/src/impl_overseer.rs#L130 should be enough, right?

**Comment by rphmeier** [comment]
> 1. do we require mpsc::Senders in those messages that we broadcast? Chances for cyclic dependencies that would not be detected by the planned cycle detection based on incoming/outgoing message types/variants.

No, I think they'd be pure data for any reasonable use-case. But I guess anything `Clone` can suffice.

> 2. what's the frequency of these?

Very frequent

> 3. what nature would those signals be, more events or more messages?

I don't understand the distinction really. specifically, stuff like the `ViableCandidateBase` from https://github.com/paritytech/polkadot/issues/4962 is the intended use-case.

> 4. what's the synchronicity requirement regarding active leaves between different subsystems?

The only requirement on signals and messaging is that a message sent after receipt of a signal on one subsystem may only be observed by another subsystem after the receipt of the same signal.

**Comment by drahnr** [comment]
No 3 was a fuzzy one, thanks for clarifying the rest!

**Comment by rphmeier** [comment]
Right now we have 

```rust
enum FromOverseer<M> {
    Signal(OverseerSignal),
    Communication { msg: M },
}
```

One way to achieve this would be to change the definition to 

```rust
enum FromOverseer<M, US> {
    Signal(OverseerSignal),
    UserSignal(US),
    Communication { msg: M },
}
```

and then have `trait Subsystem` gain an associated `type UserSignal` (which is usually `Void`).

and then have the overseer be generic over `US` where the subsystems are all bounded on `where US: From<Subsystem::UserSignal>`

**Comment by drahnr** [comment]
Of we go for the pull based retrieval, we can close this, or are there any remaining use cases?

**Comment by rphmeier** [comment]
There are possibly other use-cases but none in the near term

**Comment by drahnr** [comment]
Closing for now
