### ISSUE TITLE
Async Backing: Prospective Parachains Subsystem

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#4963]
The prospective parachains subsystem is responsible for tracking off-chain progress of parachain candidates and emulating the inclusion logic. 

The prospective parachains subsystem needs to be notified of all seconded fragments and all backed fragments. This will come from the candidate-backing subsystem.

It notifies all subsystems when there are new candidates that are backed and can reasonably be used as a base for further candidates. It accounts for a constant 'depth' limitation which defends against bad validator groups creating an unbounded stack of prospective candidates.

It answers requests from the provisioner about which candidates should be included in the next block when informed about anything that has become available with new bitfields.

**Comment by slumber** [comment]
Closed by #4913
