### ISSUE TITLE
Polkadot node with ParityDB has crashed after update to 0.9.17

### ISSUE THREAD

**Issue by husonghua** [paritytech/polkadot#4983]
Polkadot version: 0.9.17
My systemd:
```
[Unit]
Description=Polkadot Node

[Service]
User=polkadot
Group=polkadot
ExecStart=/usr/local/bin/polkadot \
        --in-peers 5 --out-peers 5 --max-parallel-downloads 2 \
        --validator \
  --rpc-methods=Unsafe \
    --unsafe-pruning \
  --pruning=1000 \
      --database paritydb-experimental \
    -lsync=warn,afg=warn,babe=warn \
  --name polkachu-polkadot-snapshot-paritydb \
  --chain=polkadot \
  --telemetry-url 'wss://telemetry-backend.w3f.community/submit/ 1'

Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
```

Crash log: 

```
2022-02-24 12:40:48 | polkadot.service: Failed with result 'exit-code'.
-- | --
  |   | 2022-02-24 12:40:48 | polkadot.service: Main process exited, code=exited, status=1/FAILURE
  |   | 2022-02-24 12:40:48 | https://github.com/paritytech/polkadot/issues/new
  |   | 2022-02-24 12:40:48 | This is a bug. Please report it at:
  |   | 2022-02-24 12:40:48 | Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x000016f0c2f4ee0abbfd8a88739684b7a26b53ae083a366927b3a7d8d831d332"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/27b8806/primitives/state-machine/src/ext.rs:189
  |   | 2022-02-24 12:40:48 | 43: clone
  |   | 2022-02-24 12:40:48 | 42: start_thread
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  |   | 2022-02-24 12:40:48 | std::sys::unix::thread::Thread::new::thread_start
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  |   | 2022-02-24 12:40:48 | <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  |   | 2022-02-24 12:40:48 | 41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  |   | 2022-02-24 12:40:48 | 40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  |   | 2022-02-24 12:40:48 | 39: std::sys_common::backtrace::__rust_begin_short_backtrace
  |   | 2022-02-24 12:40:48 | 38: tokio::runtime::task::raw::poll
  |   | 2022-02-24 12:40:48 | 37: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 36: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 32: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  |   | 2022-02-24 12:40:48 | 31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 30: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
  |   | 2022-02-24 12:40:48 | 29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  |   | 2022-02-24 12:40:48 | 28: <polkadot_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
  |   | 2022-02-24 12:40:48 | 27: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  |   | 2022-02-24 12:40:48 | 26: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  |   | 2022-02-24 12:40:48 | 25: sc_executor_common::wasm_runtime::WasmInstance::call_export
  |   | 2022-02-24 12:40:48 | 24: <sc_executor_wasmtime::runtime::WasmtimeInstance<H> as sc_executor_common::wasm_runtime::WasmInstance>::call
  |   | 2022-02-24 12:40:48 | 23: sc_executor_wasmtime::runtime::perform_call
  |   | 2022-02-24 12:40:48 | 22: wasmtime_setjmp
  |   | 2022-02-24 12:40:48 | 21: wasmtime_runtime::traphandlers::catch_traps::call_closure
  |   | 2022-02-24 12:40:48 | 20: <unknown>
  |   | 2022-02-24 12:40:48 | 19: <unknown>
  |   | 2022-02-24 12:40:48 | 18: <unknown>
  |   | 2022-02-24 12:40:48 | 17: <unknown>
  |   | 2022-02-24 12:40:48 | 16: <unknown>
  |   | 2022-02-24 12:40:48 | 15: <unknown>
  |   | 2022-02-24 12:40:48 | 14: <unknown>
  |   | 2022-02-24 12:40:48 | 13: <unknown>
  |   | 2022-02-24 12:40:48 | 12: <unknown>
  |   | 2022-02-24 12:40:48 | 11: <unknown>
  |   | 2022-02-24 12:40:48 | 10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  |   | 2022-02-24 12:40:48 | 9: sp_io::storage::ExtStorageGetVersion1::call
  |   | 2022-02-24 12:40:48 | 8: sp_io::storage::get_version_1
  |   | 2022-02-24 12:40:48 | 7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  |   | 2022-02-24 12:40:48 | 6: core::result::unwrap_failed
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  |   | 2022-02-24 12:40:48 | 5: core::panicking::panic_fmt
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  |   | 2022-02-24 12:40:48 | 4: rust_begin_unwind
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  |   | 2022-02-24 12:40:48 | 3: std::sys_common::backtrace::__rust_end_short_backtrace
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  |   | 2022-02-24 12:40:48 | 2: std::panicking::begin_panic_handler::{{closure}}
  |   | 2022-02-24 12:40:48 | at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  |   | 2022-02-24 12:40:48 | 1: std::panicking::rust_panic_with_hook
  |   | 2022-02-24 12:40:48 | 0: sp_panic_handler::set::{{closure}}
  |   | 2022-02-24 12:40:48 | Version: 0.9.17-de0ecd4760-x86_64-linux-gnu
```
This is the data backup https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_10000000.tar.lz4
This is the instruction of how to uncompress the file: https://polkachu.com/snapshots/polkadot/paritydb
The file is guaranteed to be available for 7 days or longer if requested.

Thanks

**Comment by bkchr** [comment]
CC @arkpar

**Comment by cheme** [comment]
For info, I did try syncing the snapshots with 0.9.17 at https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_10000000.tar.lz4, [polkadot_9163865.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_9163865.tar.lz4) is corrupted, [polkadot_9091874.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_9091874.tar.lz4) synch fine.

**Comment by husonghua** [comment]
@arkpar The pruning setting is 
```
  --rpc-methods=Unsafe \
    --unsafe-pruning \
  --pruning=1000 \
```
The full systemd has been posted earlier that includes all pruning settings. 

The snapshots were taken when the polkadot service was halted, so the database was not live. 

[polkadot_9091874.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_9091874.tar.lz4) was taken at height 9091874 and the polkadot version is 0.9.16. 
[polkadot_9163865.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_9163865.tar.lz4) was taken at height 9163865 and the polkadot version is 0.9.17. 
[polkadot_10000000.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_10000000.tar.lz4) was at an unknown height after height 9163865 and the polkadot version is 0.9.17.

**Comment by ggwpez** [comment]
Was already wondering why the Polkachu ParityDB snap was gone :sweat_smile:

**Comment by husonghua** [comment]
Haha. You can still access the polkadot parityDB snapshots through this absolute link: https://polkachu.com/snapshots/polkadot/paritydb. I just took the link off the website to avoid confusions.

**Comment by arkpar** [comment]
We've identified an issue which could have led to the DB corruption on write error. 
@husonghua perhaps there was an abnormal shutdown somewhere between 9091874 and 9163865? Like the node running out of disk space?

Thank you for providing the files. You can now restore the node from [polkadot_9091874.tar.lz4](https://substrate-snapshots.polkachu.xyz/polkadot_paritydb/polkadot_9091874.tar.lz4) or do a resync. It should continue working with 0.9.17

**Comment by husonghua** [comment]
No abnormal shutdown and the disk utilization was below 50% at all time on the node. 

The node is used for snapshot service. On a daily basis, it shuts down with "sudo service polkadot stop", takes the snapshot, and then "sudo service polkadot start".

**Comment by arkpar** [comment]
Do you have logs from that period (9091874 - 9163865) that you can share?

**Comment by husonghua** [comment]
It is a bit embarrassing, but I actually do not have know to find those logs. I use systemd to run polkadot binary and use journalctl to tail the logs in real time. Not sure where I can find the stored logs, not to mention how to carve out the period you mentioned. Give me some help, and I might be able to find it for you.

**Comment by arkpar** [comment]
The logs should be accessible with `journalctl`
`sudo journalctl -u polkadot.service > polkadot.log`

**Comment by husonghua** [comment]
You can download the log here: https://www.dropbox.com/s/kpmdxiu33e2ltnt/polkadot.log?dl=0

**Comment by husonghua** [comment]
Sorry for the delay. You am happy to provide ssh access. Please email hello@polkachu.com. I think that the easiest way is for me to add your SSH public key to the authorized_keys file on the server.

**Comment by arkpar** [comment]
Looks like a hardware or virtualisaton issue with the machine. CPU registers get zeroed sometime. The node is crashing in various seemingly impossible places. So does the rust compiler and other apps.

**Comment by ggwpez** [comment]
> The node is crashing in various seemingly impossible places. So does the rust compiler and other apps.

I had something like that for a year and was unable to find the cause.  
Turned out to be faulty ram, you may want to run a *memtest86*. Just a tip @husonghua

**Comment by husonghua** [comment]
Thanks for tip. I have definitely learned quite a lot about machine diagnostics through this Github issue. Thanks for spending the time. I will move this polkadot node to a new machine.

**Comment by gituser** [comment]
I have the same issue with v0.9.17. Polkadot seems to be crashing with OOM, even though there is 20GB memory provided for it out of the blue.

I guess I need to resync the DB as there might be some sort of a corruption.

* is there any way to fix the corruptions in the DB besides syncing from scratch?
* any way to change pruning settings after the DB was initialized?
