### ISSUE TITLE
custom type json file  need update

### ISSUE THREAD

**Issue by raojianli** [paritytech/polkadot#5034]
- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.
- Logs could be very helpful. If possible, submit the whole log. Please format it as ```code blocks```.
- Describe the role your node plays, e.g. validator, full node or light client.
- Any command-line options were passed?

**Comment by bkchr** [comment]
Custom types json is not used anymore and this is also the wrong place to report problems. Please open it in the polkadot-js repo and please write a proper issue which describes your problem.
