### ISSUE TITLE
Error "host doesn't provide such function: env:ext_trie_blake2_256_ordered_root_version_2"

### ISSUE THREAD

**Issue by clearest555** [paritytech/polkadot#5039]
I am running polkadot client on my machine with the following configuration.  
```
version:v0.9.13

--rpc-external
--chain=polkadot
--database=rocksdb
--pruning=150000
--rpc-port=9933
--sync=full
--rpc-cors=all
--detailed-log-output
--log=info
```

After the block with number 9280180 (the first block after [Democracy Referenda#53](https://polkadot.subscan.io/referenda/53)  executed), the polkadot client is unable to import the block. The error message at that time is as follows:   
```
WARN tokio-runtime-worker sc_service::client::client: Block prepare storage changes error:  
RuntimeApiError(Application(VersionInvalid("RuntimeConstruction(Other(\"host doesn't provide such function: env:ext_trie_blake2_256_ordered_root_version_2\"))")))  
WARN tokio-runtime-worker sync: 💔 Error importing block 0xf1f305ccf4c26234c0a5f8d981723df3cd5e98b65442c3450e74c839c4dbdb74: Err(Other(ClientImport("Import failed: Error at calling runtime api: Failed to get runtime version: RuntimeConstruction(Other(\"host doesn't provide such function: env:ext_trie_blake2_256_ordered_root_version_2\"))")))  
```

[v0.9.16](https://github.com/paritytech/polkadot/releases/tag/v0.9.16) release notes state the following: 
>> The runtimes in this release contain 2 new host functions.  
>> It is critical that you update your client before the chain switches to the new runtimes. If you do not update your client before the new runtime is enacted, your node will stop handling parachains functionalities properly until you upgrade.    

However, in my usage of the client, I assume that there is no problem even if parachains functionallities cannot be handled. In other words, I am aware that there is no problem without upgrading the client to 0.9.16.  

Is this error due to the polkadot client version 0.9.15? (i.e. Am I mistaken and need to handle parachains functionallities to import the block?)
Or could it be another bug?  
  
I would appreciate an answer asap.

**Comment by bkchr** [comment]
This is a new host function. This requires that you update your polkadot binary. So, please update and then it will work again.

**Comment by clearest555** [comment]
Thank you for your prompt reply! I'll try that.
