### ISSUE TITLE
Update collator-protocol for asynchronous backing

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5054]
If the runtime API version indicates that asynchronous backing is supported, we should handle more advertisements and second more candidates.

**Comment by rphmeier** [comment]
We'll need to make use of `GetHypotheticalDepths` from #4913 , as well as some new message type which tells us when new blocks are seconded or backed for a para. We should allow collators to make a few (up to `MAX_DEPTH`? announcements per relay-parent) and we'll ignore ones that we don't recognize.

We should only fetch & second collations that are built on top of the root of some fragment tree or have a parent which is backed. We could relax this somewhat to fetch & second collations that are built on top of a Seconded candidate which we've validated locally, but that'd be more complex and the 'backed' rule should work OK although it's not as efficient.

We also need to obey the rule that we only second 1 block per depth per relay-parent.

**Comment by eskimor** [comment]
> We should only fetch & second collations that are either built on top of the root of some fragment tree or have a parent which is backed. We could relax this somewhat to fetch & second collations that are built on top of a Seconded candidate which we've validated locally, but that'd be more complex and the 'backed' rule should work OK although it's not as efficient.

Because it just tripped me again: 'backed' in this context means we have seen enough votes to consider it backed - it is not yet backed on chain, otherwise the above would make little sense.

**Comment by rphmeier** [comment]
Yeah. I opened a follow-up for the optimiation of the fetching rule as well

**Comment by rphmeier** [comment]
related: #5923
