### ISSUE TITLE
Update collation-generation for asynchronous backing

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5056]
Once asynchronous backing is enabled, collation will be decoupled from the progress of the relay-chain. This subsystem should receive collations without pulling from  the collator. It should give the collator-side hints about what to build upon, but no more than that.

**Comment by bkchr** [comment]
These hints should be "pull based". Aka the collation logic will ask collation generation on what to build on. Do you have any idea what kind of logic would be used there? Before I thought that the collation logic should use the select chain logic of the relay chain and that should be enough?

**Comment by rphmeier** [comment]
> These hints should be "pull based". Aka the collation logic will ask collation generation on what to build on. Do you have any idea what kind of logic would be used there?

Authoring strategies will probably have to get a bit more intricate.

**Comment by bkchr** [comment]
> I have some ideas, but nothing that minimizes orphan blocks.

How do we get orphan blocks? Because we build on some "old" block that already has some other prospective blocks build on it?

**Comment by rphmeier** [comment]
Yeah. Forks, races, and skipped slots due to full backlog

**Comment by rphmeier** [comment]
@slumber any status update on this?
