### ISSUE TITLE
Update candidate-backing for asynchronous backing

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5057]
For asynchronous backing, the candidate-backing subsystem will have a few key changes. 

We need to notify the prospective-parachains subsystem about all new seconded candidates and backed candidates. We'll probably remove the concept of seconding two candidates under the same relay-parent being misbehavior (spam should be prevented on the network level - #5055).  

And we'll need to keep around statement tables until relay-parents go obsolete, not just inactive. More specifically, we should continue accepting candidates for relay-parents as long as any of the active leaves could consider that relay-parent to be relevant. See #4963

**Comment by rphmeier** [comment]
> And we'll need to keep around statement tables until relay-parents go obsolete, not just inactive. More specifically, we should continue accepting candidates for relay-parents as long as any of the active leaves could consider that relay-parent to be relevant.

This is addressed in #4963 now with a `GetMinimumRelayParent` message.

**Comment by rphmeier** [comment]
We'll also want #4259 at least partially done as a pre-requisite.

**Comment by slumber** [comment]
Closed by #5557
