### ISSUE TITLE
Collation request timeout too aggressive

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5061]
https://github.com/paritytech/polkadot/blob/c1a8115271ff5542bd3ec827d2791714b625417c/node/network/collator-protocol/src/validator_side/mod.rs#L87

We get quite a lot of logs in practice on Kusama validators and on testnet validators that indicate this timeout is being reached. There are two issues; this timeout is possibly too aggressive and our network stack is not transmitting data very quickly. This is likely related to #4911

**Comment by rphmeier** [comment]
cc @eskimor

**Comment by eskimor** [comment]
I am assuming you are referring to this log message:

```
Timeout hit - already seconded?
```

This only means that we would start fetching an alternative collation, if there was any - which will never be the case with Aura. But indeed, I am seeing:

```
Successfully dequeued next advertisement - fetching ...
```

and lots of those on a [single validator in just one second](https://grafana.parity-mgmt.parity.io/goto/6b6DEwYnz?orgId=1). This seems weird.

**Comment by rphmeier** [comment]
Yeah, that's what I'm referring to. The timeout doesn't necessarily indicate that there's another announcement, does there?

**Comment by eskimor** [comment]
> Yeah, that's what I'm referring to. The timeout doesn't necessarily indicate that there's another announcement, does there?

Exactly, if you see the timeout message, all that means is that `MAX_UNSHARED_DOWNLOAD_TIME` has passed since the last fetch was started and we therefore check whether a collation for this para and relay parent has already been seconded and if not another advertisement (if any is available) will be dequeued for fetch.
