### ISSUE TITLE
Collators don't clear connection requests until they produce another collation

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5062]
https://github.com/paritytech/polkadot/blob/c1a8115271ff5542bd3ec827d2791714b625417c/node/network/collator-protocol/src/collator_side/mod.rs#L518-L533

is only invoked here, after a collation has been sent to the collator-protocol subsystem

https://github.com/paritytech/polkadot/blob/c1a8115271ff5542bd3ec827d2791714b625417c/node/network/collator-protocol/src/collator_side/mod.rs#L392-L404

If there is no collation for some time, an outdated connection request will remain in-memory.

**Comment by slumber** [comment]
Better to sync it with https://github.com/paritytech/polkadot/pull/5226 since it changes the connection logic
