### ISSUE TITLE
StatementDistributionMessage::get_metadata is a footgun and should be removed

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5072]
https://github.com/paritytech/polkadot/blob/88d66ac669c5f9c5d82651ff70fda9691f4e0ece/node/network/protocol/src/lib.rs#L336-L344

The metadata it returns will be the same for `Valid` and `Seconded` statements. This is a footgun, because it's not obviously broken.

It's only used in tests now, so it would be best to remove it and update the tests to construct the metadata manually.

**Comment by Doordashcon** [comment]
Believe this has been addressed :)
