### ISSUE TITLE
My parallel chain encountered an error while synchronizing the block information of the relay chain and stopped updating the block information of the relay chain.

### ISSUE THREAD

**Issue by 99Kies** [paritytech/polkadot#5111]
network: rococo live
parachain release version: polkadot-v0.9.17

![image](https://user-images.githubusercontent.com/45918704/158242464-30121ba7-c6ce-4466-a3c0-9a5a08a36b10.png)

**Comment by bkchr** [comment]
Rococo was just reset. Find the newest chain spec here: https://github.com/paritytech/polkadot/pull/5113

**Comment by 99Kies** [comment]
why is too slow?
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/45918704/158310572-16711e39-fb84-4fe5-8ace-3a0f3cf5c371.png">
