### ISSUE TITLE
Histogram tracking the amount of time inter-subsystem messages are in-flight

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#5134]
We can randomly sample something like 1% of messages to attach a timer to the `MessagePacket` here: https://github.com/paritytech/polkadot/blob/a3908d2b41a0d909ce132bd04146b02730aa3841/node/overseer/overseer-gen/src/lib.rs#L170

The challenge is that the overseer-gen macros know nothing about prometheus.

**Comment by drahnr** [comment]
And that is intended, only the channels have a `fn meter()` that provides a `ReadOut` of all the channels.

**Comment by drahnr** [comment]
#5135 solves this, we could consider measuring reaponse oneshots systematically (see #5191 )
