### ISSUE TITLE
Update inflation model to model with parachains

### ISSUE THREAD

**Issue by jonasW3F** [paritytech/polkadot#5195]
The ideal staking rate in the inflation model of Polkadot is still hardcoded to be 75% [here](https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L523). On Kusama there is already a more advanced mechanism that scales with the number of parachains and it is probably time to update Polkadot to that model.

**Comment by jonasW3F** [comment]
Any updates here @kianenigma ?

**Comment by paradox-tt** [comment]
I was about to ask why we haven't applied the new model to Polkadot.
