### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/polkadot#520]
There is a small bug in the documentation. In 3.2. Local Two-node Testnet, the commands should be `./polkadot --chain=local --alice -d /tmp/alice` and `./polkadot --chain=local --bob -d /tmp/bob --port 30334 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/ALICE_BOOTNODE_ID_HERE` since the option `--key` is not recognized

**Comment by SCaptainCAP** [comment]
Also if you run the node with `-h` flag you will see the next line:
> --ws-port <PORT>                             Specify WebSockets RPC server TCP port.
But if you want to specify the WebSocket port you should use the `--port` flag

**Comment by rphmeier** [comment]
oudated
