### ISSUE TITLE
Whitelist XCM Storage Read Each block from Benchmarking

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#5203]
For example:

```rust
// Storage: XcmPallet SupportedVersion (r:1 w:0)
// Storage: XcmPallet VersionDiscoveryQueue (r:1 w:1)
// Storage: XcmPallet SafeXcmVersion (r:1 w:0)
// Storage: Configuration ActiveConfig (r:1 w:0)
```

All of these storage items are read each block, and thus do not also need to be included into the main benchmark weights.

See: https://github.com/paritytech/polkadot/pull/4442

**Comment by KiChjang** [comment]
I think https://github.com/paritytech/polkadot/pull/4442/commits/a7a5387a6720bebe7b336358ee2891654016f61f addresses this.

**Comment by KiChjang** [comment]
Actually, I didn't add the XCM pallet's storage items, as I wasn't sure if they're really read each block.

**Comment by shawntabrizi** [comment]
I think the assumption is that you should expect at least one XCM message present each Polkadot block, so yeah, all of them would be whitelisted.

But would be best we actually design this whitelisting in the FRAME macros.

**Comment by franciscoaguirre** [comment]
This was fixed in https://github.com/paritytech/polkadot/pull/6871
