### ISSUE TITLE
Way not integrate Sandbox Hostfunction for parachain in Polkadot?

### ISSUE THREAD

**Issue by atenjin** [paritytech/polkadot#5223]
Currently, Polkadot runs parachain with following hostfuncion:
```bash
type HostFunctions = (
	sp_io::misc::HostFunctions,
	sp_io::crypto::HostFunctions,
	sp_io::hashing::HostFunctions,
	sp_io::allocator::HostFunctions,
	sp_io::logging::HostFunctions,
	sp_io::trie::HostFunctions,
);
```

But some parachain will run a wasm binary in runtime, like pallet-contracts module, gear(https://github.com/gear-tech/gear), or some parachain will become a layer1 to verify the runtime code in a layer2. They all need the Sandbox Hostfunction to run the wasm binary in `wasmer`, otherwise they just can run the wasm code in a integrated `wasmi,` which is running slow then `wasmer`.

I search all issues like:
https://github.com/paritytech/polkadot/issues/99
https://github.com/paritytech/polkadot/issues/1269 
https://github.com/paritytech/polkadot/issues/4721

But have not see more reason for this.

So can you guys add the Sandbox Hostfunction in future? And they any reasons why you do not wanna do this?
I think this Hostfunction can provide a more imaginative way for parachain to do more thing.

**Comment by bkchr** [comment]
Sandbox host functions are not yet stable. The problem is that if they are ever added, then they need to be supported until the end of the universe.

Cc @pepyakin

**Comment by mrcnski** [comment]
@eskimor What is a sandbox host function? Is this related to PVF hardening? Can we triage this issue or close if not relevant?

**Comment by burdges** [comment]
I think stable sandboxing looks far off..

**Comment by bkchr** [comment]
Not relevant.
