### ISSUE TITLE
Why does the balance increase or decrease in the event of an Initialization phase?

### ISSUE THREAD

**Issue by mone-d** [paritytech/polkadot#5245]
I understand that balance changes are recorded on transfer and withdraw events.
I thought that event is triggered by Extrinsics and the ApplyExtrinsics is recorded in Phase.
However, I recently discovered an event that does not have an ApplyExtrinsics and has an Initialization in phase.
When does such an event without ApplyExtrinsics occur?

This is the event details.
https://polkadot.subscan.io/extrinsic/9676800-0?tab=event

**Comment by bkchr** [comment]
As you see there, the spending period of the treasury ended and some payouts happened. These payouts triggered these balance events.

**Comment by mone-d** [comment]
Thank you for your response.
