### ISSUE TITLE
Validator shuts down with "subsystem exited with error subsystem" while validating. 

### ISSUE THREAD

**Issue by lx38** [paritytech/polkadot#5250]
It happened twice already in datacenter Equinix. It just error out suddenly and stops responding. If you need copy of database let me know. 

My guess now is that it has something to do with Hardware, as I have another 2 validators running in different datacenters on 0.9.17 w/o any issues so far. 

The second guess is that using 'paritydb' can cause issues, but on 0.9.18 its not anymore expiremental. 

Validator downloaded blockchain fresh, no polkashots used. 

It stays up for 12h or so and then errors out.

I've now migrated back to previous datacenter and try running 0.9.18+paritydb there and see if any issues. 

-------

- It would help if you submit info about the system you are running, e.g.: operating system, kernel version, amount of available memory and swap, etc.

Hardware: 
PROC2 x Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz     RAM384GB   

Free space 11GB

Validator ver 0.9.18

Swap free:       2GB            

- Describe the role your node plays, e.g. validator, full node or light client.
Active Validator. 

- Any command-line options were passed?
```
/usr/bin/polkadot --validator \
                            --base-path /home/polkadot \
                            --chain polkadot \
                            --name [cut] \ 
                            --listen-addr /ip4/[strip]/tcp/11111 \
                            --ws-port 22222 \
                            --rpc-port 33333 \
                            --no-prometheus \
                            --no-mdns \
                            --database paritydb --unsafe-pruning --pruning 1000 \
                            --no-telemetry \
                            --in-peers 50 --out-peers 50 --max-parallel-downloads 7

Apr 02 19:43:54 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:43:54 ♻️  Reorg on #9702508,0xa117…d088 to #9702508,0x0c19…5278, common ancestor #9702507,0xcea6…133b
Apr 02 19:43:54 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:43:54 ✨ Imported #9702508 (0x0c19…5278)
Apr 02 19:43:57 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:43:57 💤 Idle (100 peers), best: #9702508 (0x0c19…5278), finalized #9702505 (0xf3eb…f10f), ⬇ 816.7kiB/s ⬆ 1.1MiB/s
Apr 02 19:44:00 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:00 ✨ Imported #9702509 (0xd0c9…e510)
Apr 02 19:44:02 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:02 💤 Idle (100 peers), best: #9702509 (0xd0c9…e510), finalized #9702506 (0x4df3…a1e5), ⬇ 368.6kiB/s ⬆ 417.1kiB/s
Apr 02 19:44:06 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:06 ✨ Imported #9702510 (0xb2a8…7e6b)
Apr 02 19:44:06 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:06 ✨ Imported #9702510 (0x6c82…4be3)
Apr 02 19:44:07 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:07 💤 Idle (100 peers), best: #9702510 (0xb2a8…7e6b), finalized #9702506 (0x4df3…a1e5), ⬇ 515.2kiB/s ⬆ 434.4kiB/s
Apr 02 19:44:12 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:12 ✨ Imported #9702511 (0x5776…682b)
Apr 02 19:44:12 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:12 💤 Idle (100 peers), best: #9702511 (0x5776…682b), finalized #9702507 (0xcea6…133b), ⬇ 641.6kiB/s ⬆ 509.8kiB/s
Apr 02 19:44:17 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:17 💤 Idle (100 peers), best: #9702511 (0x5776…682b), finalized #9702509 (0xd0c9…e510), ⬇ 676.0kiB/s ⬆ 309.8kiB/s
Apr 02 19:44:18 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:18 ✨ Imported #9702512 (0x6f46…f524)
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 Subsystem approval-voting-subsystem appears unresponsive. origin=polkadot_service::relay_chain_selection::SelectRelayChainInner<sc_client_db::Backend<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32, sp_runtime::traits::BlakeTwo256>, sp_>
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="candidate-validation-subsystem" err=FromOrigin { origin: "candidate-validation", source: Generated(Context("Signal channel is terminated and empty.")) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 error receiving message from subsystem context for job job="candidate-backing-job" err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="availability-distribution-subsystem" err=FromOrigin { origin: "availability-distribution", source: IncomingMessageChannel(Generated(Context("Signal channel is terminated and empty."))) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 error receiving message from subsystem context for job job="bitfield-signing-job" err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 error receiving message from subsystem context for job job="provisioner-job" err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="availability-recovery-subsystem" err=FromOrigin { origin: "availability-recovery", source: Generated(Context("Signal channel is terminated and empty.")) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 error receiving message from subsystem context: Generated(Context("Signal channel is terminated and empty.")) err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 Shutting down Network Bridge due to error err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="chain-api-subsystem" err=FromOrigin { origin: "chain-api", source: Generated(Context("Signal channel is terminated and empty.")) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="network-bridge-subsystem" err=FromOrigin { origin: "network-bridge", source: Context("Received SubsystemError from overseer: Generated(Context(\"Signal channel is terminated and empty.\"))") }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="dispute-distribution-subsystem" err=FromOrigin { origin: "dispute-distribution", source: SubsystemReceive(Generated(Context("Signal channel is terminated and empty."))) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="statement-distribution-subsystem" err=FromOrigin { origin: "statement-distribution", source: SubsystemReceive(Generated(Context("Signal channel is terminated and empty."))) }
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 Encountered error finding best chain containing 0x0c1927656daa311bc794b14126f1187d4099b8fabbd9b18a46eaef798c6a5278: Request approved ancestor from approval voting got canceled
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 Could not cast prevote: previously known block 0x0c1927656daa311bc794b14126f1187d4099b8fabbd9b18a46eaef798c6a5278 has disappeared
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 subsystem exited with error subsystem="runtime-api-subsystem" err=Generated(Context("Signal channel is terminated and empty."))
Apr 02 19:44:20 polka-fr-01 polkadot-chf[125834]: 2022-04-02 19:44:20 Essential task `overseer` failed. Shutting down service.
```

**Comment by bkchr** [comment]
CC @drahnr

**Comment by lx38** [comment]
Do I need to run polkadot binary with some flags in order to obtain
stack trace?

On April 4, 2022, GitHub ***@***.***> wrote:
> If it happens again please get a stack trace. You can get one either
> with gdb
>
> gdb --batch --quiet -ex "thread apply all bt full" -p <pid>
> or eu-stack
>
> sudo apt install elfutils eu-stack -id -p <pid>

—
Reply to this email directly, view it on GitHub
<https://github.com/paritytech/polkadot/issues/5250#issuecomment-
1087666181>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ADACMVUKXQFDRJKLWROFORTVDL7XJANCNFSM5SPU73VA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by arkpar** [comment]
> Do I need to run polkadot binary with some flags in order to obtain
stack trace? 

No

**Comment by lx38** [comment]
The node failed again. Attaching tail of logs, and eu-stack report. after this logs node does not produce any logs anymore .. 

[logs.zip](https://github.com/paritytech/polkadot/files/8417098/logs.zip)

**Comment by drahnr** [comment]
CC @eskimor could you take a look, this _could_ be related to the pre-refactoring disputes coordinator

**Comment by lx38** [comment]
Sorry early report. 

The node hangs for a while producing no logs, then it round robin again producing the same output and then stalls again producing nothing for 10-20 sec. 

Take a look at the updated tail.

[update.zip](https://github.com/paritytech/polkadot/files/8417176/update.zip)

**Comment by eskimor** [comment]
> CC @eskimor could you take a look, this _could_ be related to the pre-refactoring disputes coordinator

It actually can not. As far as I understand, this is happening on Polkadot. `dispute-coordinator` is not yet active there.

**Comment by lx38** [comment]
> It actually can not. As far as I understand, this is happening on Polkadot. `dispute-coordinator` is not yet active there.

well its polkadot, but I still see this error, so someway or another dispute coordinator has problems)

Apr 05 10:16:38 polka-fr-01 polkadot-chf[1491583]: 2022-04-05 10:16:38.145 DEBUG tokio-runtime-worker parachain::candidate-backing: Dispute coordinator confirmation lost

**Comment by eskimor** [comment]
That message actually just confirms that it is not running :-) My initial reaction would be: We should try without `paritydb` to narrow it down some more.

**Comment by drahnr** [comment]
> > CC @eskimor could you take a look, this _could_ be related to the pre-refactoring disputes coordinator
> 
> It actually can not. As far as I understand, this is happening on Polkadot. `dispute-coordinator` is not yet active there.

Mea culpa. The issue is _rooted_ in backing, and I think it's again the outgoing confirmations that might lock up due to the gossip output. We'd need more metrics for this, but those got only introduced post 0.9.18 which would shed some good light if that's the solution for the delays ( https://github.com/paritytech/polkadot/pull/5135 ). It's tracked as https://github.com/paritytech/polkadot/issues/4911 

I am not convinced this is the same issue as initially reported.

**Comment by arkpar** [comment]
The stack trace is not that useful unfortunately, as the binary was built with no debugging symbols. @lx38 where did you get the binary from? Could you try using one at https://github.com/paritytech/polkadot/releases/download/v0.9.18/polkadot ?

**Comment by lx38** [comment]
Shall I launch w/o paritydb ? I guess issue might go away, will that help narrow it down or you consider its not important? If not importan I switch to rocks and continue with rocks from now on

**Comment by arkpar** [comment]
If the issue is indeed database related it would help a lot if we catch it. So I suggest leaving paridydb on until we can rule it out.

**Comment by lx38** [comment]
So do you want me to download 0.9.18 with debug symbols to rerun and wait for the same to happen ? (I use one from deb apt repo)

**Comment by drahnr** [comment]
> So do you want me to download 0.9.18 with debug symbols to rerun and wait for the same to happen ? (I use one from deb apt repo)

Yes please. If you can, please collect relevant metrics as well. This could be very helpful

**Comment by lx38** [comment]
To be clear : Which metrics you want me to collect?)

**Comment by lx38** [comment]
New updates. 

On old datacenter hardware I faced the same issue today with combination of paritydb+0.9.18 . So now I believe that its paritydb issue.

**Comment by drahnr** [comment]
Could you provide the backtrace?

Regarding metrics, there is the default dashboard in the repo, a screenshot of that or anything in there that seems out of the ordinary would help.

**Comment by lx38** [comment]
Rerun with rocksdb and see if that would repeat.

**Comment by lx38** [comment]
I do not use prometheus/grafana so those dashboards are no use for me. I
use other provider and had seen no benefits to setup the /monitoring for
the node , as those grafs do not help validator much :) So I can't help
there., 

As for backtrace I can't provide as it was production validator
currently in the active para/set and I had to quickly restart it not to
get slashed/and continue earning points.

As of now I can't help with more data.

But you can easily reproduce it on your end, just try to launch fresh
validator with AUTHORITY flag on (but no need to be actually validating)
with 'paritydb', let it download the chain and wait.  it will halt in 1-
2 days. 

Igor

On April 6, 2022, GitHub ***@***.***> wrote:
> Could you provide the backtrace?
>
> Regarding metrics, there is the default dashboard in the repo, a
> screenshot of that or anything in there that seems out of the ordinary
> would help.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/paritytech/polkadot/issues/5250#issuecomment-
1089923132>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ADACMVV2MRBBKIFACT5JHNTVDU4WLANCNFSM5SPU73VA>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by lx38** [comment]
Quick update. with RocksDB running fine.

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by drahnr** [comment]
The misleading termination error is tracked in #5318 . Without backtraces of the crash with either the precise version / hash it was built from or with full symbol tables, I am afraid there is nothing left that we can do.

**Comment by lx38** [comment]
It was installed from default repo via APT on Ubuntu...so far everything running fine on 0.9.18/rocksdb and 0.9.17/paritydb-experemental. no crashes so far.
