### ISSUE TITLE
Collator protocol: issue a connection request prior to distributing the collation

### ISSUE THREAD

**Issue by slumber** [paritytech/polkadot#5255]
Collator protocol only connects to validators assigned to core when the collation gets [distributed](https://github.com/paritytech/polkadot/blob/master/node/network/collator-protocol/src/collator_side/mod.rs#L354-L361).

This can be improved if we extract the "connect to our validators" into a new type of message. Prior to producing a collation a collator would send a `Connect` request to `collator-protocol`, this subsystem in turn figures out the group and issues connection requests, by the time a collator wants to distribute a collation, the connection should be already established

There're 2 approaches to do this: one is to figure out whether we're collating in `collation-generation` and send `Connect` right from there, or just send it from cumulus.
The first approach still requires some changes to cumulus because there's no way to discover whether it's collator's turn or not using the `CollatorFn`.

**Comment by slumber** [comment]
cc @bkchr

**Comment by bkchr** [comment]
I would change `CollatorFn` to a trait and there you have two methods `produce_pov(relay_block)` and `should_preconnect(current_best_relay_block)` (these names are shit, but hopefully help to understand). Then the changes in Cumulus should be relative straight forward.

While `should_preconnect` should probably after we have called `produce_pov`.

**Comment by rphmeier** [comment]
> While should_preconnect should probably after we have called produce_pov.

I would expect it to be called before. But the trait approach seems right overall.

**Comment by bkchr** [comment]
My idea is that when you call `produce_pov` you will let the collator build block X and then when you call `should_preconnect` you ask if the collator also builds block `X + 1` and thus, needs to be connected. While asking to build block X can return `None`, `should_preconnect` could return `true`.

**Comment by eskimor** [comment]
@slumber What @bkchr is suggesting is precisely the behavior we suggested in https://github.com/paritytech/polkadot/issues/4381 and discussed in chat, the reason for the "inverted" order is that the connect would already be for the next block (so the order does not matter _that_ much).

So we ask: "Got collation?" -no? ok, well, but want to get connected for the next block already?

@bkchr The idea by @slumber is to not necessarily `pre-connect` on the previous block already, but just before asking for the collation, so we can issue connection requests while the collator is still preparing the collation. This would be slightly simpler than pre-connecting on the previous block, so might be a good first step.  From your perspective, would it make any sense? Or in other terms would this allow us to issue connection requests significantly earlier? In my understanding this might gain us half a second advantage.

**Comment by eskimor** [comment]
Interface wise, if cumulus returns `true` for the `should_preconnect` call for both the previous block and the block it is going to provide the collation on, then cumulus would stay unaffected of the actual implementation and @slumber can start with what is the easiest and extend afterwards.

Only downside is, that we would stay connected a few seconds longer than necessary and occasionally connect to a validator group without actually providing a collation. Both seem fine for the time being.

**Comment by bkchr** [comment]
> From your perspective, would it make any sense? Or in other terms would this allow us to issue connection requests significantly earlier? In my understanding this might gain us half a second advantage.

I mean we can do this. Should work as well. However, be aware that you only get half a second if there parachain block is completely full. For empty blocks you only get some milliseconds, but then you probably have enough time anyway.

**Comment by eskimor** [comment]
Closing, this will be subsumed by another ticket soon.
