### ISSUE TITLE
crashed every minute  after update to 0.6.6

### ISSUE THREAD

**Issue by liangping** [paritytech/polkadot#532]
ov  4 15:58:50 localhost polkadot[27395]: 2019-11-04 15:58:50 Libp2p => Query for [18, 32, 123, 123, 111, 217, 39, 251, 218, 193, 107, 52, 27, 66, 253, 40, 158, 140, 160, 138, 199, 51, 78, 178, 230, 115, 228, 167, 218, 252, 152, 119, 9, 208] timed out with 20 results
Nov  4 15:58:53 localhost polkadot[27395]: ====================
Nov  4 15:58:53 localhost polkadot[27395]: Version: 0.6.6-ccd1c6eb-x86_64-linux-gnu
Nov  4 15:58:53 localhost polkadot[27395]: stack backtrace:
Nov  4 15:58:53 localhost polkadot[27395]:    0: substrate_panic_handler::panic_hook
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/panic-handler/src/lib.rs:148
Nov  4 15:58:53 localhost polkadot[27395]:    1: substrate_panic_handler::set::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/panic-handler/src/lib.rs:58
Nov  4 15:58:53 localhost polkadot[27395]:    2: std::panicking::rust_panic_with_hook
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libstd/panicking.rs:481
Nov  4 15:58:53 localhost polkadot[27395]:    3: std::panicking::continue_panic_fmt
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libstd/panicking.rs:384
Nov  4 15:58:53 localhost polkadot[27395]:    4: rust_begin_unwind
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libstd/panicking.rs:311
Nov  4 15:58:53 localhost polkadot[27395]:    5: core::panicking::panic_fmt
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libcore/panicking.rs:85
Nov  4 15:58:53 localhost polkadot[27395]:    6: core::panicking::panic
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libcore/panicking.rs:49
Nov  4 15:58:53 localhost polkadot[27395]:    7: <u32 as core::ops::arith::Sub>::sub
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/arith.rs:198
Nov  4 15:58:53 localhost polkadot[27395]:    8: substrate_network::protocol::sync::fork_sync_request
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/network/src/protocol/sync.rs:1290
Nov  4 15:58:53 localhost polkadot[27395]:    9: substrate_network::protocol::sync::ChainSync<B>::block_requests::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/network/src/protocol/sync.rs:583
Nov  4 15:58:53 localhost polkadot[27395]:   10: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:859
Nov  4 15:58:53 localhost polkadot[27395]:   11: core::iter::traits::iterator::Iterator::try_fold
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1671
Nov  4 15:58:53 localhost polkadot[27395]:   12: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:859
Nov  4 15:58:53 localhost polkadot[27395]:   13: core::iter::traits::iterator::Iterator::try_for_each
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1708
Nov  4 15:58:53 localhost polkadot[27395]:   14: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:845
Nov  4 15:58:53 localhost polkadot[27395]:   15: <either::Either<L,R> as core::iter::traits::iterator::Iterator>::next
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/either-1.5.3/src/lib.rs:643
Nov  4 15:58:53 localhost polkadot[27395]:   16: <substrate_network::protocol::Protocol<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/network/src/protocol.rs:1662
Nov  4 15:58:53 localhost polkadot[27395]:   17: <substrate_network::behaviour::Behaviour<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/network/src/behaviour.rs:35
Nov  4 15:58:53 localhost polkadot[27395]:   18: <libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo> as futures::stream::Stream>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.2.0/src/lib.rs:426
Nov  4 15:58:53 localhost polkadot[27395]:   19: <substrate_network::service::NetworkWorker<B,S,H> as futures::stream::Stream>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/network/src/service.rs:716
Nov  4 15:58:53 localhost polkadot[27395]:   20: substrate_service::build_network_future::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/git/checkouts/substrate-7e08433d4c370a21/595f18e/core/service/src/lib.rs:442
Nov  4 15:58:53 localhost polkadot[27395]:   21: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/poll_fn.rs:43
Nov  4 15:58:53 localhost polkadot[27395]:   22: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map_err.rs:30
Nov  4 15:58:53 localhost polkadot[27395]:   23: <futures::future::select::Select<A,B> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/select.rs:48
Nov  4 15:58:53 localhost polkadot[27395]:   24: futures::future::chain::Chain<A,B,C>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
Nov  4 15:58:53 localhost polkadot[27395]:   25: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
Nov  4 15:58:53 localhost polkadot[27395]:   26: <alloc::boxed::Box<F> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
Nov  4 15:58:53 localhost polkadot[27395]:   27: <alloc::boxed::Box<F> as futures::future::Future>::poll
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
Nov  4 15:58:53 localhost polkadot[27395]:   28: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
Nov  4 15:58:53 localhost polkadot[27395]:   29: futures::task_impl::Spawn<T>::enter::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
Nov  4 15:58:53 localhost polkadot[27395]:   30: futures::task_impl::std::set
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
Nov  4 15:58:53 localhost polkadot[27395]:   31: futures::task_impl::Spawn<T>::enter
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
Nov  4 15:58:53 localhost polkadot[27395]:   32: futures::task_impl::Spawn<T>::poll_fn_notify
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
Nov  4 15:58:53 localhost polkadot[27395]:   33: futures::task_impl::Spawn<T>::poll_future_notify
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
Nov  4 15:58:53 localhost polkadot[27395]:   34: tokio_threadpool::task::Task::run::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:145
Nov  4 15:58:53 localhost polkadot[27395]:   35: core::ops::function::FnOnce::call_once
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
Nov  4 15:58:53 localhost polkadot[27395]:   36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:315
Nov  4 15:58:53 localhost polkadot[27395]:   37: std::panicking::try::do_call
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
Nov  4 15:58:53 localhost polkadot[27395]:   38: __rust_maybe_catch_panic
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libpanic_unwind/lib.rs:80
Nov  4 15:58:53 localhost polkadot[27395]:   39: std::panicking::try
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
Nov  4 15:58:53 localhost polkadot[27395]:   40: std::panic::catch_unwind
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
Nov  4 15:58:53 localhost polkadot[27395]:   41: tokio_threadpool::task::Task::run
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:130
Nov  4 15:58:53 localhost polkadot[27395]:   42: tokio_threadpool::worker::Worker::run_task2
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:567
Nov  4 15:58:53 localhost polkadot[27395]:   43: tokio_threadpool::worker::Worker::run_task
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:459
Nov  4 15:58:53 localhost polkadot[27395]:   44: tokio_threadpool::worker::Worker::try_steal_task
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:416
Nov  4 15:58:53 localhost polkadot[27395]:   45: tokio_threadpool::worker::Worker::try_run_task
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:301
Nov  4 15:58:53 localhost polkadot[27395]:   46: tokio_threadpool::worker::Worker::run
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:241
Nov  4 15:58:53 localhost polkadot[27395]:   47: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
Nov  4 15:58:53 localhost polkadot[27395]:   48: tokio_timer::timer::handle::with_default::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101
Nov  4 15:58:53 localhost polkadot[27395]:   49: std::thread::local::LocalKey<T>::try_with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Nov  4 15:58:53 localhost polkadot[27395]:   50: std::thread::local::LocalKey<T>::with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Nov  4 15:58:53 localhost polkadot[27395]:   51: tokio_timer::timer::handle::with_default
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84
Nov  4 15:58:53 localhost polkadot[27395]:   52: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
Nov  4 15:58:53 localhost polkadot[27395]:   53: tokio_timer::clock::clock::with_default::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137
Nov  4 15:58:53 localhost polkadot[27395]:   54: std::thread::local::LocalKey<T>::try_with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Nov  4 15:58:53 localhost polkadot[27395]:   55: std::thread::local::LocalKey<T>::with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Nov  4 15:58:53 localhost polkadot[27395]:   56: tokio_timer::clock::clock::with_default
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117
Nov  4 15:58:53 localhost polkadot[27395]:   57: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
Nov  4 15:58:53 localhost polkadot[27395]:   58: tokio_reactor::with_default::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:237
Nov  4 15:58:53 localhost polkadot[27395]:   59: std::thread::local::LocalKey<T>::try_with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Nov  4 15:58:53 localhost polkadot[27395]:   60: std::thread::local::LocalKey<T>::with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Nov  4 15:58:53 localhost polkadot[27395]:   61: tokio_reactor::with_default
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.10/src/lib.rs:217
Nov  4 15:58:53 localhost polkadot[27395]:   62: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
Nov  4 15:58:53 localhost polkadot[27395]:   63: tokio_threadpool::callback::Callback::call
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/callback.rs:22
Nov  4 15:58:53 localhost polkadot[27395]:   64: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:127
Nov  4 15:58:53 localhost polkadot[27395]:   65: tokio_executor::global::with_default::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
Nov  4 15:58:53 localhost polkadot[27395]:   66: std::thread::local::LocalKey<T>::try_with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Nov  4 15:58:53 localhost polkadot[27395]:   67: std::thread::local::LocalKey<T>::with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Nov  4 15:58:53 localhost polkadot[27395]:   68: tokio_executor::global::with_default
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
Nov  4 15:58:53 localhost polkadot[27395]:   69: tokio_threadpool::worker::Worker::do_run::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:125
Nov  4 15:58:53 localhost polkadot[27395]:   70: std::thread::local::LocalKey<T>::try_with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:262
Nov  4 15:58:53 localhost polkadot[27395]:   71: std::thread::local::LocalKey<T>::with
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/local.rs:239
Nov  4 15:58:53 localhost polkadot[27395]:   72: tokio_threadpool::worker::Worker::do_run
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:116
Nov  4 15:58:53 localhost polkadot[27395]:   73: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:345
Nov  4 15:58:53 localhost polkadot[27395]:   74: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/sys_common/backtrace.rs:77
Nov  4 15:58:53 localhost polkadot[27395]:   75: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/mod.rs:470
Nov  4 15:58:53 localhost polkadot[27395]:   76: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:315
Nov  4 15:58:53 localhost polkadot[27395]:   77: std::panicking::try::do_call
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:296
Nov  4 15:58:53 localhost polkadot[27395]:   78: __rust_maybe_catch_panic
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libpanic_unwind/lib.rs:80
Nov  4 15:58:53 localhost polkadot[27395]:   79: std::panicking::try
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
Nov  4 15:58:53 localhost polkadot[27395]:   80: std::panic::catch_unwind
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
Nov  4 15:58:53 localhost polkadot[27395]:   81: std::thread::Builder::spawn_unchecked::{{closure}}
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/thread/mod.rs:469
Nov  4 15:58:53 localhost polkadot[27395]:   82: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
Nov  4 15:58:53 localhost polkadot[27395]:   83: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov  4 15:58:53 localhost polkadot[27395]:   84: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov  4 15:58:53 localhost polkadot[27395]:              at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
Nov  4 15:58:53 localhost polkadot[27395]:       std::sys_common::thread::start_thread
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libstd/sys_common/thread.rs:13
Nov  4 15:58:53 localhost polkadot[27395]:       std::sys::unix::thread::Thread::new::thread_start
Nov  4 15:58:53 localhost polkadot[27395]:              at src/libstd/sys/unix/thread.rs:79
Nov  4 15:58:53 localhost polkadot[27395]:   85: start_thread
Nov  4 15:58:53 localhost polkadot[27395]:   86: __clone
Nov  4 15:58:53 localhost polkadot[27395]: Thread 'tokio-runtime-worker-0' panicked at 'attempt to subtract with overflow', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/arith.rs:198

**Comment by bkchr** [comment]
Please compile it in release mode and use the latest `v0.6` that already contains a fix for this.

**Comment by liangping** [comment]
thanks
