### ISSUE TITLE
Release v0.9.17 has misnamed binary: v0.9.17-rc4

### ISSUE THREAD

**Issue by ungurflorin** [paritytech/polkadot#5339]
Hey guys,

The `polkadot` binary in the [v0.9.17 release](https://github.com/paritytech/polkadot/releases/tag/v0.9.17-rc4) has the wrong name: https://github.com/paritytech/polkadot/releases/download/v0.9.17-rc4/polkadot (this downloads the file).

I guess somebody already knew about this since the https://github.com/paritytech/polkadot/releases/tag/v0.9.17 link points to a release that has no binaries?

Wondering if you already know what went wrong here.

This made for quite a funny story. See [/usr/local/bin/polkadot: line 1: Not: command not found](https://florinungur.com/essays/2022/04/18/not-command-not-found).

**Comment by bkchr** [comment]
Cc @coderobe

**Comment by coderobe** [comment]
Yeah, messed that one up. Releases after that one do not have this issue.

**Comment by chevdor** [comment]
It is best to query github for the download paths and not assume the url but indeed that was a one time isssue and the assumption you use still holds today.
