### ISSUE TITLE
Pallet errors are not visible anywhere when submitted via XCM Transact

### ISSUE THREAD

**Issue by haerdib** [paritytech/polkadot#5394]
When submitting a transaction via the XCM `Transact`, errors happening within the relevant pallet are not shown anywhere:

https://github.com/paritytech/polkadot/blob/9428d8c3ebcd4ec5fb9095549be7d5f84c48d8a2/xcm/xcm-executor/src/lib.rs#L347-L353
 
XCM Logs will simply report an `xcm::execute_xcm_in_credit: result: Ok(())`  even if the pallet call has failed. This makes it very hard to debug. 

It would be very helpful if the error returned by the pallet would at least be logged somewhere. Or even more preferable: If the XCM execution would not result in an `Ok(())`, but in an `Error` instead… or an `Ok` with a corresponding error message in it, such that one can debug from the parachain side.

**Comment by dzmitry-lahoda** [comment]
is seems in progress with v3 https://github.com/paritytech/polkadot/issues/4623

**Comment by haerdib** [comment]
Yes, that's it. Thanks a lot :)
