### ISSUE TITLE
Migrate to the new runtime-version macro

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#5395]
Currently, Polkadot, Kusama and other runtimes use an older way of declaring the runtime version:

https://github.com/paritytech/polkadot/blob/15444a6e77c784abb8f2635ec4fd0c9f7a29e138/runtime/polkadot/src/lib.rs#L107-L121

In https://github.com/paritytech/substrate/issues/7327 (PR https://github.com/paritytech/substrate/pull/8688) Substrate changed the way runtime communicates the runtime version.

To complete this task, all the runtimes should migrate to the new runtime version specification mechanism. For the example, see the PR above [here](https://github.com/paritytech/substrate/pull/8688/files#diff-67684005af418e25ff88c2ae5b520f0c040371f1d817e03a3652e76b9485224aR108)

**Comment by Doordashcon** [comment]
entails majorly including the proc-macro in all runtimes?

**Comment by bkchr** [comment]
Yes.
