### ISSUE TITLE
Flaky test in `approval-distribution`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot#5417]
See: https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/1530940 from the totally unrelated https://github.com/paritytech/polkadot/pull/5405 

cc @drahnr @eskimor

**Comment by eskimor** [comment]
LOL, I have to reduce that timeout to 1 microsecond to reproduce locally. Either those CI machines must be under really heavy load for a 100ms timeout to hit or something else weird is going on. I guess real heavy load, with context switches can explain even 100000x slower execution. :shrug:  Will nevertheless have a closer look, whether it could also be something else.

**Comment by eskimor** [comment]
Nope, it really seems to be that slow. I'll increase the timeout some more to make it even less likely to hit.

**Comment by eskimor** [comment]
If this keeps being a problem, we might also increase the channel capacity a bit: https://github.com/paritytech/polkadot/blob/88d66ac669c5f9c5d82651ff70fda9691f4e0ece/node/subsystem-test-helpers/src/lib.rs#L239

**Comment by eskimor** [comment]
https://github.com/paritytech/polkadot/pull/5427
