### ISSUE TITLE
Reduce subsystem channel size on test networks

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#5436]
This way we can detect issues due to blocking channels on test networks better.

Given that the bounded channel size for subsystems seems to get [passed into](https://github.com/paritytech/polkadot/blob/c4ee9d463adccfa3bf436433e3e26d0de5a4abbc/node/overseer/overseer-gen/proc-macro/src/parse_attr.rs#L197) the overseer-gen macro a command line argument might be a bit too much to ask.

I'd suggest to use a feature flag that gets enabled on CI, but not for proper releases (we already had a similar setup in the past).

**Comment by drahnr** [comment]
if we want this for a one-off test, we could just use the annotation `#[overlord(.., message_capacity=16, ..)]` and that's it. If want this to be dynamic, that's definitely do-able, just requires maybe one or two more additions to the builder pattern.

**Comment by eskimor** [comment]
Let's keep things simple. A feature flag that can be enabled on CI, but not for releases should already do the trick.

**Comment by drahnr** [comment]
My formulation might have been unclear, the above is already impl'd and works :)

**Comment by drahnr** [comment]
That's correct, but for me it's a nop :)

**Comment by eskimor** [comment]
I would expect us to deploy this on a couple of nodes - fix any issues and then have it deployed by default on test nets, like Versi. Hence the feature flag.

**Comment by drahnr** [comment]
I'll create a lil smith tomorrow
