### ISSUE TITLE
Find and fix any subsystem cycles via Versi

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#5460]
Based on [this](https://github.com/paritytech/polkadot/pull/5454) we can deploy nodes to some validator group on Versi with a reduced message channel size in order to provoke blocking. 

Once nodes stall because of a deadlock - debug & find the cycle (see node stall in the knowledge share section). Continue until nodes are not stalling any more, even with very small message queues.

Once all cycles are found and fixed, we should deploy a reduced channel size (e.g. 100) to all nodes on Versi and leave it like that. This way, if we accidentally introduce a cycle it should be very likely be detected on Versi already. Also consider using a reduced channel size in at least some Zombienet tests.

**Comment by sandreim** [comment]
implemented a compile time solution in https://github.com/paritytech/polkadot/pull/5614.
