### ISSUE TITLE
OOM on Rococo paritydb validators

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot#5553]
We are seeing Rococo validators OOMs only on our nodes which are running with paritydb.
[Here is a grafana dashboard snapshot](https://snapshots-origin.grafana.net/dashboard/snapshot/BVgpSmGgSiyT2mUCbhgClnwT4ub7hFmC?orgId=2) of the relevant memory dashboards for a sample affected node.

I haven't noticed any particular logs.
Version: `polkadot 0.9.19-f926bada`
Flags:
```
--base-path /home/parity/.local/share/polkadot --detailed-log-output --name rococo-3-validator-6 --validator --node-key-file /home/parity/keys/rococo_relaychain_p2p_key --chain /home/parity/chainspecs/rococo_relaychain_chainspec.json --listen-addr=/ip4/0.0.0.0/tcp/30333 --public-addr=/ip4/34.91.84.25/tcp/30333 --in-peers 100 --out-peers 50 --database paritydb --db-cache 512 --telemetry-url wss://submit.telemetry.parity-stg.parity.io/submit/ 1 --pruning=1000 --unsafe-pruning -lyamux=info,afg=info,sub-libp2p=debug,parachain=debug --prometheus-external --prometheus-port 9615 --ws-port 9944 --ws-max-connections 100 --rpc-port 9933 --execution wasm --wasm-execution=Compiled --listen-addr /ip4/0.0.0.0/tcp/30334/ws --beefy --enable-offchain-indexing=true
```
Hardware: GCP instance `n1-standard-4`

**Comment by arkpar** [comment]
@PierreBesson could you please upgrade to 0.9.22 and see if it still runs out of memory?

**Comment by ccris02** [comment]
@PierreBesson unrelated question. Where can I get Templet for this Dashboard?

**Comment by PierreBesson** [comment]
@arkpar I confirm that after upgrading to 0.9.22, the issue go away. So this was fixed by https://github.com/paritytech/parity-db/pull/68
@ccris02 This is the ["Grafana Node Exporter Full" dashboard](https://grafana.com/grafana/dashboards/1860).
