### ISSUE TITLE
RFC: XCM support for custom/different pallet instances between Rococo and Wococo

### ISSUE THREAD

**Issue by acatangiu** [paritytech/polkadot#5584]
We want to create an XCM-capable bridge `RococoBridgeHub <> WococoBridgeHub`, where:
- `RococoBridgeHub` - _bridge parachain_ running on Rococo
- `WococoBridgeHub` - _bridge parachain_ running on Wococo

From [bridges-repo issue](https://github.com/paritytech/parity-bridges-common/issues/1401):
> The problem is that the runtime is shared between Rococo and Wococo. In non-XCM bridges we solve that by adding second instance of our pallets - first instance is active on Rococo and the other one on Wococo. It'd be great if we could use XCM pallet to send XCMs between Rococo and Wococo, but it doesn't support additional instances.

>To me it looks like the only thing that needs to be changed is [this line](https://github.com/paritytech/polkadot/blob/21323b7d2e3c19e149d2f24b51c7bada4782a0c5/runtime/rococo/src/xcm_config.rs#L40). So probably change `const` to `storage`? Or use conditional compilation and build different runtimes for Rococo and Wococo? Some other solution?

Duplicating the issue here in polkadot for visibility.

**Comment by bkontur** [comment]
obsolete, we dont need to update Rococo runtime (hack/fix is in shared bridge-hub-rococo runtime)
