### ISSUE TITLE
Add a dispatchable to reserve transfer back assets to the reserve.

### ISSUE THREAD

**Issue by NachoPal** [paritytech/polkadot#5629]
Right now, `pallet-xcm` does not provide a method to to send back KSM/DOTs that where previously reserve transferred from Relay to Parachain.

`reserve_transfer_assets` is meant to be used by the Reserve, but it does not work in the case a Parachain wants to send the assets back to its Reserve (Relay Chain).

We need to add a new dispatchable similar to this: https://github.com/open-web3-stack/open-runtime-module-library/blob/c439a50e01944aedeef33231e0824a17ed1813bc/xtokens/src/lib.rs#L659-L677 to make use of `InitiateReserveWithdraw`.

**Comment by xlc** [comment]
Sounds like we need to figure out https://github.com/paritytech/substrate/discussions/11530 first before introducing more duplicated code.

**Comment by NachoPal** [comment]
Closing as it is being discussed here: https://github.com/paritytech/polkadot/pull/5975
