### ISSUE TITLE
staking-miner: SIGTERM handling

### ISSUE THREAD

**Issue by bakhtin** [paritytech/polkadot#5649]
A staking-miner binary does not handle SIGTERM signal. In particular, it leads to a Docker container with staking-miner binary in it being unable to terminate gracefully.

Duplicate: https://github.com/paritytech/staking-miner/issues/11

**Comment by bkchr** [comment]
CC @niklasad1

**Comment by Supportteam1** [comment]
Open this live chat to talk to the customer service directly for fast response 

 https://direct.lc.chat/14190504/
