### ISSUE TITLE
KSM network token failed to cross chain to parallel chain.

### ISSUE THREAD

**Issue by 99Kies** [paritytech/polkadot#5666]
Here are the details of my extrinsic. -> https://kusama.subscan.io/account/5C8QKBCqKZFZPMZ3dT7EuCU7zx5LmViRDn79dEATcNAF5X3Z

and this is my extrinsic error.
```bash
error: 750645000: DestinationUnsupported
```

this my parachain event log.
https://polkadot.js.org/apps/#/explorer/query/0x1df61c15d8db62de7167a2d3238d9b68b22bdd72ca22fd6ac4a5f2c611ef0e4f

**Comment by bkchr** [comment]
CC @KiChjang

**Comment by KiChjang** [comment]
The relay chain doesn't know which XCM version to select when sending to parachain 2115, however I see that it now understands that 2115 uses XCMv2, so if you send it again, it should just work.

**Comment by 99Kies** [comment]
@KiChjang emmmm, So can I still get my lost ksm back, or where did this ksm go?

**Comment by 99Kies** [comment]
The xcm version of 2115 is v2. I did not encounter this problem when I tested it on rococo-local and rococo-live.

**Comment by KiChjang** [comment]
> The xcm version of 2115 is v2. I did not encounter this problem when I tested it on rococo-local and rococo-live.

The point isn't whether or not the XCM version of 2115 is 2, it's what _the relay chain_ thinks of the supported XCM version of 2115 is. You can check it yourself via `xcmPallet.supportedVersion` under Chain State.

**Comment by 99Kies** [comment]
> > @KiChjang emmmm, So can I still get my lost ksm back, or where did this ksm go?
> 
> It's in the sovereign account of your destination parachain here: https://kusama.subscan.io/account/F7fq1isK9a3VBpKQAyHVDYX3cYcUcdzzwUQV3HGKB3avk6A, if you can contact the parachain maintainers, I think they'll be able to transfer the 1 KSM held there.

This is cool, so if I am the operation and maintenance of the parachain, how should I get this token, we don't seem to have the private key of para-2115-id.

**Comment by bkchr** [comment]
You can send a XCM originating from the parachain to return back the tokens.

**Comment by 99Kies** [comment]
> You can send a XCM originating from the parachain to return back the tokens.

@bkchr Can you provide me an example (like what method should I call on the parachain), it will be more intuitive. thanks!

**Comment by 99Kies** [comment]
@KiChjang The parachain(**2115**) needs to refund 1ksm to the user **5G48MUSiceK26a32TA3NSciGr2w7azCMVbCMsyKQDyjj6BWt**.(I'm simulating this operation on the testnet)
I am trying to build this function:
![image](https://user-images.githubusercontent.com/45918704/175107951-45b0480e-93ec-4d2e-80f5-c4edfd6987e0.png)
![image](https://user-images.githubusercontent.com/45918704/175107985-fd2931fd-29f8-4cd4-b96d-a7b7c9178f27.png)
**but it failed.**
![image](https://user-images.githubusercontent.com/45918704/175108092-6354d262-fe0d-4968-a129-cffc834c76de.png)

**Comment by KiChjang** [comment]
Have you looked at the code where it fires off the `Filtered` error?

Look, this is a very low-effort operation, I've noticed that you've been asking questions just to have someone spoon feed the answers to you. _You_ need to take some responsibility for your own problems and not simply offload them to someone else.

If you ask these sorts of low-quality questions again, I'm not going to answer them any longer.

**Comment by 99Kies** [comment]
@KiChjang Thanks for the encouragement, debugging can find the problem. I solved this problem.
The right way:
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/45918704/175362268-3b45b6a1-4e71-40d4-addc-247af7a000fc.png">
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/45918704/175362319-6a3bf7e5-9185-4d56-8497-49be4224f8b1.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/45918704/175362338-2ccde6f5-43ea-46fa-b5bb-39285ad7ea63.png">
This is the log of success in the relay chain:
![origin_img_v2_01317a73-50b4-4f09-abf4-85920dc7a74h](https://user-images.githubusercontent.com/45918704/175362605-58662822-5b0e-40fd-a69b-43aea5aee91a.jpg)
![qKShwXJnyg](https://user-images.githubusercontent.com/45918704/175362632-e23a7c02-98eb-4692-a4bd-5d3bb567f327.jpg)
