### ISSUE TITLE
rpc server: HTTP REST API not available anymore

### ISSUE THREAD

**Issue by bert2002** [paritytech/polkadot#5680]
Hi,
just updated from `.21` to .23` and it seems to me the `/system_health` endpoint does not work anymore. Was it deprecated and is there a replacement?

```
curl http://127.0.0.1:9933/system_health -X POST -H "Content-Type: application/json"
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```
Thanks,
bert

**Comment by ordian** [comment]
cc @niklasad1

**Comment by niklasad1** [comment]
You need to call `curl http://127.0.0.1:9933/health -X GET -H "Content-Type: application/json"`

`system_health` is the actual method that is called, are you sure that worked on `.21`? 

Must be some difference how the jsonrpc libraries handles then then.

**Comment by niklasad1** [comment]
See https://github.com/paritytech/substrate/blob/polkadot-v0.9.21/client/rpc-servers/src/lib.rs#L145

**Comment by bert2002** [comment]
yes was working with `.21`. 
Just tested and the `/health` endpoint works as a `GET` request.

```
curl http://127.0.0.1:9933/health -X GET -H "Content-Type: application/json"
{"jsonrpc":"2.0","result":{"peers":50,"isSyncing":false,"shouldHavePeers":true},"id":0}```

**Comment by bert2002** [comment]
Just saw its happening to one more endpoint

```
curl http://127.0.0.1:9933/chain_getBlock -X POST -H "Content-Type: application/json"
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```

**Comment by niklasad1** [comment]
Ok, I see now it's the REST API that does that in the old library.

**Comment by bert2002** [comment]
Yes thats it @niklasad1. To use it as a param it works without any problem.
