### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail if...

### ISSUE THREAD

**Issue by rickw** [paritytech/polkadot#569]
Thread 'import-queue-worker-0' panicked at 'applying the snapshot can only fail if the passed instance is different
			from the one that was used for creation of the snapshot;
			we use the snapshot that is directly associated with the instance;
			thus the snapshot was created using the instance;
			qed: ApplySnapshotFailed', src/libcore/result.rs:1165

[bug1.log](https://github.com/paritytech/polkadot/files/3832131/bug1.log)

**Comment by pepyakin** [comment]
[Root issue](https://github.com/paritytech/substrate/issues/3780)

**Comment by pepyakin** [comment]
Closing as duplicate.
