### ISSUE TITLE
Incorrect pre-genesis Kusama claim

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/polkadot#575]
I have identified a 'strange' account in the genesis state of Kusama.
https://polkascan.io/pre/kusama-cc2/account/CiPwZi4DmaGwT844zSbMozYpmUey6RETPMsxSSy48UKNZGv

This account has publicKey: "0628dae391a37ccb6ccae7e6b6495c2622d69cda000000000000000000000000"

It caught my attention because of the trailing zeros.
This appears to be a valid Ethereum-address:
https://etherscan.io/address/0x0628dae391a37ccb6ccae7e6b6495c2622d69cda

This Ethereum address has a DOT-allocation.
I believe this should be corrected (intervention W3F) or someone will not be happy.
Likely someone made a (costly) mistake in the pre-genesis claims-procedure.

**Comment by emielvanderhoek** [comment]
Voila, cause confirmed:
```
Function: claim(address _eth, bytes32 _pubKey)

MethodID: 0xc8622c24
[0]:  0000000000000000000000000628dae391a37ccb6ccae7e6b6495c2622d69cda
[1]:  0628dae391a37ccb6ccae7e6b6495c2622d69cda000000000000000000000000
```

Source: https://etherscan.io/tx/0x64d413c182ffe7769eeb99c802108f80e381f739939fb802b7bb5eaf4c6144b9

**Comment by emielvanderhoek** [comment]
FWIW: this is the only occurrence of its kind.

**Comment by gavofyork** [comment]
Reverted the claim tx. The original claimant can use the Kusama claims module to claim to somewhere sensible.
