### ISSUE TITLE
Run `Extrinsic Ordering` check against a local reference node

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#5762]
Currently the [Extrinsic Ordering Worfklow](https://github.com/paritytech/polkadot/actions/workflows/release-20_extrinsic-ordering-check-from-bin.yml) uses a live node as reference. 

This is fine _most of the time_ as long as the live node we use as reference runs the latest runtime. This is unfortunately not always the case.

To avoid the risk of using an older runtime as reference, we should, instead of using a live node, start the reference node locally based on a binary provided by the user, just as we currently do for the second node.

**Comment by coderobe** [comment]
implemented in https://github.com/paritytech/polkadot/pull/5790
