### ISSUE TITLE
Prometheus current block metrics since v0.9.25 

### ISSUE THREAD

**Issue by Generic-Chain** [paritytech/polkadot#5771]
Seems that the sync_target block# in prometheus is trailing best and finalized since the release. 

Prior to v0.9.25 sync_target was always >= to best and finalized  - see images below, the historical graph shows the delta going negative since the upgrade to v0.9.25

![sync_delta](https://user-images.githubusercontent.com/98120051/178020673-2001eedb-da6d-489a-82ce-8a75440f48c5.png)
![sync_target](https://user-images.githubusercontent.com/98120051/178020676-3269f85a-941d-405a-abc3-97bee355638e.png)

**Comment by Generic-Chain** [comment]
seems that since v0.9.26 the delta is even higher in Polkadot for some reason (but is the same as in v0.9.25 for Kusama)

**Comment by bkchr** [comment]
Should be fixed by https://github.com/paritytech/substrate/pull/11817
