### ISSUE TITLE
XCM HrmpNewChannelOpenRequest and HrmpAcceptOpenChannel cannot execute on parachains

### ISSUE THREAD

**Issue by doutv** [paritytech/polkadot#5786]
Settings: 
- Local development using polkadot-launch
- Relay chain: rococo-0.9.18
- 2 Parachain: moonbeam-0.24.0 moonbase
- Open HRMP channel between 2 parachains via polkadot-launch
- Change xcm Logging level to trace `--log=info,xcm=trace`

After polkadot-launch finish initialization, I noticed the following xcm barrier error happen on parachain:
```
DEBUG tokio-runtime-worker xcm::execute_xcm_in_credit: [🌗] Barrier blocked execution! 
Error: (). (origin: MultiLocation { parents: 1, interior: Here }, 
message: Xcm([HrmpNewChannelOpenRequest { sender: 1000, max_message_size: 30000, max_capacity: 8 }]), 
weight_limit: 125000000000, weight_credit: 0)
```

Also, I noticed that even HrmpNewChannelOpenRequest passes xcm barrier, it still cannot be executed since it's intentionally unimplemented: 
https://github.com/paritytech/polkadot/blob/v0.9.18/xcm/xcm-executor/src/lib.rs#L505

Same for HrmpAcceptOpenChannel.

**I wonder why these 2 XCM instructions are unimplemented but they are sent to parachains.**

The HRMP channel opened successfully regardless of the above error.

**Comment by xlc** [comment]
They are notifications to parachains and it is up to parachains to handle it (or not). There are no errors and just parachains choose to block/ignore such message.

**Comment by doutv** [comment]
> They are notifications to parachains and it is up to parachains to handle it (or not). There are no errors and just parachains choose to block/ignore such message.

Thanks a lot!
