### ISSUE TITLE
Exposed Metadata XCM Type closed loop.

### ISSUE THREAD

**Issue by darkfriend77** [paritytech/polkadot#5803]
Actual Polkadot Metadata parsed with state.getMetadata()

In the exposed types metadata of XCM it seems there is a closed loop (polkadot state.getMetadata()), Has anyone stumbled across this issue when generating artifacts from the metadata?

![image](https://user-images.githubusercontent.com/17710198/180184013-691bb2f1-a5a1-460f-ad44-5d24ec46da20.png)

**Comment by ascjones** [comment]
It is by design, representing "self-referential" types: in this case the type is `Order` which has a variant with the field `Vec<Order>`.

See the test case https://github.com/paritytech/scale-info/blob/master/test_suite/tests/json.rs#L770
