### ISSUE TITLE
Pruning parameter not honored

### ISSUE THREAD

**Issue by rvalle** [paritytech/polkadot#5807]
I need to recurrently analyze the tip of the blockchain, more or less history-depth.

So I have deployed a polkadot node with `--pruning 2500000` for a conservative 2x size of the required chuck.

When I use RPC interface to query blocks they  have already been discarded. First `chain.getBlockHash` and then `chain.getBlock` results in `Unknown block, state already discarded`

However there are more than the pruning default of 256 blocks, as I managed to query a block 4000 blocks old but not the requested 2.5M

I wonder if the parameter got truncated somewhere or something else went wrong.

The amount of data stored in the node, however, seems consistent with 2.5M blocks when comparing to another full archive node we have.

**Comment by rvalle** [comment]
I think this may have something to do with using ```--sync fast``` 
I have the feeling that pruning is happening for the blocks received after sync finished. is that the case?
now I can go back 8000 blocks, but the head has advanced some 4000 blocks.

**Comment by arkpar** [comment]
Pruning setting indeed has a hard maximum setting of IIRC 4096 blocks. This is has to do with the fact that current implementation requires some in-memory upkeep for tracking live branches and setting it too high will use too much memory and degrade performance. If you need to store 2.5M blocks worth of history, your only option currently is to use archive mode.

**Comment by jasl** [comment]
> Pruning setting indeed has a hard maximum setting of IIRC 4096 blocks. This is has to do with the fact that current implementation requires some in-memory upkeep for tracking live branches and setting it too high will use too much memory and degrade performance. If you need to store 2.5M blocks worth of history, your only option currently is to use archive mode.

I need to set a large pruning blocks too, I've searched `4096` as keyword in Substrate and Polkadot codebase, it seems there's no reference, maybe the limit has changed recently?

**Comment by bkchr** [comment]
@jasl https://github.com/paritytech/substrate/blob/7b81072843e584ef2bee449081aed5c963021ee9/client/service/src/builder.rs#L278-L280

**Comment by ggwpez** [comment]
> Pruning setting indeed has a hard maximum setting of IIRC 4096 blocks  

So is this just silently truncating the value? I think we should rather error and tell the user to chose a lower value.

**Comment by arkpar** [comment]
I was actually incorrect. 4096 is the limit for unflinalized blocks as specified [here](https://github.com/paritytech/substrate/blob/1399afdcd8ab4d7fad149c96f9cadcaf04b94f86/client/service/src/builder.rs#L273). There's no hard limit for pruning setting, even though I think there should be one, as the memory usage is growing linearly with the number of blocks that are pending pruning.

In this case it is not working because you use fast sync indeed. Fast sync does not execute blocks therefore state history before the sync point is not available.

It should be possible to get rid of in-memory bookeeping for state pruning with some changes to the implementation. I'll file a separate issue for that.

**Comment by rvalle** [comment]
thanks @arkpar 
Ok, I will try to create a node with 2.5M pruning setting... see what kind of memory required. Now I know this is the reason behind #5804

**Comment by rvalle** [comment]
@arkpar https://github.com/paritytech/substrate/issues/11911 was resolved yesterday.

How can I trace when the fix will be release in polkadot node? I would like to test the 2.5M pruning setup.

When I look at cargo file I don't see any straight versioned dependency. I can see dependencies, for example, from  the runtime to substrate master branch. Does it mean that next polkadot node release will come with this fix?
