### ISSUE TITLE
TryRuntime: Custom("[backend]: frontend dropped; terminate client")

### ISSUE THREAD

**Issue by GopherJ** [paritytech/polkadot#5819]
Hi, after upgrading from polkadot-v0.9.24 to polkado-v0.9.26, try runtime command starts to fail no matter which RPC node I'm using.

```
Custom("[backend]: frontend dropped; terminate client")
```

**Comment by ark930** [comment]
The same issue occurred for Bifrost when running try-runtime which upgrade deps from polkadot-v0.9.22 to polkadot-v0.9.25

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by GopherJ** [comment]
hi we would like to release, @kianenigma any idea on this?

**Comment by kianenigma** [comment]
what is the full command you are using?

**Comment by GopherJ** [comment]
hi @kianenigma we use the following command

```
cargo run --bin parallel --release --features try-runtime --features runtime-benchmarks -- try-runtime --chain $(CHAIN) --wasm-execution=compiled on-runtime-upgrade live --uri=$(URL)
```

**Comment by kianenigma** [comment]
I doubt if anything has changed in try-runtime that would cause this. Can you try with multiple different nodes? also local nodes, also, with these flags: 

```
	--rpc-cors all \
	--rpc-max-payload 1000 \
	--ws-max-out-buffer-capacity 1000 \
```

The errors suggests that the connection is being terminated from the node.

**Comment by kianenigma** [comment]
Running `target/release/substrate try-runtime --execution=Native --chain=dev on-runtime-upgrade live --uri 'wss://heiko-rpc.parallel.fi:443'` on substrate master works for me (it starts scraping data correctly). 

Which cumulus version you are running, and what is the linked substrate version there?

**Comment by GopherJ** [comment]
> Running `target/release/substrate try-runtime --execution=Native --chain=dev on-runtime-upgrade live --uri 'wss://heiko-rpc.parallel.fi:443'` on substrate master works for me (it starts scraping data correctly).
> 
> Which cumulus version you are running, and what is the linked substrate version there?

hi, we are on polkadot & cumulus v0.9.26

**Comment by GopherJ** [comment]
> I doubt if anything has changed in try-runtime that would cause this. Can you try with multiple different nodes? also local nodes, also, with these flags:
> 
> ```
> 	--rpc-cors all \
> 	--rpc-max-payload 1000 \
> 	--ws-max-out-buffer-capacity 1000 \
> ```
> 
> The errors suggests that the connection is being terminated from the node.

I've definitely tried on local nodes and onfinality nodes, none of them work for me, but local nodes it'll quit with another error instead:

```
get_keys not found
```

something like this, I'll re-try and let you know

**Comment by GopherJ** [comment]
@kianenigma I changed the rpc nodes' config, but still I can reproduce the issue:

![image](https://user-images.githubusercontent.com/33961674/182058374-974b6f6d-45d5-47d4-930c-7eaf25e22460.png)

**Comment by GopherJ** [comment]
I tried with `LTO=true` binary which still have the same issue, @kianenigma we dont have this in polkadot-v0.9.24 or earlier, there must be something wrong or breaking change that we dont know, could you help on our release process

**Comment by kianenigma** [comment]
> @kianenigma I changed the rpc nodes' config, but still I can reproduce the issue:
> 
> ![image](https://user-images.githubusercontent.com/33961674/182058374-974b6f6d-45d5-47d4-930c-7eaf25e22460.png)

What logs do you see in the node when this error happens? that should illuminate the issue.

**Comment by niklasad1** [comment]
@GopherJ 

"frontend dropped; terminate client" just implies that the `ws client` has been dropped and not necessarily something critical.

Can you just double check that you are not running into https://github.com/paritytech/substrate/issues/11772?

As all other logs such as `Connection established to target: Target { sockaddrs: [], host: "heiko-rpc.parallel.fi", host_header: "heiko-rpc.parallel.fi:443", _mode: Tls, path_and_query: "/" }` is missing as well...

**Comment by hqwangningbo** [comment]
@GopherJ You can check your tracing-core version. Try demoting to tracing core = "=0.1.26"

**Comment by GopherJ** [comment]
thanks @niklasad1 @hqwangningbo !
