### ISSUE TITLE
Official docker polkadot image contains a `polkadot` executable with missing symbol table

### ISSUE THREAD

**Issue by koute** [paritytech/polkadot#5828]
Our [official docker image for polkadot](https://hub.docker.com/r/parity/polkadot) contains a `polkadot` binary with its whole `.symtab` section stripped. This results in useless backtraces anytime anything panics (e.g. see [here](https://github.com/paritytech/polkadot/issues/5604#issuecomment-1194004242) or [here](https://github.com/paritytech/polkadot/issues/5809#issue-1316792837)).

The most likely culprit of this is that while building the image something (either directly on indirectly) calls `strip` on the `polkadot` binary which strips out the `.symtab` section necessary to decode the backtrace symbols. If so it instead should be called with the `--strip-debug` argument which will ensure that the symbol table is preserved.

(The `polkadot` binaries we put up in our Github releases don't have this problem.)

cc @paritytech/ci

**Comment by ggwpez** [comment]
One way of checking this is to use the [file](https://linux.die.net/man/1/file) on the binary before releasing it.  
When used on the released Polkadot binary, this returns:  
```pre
polkadot: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=38dc68abeb2d1fcb5a475a85a221d4f59470eb4b,
with debug_info, not stripped
```

on the Docker version of the binary, it shows "stripped":  
```pre
docker-polkadot: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=9823d45269bac875dde7c7ead70bc497e771b98e,
stripped
```

**Comment by coderobe** [comment]
this probably comes from the .deb package that the docker build pulls from, i'll dig further

**Comment by coderobe** [comment]
it looks like cargo-deb strips it, we can pass `--no-strip` to that when building the deb to avoid this

**Comment by ordian** [comment]
This is resolved, right?

**Comment by koute** [comment]
I just checked our newest Docker image; the `.symtab` section's there now, so this should be resolved. Thanks.
