### ISSUE TITLE
Deploy Parachains [DOC]

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/polkadot#585]
I'm trying to deploy a parachain following the instructions at https://wiki.polkadot.network/docs/en/build-deploy-parachains#deploying-the-parachain. The documentation says to follow those steps: Click on `democracy` -> `propose(proposal,value)` -> `parachains` -> `registerParachain(id,code,initial_head_data)`. However, when i try to reproduce it on my local 2 node testnet, the only option for parachains is `setHeads(head)`.

**Comment by lsaether** [comment]
That page is very out of date and won't work with recent builds. Instead, maybe you would like to try the [cumulus demo](https://github.com/paritytech/cumulus#running-a-collator)?

**Comment by damianoazzolini** [comment]
Ok, i'll give it a try! Using this method, will i be able to deploy a smart contract through the web interface on this parachain right?

**Comment by gavofyork** [comment]
Perhaps; if not, then soon, anyway. It's all quite heavily under development.
