### ISSUE TITLE
Missing key 'higestBlock'  in RPC responce `system_syncState`.

### ISSUE THREAD

**Issue by base1217** [paritytech/polkadot#5860]
Hello,

There is not `highestBlock` key in RPC response 'system_syncState' anymore.

Is it okay?

**Comment by stakeworld** [comment]
Maybe related to #5771 ?

**Comment by bkchr** [comment]
The missing key is a valid return. It just means that there is no block with a higher number than the best block of your local node in the network.

I created a pr to make this always return the highest block, which now defaults to your local node best block: https://github.com/paritytech/substrate/pull/11979
