### ISSUE TITLE
Is Yamux updated in the next version of docker image?

### ISSUE THREAD

**Issue by paperfrog95** [paritytech/polkadot#5893]
```
Thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_flush called after error.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/quicksink-0.1.2/src/lib.rs:225

This is a bug. Please report it at: https://github.com/paritytech/polkadot/issues/new
```
Knowing that there is a bug like this,
I know what can be solved by updating Yamux.

But we hope to use a pure Docker image.
Will this be solved in the next version of the Docker image?

And for docker users, could you briefly tell me how to solve it at this point?

I don't know how to update yamux in Docker.

**Comment by bkchr** [comment]
Yes, it will be part of the next release: https://github.com/paritytech/polkadot/pull/5861
