### ISSUE TITLE
Can i run a validator node with pre-built binary ?

### ISSUE THREAD

**Issue by singhsahilzeeve** [paritytech/polkadot#5917]
According to the steps mentioned in official [docs](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot) one needs to clone and build the binary to run a validator node. Is it possible to run a validator node with a pre-built binary downloaded from the [release section.](https://github.com/paritytech/polkadot/releases/download/v0.8.22/polkadot)?

**Comment by bkchr** [comment]
Yes, using the pre-built binaries is completely okay.
