### ISSUE TITLE
Nominator's commission is decreased in some era. 

### ISSUE THREAD

**Issue by liangping** [paritytech/polkadot#593]
My validator name is PING.  I found that nominator's commission is decreased in some era and I didn't found any slash during that era.  I doubt it could be a bug.  

While validator's commission is increased. 

![Screenshot_20191116_200542](https://user-images.githubusercontent.com/2882920/68992911-b4dcfc80-08ac-11ea-826f-1127cbb62563.jpg)

![Screenshot_20191116_194512](https://user-images.githubusercontent.com/2882920/68992829-e3a6a300-08ab-11ea-8365-717bcf6219e3.jpg)

Slash history
![Screenshot_20191116_201409](https://user-images.githubusercontent.com/2882920/68992994-bfe45c80-08ad-11ea-8a85-d2827efb1b9f.jpg)

**Comment by liangping** [comment]
Since there is no slashes. the nominator's balance should at lease keep as same as previous epoch.

**Comment by joepetrowski** [comment]
Your nominators are probably nominating more than one validator, and Phragmen has assigned a different backing to you than the other era. This is not indicative of their balances.

**Comment by liangping** [comment]
OK，thanks
