### ISSUE TITLE
Storage requirements for validator node

### ISSUE THREAD

**Issue by singhsahilzeeve** [paritytech/polkadot#5937]
What can be the storage required for  a Validator node and a Full node for next 12 months.

**Comment by bkchr** [comment]
Please check this: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware

**Comment by singhsahilzeeve** [comment]
> Please check this: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware

Thanks a lot for this information. According to this guide, 1 TB of Hardisk may be sufficient but my concern is that for the next 6 months or 12 months will 1 TB be enough? I tried to run it locally and observed the storage it takes versus the time. I noted that it estimates about 4Tb of memory for the next 12 months. Will I require 4 Tb of space?

**Comment by bkchr** [comment]
Running a validator doesn't require running as archive node. Thus, it only keeps the recent state in the db, which is much smaller than 1TB.
