### ISSUE TITLE
Get staking on Versi

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#5940]
In order to test Versi, we need validators staked on Versi. It should also be enabled on Rococo, but that is orthogonal.

Open tasks:

- [ ] Figure out how this is supposed to work with the validator-manager (talk with devops)
- [ ] Adjust chain spec for Versi to enable staking, based on Westend.
- [ ] Chainspec should also be usable for zombienet tests, so we can test slashing via zombienet as well.

**Comment by bkchr** [comment]
Why do you need staking? To test slashing?

**Comment by eskimor** [comment]
Zombienet tests are fine for now.
