### ISSUE TITLE
Figure Out XCM Weight Story

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#5945]
In order for XCM to not depend on any FRAME crates, it defines and uses its own local Weight definition.

For the migration to Weight v1.5 and eventually v2, this probably wont work.

So we have some low hanging fruit now that we need to fix up and make XCM use REAL weight types.

You can see how XCM was migrated for the time being here: https://github.com/paritytech/polkadot/pull/5943

**Comment by KiChjang** [comment]
I _think_ this is done -- we've moved the `Weight` definition to its own `sp-weights` crate in Substrate, and we can now pull that dependency in. This is good as it doesn't depend on `sp-runtime` or `sp-core` and is pretty light-weight.
