### ISSUE TITLE
Test Versi Scaling Limit

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#5962]
To get an idea what could be feasible on Kusama.

Test:

- 250 para validators + 50 parachains.
- 300 para validators + 60 parachains.

See where block times start to suffer, also check what difference it makes when validator set is scaled up to Kusama size as well. If block times for 250 para validators is still good, but not for 300 - check whether 250 is also good if there are 900 authorities in total.

Depending on the result, other experiments might be worthwhile as well:

300 para validators with only 50 parachains for example: This makes sense to test with non trivial POVs, as a higher number of para validators with same number of parachains reduces load on approval checkers - this will only be noticeable if there actually is any load (candidates perform some computation).

**Comment by ggwpez** [comment]
How will you test this? With zombienet?  

Are you just testing the network size or also performance (transactions per second)?

**Comment by eskimor** [comment]
On Versi - our test net. The most important performance metric we will be monitoring is block rate of parachains. Especially for the second part, we might also look into transactions per second.

**Comment by sandreim** [comment]
I think we can easily deploy polkadot-introspector for block time monitoring, but it would only work with cumulus collators as it requires us to connect to collators via RPC and get inherent TS (which doesn't work for cumulus). However adding Prometheus mode for parachain commander would solve that as we would compute the para block times from the relaychain data.

**Comment by sandreim** [comment]
this is also overlapping with https://github.com/paritytech/polkadot/issues/4776

**Comment by eskimor** [comment]
@tdimitrov could you have a look into this one as well, as soon as Versi is operational again please?

**Comment by ggwpez** [comment]
How does this relate to https://github.com/paritytech/polkadot-stps/ ?  
Do you want to produce some official sTPS numbers or just get an idea?

**Comment by sandreim** [comment]
In the context of this issue we want to identify the performance bottlenecks so we have a high level idea of where to dig further and iterate on optimizing the node performance wrt parachain consensus.

**Comment by tdimitrov** [comment]
I ran 250 validators with 50 parachains on versi.

Block times on relay chain and parachains looked generally okay. There were occasional 12/18/24 sec block times on some parachains.
On the next day one parachain has stalled but there was an issue with the database on it so I assume this was unrelated.

I noticed `approval-distribution` channel size increased slightly:
![Screenshot from 2022-10-27 19-19-37](https://user-images.githubusercontent.com/610755/198588587-a572778f-1811-4dd7-a034-766fae4e0979.png)
There were also some peaks with `approval-voting` and `bitdield-distribution` subsystems channel size:
![Screenshot from 2022-10-27 19-19-44](https://user-images.githubusercontent.com/610755/198588706-acbd58a9-797d-4836-ae1f-298bb023e43b.png)
![Screenshot from 2022-10-27 19-20-00](https://user-images.githubusercontent.com/610755/198588834-624736c4-8c9f-4524-af5a-909f59de8436.png)

ToFs for `approval-distribution` were increased:
![Screenshot from 2022-10-27 19-20-19](https://user-images.githubusercontent.com/610755/198588908-9c5cd2db-6167-48b6-b6c2-9544fa15ecc0.png)
ToFs of `approval-voting` and `bitfield-distribution` increased a little too:
![Screenshot from 2022-10-27 19-20-39](https://user-images.githubusercontent.com/610755/198589072-4c87cd17-2ee0-42e2-b363-fecd8328b49c.png)
![Screenshot from 2022-10-27 19-21-11](https://user-images.githubusercontent.com/610755/198589099-87a8bc48-5ebd-4f04-a57a-97d7756c6497.png)

**Comment by eskimor** [comment]
Nice, thank you Tsveto! So this looks like we are already pushing limits here. I would be very interested how this behaves with extending this to more validators. I have seen in the past that approval-distribution does not seem to like an increased validator set, would be good to confirm or disprove this. So in particular:

Increase the validator set even further, let's say 100 more nodes - see how ToFs and channel sizes behave.

**Comment by rphmeier** [comment]
questions on my mind:
  * how are the slow ToFs distributed across machines? i.e. do we see roughly the same ToF graph on all machines or are a few of them slower than others?
  * what is the bottleneck in approval-distribution? are messages not being processed because of work being done in the approval-distribution subsystem or because it's waiting on something else, which is slow?
  * since it only communicates with the network bridge and approval-voting, is network-bridge the culprit? 
  * if so, why?
  * How does the behavior change as we scale Versi?

**Comment by eskimor** [comment]
Where does approval-voting actually block on approval-distribution. I only see it sending messages via unbounded to approval distribution.

**Comment by eskimor** [comment]
> questions on my mind:
> 
>     * how are the slow ToFs distributed across machines? i.e. do we see roughly the same ToF graph on all machines or are a few of them slower than others?
> 
>     * what is the bottleneck in approval-distribution? are messages not being processed because of work being done in the approval-distribution subsystem or because it's waiting on something else, which is slow?
> 
>     * since it only communicates with the network bridge and approval-voting, is network-bridge the culprit?
> 
>     * if so, why?
> 
>     * How does the behavior change as we scale Versi?

We identified a bottleneck. I would expect fixing that to bump up performance at least threefold.

**Comment by sandreim** [comment]
> questions on my mind:
> 
> * how are the slow ToFs distributed across machines? i.e. do we see roughly the same ToF graph on all machines or are a few of them slower than others?

Things look similar across machines.
> * what is the bottleneck in approval-distribution? are messages not being processed because of work being done in the approval-distribution subsystem or because it's waiting on something else, which is slow?

Yeah, the importing of assignments and approvals is serialized and both wait for approval voting subsystem checks before doing book keeping. I'm working on some changes to wait for the approval voting checks in parallel but still serialising work per peer so to not break deduplication. We would expect approval voting to have more work to do in this scenario and for it no not block when sending messages to `approval-distribution` as we'll clear the queue faster there.

> * since it only communicates with the network bridge and approval-voting, is network-bridge the culprit?

`network-bridge` looks fine, very few instances where we'd block on its queue being full.
> * if so, why?
> * How does the behavior change as we scale Versi?

Currently we are blocked by a deployment/networking issue. We can't even get to 200 validators because of low connectivity (authority discovery failures).

**Comment by sandreim** [comment]
> Where does approval-voting actually block on approval-distribution. I only see it sending messages via unbounded to approval distribution.

https://github.com/paritytech/polkadot/blob/0bc8fddc19a628fd304a170c6a5f3c1cdd771b72/node/core/approval-voting/src/lib.rs#L1008

**Comment by eskimor** [comment]
Darn :1st_place_medal:  ... yep, I did not see that one :see_no_evil:

**Comment by rphmeier** [comment]
> https://github.com/paritytech/polkadot/blob/0bc8fddc19a628fd304a170c6a5f3c1cdd771b72/node/core/approval-voting/src/lib.rs#L1008

It's worth noting that the `BecomeActive` logic only gets triggered once during a node's lifetime - that is, when it first gets into sync. It should be unbounded but this isn't going to import long-running performance.




> The issue we suspect is causing most pain is the importing of assignments and approvals which are serialized and both wait for approval voting subsystem checks before doing book keeping. I'm working on some changes to wait for the approval voting checks in parallel but still serialising work per peer so to not break deduplication. We would expect approval voting to have more work to do in this scenario and for it no not block when sending messages to `approval-distribution` as we'll clear the queue faster there.

Ok, this makes sense and I hope it is indeed the bottleneck.

**Comment by sandreim** [comment]
> but my expectation was that anything waiting on approval-voting would be bottlenecked on the DB write, and we disproved that in the past, didn't we? Otherwise, the only work that approval-voting does is verify a signature (not insignificant, but would be a surprising bottleneck at these message volumes), update some in-memory state, and do some DB reads (which should be cached by RocksDB, no?)

Yes, we disproved the DB as being the bottleneck in the past.

**Comment by sandreim** [comment]
We concluded last round of testing at 350 paravalidators and 60 parachains with PR https://github.com/paritytech/polkadot/pull/6530. 

Finality lag:
<img width="851" alt="Screenshot 2023-01-23 at 14 52 27" src="https://user-images.githubusercontent.com/54316454/214045332-f6e71f19-073b-46e6-ad0f-dde6a72d2a36.png">

Parachain block times:
<img width="1721" alt="Screenshot 2023-01-23 at 14 52 51" src="https://user-images.githubusercontent.com/54316454/214045350-ff400f30-21e1-4907-8c81-61fdcb840236.png">

Board https://github.com/orgs/paritytech/projects/63 for tracking.
