### ISSUE TITLE
ZombieNet: ensure that asynchronous backing logic is backwards compatible with v1

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#6001]
The test is simple: start a 2-node testnet with 1 parachain, where one node runs `master` and the other runs the asynchronous backing feature branch. Set the group size to 2 in genesis and ensure that the parachain progresses at the expected rate.

**Comment by eskimor** [comment]
@sandreim Can someone on Engineering take that?

**Comment by sandreim** [comment]
Sure, is the branch in healthy state right now ?

**Comment by eskimor** [comment]
No, but I am working on it.

**Comment by bredamatt** [comment]
Just to confirm, this https://github.com/paritytech/polkadot/tree/rh-async-backing-statement-distribution is the branch we are talking about here, right?

**Comment by eskimor** [comment]
No actually it is: rh-async-backing-feature
https://github.com/paritytech/polkadot/pull/5022

The branch referenced by you will be merged into rh-async-backing-feature once ready.

**Comment by eskimor** [comment]
Ok, branch should be ready now. Existing Zombienet tests are failing, but I don't really know why - might be unrelated to the actual changes?

**Comment by bredamatt** [comment]
Not sure why this happens, but I did a checkout of the branch and attempted building - then I saw this issue:

```
error: `sp_trie::recorder::Recorder<H>::as_trie_recorder::{opaque#0}<'_>` does not live long enough
   --> /Users/mattia/.cargo/git/checkouts/substrate-7e08433d4c370a21/1f720c1/primitives/state-machine/src/trie_backend_essence.rs:181:44
    |
181 |         let recorder = recorder.as_mut().map(|r| r as _);
    |                                                  ^

error: `sp_trie::recorder::Recorder<H>::as_trie_recorder::{opaque#0}<'_>` does not live long enough
   --> /Users/mattia/.cargo/git/checkouts/substrate-7e08433d4c370a21/1f720c1/primitives/state-machine/src/trie_backend_essence.rs:219:44
    |
219 |         let recorder = recorder.as_mut().map(|r| r as _);
    |                                                  ^

   Compiling sp-weights v4.0.0 (https://github.com/paritytech/substrate?branch=master#1f720c11)
error: could not compile `sp-state-machine` due to 2 previous errors
```

I had a similar issue on my branch, and what solved it was a merge of the latest commits on master to the branch. @eskimor do you have this issue when you try `cargo check` or `cargo build` at all?

**Comment by bredamatt** [comment]
Seems to be working just fine with this zombienet configuration: 
```
[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"

[relaychain.genesis.runtime.runtime_genesis_config.configuration.config]
  max_validators_per_core = 2

  [[relaychain.nodes]]
  name = "alice"
  command = "polkadot-async" // This is the binary from the async backing branch
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  command = "polkadot" // this is the master branch binary
  extra_args = [ "--bob" ]

[[parachains]]
id = 100
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  command = "parachain-template-node"
  args = ["-lparachain=debug"]
```

What is the best way to share the findings for this type of issue? Should we simply share the logs here, or use some other form of visibility, or potentially write a zombienet feature test and add it to the branch?

**Comment by sandreim** [comment]
I think it makes sense to keep the CI test in the async branch for now, just to make sure we dont break things as we go fwd.

**Comment by rphmeier** [comment]
Yeah, @bredamatt please open a PR against the feature branch and file a follow-up issue to remove the test once synchronous backing is obsolete.

**Comment by bredamatt** [comment]
@rphmeier @eskimor @sandreim waiting for the above before finishing up the CI test on the async branch.

**Comment by rphmeier** [comment]
We should just merge `rh-async-backing-feature` with master. I believe @slumber has plans to do this in the near future

**Comment by sandreim** [comment]
done in https://github.com/paritytech/polkadot/pull/6314
