### ISSUE TITLE
Explore the idea of XCM dialects

### ISSUE THREAD

**Issue by KiChjang** [paritytech/polkadot#6013]
One of the realizations recently is that the `Call` type parameter to the `Xcm` struct need not be an actual runtime call type; instead, it can be any type that is SCALE encodable/decodable. Given that's the case, what implementors can do would be to make use of `Transact` as a way to develop their own _dialect_ of XCM, complete with dialect IDs, versioning and so on.

What we could try and prototype now would be to see how sensible and realistic that this could be implemented nowadays, and provide code examples of doing so.

**Comment by KaiserKarel** [comment]
Recapping our conversation on this:

- [ ] Create a branch for prototyping this, containing changes to Xcm and the spec, (not intended to be merged).
- [ ] Adjust the Transact Call spec to make it clearer that it is very customizable.
- [ ] Define dialects spec, which is mainly intended for defining versioning and schema detection. Actual dialects are completely opaque.
- [ ] Ape and code out an `xcm/amm` dialect or something similar, focussed on a specific use case that is too specific for XCM itself.

**Comment by KaiserKarel** [comment]
One question I'd have is:

Should dialects be combined: aka if a chain supports `xcm/amm` and `xcm/lend`, can I construct the following:

```
Transact {
    payload: encode![Amm::Swap, Lend::Borrow]
}
```

Or do we intend each `Transact` to nest a single dialect?

**Comment by KiChjang** [comment]
I think each `Transact` instruction should handle only 1 dialect at a time. This is because each dialect is going to have its own versioning and schema that should be negotiated first, before dialectal instructions can be executed. Mixing several dialects together in 1 `Transact` would easily complicate the negotiation algorithm.

**Comment by KiChjang** [comment]
Actually, I don't think I was entirely correct in my previous comment. If dialect version negotiation is a concern, then what we could do is simply create a new XCM instruction, maybe called `ExpectDialect`, and use that to handle all version negotiations regarding dialects. That way, each `Transact` can contain instructions from multiple dialects. What I am then interested in figuring out is what should happen when one dialect instruction conflicts with another, but that is probably up to the chain to solve.

In addition, I have recently came across https://github.com/paritytech/trappist, and have been talking with @hbulgarini about the possibility of constructing an example of an XCM dialect in Trappist. What we would then have to do is to fork the current XCM v3 branch, implement the `ExpectDialect` instruction, and have Trappist use it to construct AMM-specific instructions as an example of what the community could build.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/xcm-as-a-standard-for-reading-and-interacting-with-parachains/266/6

**Comment by KiChjang** [comment]
I am more of the opinion now that XCM dialects simply create new XCM instructions, but any of them can simply be rewritten using `Transact`. A new XCM instruction does not simply contain the instruction itself, but also new registers and configuration items, which XCM dialects cannot really add or handle.

As such, going forward, I think it's best to direct any specific feature requests to the [XCM format specification repository](https://github.com/paritytech/xcm-format). We are currently in the process of formalizing and opening up the proposals process for the next XCM version.
