### ISSUE TITLE
[XCM] Replace Wild(All) for teleports and wherever else possible

### ISSUE THREAD

**Issue by ruseinov** [paritytech/polkadot#6030]
As the XCM v3 comes in we'd need to fix https://github.com/paritytech/polkadot/blob/53253de77f1649ecbb650df2ec3e29d0d1110a2d/xcm/pallet-xcm/src/lib.rs#L874 and similar occurrences with the new invariants of Wild.

Why? Because we are relying on coefficients to calculate weights, for example [here](https://github.com/paritytech/cumulus/blob/master/parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs#L41) and that turns out way more expensive, because we don't know an exact or approximate number of assets teleported. 

cc @KiChjang

**Comment by KiChjang** [comment]
It's not clear what coefficients mean from your description, I think what you meant was that we rely on the number of asset classes that is specified in the asset wildcard to calculate weights.

**Comment by KiChjang** [comment]
@ruseinov Is this already done?

**Comment by KiChjang** [comment]
I think this has already been done in cumulus.
