### ISSUE TITLE
Implement `StagingValidityConstraints` Runtime API method

### ISSUE THREAD

**Issue by slumber** [paritytech/polkadot#6036]
A corresponding TODO
https://github.com/paritytech/polkadot/blob/2c215b21cbb00e4dac033892dc750958513c1295/runtime/parachains/src/runtime_api_impl/vstaging.rs#L29-L31
Called in
https://github.com/paritytech/polkadot/blob/2c215b21cbb00e4dac033892dc750958513c1295/node/core/prospective-parachains/src/lib.rs#L555-L569

**Comment by slumber** [comment]
cc @rphmeier

**Comment by rphmeier** [comment]
Yes. Worth noting that in #6014 we leaned heavier on the "Also, never cross session boundaries" part.

**Comment by eskimor** [comment]
Also make sure to use the new staging API functionality for this.

**Comment by slumber** [comment]
Resolved by #6258
