### ISSUE TITLE
Allow `RollingSessionWindow` to grow beyond `dispute_period`

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6040]
Currently, if finality stalls on testnets for more than `dispute_period`, we need to manually fix with sudo `forceApprove` calls.
By keeping sessions in window for all the unfinalized chain, finality will recover automatically. 

OOM is not a concern here, since `SessionInfo` is <10kb, so we can afford keeping thousands (months) of them in memory.

**Comment by eskimor** [comment]
Are there any other reasons approval-voting might permanently fail to approve a candidate?
