### ISSUE TITLE
No warning when using deprecated flag --prunning

### ISSUE THREAD

**Issue by tugytur** [paritytech/polkadot#6042]
`--prunning` got deprecated with [11934](https://github.com/paritytech/substrate/pull/11934).

It's backwards compatible but there is no warning shown when it's still used.

On startup it should show a warning to get people to update their flag to `--state-pruning`

**Comment by bkchr** [comment]
Why? We added `--pruning` as alias and that can stay. So, no need to show any warning or whatever.

**Comment by tugytur** [comment]
thanks for the info. I assumed it's eventually gonna be removed.

**Comment by tugytur** [comment]
> Why? We added `--pruning` as alias and that can stay. So, no need to show any warning or whatever.

thanks for the info. I assumed it's eventually gonna be removed.
