### ISSUE TITLE
Extract orchestra framework to separate repo

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot#6043]
Currently `orchestra` lives well hidden inside the tree, it be great to give it some more visbility out of tree and apply changes outside the stepping of polkadot releases.

Crates to be move to a separate repo would include:

`orchestra`
`orchestra-procmacro`
`prioritized-metered-channel`

This has been the long edge of @rphmeier and myself, with a plan to be used by us (current active impl).

Happy to (co-)maintain

CC @sandreim

**Comment by sandreim** [comment]
Thanks for the ticket @drahnr . As you probably know, the only concer here was about keeping things in sync with our internal usage in Polkadot, but overall it is definitely a good idea which I fully support as well.

Let's track the progress here and I'll take care of creating the new repository and migrating all `Orchestra` specific issues there.

**Comment by sandreim** [comment]
@drahnr would you also be interested in helping us maintain it ?
