### ISSUE TITLE
Check validity of chunks fetched from disk

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6070]
Otherwise in case of a database corruption we would raise a dispute, although nobody did anything wrong (and we would get slashed).

This happened in the wild:

```
Data recovery invalid for candidate (0xdda32ca1be4330913b93a701a4c84192b8934764e8ae0f13e72518d5e4e97357, Id(2124)) para_id=Id(2124) candidate_hash=0xdda32ca1be4330913b93a701a4c84192b8934764e8ae0f13e72518d5e4e97357 traceID=294606636697047689533880607601836179858\n","stream":"stderr","time":"2022-09-21T19:18:38.194880785Z"}
```

-> Also check for other occurrences, where we would accuse others in case of a hardware error/local problem.

**Comment by eskimor** [comment]
[Here](https://github.com/paritytech/polkadot/blob/ffed273daba5e5c66e917c09469e6a042b994ed8/node/network/availability-recovery/src/lib.rs#L499) we blindly assume that anything coming from disk must be correct.

**Comment by ordian** [comment]
As the comment says
https://github.com/paritytech/polkadot/blob/ffed273daba5e5c66e917c09469e6a042b994ed8/node/network/availability-recovery/src/lib.rs#L504-L505

recovery shoudn't happen for backers and hence at most 1 chunk is expected there.

**Comment by ordian** [comment]
Why do we request all chunks and not just our chunk there?

**Comment by sandreim** [comment]
should this be a checksum of the chunks that we store along the chunks themselves in DB ?

**Comment by eskimor** [comment]
> Why do we request all chunks and not just our chunk there?

This is recovery - we need n/3+1 chunks. But first we fetch our own chunk from disk (and don't check it again whether it is still valid). Which makes sense from a logical standpoint (it has been checked already), but that does not account for db corruptions.

**Comment by eskimor** [comment]
> recovery shoudn't happen for backers and hence at most 1 chunk is expected there.

yes, but then we use this one chunk for recovering, hence it will fail if it is garbage.

**Comment by ordian** [comment]
> This is recovery - we need n/3+1 chunks. But first we fetch our own chunk from disk (and don't check it again whether it is still valid). Which makes sense from a logical standpoint (it has been checked already), but that does not account for db corruptions.

Yes, I mean why `QueryAllChunks` instead of `QueryChunk` as this is not supposed to be called on backers?

> yes, but then we use this one chunk for recovering, hence it will fail if it is garbage.

Reed-Solomon should tolerate some amount of invalid chunk, it's used for error-correction in CDs for that purpose only.
I don't know that the threshold is for our parameters, but you can tweak the test here and see it works
https://github.com/paritytech/polkadot/blob/c620450de80f76e15a735a0d13efe4540d3053a0/erasure-coding/src/lib.rs#L370-L377

**Comment by ordian** [comment]
Ok, actually with 1 invalid chunks and (n-1)/3 + 1 overall it fails, but it can tolerate at least 1 invalid if you add more chunks.

**Comment by eskimor** [comment]
Yes, but we don't rely on correction as we are actually checking their validity (except for the one fetched from disk). I read that `QueryAllChunks` as get me all the chunks we have ... will usually be only 1, but if we had more for some reason, we should use them ... This used to be more likely where disputes stored the recovered chunks, which we no longer do.

**Comment by ordian** [comment]
> should this be a checksum of the chunks that we store along the chunks themselves in DB ?

I assume there checking chunks means checking merkle proofs which are included in https://github.com/paritytech/polkadot/blob/c620450de80f76e15a735a0d13efe4540d3053a0/node/primitives/src/lib.rs#L496.

**Comment by sandreim** [comment]
I see what you mean, that makes more sense
