### ISSUE TITLE
Master fails to build in Linux

### ISSUE THREAD

**Issue by elopio** [paritytech/polkadot#618]
I'm trying to build the current master in Debian 10. I get this error:

`error: linking with `cc` failed: exit code: 1`

Full log: https://paste.ubuntu.com/p/pJN9PZv39v/

Looking into the repo, it seems the same error happens on CI: https://gitlab.parity.io/parity/polkadot/-/jobs/310559
Apparently introduced by: https://github.com/paritytech/polkadot/pull/600

**Comment by bkchr** [comment]
Fixed in master
