### ISSUE TITLE
Tests for the Prospective Parachains subsystem

### ISSUE THREAD

**Issue by slumber** [paritytech/polkadot#6186]
There're [tests](https://github.com/paritytech/polkadot/blob/41e2f4d4f657b1a8eca4fe6c2a7ac906449961a1/node/core/prospective-parachains/src/fragment_tree.rs#L690) for the fragment tree implementation but not for the subsystem itself. It should be tested as well.

**Comment by m-cat** [comment]
Looks like there are already some tests for `prospective_parachains` in [`backing`](https://github.com/paritytech/polkadot/blob/rh-async-backing-feature/node/core/backing/src/tests/prospective_parachains.rs#L1). What tests do we still need?

**Comment by slumber** [comment]
> Looks like there are already some tests for `prospective_parachains` in [`backing`](https://github.com/paritytech/polkadot/blob/rh-async-backing-feature/node/core/backing/src/tests/prospective_parachains.rs#L1). What tests do we still need?

Test file name `prospective_parachains.rs` refers to testing backing behavior when async backing is enabled (= prospective parachains subsystem is enabled). 
https://github.com/paritytech/polkadot/blob/9f27a2f0e82ab1860e36e2ec45c88afa0209d1f2/node/core/backing/src/tests/prospective_parachains.rs#L17
It's similar to collator protocol
https://github.com/paritytech/polkadot/blob/9f27a2f0e82ab1860e36e2ec45c88afa0209d1f2/node/network/collator-protocol/src/collator_side/tests/prospective_parachains.rs#L17
However, it only tests that backing works, and cannot do otherwise, prospective parachains subsystem itself has 0 tests as of now.

An important thing to test is how prospective parachains handles activations and prunes candidates that leave the view. Does it collect candidate membership correctly? Does it return backable candidate with a required path provided?
And so on.

**Comment by mrcnski** [comment]
Closed in #6454
