### ISSUE TITLE
Introduce a `NetworkBridgeEvent::UpdatedAuthorityIds`

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#6192]
The current network logic doesn't handle the ability for peers to update their authority IDs (i.e. key rotation) very well. The network bridge should be continually updating its known authority IDs for each peer ID and informing subsystems of any changes so they can adapt accordingly.

**Comment by bkchr** [comment]
BTW, it can also happen the other way around, the peerid for an authorityid changes. Both sides can change and peerid can also change much more often than the authorityid.

**Comment by ordian** [comment]
> BTW, it can also happen the other way around, the peerid for an authorityid changes

That would imply that the node with an old PeerId will disconnect and with the new one connect. We already track `AuthorityId` changes on connection/disconnection.
