### ISSUE TITLE
Retry failed PVF execution

### ISSUE THREAD

**Issue by m-cat** [paritytech/polkadot#6195]
PVF execution that fails due to `AmbiguousWorkerDeath` should be retried once. This should reduce the occurrence of failures due to transient conditions.

This can be a good first step towards fully implementing https://github.com/paritytech/polkadot/issues/6102. (Based on recent conversations, it is unclear if we want that. But implementing this present issue would be useful regardless.)

**Comment by rphmeier** [comment]
Also possibly related: https://github.com/paritytech/polkadot/issues/2029

**Comment by m-cat** [comment]
@pepyakin I just had a talk with @ordian and he had a question. I'm writing it here so I don't forget, but it can wait until we have our discussion in-person.

The question is, should we always retry the failed execute job regardless of the calling subsystem and regardless of the specific cause of failure? The implication for me, is whether I implement this once in the PVF subsystem, or implement it on the caller side. The latter would be more general but might involve some duplication.

Not sure if that makes sense out of context but cc @eskimor

**Comment by eskimor** [comment]
Good point, retrying is mostly necessary during approval/disputes. Doing a retry in backing is not required and one could argue, we should not: Like if something is brittle to evaluate, depending on the actual reasons, we should rather not back it. In practice it should not matter much though, as if this was an attack you can also try again by just providing another similar candidate the next time. So I don't think not retrying in backing is worth any code complication. Especially given that this is an edge case we are talking here to begin with.

**Comment by eskimor** [comment]
Important: The retry should be delayed, I am thinking of something like at least a second. The longer the delay, the "safer". Any transient disturbing condition is more likely to have gone away already. On restarts, the restart is more likely to have happened/completed already, ... (hence the second try would not even happen in that case)

**Comment by pepyakin** [comment]
@eskimor well put,

I might add that in backing, there perhaps not much time to even retry execution.

**Comment by burdges** [comment]
Any idea what conditions cause `AmbiguousWorkerDeath`?

**Comment by eskimor** [comment]
OOM, restarts, ... the process gets killed by the operating system for some reason. @pepyakin knows better probably.
