### ISSUE TITLE
Test Versi with 40 validators and 60 parachains

### ISSUE THREAD

**Issue by tdimitrov** [paritytech/polkadot#6201]
Deploy the configuration above and observe the behaviour - the network should be able to survive such scenario. This means that parachains might stall, relay chain block time might degrade but after scaling back to normal conditions (10 parachains) the network recovers.

**Comment by tdimitrov** [comment]
@sandreim can we close this one? There root cause for the stall was the connectivity issues.

**Comment by sandreim** [comment]
I don’t think we tried this yet AFAIK.

**Comment by sandreim** [comment]
Tried this and the only issue I observed was that backing group rotations might not be fair wrt to all paras getting assigned to one. AFAIU this is not really supported, but at least we still this doesn't stall finality or break the chain in any way.
