### ISSUE TITLE
Don't fetch approval votes in dispute coordinator

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6207]
We agreed to only slash backers, so dispute-coordindator fetching approval votes as described in the guide is actually no longer necessary and can be removed.

Hence we can also close: https://github.com/paritytech/polkadot/issues/5864

**Comment by eskimor** [comment]
@BradleyOlson64 an easy one for you.

**Comment by burdges** [comment]
We're happy with this for now, and maybe for the foreseeable future, but we'd maybe put this back if we're every really happy with other solutions.

There is no reason for this distant future possibility to impacts removing this feature right now.  We're not a programing language so we do not obey the ["time traveller rule of 3"](https://github.com/rust-lang/rfcs/issues/1362#issuecomment-156116312).  ;)

**Comment by rphmeier** [comment]
Aren't approval votes necessary to reach supermajority in the case of a dispute of a valid block?

The slashing logic should be separated from the actual process of getting statements on-chain, and it seems to me that we actually need as many statements to get on-chain as possible.

**Comment by BradleyOlson64** [comment]
My understanding is that approval voters would still always be prompted to redistribute their vote via off chain dispute distribution. So we had redundency in vote distribution that was only necessary when we wanted to make sure bad approval votes receive slashes. This change wouldn't disrupt our ability to reach a supermajority unless my thinking is entirely off base.

**Comment by eskimor** [comment]
So, indeed I thought about this some more and also talked a bit with Jeff. It is true what Bradley mentioned, that we don't need approval votes for reaching super majority, because validators will either send their approval vote in dispute-distribution or they vote with an explicit vote (it is racing) - what exactly happens and what different trad-offs exist is documented in the guide.

What I was concerned about when implementing this, is that malicious approval voters would be able to just vote valid in approval voting without fearing any consequences, because when their DoS does not turn out to succeed they would just vote invalid via an explicit vote. Without other validators recording their approval vote, this would enable them to avoid the slash.

If we only slash backers this is a non-issue, buuut things are not that simple:
While we not necessarily need to make sure to slash malicious approval checkers, we should make as sure as possible to incentivize actually running the validation. So not slashing approval checkers is actually not an option for this reason and it is indeed premature to remove this code. 

@BradleyOlson64 what should change though is the reasoning in the guide, let's discuss today at some point and have that updated.

**Comment by eskimor** [comment]
One good outcome of this change of reasoning is, that it is less crucial to absolutely catch all approval voters in absolutely all cases, because well game theory. You are way less likely to go through extreme efforts just to be able to be lazy .. .as that kind of defeats the point of being lazy.

Hence, making it just very likely to get caught and punished voting valid for something that is invalid is enough to incentivize doing the work. I am particular referring to [this](https://github.com/paritytech/polkadot/issues/5864) ticket - handling that edge case should not be required anymore.

**Comment by rphmeier** [comment]
> validators will either send their approval vote in dispute-distribution or they vote with an explicit vote (it is racing) 

Don't we only queue participation if there is no own vote?

**Comment by eskimor** [comment]
No matter what, we are making sure to send our own vote to other validators. That vote can either be explicit due to participation or an already existing approval vote. By this we ensure we can reach super majority.

**Comment by eskimor** [comment]
I agree with the complexity of this part. Can be fixed by "just" storing approval votes always reliably and efficient - so not like we did last time. Something to revisit again when we get to rewarding approvals.
