### ISSUE TITLE
New proxy type for NominationPools 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot#6211]
A new variant that allows `NominationPools` calls. 

Not quite urgent, since most UIs don't support proxy that well yet.

**Comment by kianenigma** [comment]
cc @rossbulat

**Comment by kianenigma** [comment]
@Ank4n this is probably a 5 min job, just being forgotten :D

**Comment by xlc** [comment]
Should we just have a proxy variant `Pallet(PalletIndex)` and `Call(PalletIndex, CallIndex)` and automatically be 80% future proof with new pallets?

**Comment by kianenigma** [comment]
I have always been a fan of more flexible proxies that allow for specific call indices instead of pallets, but there has been push-back that for Polkadot we want to be conservative. 

That being said, now with https://github.com/paritytech/substrate/pull/12891, I think we should allow this.

**Comment by Ank4n** [comment]
> Should we just have a proxy variant `Pallet(PalletIndex)` and `Call(PalletIndex, CallIndex)` and automatically be 80% future proof with new pallets?

Created a separate issue for this here
https://github.com/paritytech/polkadot/issues/6847
