### ISSUE TITLE
Pass motion to enable pre-checking on Kusama + Polkadot

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6212]
Pass motion to enable [prechecking](https://github.com/paritytech/polkadot/blob/3eb61f8871220f2a17a98342382270782cdb4b0c/runtime/parachains/src/configuration.rs#L221).

@bkchr The mentioned go ahead signal: Do you have insights whether this is already honored by all deployed parachains on Polkadot and Kusama?

Prior to this we have to make sure 0.9.30 is rolled on a super majority of validators (the necessary node side changes are contained there).

@slumber how are things looking on Rococo/Westend? Have we enabled yet? - disregard, I just saw the messages. Thanks!

**Comment by ordian** [comment]
On Rococo, do we need to include `Paras::ValidateUnsigned` here https://github.com/paritytech/polkadot/blob/d17ee12922b069423b0d9eb562d579eaebe0940e/runtime/rococo/src/lib.rs#L1388 as Babe does https://github.com/paritytech/polkadot/blob/d17ee12922b069423b0d9eb562d579eaebe0940e/runtime/rococo/src/lib.rs#L1315

https://github.com/paritytech/polkadot/blob/d17ee12922b069423b0d9eb562d579eaebe0940e/runtime/parachains/src/paras/mod.rs#L977-L978

**Comment by eskimor** [comment]
I am confused, aren't we using the Rococo runtime on Versi? Hence how did this work on Versi if it now fails on Rococo?

**Comment by eskimor** [comment]
Ok, Polkadot and Kusama need this as well. This means we need another runtime upgrade before being able to enable it. Ok, I'll make a PR.

**Comment by eskimor** [comment]
https://github.com/paritytech/polkadot/pull/6214

**Comment by bkchr** [comment]
> @bkchr The mentioned go ahead signal: Do you have insights whether this is already honored by all deployed parachains on Polkadot and Kusama?

I think this was rolled out quite some time ago. Aka it should be already available on all parachains.
