### ISSUE TITLE
Node-side metrics for asynchronous backing

### ISSUE THREAD

**Issue by slumber** [paritytech/polkadot#6236]
There're several places with a potential of being a hotspot. We should introduce metrics for them to aid debugging during the testing phase.
Namely:
https://github.com/paritytech/polkadot/blob/0f3ef99e0277832aa8967d6ac552fd28c2cb7535/node/core/prospective-parachains/src/lib.rs#L245-L247

https://github.com/paritytech/polkadot/blob/0f3ef99e0277832aa8967d6ac552fd28c2cb7535/node/network/collator-protocol/src/validator_side/mod.rs#L1325-L1332

And maybe some more (@rphmeier ?)

**Comment by mrcnski** [comment]
Closed by https://github.com/paritytech/polkadot/pull/6549.
