### ISSUE TITLE
Add a light client code that compiles in the browser

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot#625]
Let's open the Polkadot equivalent of https://github.com/paritytech/substrate/issues/2416

Just like in Substrate, we should progressively make crates compile for `wasm32-unknown-unknown` and add CI checks to prevent PRs from breaking the build (as in https://github.com/paritytech/substrate/blob/25b99d47832b7485082bf98232b66e0779b82713/.gitlab-ci.yml#L219-L231).

**Comment by tomaka** [comment]
Some update here: it is possible to compile Polkadot for the browser, and it works well.

**Comment by rphmeier** [comment]
done with smoldot
