### ISSUE TITLE
implementers-guide: Add section for PVF module

### ISSUE THREAD

**Issue by m-cat** [paritytech/polkadot#6263]
# ISSUE

## Overview

We have a section for the `pvf-checker` subsystem, but not `pvf`. This is its
own module which includes preparation and execution of PVFs, and does not
seem to be documented right now.

## Possible outline

- [ ] Callers and entrypoint
- [ ] Artifacts
- [ ] Preparation
  - [ ] Flow
  - [ ] Timeouts
  - [ ] Retrying
- [ ] Execution
  - [ ] Flow
  - [ ] Retrying
- [ ] Sessions and execution environments

**Comment by slumber** [comment]
small note: unlike `pvf-checker`, it's not a subsystem
