### ISSUE TITLE
Parathreads shouldn't be allowed in Slot Auctions, right?

### ISSUE THREAD

**Issue by Chralt98** [paritytech/polkadot#6272]
https://github.com/paritytech/polkadot/blob/a59c120ce8d63ae6e0ba0a365d98ea9142a6b770/runtime/common/src/auctions.rs#L430

```rust
/// Return if a `ParaId` is registered in the system.
fn is_registered(id: ParaId) -> bool {
      Self::is_parathread(id) || Self::is_parachain(id)
}
```

Example: slot auction bid for para id `2230` on Kusama, in which it was a parathread.

**Comment by Chralt98** [comment]
If it should be like it is now. What should happen when the Parathread is deregistered? Assume a Parathread wins an auction, but it was deregistered before. So, then another lucky Registerer could get the Parachain slot for free?

**Comment by shawntabrizi** [comment]
Right now there is only two states for a Para. It can be a Parathread or a Parachain. If you are a parathread, of course you can bid for a slot to get a parachain.

> Assume a Parathread wins an auction, but it was deregistered before. So, then another lucky Registerer could get the Parachain slot for free?

No, if a parathread deregisters itself before it onboards, then the onboarding will fail, and no new parachain will be allocated. This is fine, if we want we can run a new auction, and this is not something anyone is incentivized to do.

**Comment by Chralt98** [comment]
So, deregister is not incentivised, but why would anyone like to shoot themselves in the foot? What if somebody called "deregister" accidentally?

**Comment by shawntabrizi** [comment]
What if you accidentally send your bitcoin to the wrong address? Or you accidentally chose the wrong gas price when making a transaction?

It is not the goal of blockchains to create arbitrary checks and rules. It makes code more complex and more vulnerable to mistakes. There is functionality to deregister a para, which makes sense if you want to clean up your data. If you accidentally call that function, that is your fault.

In any case, most everything is repairable via governance if something really bad happens as a result of an action like this.

**Comment by Chralt98** [comment]
Let us keep the good mood up. Everything is fine 😇. Thanks so much for your answers. It is really valuable for me.

Your example with the bitcoin transaction is perfect.
