### ISSUE TITLE
provisioner: prioritize backing votes for disputes

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6274]
See https://github.com/paritytech/polkadot/pull/6249/#discussion_r1020534300 for the context.

With our slashing design centered around backers for both valid and invalid cases and in the light of #6249, we should always prioritize missing backing votes when selecting votes for a dispute set.

- [ ] Add a test in provisioner that we if there are missing backing votes on-chain, we always select them.

**Comment by eskimor** [comment]
@BradleyOlson64 This should be fairly simple as well.

**Comment by eskimor** [comment]
Not only prioritize, but make sure there are always imported - even if the chain already knows about some valid votes for those validators.

**Comment by BradleyOlson64** [comment]
The first issue I'm seeing is that we import votes to the provisioner from the disputes subsystem in an order that can't account for backing votes specifically. It only knows about which disputes to prioritize, not which votes to prioritize.

I think a solution might be to set up another call similar to `request_votes` called `request_backing_votes`. Not sure how easy it would be to support such a call from the dispute subsystem side, but without it I don't see how we could guarantee all unknown backing votes get into the dispute set.

**Comment by ordian** [comment]
Heads up: in #6249 I implement the following logic

> // We allow backing statements to be imported after 
> // explicit "for" vote, but not the other way around.

This makes it easier to implement slashing with our currrent design and should be fine considering
> /// Backers should not participate in explicit voting so this only possible on malicious backers.

That means if we select a backing vote (if it's not present already), we should not select an explicit "Valid" vote in the same set. 
 
 > It only knows about which disputes to prioritize, not which votes to prioritize.
My understanding is vote selection in provisioner (in the new version) happens in https://github.com/paritytech/polkadot/blob/b4b3fa59bb959a50db1435c9e85eeab16cbdd1b3/node/core/provisioner/src/disputes/prioritized_selection/mod.rs#L168

**Comment by ordian** [comment]
The issue was closed, but I don't see it being actually fixed or am I missing something (and the test is missing)?
If an attacker places an explicit "for" vote and "against" vote, wouldn't it backing vote be filtered by the next honest block author?
Here 
https://github.com/paritytech/polkadot/blob/6a5d31fcbdd3ac5dd880e0bf3616e303b5bb480f/node/core/provisioner/src/disputes/prioritized_selection/mod.rs#L200

https://github.com/paritytech/polkadot/blob/6a5d31fcbdd3ac5dd880e0bf3616e303b5bb480f/node/core/provisioner/src/disputes/prioritized_selection/mod.rs#L384-L387

**Comment by ordian** [comment]
Another way to solve this problem is to ensure backers never participate in disputes in the first place as they shouldn't.

**Comment by ordian** [comment]
As discussed on the call, we can get away with this problem by not allowing importing disputes votes without backing threshold backing votes. We already check it's non-empty in #6249, but we can also check for a threshold.

**Comment by ordian** [comment]
> We already check it's non-empty in https://github.com/paritytech/polkadot/pull/6249, but we can also check for a threshold.

Actually, checking for a minimum_backing_votes is a bit tricky. We'd need to know the validator group size, which is not readily available in the disputes context.

It would still be nice for the provisioner to include the remaining backing votes even if explicit "for" votes has been placed on chain, so we can slash as many backers as possible. Provisioner has the information about kinds of valid votes.

**Comment by eskimor** [comment]
Yes, let's modify the filtering in the provisioner to never filter backing votes, even if the chain knows about them.

**Comment by eskimor** [comment]
@BradleyOlson64 We do indeed filter votes and not only full disputes [here](https://github.com/paritytech/polkadot/blob/6f74775a7b61b4017f7c73e94d105396780eb066/node/core/provisioner/src/disputes/prioritized_selection/mod.rs#L199). We need to modify this to never filter backing votes, even if the chain knows about valid votes for that validator.

**Comment by BradleyOlson64** [comment]
This should do the trick https://github.com/paritytech/polkadot/pull/6494
