### ISSUE TITLE
Audit runtime for consensus issues between native & wasm

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#63]
- Check edge conditions in externalities are handled equivalently between native & wasm.
- Check for platform-dependent gotchas (e.g. unguarded use of `usize`) between native & wasm.

**Comment by rphmeier** [comment]
> unguarded use of usize

this could be completely prevented by not having an implementation of `EndianSensitive` for `usize`

**Comment by pepyakin** [comment]
@rphmeier FWIW, https://github.com/laumann/compiletest-rs

**Comment by rphmeier** [comment]
I'm aware of that, but it doesn't compile on stable :\
