### ISSUE TITLE
Log `ru_maxrss` from `getrusage` for PVF workers

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#6317]
# ISSUE

## Overview

[Original comment](https://github.com/paritytech/polkadot/pull/6282#issuecomment-1320152401) by @eskimor:

> ru_maxrss ... could be interesting. By checking the amount of memory used, we might get a better heuristic on whether something is likely valid, but the machine has issues or likely invalid (excessive RAM usage). Don't have a clear strategy, seems very brittle at first thought.

We decided that just logging it for now would be nice.

**Note:** The `cpu_time` crate also has support for Windows. Not sure if Windows has something like `ru_maxrss`. Do we care?

## Related Links

Follow-up from https://github.com/paritytech/polkadot/pull/6282.

**Comment by mrcnski** [comment]
Don't think either Windows nor MacOS supports this; see [here](https://docs.rs/libc/0.2.66/src/libc/unix/mod.rs.html#1026). We might be able to get similar data with `tikv-jemalloc-ctl`, as described in https://github.com/paritytech/polkadot/issues/6472.

**Comment by bkchr** [comment]
We don't really support macos nor windows officially for validators. We merge fixes and ensure that it compiles for these targets, but if it not supporting all features it should be okay.

**Comment by vstakhov** [comment]
`struct rusage` is not really defined by POSIX standard, so Darwin and Windows are free to do whatever they like here, I'm afraid. However, at least in the recent OSX versions, `getrusage` has the field:

```c
 long ru_maxrss;          /* max resident set size */
 ```

**Comment by mrcnski** [comment]
> Don't think either Windows nor MacOS supports this; see [here](https://docs.rs/libc/0.2.66/src/libc/unix/mod.rs.html#1026).

Actually, I tried it and it seems like MacOS does support `max_rss` (though not Windows). I'm not really sure what I was looking at in that link TBH. 😅
