### ISSUE TITLE
CI: add clippy checks

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6332]
Steps:
- [ ]  Introduce a list of lints that we don't want to fix straight away similar to https://github.com/paritytech/substrate/blob/master/.cargo/config.toml
- [ ] Fix the rest of the clippy warnings: `cargo clippy --fix`
- [ ] Introduce a CI check for clippy similar to Substrate's: https://github.com/paritytech/substrate/blob/6cb4b6799de6f784f4c42eb01a76a8fa67039a67/scripts/ci/gitlab/pipeline/test.yml#L38-L52

**Comment by bkchr** [comment]
> * Introduce a list of lints that we don't want to fix straight away similar to https://github.com/paritytech/substrate/blob/master/.cargo/config.toml

It should be exactly the same config. We should not use different confings in our repos.

**Comment by ordian** [comment]
> > * Introduce a list of lints that we don't want to fix straight away similar to https://github.com/paritytech/substrate/blob/master/.cargo/config.toml
> 
> It should be exactly the same config. We should not use different confings in our repos.

We could initially allow more lints to fail and fix them gradually. 
There are also some lints in Substrate that could be fixed in Polkadot (I haven't actually checked, but in theory), e.g. 
> "-Aclippy::borrowed-box",              # Reasonable to fix this one

We shouldn't wait for substrate to fix it first.
