### ISSUE TITLE
Kusama governance proxies should include OpenGov/Gov2 pallets

### ISSUE THREAD

**Issue by laboon** [paritytech/polkadot#6333]
https://github.com/paritytech/polkadot/blob/9a994265d0229d1f64a8039bc4601748c3d5140a/runtime/polkadot/src/lib.rs#L1207

Right now, it appears that only Gov v1 pallets are allowed via Governance proxies. I would assume that OpenGov/Gov2 pallets (ConvictionVoting, Referenda) would also be included as allowable calls via such proxies.

**Comment by ironoa** [comment]
maybe related: also the [delegation feature](https://polkadot.network/blog/gov2-polkadots-next-generation-of-decentralised-governance/#agile-delegation) seems not working yet. I tried to setup both a democracy(delegate) and a 
convictionvoting(delegate) delegations on Kusama, but neither one of them two seems to produce the effect of having a referenda vote from the delegated account backed by the added power of the delegator account.
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/25957738/203986206-444364d0-22e7-4203-a38c-84109792f9d4.png">
Am I missing something ?
