### ISSUE TITLE
`approval-distribution` aggression should only trigger based on approval checking lag

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot#6414]
Currently it is triggering based on relay chain lag: `best - finalized`

**Comment by ordian** [comment]
We might consider removing l2 aggression level. There is no evidence it actually helps anything.

**Comment by sandreim** [comment]
I also did not find any evidence that it helps overall, but I didn't test this long enough and in harsh network environments where it is supposed to help.

**Comment by sandreim** [comment]
Going to implement this. I still consider removing it but, TBH I think it would still be useful if it triggers only when network issues occur.
