### ISSUE TITLE
Era 4543 with runtime 9340

### ISSUE THREAD

**Issue by rcrvano** [paritytech/polkadot#6420]
Hello. 

Can you tell me please why the "EraPaid" event does not appear in runtime #9340? 
I see that the last era #4543 is active for more than 3 days and more than 40.000 blocks?

Last event "Staking.EraPaid" was detected in block 15.675.064 for era 4542
https://kusama.subscan.io/event?block=15675064&page=2
 
Last finalized block is 15.715.470
and here I see that the 4543 era is still active 
https://kusama.subscan.io/validator

**Comment by bkchr** [comment]
AFAIK because there are no elections currently. Because of the issues last friday.

CC @kianenigma

**Comment by FrodoBaggins74524** [comment]
Possible reasons could include:

The event is not being emitted correctly by the smart contract or runtime
There is a bug in the system that is preventing the event from being recorded or processed
The system is not configured correctly to handle or display the event
There is an issue with the block explorer or the way you are accessing the event data
It's worth to check the smart contract code, the configuration and the system logs to see if there are any errors or issues that could be causing this problem.
