### ISSUE TITLE
[ci]: `check-transaction-versions` job doesn't work the `git fetch origin release` is wrong

### ISSUE THREAD

**Issue by niklasad1** [paritytech/polkadot#6422]
The `check-transaction-versions` is trying to fetch origin `release` which doesn't exist, so that has probably never worked.
https://github.com/paritytech/polkadot/blob/master/scripts/ci/gitlab/pipeline/build.yml#L56 is the cause of that.

[See failed job here](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2145795)

It should most likely find `release-v<some version>` or the latest tag.

//cc @paritytech/ci

**Comment by alvicsam** [comment]
Hm, it's strange. It worked previously https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2143528

**Comment by coderobe** [comment]
> Hm, it's strange. It worked previously https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2143528

that output is wrong too, though. best just allow-failure: true for the time being as it's not working correctly and breaking companion merges and such. we double-check transaction version when releasing anyway.

**Comment by alvicsam** [comment]
> we double-check transaction version when releasing anyway.

should we have this job in the pipeline then?
