### ISSUE TITLE
where is the official docker image for v0.9.35 and v0.9.34

### ISSUE THREAD

**Issue by nuaays** [paritytech/polkadot#6435]
I have checked  https://hub.docker.com/r/parity/polkadot/tags

there is no the docker image for version v0.9.35 and v0.9.34

**Comment by bkchr** [comment]
These were runtime only releases, so no node release which required a new docker image.

**Comment by nuaays** [comment]
@bkchr then shoule we need to update the runtime to the latest version ? and how to?
thanks

**Comment by bkchr** [comment]
This happens on chain, nothing you need to do

**Comment by nuaays** [comment]
thanks @bkchr 
BTW, we are using local chain node with the version parity/polkadot:v0.9.33
