### ISSUE TITLE
nginx / proxy_set_header Host $host

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/polkadot#6438]
I couldn't make the following guide work on my end: "[Set up Secure WebSocket for Remote Connections"](https://wiki.polkadot.network/docs/maintain-wss)

In particular, I would get the following error in my Polkadot or Kusama node log:
```2022-12-14 08:39:28 Accepting new connection 1/100
2022-12-14 08:39:28 Rejected connection: HttpHeaderRejected("host", "mydomainname.tld")
```

Now, if I replace `proxy_set_header Host $host;` with `proxy_set_header Host localhost:9944;` I do not get this issue anymore.

Maybe I am doing something wrong and my approach has negative tradeoffs, but I thought I would report my situation in case it would be useful.

Also this could be wrong, but it seems[0] `ipv6only=on` is now implied (default). 

Personally, instead of:
```
listen [::]:443 ssl ipv6only=on;
listen 443 ssl;
```
I simply use:
```
listen [::]:443 ssl;
listen 443 ssl;
```

This could probably be simplified with a one-liner including `ipv6only=off`

[0] https://serverfault.com/a/638370

**Comment by BulatSaif** [comment]
Thank you for submitting the issue.  
The guide which you provided should work, check that your polkadot/kusama node has `--rpc-cors all` flag set. 

Note: if Nginx and polkadot/kusama node on different VM or containers you also should set:
```
--unsafe-rpc-external 
--unsafe-ws-external 
```

**Comment by LukeWheeldon** [comment]
Ah indeed, I was missing this flag. Thanks a lot @BulatSaif!
