### ISSUE TITLE
CI: check_labels job is broken

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#6441]
I assume someone renamed the labels and now https://github.com/paritytech/polkadot/blob/master/scripts/ci/github/check_labels.sh#L26 is failing. The check should be adjusted to new labels.

Example: #6187, https://github.com/paritytech/polkadot/actions/runs/3702313961/jobs/6272452336

cc @the-right-joyce

**Comment by the-right-joyce** [comment]
Hi, we're working on it. Will be fixed by today.

**Comment by sandreim** [comment]
still broken ?  https://github.com/paritytech/polkadot/actions/runs/3702819109/jobs/6273526204

**Comment by the-right-joyce** [comment]
`B1-note_worthy` also reverted to` B1-releasenotes`
Should work now
