### ISSUE TITLE
Polkadot primitives versioning

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot#6480]
A necessity to bump the primitives' version to the next one results in 2000+ lines of PR. The actual logic of such a PR gets buried under purely technical changes of versioning. (See #6161)

The problem is that primitives are referred by their current version, and bumping the version requires moving all the primitives to a new module with a higher version number. So, any source referring to a primitive (that is, effectively, every source file of Polkadot) needs to be altered only to adopt that simple change: `use polkadot_primitives::v2` -> `use polkadot_primitives::v3`.

The proposal is to reexport all the primitives not currently requiring versioning in the root of the `polkadot_primitives` crate.

That is, if we have a `StablePrimitive` that does not change from `v1` to `v2` and an `UpgradedPrimitive` which changes from `v1` to `v2`, `primitives/src/lib.rs` would look like the following:

```rust
pub mod v1;
pub mod v2;
pub use v2::StablePrimitive;
```

Thus, any module referring to `polkadot_primitives::StablePrimitive` doesn't need to be changed to adopt a new version in which the primitive did not change anyway. Still, if a module uses `UpgradedPrimitive`, it is forced to explicitly choose between either `v1` or `v2` as we have two different versions of the primitive.

A further upgrade to `v3` would involve changes in the `polkadot_primitives` crate root and point changes to the code using primitives that became versioned during the upgrade, and it will not be as awfully polluting as it is right now.

CC @rphmeier @eskimor @tdimitrov

**Comment by eskimor** [comment]
I think that makes sense and is a good idea.

Further upgrade path would be:

1. We introduce v3 - same game.
2. We deprecate/remove v1: Anything that is the same in v2 and v3 is now "stable" can now be imported directly via the root module as well.

If we change a primitive like `SessionInfo` this would hardly result in less code changes though (as it is used everywhere). Would be an argument to be a bit conservative about what to add/change to/in `SessionInfo`.

Orthogonal: If we need to change a primitive that is used so much, we should probably make it two PRs. Where one is just about the introduction of the new/changed primitive.
