### ISSUE TITLE
diener not parsing Cargo.toml under new workspace syntax

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot#6485]
Diener version: v0.4.2
IDE: VS Code

Both rust analyzer on the latest version and `diener` are failing to pass Cargo.toml files now they have the `authors.workspace = true` syntax in them. I've attempted to update toolchains to latest versions with no joy. Rust analyzer can be disabled, but diener is required in my workflow to test migrations / companions.

```
Error: "Failed to parse `/Users/macbookpro/polkadot/polkadot/Cargo.toml` as `Cargo.toml`: TomlError { message: \"TOML parse error at line 11, column 8\\n   |\\n11 | authors.workspace = true\\n   |        ^\\nUnexpected `.`\\nExpected `=`\\n\" }"
```

**Comment by kianenigma** [comment]
You can use cargo path overrides as well https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#paths-overrides.

**Comment by bkchr** [comment]
It is already fixed in the latest git version of diener, I will push it to crates.io. I don't have any problems with rust analyzer, you should update it to the latest version.
