### ISSUE TITLE
error: failed to run custom build command for `librocksdb-sys v5.11.3`

### ISSUE THREAD

**Issue by tianyinoo** [paritytech/polkadot#65]
when running command  "cargo build", this error occurs. I want to know how to solve it, thanks!

**Comment by seunlanlege** [comment]
![screenshot from 2019-01-08 12-04-50](https://user-images.githubusercontent.com/16494314/50827027-a98c7c80-133d-11e9-94c6-c92a1cec02cd.png)

**Comment by pepyakin** [comment]
Hm, I'm not that acquainted with librocksdb-sys, but does it actually depends on libssl?
@tianyinoo what does the log say?

**Comment by tianyinoo** [comment]
I have solved the problem. Because when I run the command "sudo apt install make clang pkg-config libssl-dev", clang isn't installed or updated.

**Comment by Hilobrain** [comment]
This is an old thread but I am interested in how did you solve this problem?

**Comment by ElleryHao** [comment]
met this now in windows,

**Comment by clearloop** [comment]
OSX in CI now.

**Comment by niklasad1** [comment]
@clearloop 

Exit code 126 implies that you don't have sufficient privileges to execute the script, please make sure that you haven't fetched the `librocksdb-sys` as root or something

**Comment by clearloop** [comment]
> @clearloop
> 
> Exit code 126 implies that you don't haven't sufficient privileges to execute the script, please make sure that you haven't fetched `librocksdb-sys` as root or something

Fixed after this: https://github.com/shamb0/substrate/commit/2b5ebd874e1127e4a2387d845b14117b8a7ea8e8

**Comment by armanriazi** [comment]
#rustup component add --toolchain=nightly rust-src rustfmt
`rustup target add wasm32-unknown-unknown`
#apt-get install llvm clang linux-headers-"$(uname -r)" #
```
apt install llvm clang
cargo build --release
```
#cargo fix --allow-dirty
#cargo fix --edition

> #ArmanRiazi.Blockchain

**Comment by csx12588** [comment]
win11子系统Ubuntu ，今天遇到了该问题
