### ISSUE TITLE
Problem with creating blocks in v0.7.6 and v0.7.7

### ISSUE THREAD

**Issue by illlefr4u** [paritytech/polkadot#650]
I'm in validator set, have a heartbeat message, but cant create the block at v0.7.6 and v0.7.7 on Kusama.
I get the following message: "Failed to fetch block body for imported block".

![kusama0312](https://user-images.githubusercontent.com/21253681/70081489-69825800-15e7-11ea-9f0b-d17283f9862a.png)

**Comment by gavofyork** [comment]
should be sorted with #652
