### ISSUE TITLE
is the state_getStorage disabled in Kusams-cc3?

### ISSUE THREAD

**Issue by freddieee** [paritytech/polkadot#651]
Hi, I was using RPC call `state_getStorage` to query the substrate data on Kusama-cc2. After upgrading to Kusama-cc3, I found this rpc call returns nothing.

For example
One of the  curl command I am using to do the query is 
`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_getStorage", "params": ["0x8cb577756012d928f17362e0741f9f2c"]}' localhost:9933`, which returns 
`{"jsonrpc":"2.0","result":null,"id":1}`

Note: 0x8cb577756012d928f17362e0741f9f2c is the 128 bits hash of "System Number"(api.query.system.number)

**Comment by bkchr** [comment]
We did change the how the keys are build. https://github.com/paritytech/substrate/blob/fc6914cdb8c322cea8a4591bbf9566dd23bfd143/frame/support/procedural/src/lib.rs#L66 see here on how it is build.
