### ISSUE TITLE
pvf: We don't add an execution request when retrying preparation

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#6535]
# ISSUE

## Overview

On repeated execution requests where the preparation previously failed, we retry the preparation under certain conditions:

https://github.com/paritytech/polkadot/blob/30005e6b6e/node/core/pvf/src/host.rs#L527

However, I noticed that we don't do anything with `result_tx` in this case. I think we are missing a line:

```rs
// Add an execution request that will wait to run after this prepare job has finished.
awaiting_prepare.add(artifact_id, execution_timeout, params, result_tx);
```

I can't remember if there was a reason I left this out, but it seems like a mistake. cc @slumber

**Comment by slumber** [comment]
Yes, the sender gets dropped. Please also extend a test to ensure that it doesn't happen (`try_recv` doesn't return `Err(Canceled)`)
