### ISSUE TITLE
api.rpc.payment.queryInfo

### ISSUE THREAD

**Issue by xihucuyu888** [paritytech/polkadot#654]
i start a local testnet chain and when i call api.rpc.payment.queryInfo, the node print logs as below

0|alice_ksm  | 2019-12-04 13:48:30 Starting parachain attestation session on top of parent 0x13e86e9a01b939925b8b5621eed29651e75ce1fb1b2f5d892e3ef73ddf9647a4. Local parachain duty is Some(LocalDuty { validation: Relay, index: 1 })
0|alice_ksm  | ====================
0|alice_ksm  | Version: 0.7.6-7754bea-x86_64-linux-gnu
0|alice_ksm  | stack backtrace:
0|alice_ksm  |    0: sp_panic_handler::set::{{closure}}
0|alice_ksm  |    1: std::panicking::rust_panic_with_hook
0|alice_ksm  |              at src/libstd/panicking.rs:477
0|alice_ksm  |    2: std::panicking::continue_panic_fmt
0|alice_ksm  |              at src/libstd/panicking.rs:380
0|alice_ksm  |    3: rust_begin_unwind
0|alice_ksm  |              at src/libstd/panicking.rs:307
0|alice_ksm  |    4: core::panicking::panic_fmt
0|alice_ksm  |              at src/libcore/panicking.rs:85
0|alice_ksm  |    5: core::result::unwrap_failed
0|alice_ksm  |              at src/libcore/result.rs:1165
0|alice_ksm  |    6: <futures::future::map::Map<A,F> as futures::future::Future>::poll
0|alice_ksm  |    7: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
0|alice_ksm  |    8: <futures::future::either::Either<A,B> as futures::future::Future>::poll
0|alice_ksm  |    9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
0|alice_ksm  |   10: futures::future::chain::Chain<A,B,C>::poll
0|alice_ksm  |   11: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
0|alice_ksm  |   12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
0|alice_ksm  |   13: <futures::future::either::Either<A,B> as
0|alice_ksm  | futures::future::Future>::poll
0|alice_ksm  |   14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
0|alice_ksm  |   15: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
0|alice_ksm  |   16: futures::task_impl::std::set
0|alice_ksm  |   17: std::panicking::try::do_call
0|alice_ksm  |   18: __rust_maybe_catch_panic
0|alice_ksm  |              at src/libpanic_unwind/lib.rs:80
0|alice_ksm  |   19: tokio_threadpool::task::Task::run
0|alice_ksm  |   20: tokio_threadpool::worker::Worker::run_task
0|alice_ksm  |   21: tokio_threadpool::worker::Worker::run
0|alice_ksm  |   22: std::thread::local::LocalKey<T>::with
0|alice_ksm  |   23: std::thread::local::LocalKey<T>::with
0|alice_ksm  |   24: std::thread::local::LocalKey<T>::with
0|alice_ksm  |   25: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
0|alice_ksm  |   26: std::thread::local::LocalKey<T>::with
0|alice_ksm  |   27: std::thread::local::LocalKey<T>::with
0|alice_ksm  |   28: std::sys_common::backtrace::__rust_begin_short_backtrace
0|alice_ksm  |   29: std::panicking::try::do_call
0|alice_ksm  |   30: __rust_maybe_catch_panic
0|alice_ksm  |              at src/libpanic_unwind/lib.rs:
0|alice_ksm  | 80
0|alice_ksm  |   31: core::ops::function::FnOnce::call_once{{vtable.shim}
0|alice_ksm  | }
0|alice_ksm  |   32: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>
0|alice_ksm  | ::call_once
0|alice_ksm  |              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
0|alice_ksm  |   33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
0|alice_ksm  |              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
0|alice_ksm  |       std::sys_common::thread::start_thread
0|alice_ksm  |              at src/libstd/sys_common/thread.rs:13
0|alice_ksm  |       std::sys::unix::thread::Thread::new::thread_start
0|alice_ksm  |              at src/libstd/sys/unix/thread.rs:79
0|alice_ksm  |   34: start_thread
0|alice_ksm  |   35: clone
0|alice_ksm  | Thread 'event.loop0' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', src/libcore/result.rs:1165
0|alice_ksm  | This is a bug. Please report it at:
0|alice_ksm  | 	https://github.com/paritytech/polkadot/issues/new

**Comment by gavofyork** [comment]
@jacogr are you using this API?

**Comment by jacogr** [comment]
Not yet since it kills the node. There has been a fix to JSONRPC that makes this work (underlying serde issues), it has not made it into Substrate as of yet. 

cc @bkchr

**Comment by tomusdrw** [comment]
@jacogr @bkchr will submit a workaround for this to substrate repo shortly.
