### ISSUE TITLE
FundNotEnded: You can't start a crowdloan if the previous crowdloan backs your current lease

### ISSUE THREAD

**Issue by Tomen** [paritytech/polkadot#6592]
# How to produce the issue:
- Win a crowdloan to obtain LP 1 - 8
- In LP 8, have an auction for LP 9-16
- Try to crowdloan.create a new crowdloan for LP 9-16

# Actual Outcome:
The extrinsic fails on: https://github.com/paritytech/polkadot/blob/dfa8c5ae321e0523f88fdc43afc6d743812ee49e/runtime/common/src/crowdloan/mod.rs#L412

# Expected Outcome:
Creating a new crowdloan should be possible

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by Tomen** [comment]
related #6685

**Comment by Tomen** [comment]
duplicate of #4758
