### ISSUE TITLE
Get stats on actual perparation durations in PVF

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6607]
I believe preparation for PVFs in the size of a few megabytes is actually very fast. Would be good to confirm this and then set a way lower preparation timeout in PVF pre-checking to tackle [this concern](https://github.com/paritytech/polkadot/pull/6551/files#r1069622776).

E.g. if we never ever saw a preparation take longer than 500ms over a month, a pre-checking timeout of 1s or 1.5s should be plenty.

**Comment by bkchr** [comment]
> I believe preparation for PVFs in the size of a few megabytes is actually very fast.

I would argue that the size of the PVFs is not the most impactful factor for the preparation time, I would assume that it is the complexity of the code to compile. Complexity will probably also influence the size of the wasm code, but we should ensure that these big PVFs are not just a result of putting garbage into the binary.

**Comment by eskimor** [comment]
PVF preparation times seem to be in the range of seconds, hence persisting PVFs over restarts (not clearing) will likely be a good optimization for the upcoming parathreads.

Nevertheless if the node gets upgraded in an incompatible way, then all those artifacts will still become invalidated and will be cleared. Hence no-show delays must take preparation time into account, to avoid pointless escalations on network upgrades.

**Comment by bkchr** [comment]
> PVF preparation times seem to be in the range of seconds, hence persisting PVFs over restarts (not clearing) will likely be a good optimization for the upcoming parathreads.

AFAIR we already had persisting at the beginning and removed it, because of bugs :P
