### ISSUE TITLE
`av-store`: use pruning interval measured in blocks

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot#6611]
We currently use seconds:
```
/// Unavailable blocks are kept for 1 hour.
const KEEP_UNAVAILABLE_FOR: Duration = Duration::from_secs(60 * 60);

/// Finalized data is kept for 25 hours.
const KEEP_FINALIZED_FOR: Duration = Duration::from_secs(25 * 60 * 60);

/// The pruning interval.
const PRUNING_INTERVAL: Duration = Duration::from_secs(60 * 5);
```

From an operational perspective, it would be better to have this data persist until any potential finality issue is solved. If finality stalls, block production will slow down and we'll have plenty of time to check any of the parachain blocks rather than rely on a centralised service like `https://povs.today/`.

**Comment by ordian** [comment]
What is problem we're solving here? 

We prune finalized state after 25 hours in av-store. Unfinalized state is *not* pruned. 

The reasons to keep finalized data available could be:
1. A parathread collator produce a block and disappear for a day and another collator should be able recover the state.
2. Inspecting the state manually in case there's a suspicious of dishonest (super-)majority attack.

Using block-based intervals could help with 2. Maybe. But I question the effort (+ db migration) vs benefit ratio here.

**Comment by sandreim** [comment]
> What is problem we're solving here?
It's only about 2. It gives that data more time to live, assuming finality has stalled and block production slows down as well.

> Using block-based intervals could help with 2. Maybe. But I question the effort (+ db migration) vs benefit ratio here.
Hard to reason about benefit in general, since this is helpful only if we have a really big problem and we want to manually inspect.

I'm inclined to keep this in the backlog as a nice to have, but  maybe we'd never need it.

**Comment by rphmeier** [comment]
Since sessions are time-based, not block-based, it seems reasonable to have intervals for pruning measured in time as well. Then we can predict how many sessions we will keep things available for.

**Comment by sandreim** [comment]
I see, changing this doesn’t make sense.
