### ISSUE TITLE
Crowdfund may be unable to re-enter an auction

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot#662]
* A crowdfund stops accepting new contributions after it has reached its cap.

* A crowdfund can span multiple auctions.

* When a fund transitions into a new auction, it must accept at least one contribution to be put back into the auction. (To be placed in the `NewRaise`)

There seems to be a fringe scenario where a crowdfund that spans multiple auctions will not be able to enter a later auction due to the fact it has hit it's cap. In this fringe scenario, the cap set for the fund was not enough to win the first auction (when it was set up), but would be enough for some later auction which occurs before its end date.

In this scenario, the funds would kind of be uselessly trapped until the crowdfund ends and retirement can begin.

**Comment by stanly-johnson** [comment]
This is solved by #2807
