### ISSUE TITLE
Implement accepting bid extrinsic, including validation and necessary spam protection (use what is there for transactions)

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6646]
The node side should accept and verify (by making use of #6645 ) incoming bids and put them in the transaction pool for later inclusion in a block.

**Comment by rphmeier** [comment]
If the bid is a regular transaction, then there is nothing explicit to do here as it would be handled entirely by Substrate's transaction queue.

**Comment by eskimor** [comment]
Indeed and if we really want an unsigned extrinsic, there is [ValidateUnsigned](https://github.com/paritytech/substrate/blob/b85246bf1156f9f58825f0be48e6086128cc0bbd/primitives/runtime/src/traits.rs#L1362). Closing for now.
