### ISSUE TITLE
Refactor consensus code into polkadot/substrate components

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#67]
The BFT code just needs a couple of things:
  - Messages in
  - Messages out
  - Sign message with local key
  - Round proposer
  - Round timeouts
  - Proposal generation function
  - Proposal evaluation function

The proposal generation  and evaluation functions should encapsulate the behavior of the specific substrate chain. This can be packaged up into its own trait.

We can package this up in a `substrate-bft` crate.

`polkadot-statement-table` crate:
The details of the proposal generation/evaluation function are what encapsulates the current statement table logic. This needs
  - Misbehavior type
  - Import of incoming statements
  - Incoming statements to trigger fetch of candidate data for evaluation of availability
  - Signing statements
  - Creation of batches of outgoing messages (to be done on a timer or by some other heuristic)

`polkadot-consensus` crate:
  - service built on top of the `substrate-network`
  - maintains connections to authorities
  - combined router for `substrate-bft` and `polkadot-statement-table` messages
  - manages local consensus identity and signing of messages
  - collates local parachain candidate
  - fetches and evaluates other candidates as necessary
  - creates full substrate block from statement table and transaction queue
  - accumulates misbehavior to be evaluated on-chain

**Comment by gavofyork** [comment]
is this done @rphmeier ?

**Comment by rphmeier** [comment]
yes, I would say so
