### ISSUE TITLE
Cannot use extrinsic nicks.set_name

### ISSUE THREAD

**Issue by vekexasia** [paritytech/polkadot#670]
Hello,

I'm sorry if this is the wrong repo. I was going to play with kusama this weekend but was unable to use the nicks.set_name extrinsic.

I've tried different ways and inputs as you can see here:

https://polkascan.io/pre/kusama-cc3/account/H72hS8xLmSiSBqbBXHND2KbN8PAoevi52B685cbGki6T9nt

I even tried to copy over the tx data from this set_name which seemed to work just fine: 
https://polkascan.io/pre/kusama-cc3/account/H72hS8xLmSiSBqbBXHND2KbN8PAoevi52B685cbGki6T9nt

Every try  was done using the polkadot.js.org web app. Open to help if you need further debugging informations.

Cheers

**Comment by shawntabrizi** [comment]
I believe the issue is that you do not have enough balance to call the function.

AFAIK, the cost of using nicknames requires a deposit of 10 KSM.

**Comment by vekexasia** [comment]
oh, that makes sense. Do you know where the code lives for that extrinsic?

**Comment by shawntabrizi** [comment]
Here:

> https://github.com/paritytech/substrate/blob/master/frame/nicks/src/lib.rs#L131

And deposit price set here:

https://github.com/paritytech/polkadot/blob/master/runtime/src/lib.rs#L540
