### ISSUE TITLE
The westend network is down

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/polkadot#6703]
Hi, not sure whether this is the correct place to report but I didn't find a better place, the westend network seems to be down.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/14008461/218208734-185da588-5327-45ff-906d-20a8c1137f41.png">

https://telemetry.polkadot.io/#list/0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e

**Comment by ggwpez** [comment]
Did this resolve for you?  
@PierreBesson was there an incident?

**Comment by PierreBesson** [comment]
Yes it's been resolved. It was caused by some Parity validators being down.
