### ISSUE TITLE
Retire `OldV1SessionInfo`

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot#6722]
`SessionInfo`s are kept on-chain for the dispute period, which is six sessions on production networks. An older version of the structure known as `OldV1SessionInfo` (see [#4545](https://github.com/paritytech/polkadot/pull/4545)) had its transition period since inclusion in the 0.9.16 release in February 2022. I believe it can be safely retired now, getting rid of some messy versioning code introduced during the transition.

**Comment by s0me0ne-unkn0wn** [comment]
@tdimitrov, it's your field of expertise. If I remove the structure from primitives and remove all the code making use of it, is it safe and sound to remove the `#[changed_in(2)] session_info()` call and forget about it?

**Comment by tdimitrov** [comment]
I'm afraid I've got no idea :(

@bkchr is it safe to remove method declarations from the runtime API if we are on a newer stable version? Are they needed for processing old blocks?

[This](https://github.com/paritytech/polkadot/blob/master/primitives/src/runtime_api.rs#L220) is the method @s0me0ne-unkn0wn refers to.

**Comment by rphmeier** [comment]
> Are they needed for processing old blocks?

No. Only the old runtime is needed to process old blocks. Runtime APIs are used to coordinate work around the head of the chain, not around old blocks.

They are safe to remove when any code invoking the old runtime API has been removed from all node binaries.
