### ISSUE TITLE
Access previous state for archive node 

### ISSUE THREAD

**Issue by lx38** [paritytech/polkadot#6769]
I have archive node running by providing "--pruning=archive" flags to polkadot. 

My expectation was the node shall keep whole state for each past block, which is not the case for me. 

It only allow me access to around 4K past states. 

This is the example I use by using subxt
```rust
    let mut iter = client
        .storage()
        .at(None)
        .await?
        .iter(polkadot::storage().system().block_hash_root(), 1000)
        .await?;

    let mut block_hashes = HashMap::new();
    while let Some((key, hash)) = iter.next().await? {
        let number = u32::decode(&mut &key.0[key.0.len() - 4..])?;
        block_hashes.insert(number, hash);
    }

    dbg!(block_hashes.len()); // => 4095
}
```

Can I somehow be able to access all states?

**Comment by bkchr** [comment]
You are calling into the state at a fixed block and the state internally prunes these block hashes. You need to use the RPC api to get the block hash for a certain block number. I assume that you are using `subxt`, please open an issue there if you have other issues/questions. Thank you.

**Comment by lx38** [comment]
Reopening the issue. 

My intention is to get state (ie. List of validators/etc) from very past bocks. Example regarding hashes was just an illustration, that I cannot access state data @ > than past 4K blocks . 

I cannot access state nither  via subxt nor via polkadotjs/apps. 

> You are calling into the state at a fixed block and the state internally prunes these block hashes

Are you saying that even if I set --prune-state=archive, there still a limit on how many states are kept in the database?

**Comment by bkchr** [comment]
You can access the state of all the previous blocks, but that is not what you are doing. You are calling into the state at a fixed block and then checking the on chain block hash storage. This on chain block storage is pruned, but this doesn't mean that all states are pruned. When you call into the runtime at a different block, there will be different hashes inside this structure. You are mixing up some stuff, this was also the reason I said you should open an issue in the subxt repo.

@jsdw can you please show him how to fetch block hashes using Rpc with subxt?

**Comment by lx38** [comment]
Thanks for clarification 

I think I started to understand what you are trying to show. 

Ps. I know how to access hash via rpc, that’s Not an issue . There was 
a mixup in my head on how state is supposed to be accessed. I will try
to expirement having this in mind! 

Thanks for your help!

Igor

On February 23, 2023, GitHub ***@***.***> wrote:
> You can access the state of all the previous blocks, but that is not
> what you are doing. You are calling into the state at a fixed block
> and then checking the on chain block hash storage. This on chain block
> storage is pruned, but this doesn't mean that all states are pruned.
> When you call into the runtime at a different block, there will be
> different hashes inside this structure. You are mixing up some stuff,
> this was also the reason I said you should open an issue in the subxt
> repo.
>
> @jsdw <https://github.com/jsdw> can you please show him how to fetch
> block hashes using Rpc with subxt?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/paritytech/polkadot/issues/6769#issuecomment-
1442135313>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ADACMVWHDAFOECCRYSOAW43WY6KXXANCNFSM6AAAAAAVFURLPI>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by lx38** [comment]
If you do not mind , can you please confirm and reject my understanding
of how node store its data:

Each block state include states from previous N blocks. 

On each new block node takes state from previous block, calculate new
state, trims oldest  block from it and saves, 

So node keeps previous N states per each block. 

And if I want to access state from random block, I must obtain it’s hash
via rpc, as in the latest block state it might not be available .

**Comment by bkchr** [comment]
No really correct. You are querying the block hashes stored in the state. This is some extra data structure maintained by frame-system and stores the last N block hashes. This is for example required for checking transaction validity.
From the node side an archive node is storing the state of each block. You can access the state of each block using Rpc as I told you :)

**Comment by jsdw** [comment]
@lx38 it sounds like you got the understanding that you need for this, and I have nothing really to add, but you are of course welcome to raise an issue in the Subxt repo as indicated if you have any specific questions on using Subxt.
