### ISSUE TITLE
Is treasury module in substrate used in polkadot?

### ISSUE THREAD

**Issue by qiushui777** [paritytech/polkadot#677]
I am reading the source code of the polkadot. Accoriding to the wiki doc and other posts, I found that treasury is implemented on Kusama.
[https://wiki.polkadot.network/docs/en/learn-treasury](https://wiki.polkadot.network/docs/en/learn-treasury)
And the related codes are implemented in substrate.
[https://github.com/paritytech/substrate/tree/master/frame/treasury](https://github.com/paritytech/substrate/tree/master/frame/treasury)

But I can’t find where polkadot use these codes. For example, reject_proposal function in
paritytech/substrate/blob/master/frame/treasury/src/lib.rs

This is really weird.  And I also found that Kusama supports all those referenda logic which should be implemented in the democrazy module in substrate. But I also can't find where polkadot calls those functions in this repo(master branch). 

So can anyone help explain this? Thanks.

**Comment by thiolliere** [comment]
Indeed democracy use treasury through the runtime implementation :-)

the treasury trait is implemented for the runtime here https://github.com/paritytech/polkadot/blob/5b4ffee3d8927948b4058d242681aac60b6c3e5e/runtime/src/lib.rs#L426-L436

democrazy make use of it there https://github.com/paritytech/polkadot/blob/5b4ffee3d8927948b4058d242681aac60b6c3e5e/runtime/src/lib.rs#L366
