### ISSUE TITLE
Polkadot's XCM config should use `WeightInfoBound` weigher

### ISSUE THREAD

**Issue by KiChjang** [paritytech/polkadot#6785]
Currently, the Polkadot XCM config uses `FixedWeightBounds` as the weigher:

https://github.com/paritytech/polkadot/blob/d56dcfaf004352dcdf2f24a108cff6e3144956c4/runtime/polkadot/src/xcm_config.rs#L320

I don't think there is a good reason for this other than oversight, especially when Kusama, Rococo and Westend all have `WeightInfoBounds` as their weigher.

We should thus change the Polkadot XCM config to use `WeightInfoBounds`. Doing so requires benchmarking XCM instructions on the Polkadot runtime to get benchmark-weighted values for each instruction's weight.

File: `runtime/polkadot/src/xcm_config.rs`

**Comment by xlc** [comment]
Why this isn't implemented?

**Comment by franciscoaguirre** [comment]
I can take this

**Comment by KiChjang** [comment]
Should be fixed by #7077.
