### ISSUE TITLE
Include PVF execution and preparation timeouts into executor environment parameters

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot#6793]
PVF timeouts are crucial for determining candidate validity, and changing a timeout throughout the network may retrospectively affect the validity of already included candidates. Thus, such changes must be effective per session, not per network. Execution environment parameters are a natural place to keep track of timeout changes for the dispute period.

**Comment by eskimor** [comment]
We do have three timeouts which relate to each other:

1. Timeout for collators.
2. Timeout for backers.
3. Timeout for approval checkers.

Timeout for backers has to be larger than the one for collators to make it very unlikely for them to reject a valid block. 

Timeout for approval checkers needs to be way larger than the timeout for backing to avoid false disputes. We currently have 6x backing timeout here.

The latter is more critical than the previous one, so a smaller factor between timeout for collators to timeout for backers can be justified. Right now it is 4x.

**Comment by rphmeier** [comment]
Timeouts for collators live in Cumulus in practice now, and IMO that is the right place for them: either Cumulus or whatever other collation binary may be created. It's the responsibility of the collators to not create anything that backers will reject. It makes the most sense for Cumulus to make use of the backing timeout and adjust based on the specifics of the parachain's block authoring mechanism.

**Comment by eskimor** [comment]
@s0me0ne-unkn0wn let's prioritize this a bit. For fully utilizing async backing benefits we need that to be configurable, so we can bump it up in a secure way. Given that we don't have time disputes yet, we could cowboy it, but better if we had a proper configuration in place.

**Comment by eskimor** [comment]
As @rphmeier we don't care about the collator timeout, but for [#paritytech/cumulus/2252](https://github.com/paritytech/cumulus/issues/2252) we will need that [dedicated collator API](https://github.com/paritytech/polkadot/issues/6817) for fetching execution environment parameters.

**Comment by s0me0ne-unkn0wn** [comment]
Yeah, I also think it should be implemented asap.

As for executor environments in collators, did you see this one? https://github.com/paritytech/polkadot/issues/6497#issuecomment-1450814577
