### ISSUE TITLE
Executor environment parameters should be configurable on the fly

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [paritytech/polkadot#6805]
Currently, executor environment parameters may only be changed with the runtime upgrade. We need the ability to configure them through governance.

**Comment by s0me0ne-unkn0wn** [comment]
@crystalin TL;DR: those are parameters of the PVF execution environment that set the semantics of Wasmtime compilation and runtime environment, current list is here: https://github.com/paritytech/polkadot/pull/6873#issuecomment-1468447449 (right now we're discussing more in #6918). They are not mandatory to be provided by governance, as we have safe defaults hardcoded, and we only want governance to be able to alter them if needed.

Longer answer may be found in #4212, #6161, #6793, #6876

**Comment by crystalin** [comment]
Thank you for the summary. 
Is there a risk if those are hardcoded/on-chain to make it more likely that if a bug is introduced which is related to those settings, that **all the validators** would be running that bug because they all have the same settings ?

**Comment by s0me0ne-unkn0wn** [comment]
As for hardcoded safe defaults, they represent the same semantics that was in place before executor parameters were introduced, so no risks here, everything is working exactly as it worked before.

Changing them through governance MAY break things. But that's the governance. It may brick the whole network if it wants. Basically, that may be achieved by lowering some limits to undesirable values. We're not going to lower anything ever, the parameters were introduced for us to be able to grow them if needed and to introduce new features (but not to get rid of old ones) so while the network is acting in its interest we are safe. But if the network wants to commit suicide, not much we can do with that :frowning_face:
