### ISSUE TITLE
Attested candidate request retry timeouts

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#6819]
@rphmeier One thing I noticed is that if a request recipient is dropping requests, the requests keep getting sent out, seemingly perpetually (I haven't dug into whether there's a limit or not). Could this be an issue?

_Originally posted by @mrcnski in https://github.com/paritytech/polkadot/issues/6755#issuecomment-1453533702_

We should have a timeout (1s-5s, choice is somewhat arbitrary) between requests to the same peer about the same candidate.

**Comment by mrcnski** [comment]
Done in https://github.com/paritytech/polkadot/pull/6833.
