### ISSUE TITLE
Inconsistent field name

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#6834]
https://github.com/paritytech/polkadot/blob/0f4f3501d6dba5242df0219455f6b3a22bfbeed6/core-primitives/src/lib.rs#L127-L131

it is `msg` for downward message but `data` for others

https://github.com/paritytech/polkadot/blob/0f4f3501d6dba5242df0219455f6b3a22bfbeed6/core-primitives/src/lib.rs#L136-L142

https://github.com/paritytech/polkadot/blob/0f4f3501d6dba5242df0219455f6b3a22bfbeed6/core-primitives/src/lib.rs#L147-L151

**Comment by bkchr** [comment]
You are free to open a pr to fix it :D

**Comment by xlc** [comment]
rename this is actually going to cause some trouble in Chopsticks 💁‍♂️ 

https://github.com/AcalaNetwork/chopsticks/blob/d664dfd95192b092198bbeb3de1500806bab7927/packages/chopsticks/src/blockchain/inherent/parachain/validation-data.ts#L20

we will need to detect the version and choose to use `msg` or `data`...

I guess we will just need to live with it
