### ISSUE TITLE
Move pallets out of `polkadot-runtime-common`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot#6858]
From https://github.com/polkadot-fellows/runtimes/pull/1#discussion_r1131514202  

There are a few pallets in `runtime/common` that we don't need for the new runtimes repo https://github.com/polkadot-fellows/runtimes/ and should move them out:
- [ ] paras register
- [ ] sudo wrapper

Although there are also other pallets like:  
- [ ] assigned slots
- [ ] auctions
- [ ] claims
- [ ] purchase
- [ ] parachains slots lease
- [ ] crowdloans
- [ ] slot range + helper (seems to only be used in crowdloans and auctions)

Can we move all of that to a new crate? Theoretically one crate per pallet would work, or a `polkadot-runtime-parachains` (as proposed by @bkchr) for the first two, or a shared `polkadot-pallets` for all or them?

**Comment by bkchr** [comment]
After some more internal discussion, we don't want this. Everything that isn't shared with other chains should go to the fellowship repo.
