### ISSUE TITLE
Found the usage of undeclared variables

### ISSUE THREAD

**Issue by philipjonsen** [paritytech/polkadot#6866]
DESCRIPTION
Variables that aren't defined, but accessed may throw reference errors at runtime.

Potential ReferenceErrors may result from misspellings of variable and parameter names, or accidental implicit globals (for example, forgetting the var keyword in a for loop initializer). Any reference to an undeclared variable causes a warning, unless the variable is explicitly mentioned in a /*global ...*/ comment, or specified in the globals key in the configuration file. A common use case for these is if you intentionally use globals that are defined elsewhere (e.g. in a script sourced from HTML).

BAD PRACTICE
const foo = someFunction();
const bar = a + 1; // 'a' is undeclared
RECOMMENDED
/*global someFunction, a*/
/*eslint no-undef: "error"*/

const foo = someFunction();
const bar = a + 1;

Look here: 

'mermaid' is not defined
[roadmap/implementers-guide/mermaid-init.js](https://github.com/philipjonsen/polkadot/blob/master/roadmap/implementers-guide/mermaid-init.js#L1-L1)

1mermaid.initialize({startOnLoad:true});
'zombie' is not defined
[zombienet_tests/smoke/0003-deregister-register-validator.js](https://github.com/philipjonsen/polkadot/blob/master/zombienet_tests/smoke/0003-deregister-register-validator.js#L9-L9)

 6
 7async function run(nodeName, networkInfo, jsArgs) {
 8    const {wsUri, userDefinedTypes} = networkInfo.nodesByName[nodeName];
 9    const api = await zombie.connect(wsUri, userDefinedTypes);
10    const action = jsArgs[0] === "register" ? "registerValidators" : "deregisterValidators"
11    const validatorName = jsArgs[1]; // used as seed
12
'zombie' is not defined
[zombienet_tests/smoke/0003-deregister-register-validator.js](https://github.com/philipjonsen/polkadot/blob/master/zombienet_tests/smoke/0003-deregister-register-validator.js#L13-L13)

10    const action = jsArgs[0] === "register" ? "registerValidators" : "deregisterValidators"
11    const validatorName = jsArgs[1]; // used as seed
12
13    await zombie.util.cryptoWaitReady();
14
15    // account to submit tx
16    const keyring = new zombie.Keyring({ type: "sr25519" });
'zombie' is not defined
[zombienet_tests/smoke/0003-deregister-register-validator.js](https://github.com/philipjonsen/polkadot/blob/master/zombienet_tests/smoke/0003-deregister-register-validator.js#L16-L16)

13    await zombie.util.cryptoWaitReady();
14
15    // account to submit tx
16    const keyring = new zombie.Keyring({ type: "sr25519" });
17    const alice = keyring.addFromUri("//Alice");
18    const validatorStash = keyring.createFromUri(`//${nameCase(validatorName)}//stash`);
19

**Comment by coderobe** [comment]
invalid automated scan report, please review your stuff before submitting
