### ISSUE TITLE
Failed to submit extrinsic

### ISSUE THREAD

**Issue by qiushui777** [paritytech/polkadot#690]
Hi, I am running a local two-node testnet, but there are some problems. I compiled the release version of the polkadot node and started the net with these two commands.

> ./polkadot --base-path ./tmp/alice --chain=local --alice --validator

> ./polkadot --base-path ./tmp/bob --chain=local --bob --validator --port 20222 --bootnodes "/ip4/127.0.0.1/tcp/30333/p2p/QmfV6dvjQma3mcnxndcoL8NHZ9nrnFhnVMreHYJyaMi62b"

After it started, I can see that the testnet is producing blocks. Then I configured the 
"https://polkadot.js.org/apps/" to connect to my local notes on port 9944.

So after all these done, everything seems well. But when I tried to send a transaction from alice to bob, it gave me this error. 

> 2019-12-12 22:31:15 Failed to submit extrinsic: Transaction pool error: Invalid transaction validity: InvalidTransaction::Custom(2)

And nor can I make any proposal on the testnet. So what I did wrong here? Why I can't transfer any money or submit any transaction?

Thanks.

**Comment by alexxuyang** [comment]
how did you build the polkadot?

**Comment by qiushui777** [comment]
> how did you build the polkadot?

I used cargo build --release to build the release version of the polkadot and I also tried the debug version which failed me either.

**Comment by alexxuyang** [comment]
I've just pull the kusama-cc3 code, v0.7.8, start a local testnet with below script:

```
target/release/polkadot \
--chain local \
--validator \
--ws-external --rpc-external --rpc-cors all \
--base-path ./db11 \
--port 30343 --rpc-port 9943 --ws-port 9954 \
--alice

target/release/polkadot \
--chain local \
--validator \
--base-path ./db22 \
--port 30344 \
--bob \
--bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmNXmSMrNigUf2RP6AWiYcXvR5EXRyCJjstt81JUgCtoXY

target/release/polkadot \
--chain local \
--validator \
--base-path ./db33 \
--port 30345 \
--name=tom \
--bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmNXmSMrNigUf2RP6AWiYcXvR5EXRyCJjstt81JUgCtoXY

target/release/polkadot \
--chain local \
--validator \
--base-path ./db44 \
--port 30346 \
--name=john \
--bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmNXmSMrNigUf2RP6AWiYcXvR5EXRyCJjstt81JUgCtoXY
```

And I start a local polkadot.js (master branch & most updated code) frontend in my machine, connect to the node, it can produce the block and I can send coin from alice to bob.

PS, the version seen in polkadot.js is: 
```
parity-polkadot v0.7.8
api v0.99.0-beta.16
apps v0.38.0-beta.62
```

**Comment by qiushui777** [comment]
You are using the UI here https://github.com/polkadot-js/apps right? I tried for a long time, but when I started the UI, it is always blank. I am considering using the substrate rpc directly but it doesn't seem like having the proposal related api...

**Comment by alexxuyang** [comment]
Yesterday one of my teammate try the UI, it broken the same way as you. Seems you need install a older version, have a try with with this commit:
[https://github.com/polkadot-js/apps/commit/5fcf9a69166b9abb8bc09089ef6fde5bc01727f2](https://github.com/polkadot-js/apps/commit/5fcf9a69166b9abb8bc09089ef6fde5bc01727f2)

**Comment by qiushui777** [comment]
Thanks your help. I am still trying with the UI. But the js api plays well in making a transaction. I shall close the issue for now.

**Comment by yuhui1208** [comment]
when i make a transfer,How do I get events about transfer extrinsic, i only get the 'system.ExtrinsicSuccess' event, can not get 'balances.Transfer' event,
