### ISSUE TITLE
Verify that all weight files were updated

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot#6906]
Before a release happens and after all weight files were supposed to be updated, we should run a script to double-check the modification date of all weight files. Actually it would be better to check the `//! DATE:` comment, since the last git modification date could be unrelated to the re-generation of the weights.  
The script that we currently use to run *all* benchmarks is not ideal; there are situations that pallets can go amiss.  

We can limit he check to runtime weight files. It should be enough to filter for
`"THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI"` through all files, but good to double check with this file glob `runtime/*/src/weights/**/*.rs,bridges/modules/*/src/weights.rs`.
PS: `//! DATE: ([0-9]+-[0-9]+-[0-9]+)` looks like a good pattern.

(Not sure where to best put this issue so consider this as place holder)  
cc @bkontur @coderobe

**Comment by s3krit** [comment]
Closing as https://github.com/paritytech/polkadot/pull/6996 is now merged
