### ISSUE TITLE
RPC service is unhealthy

### ISSUE THREAD

**Issue by lovelaced** [paritytech/polkadot#691]
Over the past 48 hours the RPC service seems to have destabilized and has stopped responding to queries multiple times but has recovered within a ~3 minute window while running Kusama CC3 version 0.7.8. There have been two instances where it did not recover and a restart of the service was required.

Logs are too large to send here but will be communicated separately.

cc @arkpar

**Comment by bkchr** [comment]
CC @tomusdrw

**Comment by tomusdrw** [comment]
Happy too look at the logs @lovelaced with current info there is not much I can do (feel free to DM me on riot at @todr:matrix.parity.io). What kind of RPC queries are you executing? How often?

**Comment by lovelaced** [comment]
It seems to have stabilized in newer releases so will close this for now.
