### ISSUE TITLE
Warp sync seemingly makes no progress

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot#6910]
Hi, I unsuccessfully tried to warp sync a Polkadot node today:

<img width="1185" alt="Screenshot 2023-03-18 at 16 06 52" src="https://user-images.githubusercontent.com/16665596/226086309-1a413ab3-5f95-4c77-9951-993f28c381c7.png">

it was stuck logging `⏩ Warping, Downloading finality proofs, 0.00 Mib` for 15 minutes until I gave up and reverted to a fast sync.

**Comment by altonen** [comment]
Can you run the node with `-lsync,sub-libp2=trace`?

**Comment by altonen** [comment]
There's only around 30 seconds of logs so it's hard to say based on that alone what is the issue. Interestingly the node only sends a few `WarpProofRequest`s even though it has ~30 connections. I've been debugging this and another syncing issue today and yesterday but I can't reproduce the issue you're reporting. If this is still reproducible for you, could capture logs over a longer period of time?

**Comment by liamaharon** [comment]
Still able to reproduce, here're [5 min of logs](https://raw.githubusercontent.com/liamaharon/misc/main/warp.output).

**Comment by altonen** [comment]
There are bunch of timeouts in the logs which are probably not that interesting but what is interesting is that there are also lots of refusals which doesn't make sense. The [warp sync request handler](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/warp_request_handler.rs#L95-L114) is very simple so unless the request is encoded incorrectly, which is probably not the case, the error and subsequent reason for refusal originates from [`WarpSyncProof::generate()`](https://github.com/paritytech/substrate/blob/master/client/consensus/grandpa/src/warp_proof.rs#L81-L186). 

Are you able to reproduce this if you use a fresh database?

**Comment by liamaharon** [comment]
I'm using a fresh database each time I try to run it (my default database has already synced using `--fast`). 

Let me know if I can help debug by adding logs or anything to that warp sync request handler.

**Comment by liamaharon** [comment]
Sure, will try that in the next couple days.

**Comment by liamaharon** [comment]
I upgraded my laptop today and can no longer replicate this. Strange because I restored from a time machine backup, so it seems like the cause of this was some really esoteric misconfiguration on my older system. 

I'm going to close this for now, however if we notice other people reporting the issue I can dust off my old laptop and bisect the commit history.

**Comment by altonen** [comment]
Alright thanks for the information. It's very bizarre but it's good to hear that it works (for) now.
