### ISSUE TITLE
Treasury account & total issuance

### ISSUE THREAD

**Issue by emielsebastiaan** [paritytech/polkadot#692]
The treasury account `F3opxRbN5ZbjJNU511Kj2TLuzFcDq9BGduA9TgiECafpg29` gets a first balance of 10k KSM at block 10596 in Kusama CC3. Before this block the treasury account is empty.

This amount does not seem to account to the totalIssuance.
Additionally (and perhaps related) in Kusama-CC2 the treasury account had an accountIndex and in CC3 it does not. 

Is this all intentional? IMO the treasury account should be included in the total issuance.

**Comment by emielvanderhoek** [comment]
This extrinsic (sudo) seems to trigger it.
https://polkascan.io/pre/kusama-cc3/transaction/0x3e84b7c8f87d3188bf8edfe995c6e3d956315a78d7ff2f3f84516dd3becca14e

Which is a weird extrinsic without any further explanation why the sudo account set this balance.
Perhaps related: There are 2715 `treasury`.`deposit`-events before block 10596 that did not result in the treasury being funded.

**Comment by emielvanderhoek** [comment]
After block 10596 the `treasury`.`deposit`-events accrue to the treasury account, but still do not account to total issuance.

**Comment by rphmeier** [comment]
if still valid, more of a FRAME issue than a Polkadot one.
