### ISSUE TITLE
Failed on compiling polkadot

### ISSUE THREAD

**Issue by qiushui777** [paritytech/polkadot#693]
I am trying to compile the latest master branch but it gave these errors.

> Compiling polkadot-primitives v0.7.9 (/root/blockchian/polka/polkadot/primitives)
error: could not compile `polkadot-runtime`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name polkadot_runtime runtime/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="log"' --cfg 'feature="serde_derive"' --cfg 'feature="std"' -C metadata=d632b7d85152ffce -C extra-filename=-d632b7d85152ffce --out-dir /root/blockchian/polka/polkadot/target/debug/deps -C incremental=/root/blockchian/polka/polkadot/target/debug/incremental -L dependency=/root/blockchian/polka/polkadot/target/debug/deps --extern bitvec=/root/blockchian/polka/polkadot/target/debug/deps/libbitvec-314f172c91dbf3c3.rmeta --extern executive=/root/blockchian/polka/polkadot/target/debug/deps/libframe_executive-0ec44692294c4141.rmeta --extern frame_support=/root/blockchian/polka/polkadot/target/debug/deps/libframe_support-034c7800b85e8bba.rmeta --extern system=/root/blockchian/polka/polkadot/target/debug/deps/libframe_system-5ba466a26e7ead67.rmeta --extern system_rpc_runtime_api=/root/blockchian/polka/polkadot/target/debug/deps/libframe_system_rpc_runtime_api-f0fd00242e15e344.rmeta --extern log=/root/blockchian/polka/polkadot/target/debug/deps/liblog-d37ec35cb7f8f690.rmeta --extern authority_discovery=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_authority_discovery-d67a2656472927b8.rmeta --extern authorship=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_authorship-983d5844212fb160.rmeta --extern babe=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_babe-19adbf601fbdd133.rmeta --extern balances=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_balances-7eebc934708260d5.rmeta --extern collective=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_collective-60b69cee88de83db.rmeta --extern democracy=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_democracy-44f81a6ec8b7e0bd.rmeta --extern elections_phragmen=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_elections_phragmen-c2473809e454309f.rmeta --extern finality_tracker=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_finality_tracker-9a6ba9188e8af9b9.rmeta --extern grandpa=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_grandpa-f124dd47fccb3999.rmeta --extern identity=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_identity-ce083f26c2afdf2b.rmeta --extern im_online=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_im_online-6d7a0f42eda73b7c.rmeta --extern indices=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_indices-0c37fc36dcb39e58.rmeta --extern membership=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_membership-65b39a54c3957585.rmeta --extern nicks=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_nicks-289caea139769f3a.rmeta --extern offences=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_offences-27757b9dc1de8ca6.rmeta --extern randomness_collective_flip=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_randomness_collective_flip-2da49556c10e1a0d.rmeta --extern session=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_session-ffdcc44a9b1c06ac.rmeta --extern staking=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_staking-ee5b77dd3a071021.rmeta --extern pallet_staking_reward_curve=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_staking_reward_curve-2cdc584e9175c3d1.so --extern timestamp=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_timestamp-a6dfc45f40987968.rmeta --extern transaction_payment=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_transaction_payment-6ae36af29342f1ef.rmeta --extern pallet_transaction_payment_rpc_runtime_api=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_transaction_payment_rpc_runtime_api-8d76917a6d3d8fbb.rmeta --extern treasury=/root/blockchian/polka/polkadot/target/debug/deps/libpallet_treasury-51940dbb5c478c5d.rmeta --extern codec=/root/blockchian/polka/polkadot/target/debug/deps/libparity_scale_codec-7239ad9bb9e687ab.rmeta --extern polkadot_parachain=/root/blockchian/polka/polkadot/target/debug/deps/libpolkadot_parachain-16b82c3d6495080b.rmeta --extern primitives=/root/blockchian/polka/polkadot/target/debug/deps/libpolkadot_primitives-822d088925e6fffc.rmeta --extern rustc_hex=/root/blockchian/polka/polkadot/target/debug/deps/librustc_hex-da8061e84a06e8de.rmeta --extern safe_mix=/root/blockchian/polka/polkadot/target/debug/deps/libsafe_mix-615656778dd7cc1f.rmeta --extern serde=/root/blockchian/polka/polkadot/target/debug/deps/libserde-2e725895b50e6ec4.rmeta --extern serde_derive=/root/blockchian/polka/polkadot/target/debug/deps/libserde_derive-e84308716e682ef7.so --extern sp_api=/root/blockchian/polka/polkadot/target/debug/deps/libsp_api-cebc3406822dac74.rmeta --extern authority_discovery_primitives=/root/blockchian/polka/polkadot/target/debug/deps/libsp_authority_discovery-b94b2f23733111c8.rmeta --extern block_builder_api=/root/blockchian/polka/polkadot/target/debug/deps/libsp_block_builder-8a2a45997ab667be.rmeta --extern babe_primitives=/root/blockchian/polka/polkadot/target/debug/deps/libsp_consensus_babe-615a1524c65a64c4.rmeta --extern sp_core=/root/blockchian/polka/polkadot/target/debug/deps/libsp_core-065716731f25f69e.rmeta --extern inherents=/root/blockchian/polka/polkadot/target/debug/deps/libsp_inherents-c3a95b5e5d9368c4.rmeta --extern sp_io=/root/blockchian/polka/polkadot/target/debug/deps/libsp_io-1a1646bc6d2d8443.rmeta --extern offchain_primitives=/root/blockchian/polka/polkadot/target/debug/deps/libsp_offchain-a99312593dfc7e98.rmeta --extern sp_runtime=/root/blockchian/polka/polkadot/target/debug/deps/libsp_runtime-6ed1b35f83e4117f.rmeta --extern sp_serializer=/root/blockchian/polka/polkadot/target/debug/deps/libsp_serializer-639212eb1d7a3f13.rmeta --extern sp_session=/root/blockchian/polka/polkadot/target/debug/deps/libsp_session-243dc8b3f3a0b895.rmeta --extern sp_staking=/root/blockchian/polka/polkadot/target/debug/deps/libsp_staking-378ef3ca350a4945.rmeta --extern rstd=/root/blockchian/polka/polkadot/target/debug/deps/libsp_std-cda142fe4cfb9eea.rmeta --extern tx_pool_api=/root/blockchian/polka/polkadot/target/debug/deps/libsp_transaction_pool-89ff5ea581f52c89.rmeta --extern version=/root/blockchian/polka/polkadot/target/debug/deps/libsp_version-5fec3b20cb63c05b.rmeta -L native=/root/blockchian/polka/polkadot/target/debug/build/clear_on_drop-0e541b0a8cb1e47b/out -L native=/root/blockchian/polka/polkadot/target/debug/build/backtrace-sys-ed99e6e95d9d8e3c/out -L native=/root/blockchian/polka/polkadot/target/debug/build/ring-8dd7d6fa90ab7344/out -L native=/usr/lib/x86_64-linux-gnu` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...

**Comment by iammelea** [comment]
The last software for Kusama is v0.7.8
v0.7.9 is not ready, for that cant build

**Comment by qiushui777** [comment]
I see. Maybe this should be noted in readme because it says the lastest master branch should build.
