### ISSUE TITLE
Revert chain if at least f+1 validators voted against a candidate

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6950]
For maximum security and minimizing effects on the network we should probably revert a chain as soon as f+1 validators voted against a candidate. This should mostly be irrelevant, except if under attack and an attacker manages to prolong full dispute resolution. By reverting as early as possible (f+1 against) we:

1. Make it even harder to get a bad candidate finalized via DoS attacks and thus strengthen the security of the network*).
2. Also improve liveness: By reverting earlier, we have less wasted effort/thrown away blocks.

*) This is defense in depth, this should not be possible even without this change, but if it was because of some bug for example, it would certainly get harder this way.

**Comment by mrcnski** [comment]
What is `f`?

**Comment by mrcnski** [comment]
I guess the byzantine threshold? Looking at [the code](https://github.com/paritytech/polkadot/blob/32b9138042/runtime/parachains/src/disputes.rs#L573-L583) it looks like we already set [relevant flags](https://github.com/paritytech/polkadot/blob/32b9138042/runtime/parachains/src/disputes.rs#L552-L559) once we hit the thresholds, but I suppose this does not trigger reversion? Where does that happen?

**Comment by mrcnski** [comment]
Cool, so I think this also would need to be changed. (Looks like there is some duplication with the runtime code linked above which maybe can be extracted out, to keep the logic in sync.)

https://github.com/paritytech/polkadot/blob/32b9138042/node/core/dispute-coordinator/src/import.rs#L198-L208

**Comment by eskimor** [comment]
@sandreim raised a good point. For spam resilience we only take into account participation for either confirmed disputes or for ones where we have seen candidates included/backed on the non-finalized chain [and a few blocks behind finality](https://github.com/paritytech/polkadot/blob/0122e14ce5b820db0b8a1dd1b998078bc5e19e69/node/primitives/src/lib.rs#L82).

The dispute for the candidate which reached f+1 votes should conclude eventually in all cases, since the dispute is confirmed. Hence we should be able to get that 100% slash through. In case there are more invalid candidates on the reverted chain, then the risk of not being able to slash those offenders is slightly increased as the fork is abandoned and can fall behind finality. In case participations have not been queued, validators will no longer participate once that fork fell behind finality by 10 blocks. 

Mitigation:

1. Assuming we get at least one 100% slash through, even when heavily loaded, then the gambler's ruin property should be maintained - also queuing participations is fast.
2. We could evaluate increasing `DISPUTE_CANDIDATE_LIFETIME_AFTER_FINALIZATION` more. This needs to be balanced with spam considerations.
