### ISSUE TITLE
Add a TITLE field for referendums in OpenGov

### ISSUE THREAD

**Issue by Nick-1979** [paritytech/polkadot#6962]
It would be more informative and standalone If we could have a short description/title field for each referendum in OpenGov, like "Reason" for tips in Gov1.
If so the [pjs referenda page](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fkusama#/referenda) and other decentralized future dapps can list referendums in a more informative way.

Ps: we are aware of subsquare, and PA, but let's think decentralized.

**Comment by bkchr** [comment]
A full decentralized solution would be to have the proposal hash connected to the explanation on something like IPFS.

**Comment by daredevil3435** [comment]
I've started contributing here by doing easy documentation issues. But now I kinda want to get into technical issues. So can anyone tell me how do I get started? What are prerequisites to get started?

**Comment by bkchr** [comment]
Perfect, then this issue is resolved.

Ty @muharem

**Comment by Nick-1979** [comment]
> referendum in referenda and democracy pallets can have an associated metadata, and it meant for such information like title,... metadata is a hash of the preimage, which stores an IPFS hash, or anything else. https://github.com/paritytech/substrate/blob/7f930c23a8458f360625c9e5e0e1446edbcbb957/frame/referenda/src/lib.rs#L675

Using it for the preImage hash is necessary, so it cannot be used simultaneously for other purposes such as IPFS hash or title, right?

**Comment by bkchr** [comment]
The hash needs to be the hash of a valid preimage. However this doesn't need to be the hash of the Referendum call. You can upload any kind of preimage with https://github.com/paritytech/substrate/blob/7f930c23a8458f360625c9e5e0e1446edbcbb957/frame/preimage/src/lib.rs#L157
