### ISSUE TITLE
Multi-signature account has wrong operation in storage.

### ISSUE THREAD

**Issue by stepanLav** [paritytech/polkadot#7010]
I faced with situation where my multi-signature account on Westend has pending operation which have initiated from account not from my signatory.

Multi-signature account:

<img width="300" alt="Screenshot 2023-04-05 at 13 32 18" src="https://user-images.githubusercontent.com/40560660/230055896-30c3f62b-9ed2-4028-8e00-a68d44c325af.png">

https://westend.subscan.io/account/5G8BRW1ipdC6dksnqtHsGSZaEK8JvmnDETuNhkL1PskGCZtW

```bash
5G8BRW1ipdC6dksnqtHsGSZaEK8JvmnDETuNhkL1PskGCZtW # multisig account
- 5Dc1tzx4QDEDXetr98Mk4RjKSMFJiLBqr2Gmco7rjz8YfwMP # signatory
- 5EpsavEfPSZC8X2E4zHdJdepzpzfSccqNP5RUVyAU9Hyi3z4 # signatory
- 5GmedEVixRJoE8TjMePLqz7DnnQG1d5517sXdiAvAF2t7EYW # signatory
- 5HE2GqLBSY9QJsWTqaeb4UQXFhuiKDKYbnx4ZV6mQduVNDR9 # signatory
```

Pending multisig operation from storage was initiated by:
```bash
- 5GcvZoiGznXcpbLHetRZp52veE5UWvHvuo7Zy34mrpPFBGrR # account not from my signatory list
```
who are not part of that multi-signature account. As a result I can't cancel or approve that operation.

<img width="300" alt="Screenshot 2023-04-05 at 13 33 24" src="https://user-images.githubusercontent.com/40560660/230056158-ee3a9bcb-e2c3-477e-bab6-8d925bd2e975.png">

When I try to [approve](https://westend.subscan.io/extrinsic/15341952-2) that operation or [cancel](https://westend.subscan.io/extrinsic/15343292-2) I receive an error.

So my question is, how that operation was assign to described account? Was it a bug or an unexpected behaviour?

**Comment by ggwpez** [comment]
Tracked here https://github.com/polkadot-js/apps/issues/9103 and should been fixed since https://github.com/paritytech/substrate/pull/13630.  

Maybe the node that you are interacting with is not updated?

**Comment by stepanLav** [comment]
I was on this one: wss://rpc.dotters.network/westend when try to understand what was wrong.
Now I've checked all public nodes:
```bash
- wss://westend-rpc.polkadot.io
- wss://wnd-rpc.stakeworld.io
- wss://westend-rpc.dwellir.com
- wss://rpc-westend.luckyfriday.io
```
and transaction still in storage on all of them. 
May it be another case for "Phantom" transaction?

**Comment by stepanLav** [comment]
Then I will close this issue, thank you!
