### ISSUE TITLE
Polkadot: 429 Too many requests

### ISSUE THREAD

**Issue by rootsoklahoma** [paritytech/polkadot#7039]
During high load, HTTP requests to the node start failing with the error **"429 Too many requests: Too many connections. Please try again later."** This same error is also displayed in the node's logs (screenshot). 
Is there a way to increase the number of simultaneously open connections, similar to using the `'--ws-max-connections'` flag for websockets?

![image](https://user-images.githubusercontent.com/126730770/230923851-cef698fb-6c8f-414c-9a28-88d29bd59907.png)

**Comment by bkchr** [comment]
Cc @niklasad1

**Comment by niklasad1** [comment]
No, unfortunately not it's hardcoded on the server running on `--rpc-port` but it will fixed by https://github.com/paritytech/substrate/pull/13384

**Comment by arturgontijo** [comment]
I faced that issue few days ago and just stopped using the HTTP server in favor of the WS one.

If I understood it right, the WS server supports both protocols...so, if you are using `--ws-port=9944` you can set your HTTP client to point to `http://localhost:9944` and it should work too.

**Comment by niklasad1** [comment]
> If I understood it right, the WS server supports both protocols...so, if you are using --ws-port=9944 you can set your HTTP client to point to http://localhost:9944 and it should work too.

Yes, that is correct and the max connections will use `--ws-max-connections` but we have planned to remove all specific `HTTP/WS` as these apply globally on the RPC server.
