### ISSUE TITLE
Improve debuggability 

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot#7079]
I had a hard time to debug the XCM weight issue caused by #6785. All the error message I got is `XcmError::Barrier`. 

I understand why propagate error is hard but we need an alternative.

One way is to add enough logs to indicate why an error is occurred. I think we already drop logging in production build so it shouldn't have any overhead. And then in releases, it will be great to also make a production build with logging and we can use wasm override to use those runtime to debug errors.

For example, we could refactor this code to log weight limit and max weight and say it failed due to under weighted

https://github.com/paritytech/polkadot/blob/f1a45b39db6dbb7610c80b82d7cfca45a807619d/xcm/xcm-builder/src/barriers.rs#L95-L105

**Comment by bkchr** [comment]
Good idea!

Cc @KiChjang

**Comment by KiChjang** [comment]
Should be fixed by #7098.

**Comment by xlc** [comment]
There are other areas needs improvement. 
e.g. I am debugging why I am getting `MaxWeightInvalid` and no idea what's the required weight

https://github.com/paritytech/polkadot/blob/0c9143e4056931fbbcc53df9ad943ac9a3552f45/xcm/xcm-executor/src/lib.rs#L554
