### ISSUE TITLE
Decrease `max_code_size` on chain

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#7108]
The `max_code_size` is currently set to `10MiB` in Kusama and Polkadot. In the node we are currently assume that the [`MAX_CODE_SIZE`](https://github.com/paritytech/polkadot/blob/6dc9e84dde2f28215ab4e994cc021676d942eb12/primitives/src/v4/mod.rs#L348) is `3MiB`. 

As discussed with @eskimor on Tuesday, the `max_code_size` can not be bigger than the [maximum block length/size](https://github.com/paritytech/polkadot/blob/6dc9e84dde2f28215ab4e994cc021676d942eb12/runtime/common/src/lib.rs#L97-L98) of Polkadot itself. Otherwise we could not build a block that includes a parachain upgrade which code is bigger than the maximum block size.

We should check all the current active PVF and their size. I would propose we downgrade the `max_code_size` on Polkadot/Kusama to `4MiB` or maybe `3MiB` depending on what the biggest active PVF is.

CC @Sophia-Gold

**Comment by ggwpez** [comment]
I snug a [change](https://github.com/paritytech/polkadot/pull/6271/commits/7caffb09e83083b57affd548215e45b25c3d64dc) into  [#6271](https://github.com/paritytech/polkadot/pull/6271/files#diff-a4486bcabe372008a5f36a581e22f9088c21a714eb99d7ee152a449f93147e52R30) since it already schedules a config upgrade in the runtime upgrade.  
Do you think that is fine or should I cherry pick it? That MR should go into the next release anyway.  

About the value: it was 4MiB previously, but i can do a sweep across the parachains to check the current max.

**Comment by ggwpez** [comment]
3 MiB would also be fine it seems, although the previous was 4. Current max across all paras is 1.78MiB. We should probably announce this in the Forum before proceeding.

<details><summary>Parachain Code Size</summary>
<p>

| Relay | Para Name | Code Size [Byte] |
| --- | --- | --- |
| kusama | Picasso | 1780294 |
| kusama | Genshiro | 1728386 |
| kusama | Genshiro crowdloan 2 | 1728386 |
| kusama | Amplitude | 1643834 |
| kusama | Bifrost | 1627241 |
| polkadot | Composable Finance | 1573213 |
| kusama | Moonriver | 1546666 |
| kusama | Shiden | 1489435 |
| kusama | Karura | 1482184 |
| kusama | Parallel Heiko | 1475447 |
| polkadot | Acala | 1474313 |
| polkadot | Moonbeam | 1469681 |
| polkadot | Parallel | 1462944 |
| polkadot | Astar | 1460806 |
| kusama | Kintsugi BTC | 1406672 |
| polkadot | Bifrost | 1402592 |
| polkadot | Pendulum | 1373998 |
| kusama | Khala Network | 1335992 |
| polkadot | Clover | 1318401 |
| kusama | Darwinia Crab | 1309678 |
| polkadot | Phala Network | 1293185 |
| polkadot | Equilibrium | 1281831 |
| kusama | QUARTZ by UNIQUE | 1202716 |
| polkadot | Interlay | 1173411 |
| polkadot | Nodle | 1151341 |
| kusama | Altair | 1134774 |
| polkadot | Efinity | 1121310 |
| polkadot | Unique Network | 1118146 |
| polkadot | HydraDX | 1105514 |
| polkadot | Litentry | 1094670 |
| kusama | Mangata | 1093053 |
| kusama | Basilisk | 1082842 |
| kusama | subzero | 1071064 |
| polkadot | Bitgreen | 1061442 |
| polkadot | Zeitgeist | 1057255 |
| kusama | Tanganika | 1031284 |
| polkadot | Watr Network | 1009246 |
| polkadot | Centrifuge | 1003614 |
| polkadot | Hashed Network | 992974 |
| kusama | Crust Shadow | 983685 |
| polkadot | Aventus | 980858 |
| kusama | Turing Network | 978139 |
| polkadot | KILT Spiritnet | 977736 |
| polkadot | Crust | 952317 |
| kusama | Pichiu | 936112 |
| kusama | Bajun Network | 917254 |
| polkadot | OriginTrail | 848760 |
| kusama | Integritee Network | 835723 |
| kusama | InvArch Tinkernet | 818355 |
| kusama | DAO IPCI | 809456 |
| kusama | Robonomics | 807109 |
| kusama | Robonomics 2 | 807109 |
| polkadot | Manta | 771372 |
| kusama | Dora Factory | 762242 |
| polkadot | Subsocial | 752136 |
| polkadot | Kylin | 728780 |
| kusama | Kabocha | 720578 |
| kusama | GM | 711752 |
| polkadot | t3rn | 644599 |
| polkadot | Kapex | 633529 |
| polkadot | Darwinia | 600779 |
| polkadot | Ajuna Network | 582751 |
| polkadot | Frequency | 540935 |
| kusama | SORA | 516993 |
| polkadot | Integritee Shell | 412227 |
| polkadot | Ares Odyssey | 0 |
| polkadot | Coinversation | 0 |
| polkadot | Darwinia Backup | 0 |
| polkadot | Geminis | 0 |
| polkadot | InvArch | 0 |
| polkadot | OAK Network | 0 |
| polkadot | OmniBTC | 0 |
| polkadot | peaq | 0 |
| polkadot | Polkadex | 0 |
| polkadot | SORA | 0 |
| polkadot | SubDAO | 0 |
| polkadot | SubGame Gamma | 0 |
| kusama | Aband | 0 |
| kusama | Bit.Country Pioneer | 0 |
| kusama | Calamari | 0 |
| kusama | Crust Shadow 2 | 0 |
| kusama | Imbue Network | 0 |
| kusama | KICO | 0 |
| kusama | KICO 2 | 0 |
| kusama | Kpron | 0 |
| kusama | Krest | 0 |
| kusama | Listen Network | 0 |
| kusama | Litmus | 0 |
| kusama | Loom Network | 0 |
| kusama | Mars | 0 |
| kusama | Parallel Heiko 2 | 0 |
| kusama | PolkaSmith by PolkaFoundry | 0 |
| kusama | RioDeFi | 0 |
| kusama | Sakura | 0 |
| kusama | Shiden Crowdloan 2 | 0 |
| kusama | SNOW Network | 0 |
| kusama | SubGame Gamma | 0 |
| kusama | SubsocialX | 0 |
| kusama | TrustBase | 0 |
| kusama | Unorthodox | 0 |

(Chains with `0` could not be contacted. Either dead RPC or already off-boarded.)

</p>
</details>

**Comment by bkchr** [comment]
> About the value: it was 4MiB previously, but i can do a sweep across the parachains to check the current max.

What you mean by previously? 


> Would you like me to make a Polkadot forum post about this? It seems pretty straightforward.

Not sure we need a forum post for this, mainly requires a governance proposal to set the value. IMO that should be enough.

**Comment by ggwpez** [comment]
> > About the value: it was 4MiB previously, but i can do a sweep across the parachains to check the current max.
> 
> What you mean by previously?

Ah nvm. I was a local change of mine :man_facepalming: 

>Not sure we need a forum post for this, mainly requires a governance proposal to set the value. IMO that should be enough.

Just wanted to ensure that all the para-chain teams see it - just in case that they have a pending upgrade that would get invalidated. But a proposal should probably be enough.

Can we still get feedback from the @paritytech/parachains-core team on this?

**Comment by bkchr** [comment]
> Just wanted to ensure that all the para-chain teams see it - just in case that they have a pending upgrade that would get invalidated. But a proposal should probably be enough.

Ahh yeah, good point. Anything above 5MiB would lead to issues right now any way.

**Comment by Sophia-Gold** [comment]
> Can we still get feedback from the @paritytech/parachains-core team on this?

We (@eskimor and I) are already tagged here :)

**Comment by eskimor** [comment]
The 3MB limit is also enforced at the network level. Hence any runtime upgrade greater than 3MB could hardly make it anyway already. (It could technically if the backing validator is the block producer at the same time.)

**Comment by ggwpez** [comment]
Kusama executed successfully.  

For Polkadot we can probably wait til OpenGov, to not block the current Referendum queue since it is not time-critical.

**Comment by shawntabrizi** [comment]
> As discussed with @eskimor on Tuesday, the max_code_size can not be bigger than the [maximum block length/size](https://github.com/paritytech/polkadot/blob/6dc9e84dde2f28215ab4e994cc021676d942eb12/runtime/common/src/lib.rs#L97-L98) of Polkadot itself.

I have always imagined some extrinsic which would append data to some storage over multiple blocks, allowing some single file stored on chain greater than the block limit.

In this case, a chain could make multiple upload extrinsics to the preimage pallet, and then trigger an upgrade from the larger file, bypassing the per-block limit.

**Comment by ggwpez** [comment]
>I have always imagined some extrinsic which would append data to some storage over multiple blocks, allowing some single file stored on chain greater than the block limit.
In this case, a chain could make multiple upload extrinsics to the preimage pallet, and then trigger an upgrade from the larger file, bypassing the per-block limit.

I think we can do this simply with `sp_io::storage::append`. But the problem is that once the preimage is uploaded, we need to move it to storage key `:code:`. And we dont have a "move data from one storage key to another" host call. So instead we have to read+write the value, thereby bringing it into the proof…

**Comment by shawntabrizi** [comment]
In this case, the limit is not the block size, but the PoV size.

For large items in PoV, we have this issue open which can solve that also using the preimage pallet: https://github.com/paritytech/polkadot/issues/5641

Yes, some engineering required, but I don't see a fundamental limitation here yet.

**Comment by ggwpez** [comment]
Polkadot proposal is here https://polkadot.polkassembly.io/referenda/9

**Comment by ggwpez** [comment]
Polkadot executed https://polkadot.subsquare.io/referenda/referendum/9 successfully.
