### ISSUE TITLE
PVF: Logging in PVF workers has no effect

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#7112]
# ISSUE

## Overview

See title. In the past to do print debugging from the workers I would write to a tmp file.

How does `gum` work beneath the hood? @sandreim any tips?

## Steps to reproduce

1. Add `sp_tracing::init_for_tests();` to `execute_good_block_on_parent`. 
2. Run `cargo test execute_good_block_on_parent -- --nocapture`.
3. Confirm that worker logs do not appear, i.e.

```rust
gum::debug!(target: LOG_TARGET, %worker_pid, "starting pvf worker ({})", debug_id);
```

in `worker_event_loop` does not do anything.

**Comment by s0me0ne-unkn0wn** [comment]
Are you testing your version with the separate worker or the current master? I'm pretty sure logging was working before. Do you remember you were testing [this](https://github.com/paritytech/polkadot/pull/6861#issuecomment-1476119298)? Point 10 in that list is a message [coming from the worker itself](https://github.com/paritytech/polkadot/pull/6861/files#diff-369b9a6176decc4dc7cce91b167c7caf8668167945152c4d64d3cc29e9c67d20R278) from inside the `worker_event_loop`, and we both surely saw that message. So if it was broken, it happened later.

**Comment by s0me0ne-unkn0wn** [comment]
> Run `cargo test execute_good_block_on_parent -- --nocapture`.

Haven't you forgotten to set up `RUST_LOG` environment variable properly?

**Comment by bkchr** [comment]
> So maybe that's the function that needs fixing. Quite sure I've run into this before as well, somehow.

Nothing needs to be fixed. You are initializing the logger with `TRACE` logs in the test process. The test process is spawning the worker executable that doesn't know anything about your logging setup in the test process. As @s0me0ne-unkn0wn said, you need to set `RUST_LOG` as env variables are inherited to child processes.
