### ISSUE TITLE
Add metric to count unapproved parachain blocks contained in unfinalized chain.

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot#7124]
Right now we only have logs: `2023-04-24 12:21:24.830 DEBUG tokio-runtime-worker parachain::approval-voting: approved blocks 15534167-[11111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 1111111111 11]-15533968... (truncated due to large window)` but these are limited by a 200 sized tracing window.

**Comment by bkchr** [comment]
While doing this, someone could also just print out what are the unapproved parachain blocks instead of printing a lot of ones :D
