### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by culmore2015** [paritytech/polkadot#713]
Jan  2 04:28:48 kusama kusama[29288]: Version: 0.7.10-5f5b8ea-x86_64-linux-gnu
Jan  2 04:28:48 kusama kusama[29288]: stack backtrace:
Jan  2 04:28:48 kusama kusama[29288]:    0: sp_panic_handler::set::{{closure}}
Jan  2 04:28:48 kusama kusama[29288]:    1: std::panicking::rust_panic_with_hook
Jan  2 04:28:48 kusama kusama[29288]:              at src/libstd/panicking.rs:477
Jan  2 04:28:48 kusama kusama[29288]:    2: std::panicking::begin_panic
Jan  2 04:28:48 kusama kusama[29288]:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Jan  2 04:28:48 kusama kusama[29288]:    4: polkadot_runtime::api::dispatch
Jan  2 04:28:48 kusama kusama[29288]:    5: std::panicking::try::do_call
Jan  2 04:28:48 kusama kusama[29288]:    6: __rust_maybe_catch_panic
Jan  2 04:28:48 kusama kusama[29288]:              at src/libpanic_unwind/lib.rs:80
Jan  2 04:28:48 kusama kusama[29288]:    7: sc_executor::native_executor::safe_call
Jan  2 04:28:48 kusama kusama[29288]:    8: std::thread::local::LocalKey<T>::with
Jan  2 04:28:48 kusama kusama[29288]:    9: <polkadot_executor::Executor as sc_executor::native_executor::NativeExecutionDispatch>::dispatch
Jan  2 04:28:48 kusama kusama[29288]:   10: std::thread::local::LocalKey<T>::with
Jan  2 04:28:48 kusama kusama[29288]:   11: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Jan  2 04:28:48 kusama kusama[29288]:   12: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Jan  2 04:28:48 kusama kusama[29288]:   13: sp_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Jan  2 04:28:48 kusama kusama[29288]:   14: <sc_client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block,sp_core::hasher::blake2::Blake2Hasher>>::call_at_state
Jan  2 04:28:48 kusama kusama[29288]:   15: <sc_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
Jan  2 04:28:48 kusama kusama[29288]:   16: <sc_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as sp_consensus::block_import::BlockImport<Block>>::import_block
Jan  2 04:28:48 kusama kusama[29288]:   17: sp_consensus::import_queue::import_single_block
Jan  2 04:28:48 kusama kusama[29288]:   18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jan  2 04:28:48 kusama kusama[29288]:   19: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Jan  2 04:28:48 kusama kusama[29288]:   20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Jan  2 04:28:48 kusama kusama[29288]:   21: futures_executor::thread_pool::PoolState::work
Jan  2 04:28:48 kusama kusama[29288]:   22: std::sys_common::backtrace::__rust_begin_short_backtrace
Jan  2 04:28:48 kusama kusama[29288]:   23: std::panicking::try::do_call
Jan  2 04:28:48 kusama kusama[29288]:   24: __rust_maybe_catch_panic
Jan  2 04:28:48 kusama kusama[29288]:              at src/libpanic_unwind/lib.rs:80
Jan  2 04:28:48 kusama kusama[29288]:   25: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jan  2 04:28:48 kusama kusama[29288]:   26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jan  2 04:28:48 kusama kusama[29288]:              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Jan  2 04:28:48 kusama kusama[29288]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Jan  2 04:28:48 kusama kusama[29288]:              at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Jan  2 04:28:48 kusama kusama[29288]:       std::sys_common::thread::start_thread
Jan  2 04:28:48 kusama kusama[29288]:              at src/libstd/sys_common/thread.rs:13
Jan  2 04:28:48 kusama kusama[29288]:       std::sys::unix::thread::Thread::new::thread_start
Jan  2 04:28:48 kusama kusama[29288]:              at src/libstd/sys/unix/thread.rs:79
Jan  2 04:28:48 kusama kusama[29288]:   28: start_thread
Jan  2 04:28:48 kusama kusama[29288]:   29: clone
Jan  2 04:28:48 kusama kusama[29288]: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/ab217bf/frame/executive/src/lib.rs:297
Jan  2 04:28:48 kusama kusama[29288]: This is a bug. Please report it at:
Jan  2 04:28:48 kusama kusama[29288]: #011https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment]
Cc @arkpar

**Comment by bkchr** [comment]
This was probably fixed.
