### ISSUE TITLE
Sorting out Release 9380 to Present

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#7162]
## Note: This issue **only** applies to runtimes and not any node releases.

The following runtimes have a bug in XCM v3 that was fixed in #7081 and #7115.

- v938\*
- v939\*
- v940\*

Polkadot is currently on v9370 and we are in the process of releasing 9420. However, some of these contain migrations, so we cannot skip them.

Notably:

- v9381: [XCM, UMP, and GRANDPA](https://github.com/paritytech/polkadot/blob/097ffd245c42aeff28cf80f8a3568e1bee2e7da7/runtime/polkadot/src/lib.rs#L1604L1612)
- v9400: [Nomination Pools](https://github.com/paritytech/polkadot/blob/a2b62fb872ba22622aaf8e13f9dcd9a4adcc454f/runtime/polkadot/src/lib.rs#L1598)

Therefore, we have two options:

1. Move all migrations from 9380 to present into the next release and mark all interim releases as unsafe. Propose v9420 as the next runtime upgrade on Polkadot.
2. Backport 7081 and 7115 into all releases from v9380 to present and propose the new v9382 runtime on Polkadot.

**Comment by coderobe** [comment]
instead of rereleasing several runtimes and delaying .42 enactment even further i would opt to go with making sure that one contains all these migrations and jumping ahead

cc @chevdor @EgorPopelyaev thoughts?

**Comment by EgorPopelyaev** [comment]
I would also agree with Mara, cause several backports and new runtimes might create some confusion

**Comment by chevdor** [comment]
There has been quite some work and many fixes in `v0.9.42` so it sounds much healthier indeed to focus on getting the runtimes `9420` through asap than to patch older runtimes.

**Comment by coderobe** [comment]
> Also remember Westend is on 9401 (so therefore up to date), and Kusama is on 9381 (so only needs 9391 and later migrations).

The migrations should have guards on them, so we can simply bring all of them forward.
I'll go check which ones are missing and prepare a pr.

**Comment by chevdor** [comment]
Closing:
- the migrations since 9380 have been included into the new release
- a special mention has been added to the release notes
