### ISSUE TITLE
[zombienet]: fix `misc-upgrade-node` 

### ISSUE THREAD

**Issue by niklasad1** [paritytech/polkadot#7177]
#6987 broke CLI arguments which in turn broke the test `zombienet-tests-misc-upgrade-node` which is temporarily disabled and should enabled again once there is polkadot release with the new CLI args.

**Comment by bkchr** [comment]
Ty @niklasad1!

@pepoviola would it be possible for zombienet to support both CLI versions at the same time? Maybe with some kind of "switch" when declaring the node?

**Comment by pepoviola** [comment]
Thanks for open this issue for tracking @niklasad1. 

@bkchr, yes I will add the possibility to set the `cli args version` in the network definition. This will allow us to set the node we use for upgrade to **not** use the deprecated flags. I will work on that today and open a new pr to with the fixed version.
Thanks!!

**Comment by pepoviola** [comment]
Issue in zombienet repo to track (https://github.com/paritytech/zombienet/issues/1005).

**Comment by pepoviola** [comment]
Hi @niklasad1, can we close this one since is already fixed in zombienet.
Thanks!

**Comment by niklasad1** [comment]
if zombienet has bumped to a version with that fix just close this issue :)

**Comment by pepoviola** [comment]
> if zombienet has bumped to a version with that fix just close this issue :)

Closing, thanks!
