### ISSUE TITLE
PVF worker: consider securing with `landlock`

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#7243]
# ISSUE

## Overview

I just found out about [landlock](https://landlock.io/). We are already working on a `seccomp`-based [solution](https://github.com/paritytech/polkadot/issues/4718) but that has been delayed due to, in a nutshell, the difficulty of knowing which syscalls are safe to block. Landlock might be easier and less controversial to implement, as it has a smaller scope (only restricts FS access). I expect it to be a temporary solution that can be totally replaced by `seccomp` sandboxing once that lands, but if it's quick to implement we should do it now. There is a [Rust crate](https://docs.rs/landlock/latest/landlock/).

### Alternative

If for some reason `landlock` doesn't work out, we can consider using `chroot` to restrict FS access. Its use as a security mechanism is widely discouraged, even by the [manpage](https://man7.org/linux/man-pages/man2/chroot.2.html), but it may be better than nothing for now, and I *think* the caveats don't apply to us.

## Related issues

https://github.com/paritytech/polkadot/issues/7266 is a prerequisite.

**Comment by sandreim** [comment]
I consider this another layer of defense in depth , but it seems to require kernel configuration support which might make it harder for node operators to enable it: https://docs.kernel.org/userspace-api/landlock.html#kernel-support

**Comment by mrcnski** [comment]
We should anyway check if it's enabled before running it. We can add a recommendation to enable it to the validator's guide.

**Comment by mrcnski** [comment]
I checked on my Linux environment (GCP) and Landlock is enabled there:

```
$ sudo dmesg | grep landlock
[    0.553664] landlock: Up and running.
```

I found [an example](https://docs.rs/landlock/latest/landlock/fn.path_beneath_rules.html) for restricting the current thread and checking whether the operation was successful. This seems like low-hanging fruit, so I'll implement this and add a note about it to the validator's guide (maybe with [this guide](https://dariofad.github.io/2021/10/16/How_to_upgrade_the_kernel_beginner.html)?). Also seems worthwhile to send to telemetry whether Landlock is enabled or not.
