### ISSUE TITLE
[XCM] Comprehensive documentation for XCM

### ISSUE THREAD

**Issue by KiChjang** [paritytech/polkadot#7274]
The vision is to create a one-stop shop for any information related to XCM.

**Comment by daredevil3435** [comment]
I would like to work on this but it'll be really helpful if I could get some guidance about where to start.

**Comment by KiChjang** [comment]
We have a repository for this already: https://github.com/paritytech/xcm-docs. Much help will be appreciated if you can review and fix issues in the current docs!

**Comment by KiChjang** [comment]
I think this can be closed as done, it's publicized now and the link works.
