### ISSUE TITLE
Gather requirements for binary distribution

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#7284]
# ISSUE

## Overview

For distributing `polkadot`, the status quo is that we have a single binary and users can:

1. download the binary
2. build it themselves and copy into the appropriate directory
3. or [install through a Deb package](https://github.com/paritytech/polkadot#debian-based-debian-ubuntu).

As per [this discussion](https://forum.polkadot.network/t/ux-of-distributing-multiple-binaries-take-2/2854), we want to start gathering requirements for a potential change to this where we would have multiple binaries. They also need to be [built with the musl target](https://github.com/paritytech/polkadot/issues/7116) which changes how (2) is done.

Do we need to keep supporting all the above cases or can we simplify it? How would multiple binaries affect the experience? How can we minimize pain for breakage? 

Questions:

- [ ] 1. What are validators’ requirements, e.g. how can we keep installation simple and minimize breakage for them?
- [x] 2. What are our requirements for testing, e.g. how is installation done on Versi right now?
  - It will most likely not have too much impact for the two ways the devops team is running nodes: docker (in kubernetes) and systemd (provisionned on VMs with ansible)

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/ux-of-distributing-multiple-binaries-take-2/2854/31

**Comment by mrcnski** [comment]
For (2), it will most likely not have too much impact for the two ways the devops team is running nodes: docker (in kubernetes) and systemd (provisionned on VMs with ansible).

I also got feedback that an install script is not needed, as long as it is clear what binaries are needed to run the node and potentially a flag to specify the path of those extra binaries (if unable to determine it automatically).

**Comment by mrcnski** [comment]
Done in https://github.com/w3f/polkadot-wiki/pull/4860
