### ISSUE TITLE
PVF: add `test-utils` feature and remove `#[doc(hidden)]`

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot#7285]
# ISSUE

## Overview

In the PVF modules we export a good amount of stuff for only testing in other crates. `#[cfg(test)]` does not expose code across crates so we use `#[doc(hidden)]` for exposing test methods. However it's unfortunate that test code ends up in production builds this way. This can be done in a nicer way by adding a [new feature](https://github.com/rust-lang/cargo/issues/8379#issuecomment-1261970561).

Credit to @s0me0ne-unkn0wn [here](https://github.com/paritytech/polkadot/pull/7253#discussion_r1204175025).

**Comment by s0me0ne-unkn0wn** [comment]
`from_discriminator_*` are definitely test-only functions (they create meaningless dummy objects just for tests), `spawn_with_program_path` is documented as test-only, but I'd check it twice just in case.

Also, I'm not sure if the CI scripts in `scripts/` have to be patched to make use of the new feature (see [test.yml](https://github.com/paritytech/polkadot/blob/master/scripts/ci/gitlab/pipeline/test.yml) in the first place), or it will just work as-is with `cargo test`.

**Comment by ggwpez** [comment]
Yea I am using the `dev-dependency` feature approach in another project and it works fine so far. Should be much better than `#[test]` anyway.

**Comment by s0me0ne-unkn0wn** [comment]
@Jpserrat as far as I see, the `spawn_with_program_path` is used in production code but just wouldn't need to be publicly exposed if it wasn't needed for integration tests. So it's okay to just keep `#[doc(hidden)]` and leave it alone.

**Comment by mrcnski** [comment]
Would also be nice to gate the puppet worker behind the new feature (as anything related to the puppet worker is test-only). I think it can be done with [`required-features`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target) in the `[[bin]]` section in `Cargo.toml`. This would improve compile times as we wouldn't always build the puppet worker on non-test builds. 🙌

**Comment by Jpserrat** [comment]
Thanks a lot for the help and suggestions with this one. Let me know if there are some improvements to be made.
