### ISSUE TITLE
TX Fees Doc Link is Nonexsistent

### ISSUE THREAD

**Issue by ferrell-code** [paritytech/polkadot#7311]
https://github.com/paritytech/polkadot/blob/ba1f65493d91d4ab1787af2fd6fe880f1da90586/runtime/common/src/lib.rs#L104

The link in the wiki is wrong too: https://wiki.polkadot.network/docs/learn-transaction-fees

Would fix, but I can't find the correct link

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by kianenigma** [comment]
Let's first tackle this at the meta level: 

@laboon @CrackTheCode016 is it reasonable that seemingly the polkadot wiki does NOT have a link checker? If so, we should add one ASAP, just as we have done in https://github.com/substrate-developer-hub/substrate-docs/pull/1974.

And what is going on in https://web3.foundation/research/? where is all the research pages? I cannot find any entry point to it :))

**Comment by CrackTheCode016** [comment]
> Would fix, but I can't find the correct link

@ferrell-code For reference, here is the correct link: https://research.web3.foundation/Polkadot/overview/token-economics#2-slow-adjusting-mechanism

I'll open a PR today to do some of this manually, and ofc add a link checker so we don't have this again :)

**Comment by laboon** [comment]
There was a link checker; I believe an upgrade to the Docusaurus software broke it at some point. I believe Keith had a manual link checker, maybe that could be included in the CI? Radha would know more.

**Comment by DrW3RK** [comment]
Yes. Here is the link checker in use for the Polkadot Wiki https://github.com/w3f/polkadot-wiki/blob/master/.github/workflows/audit-links.yml
