### ISSUE TITLE
Enable slashing on Polkadot

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#7336]
Slashing for invalid blocks is already live on Kusama, but Polkadot is still missing.

**Comment by eskimor** [comment]
@ordian is this blocked by anything?

**Comment by ordian** [comment]
Was implemented in #6960.

**Comment by eskimor** [comment]
Oh - forgot to remove the mention as well. Thanks @ordian, I for some reason saw the handler being () in the polkadot runtime file, when looking again it was suddenly there ... was about time to call it a day I guess. :-S
