### ISSUE TITLE
Adding `Copy` to AccountId Trait

### ISSUE THREAD

**Issue by JuaniRios** [paritytech/polkadot#7346]
I was wondering what the reason is for not having frame_system::Config::AccountId require Copy.

It would reduce having to do `.clone()` in many places in our code, and u8 arrays (the IDs most parachains use) can implement it by default with the derive macro.

**Comment by bkchr** [comment]
This is more a Substrate question. However, just because `AccountId` is an array of 32 elements, doesn't mean that it always need to stay this way. Maybe someone uses something different in their chain.

I get that copy is easier to use, but TBH `.clone()` is also not such a big issue.
