### ISSUE TITLE
executable flag "--no-private-ip" does not prevent discovery of nodes in the "10.0.0.0        -   10.255.255.255" range

### ISSUE THREAD

**Issue by aperture-sandi** [paritytech/polkadot#7350]
Running version "polkadot 0.9.42-9b1fc27cec4"

See log below...
```
2023-06-10 15:30:20 discovered: <id> /ip4/10.x.x.x/tcp/2435
2023-06-10 15:30:20 discovered: <id> /ip4/10.x.x.x/tcp/2435
2023-06-10 15:30:20 discovered: <id> /ip4/10.x.x.x/tcp/30333
2023-06-10 15:30:20 discovered: <id> /ip4/10.x.x.x/tcp/30333
```
(node id and ip addresses masked in log above)

**Comment by altonen** [comment]
Please see documentation for the flag, it's not meant to prevent peer discoveries in the local network. Or are you saying the node is establishing connections to these discovered peers despite you providing `--no-private-ip`?

**Comment by bkchr** [comment]
Given the title of the issue and that `--no-private-ip` is just about not connecting to private ips and not about preventing its discovery, I'm closing this issue.
