### ISSUE TITLE
Include nomination pools, voterlist, and fast-unstake in Staking proxy filter list

### ISSUE THREAD

**Issue by laboon** [paritytech/polkadot#7362]
For a Staking proxy, I would think that the follow staking-related pallets would be allowed to be called.

```
RuntimeCall::VoterList(..)
RuntimeCall::NominationPools(..)
RuntimeCall::FastUnstake(..)
```

Here:
https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L1035

and for other relevant chains, e.g. Kusama and Westend.

**Comment by xlc** [comment]
someone should write some tests as well
