### ISSUE TITLE
default json http rpc port has changed in 0.9.43

### ISSUE THREAD

**Issue by bb4L** [paritytech/polkadot#7363]
i'm running nodes with the docker image

example log from `0.9.41`:
```
2023-06-14 07:57:39 Running JSON-RPC HTTP server: addr=0.0.0.0:9933, allowed origins=["*"]    
```
example log from `0.9.43`:
```
2023-06-14 07:59:49 Running JSON-RPC server: addr=0.0.0.0:9944, allowed origins=["*"]    
```

**Comment by nuaays** [comment]
+1

**Comment by bkchr** [comment]
AFAIK http and ws are now provided using one port. Is that correct @niklasad1?

**Comment by niklasad1** [comment]
> AFAIK http and ws are now provided using one port. Is that correct @niklasad1?

Yes, both `HTTP` and `WS` are enabled on the JSON-RPC and it's running on 9944 by default.

Thus, the dedicated HTTP server has been removed (the changelog could been a bit verbose regarding that) but it states says the `CLI flags` to indicate that the JSON-RPC supports both WS and HTTP.
