### ISSUE TITLE
[v0.9.43] Removal of the options ws-port and ws-external

### ISSUE THREAD

**Issue by gitmewai** [paritytech/polkadot#7364]
I believe not only the default port changed in `v0.9.43` as mentioned in https://github.com/paritytech/polkadot/issues/7363 but also the removal of the options `--ws-port` and `--ws-external` in `v0.9.43` also mentioned in https://github.com/paritytech/polkadot/issues/7361 .

```
Jun 14 08:20:20 polkadot-1 systemd[1]: Started westend node.
Jun 14 08:20:20 polkadot-1 polkadot[226905]: error: unexpected argument '--ws-port' found
Jun 14 08:20:20 polkadot-1 polkadot[226905]:   tip: a similar argument exists: '--rpc-port'
Jun 14 08:20:20 polkadot-1 polkadot[226905]: Usage: polkadot --name <NAME> --public-addr <PUBLIC_ADDR>... --listen-addr <LISTEN_ADDR>... --rpc-methods <METHOD SET> --rpc-port <PORT> <--chain <CHAIN_SPEC>|--dev|--base-path <PATH>|--log <LOG_PATTERN>...|--detailed-log-output|--disable-log-color|--enable-log-reloading|--tracing-targets <TARGETS>|--tracing-receiver <RECEIVER>>
Jun 14 08:20:20 polkadot-1 polkadot[226905]: For more information, try '--help'.
Jun 14 08:20:20 polkadot-1 systemd[1]: polkadot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 14 08:20:20 polkadot-1 systemd[1]: polkadot.service: Failed with result 'exit-code'.
```

Can the team explain the breaking changes in `v0.9.43`, please? How websocket is supported in `v0.9.43`?

**Comment by bkchr** [comment]
Yeah they were removed as part of the following pr: https://github.com/paritytech/substrate/pull/13384

I have updated the release notes to make these changes more prominent.

**Comment by hugh-onf** [comment]
Did we have some typo? `--rpc--port` not there but `--rpc-port`, notice the `--`.
Thanks.
![image](https://github.com/paritytech/polkadot/assets/105209853/2b3aca02-83bf-4025-b971-f98ecaf6a591)

**Comment by niklasad1** [comment]
Yes, you are correct
