### ISSUE TITLE
Local Relay - Validators never import blocks from collators, "Collation wasn't advertised to any validator."

### ISSUE THREAD

**Issue by Romulus10** [paritytech/polkadot#7384]
I've been working on getting a test relay up and running in the cloud (Docker containers running on Debian virtual machines) for remote testing, and we've got everything running. The relay chain is able to sync, and sees the parachain. The collators see each other. We then noticed the following:

1) The parachain is trying to collate, but the blocks are never picked up by the relay.
2) We're getting a log that collation was not advertised to any validators.
3) That seems to be because finality is dropping behind on the relay chain, to the point where the relay's finalized block was 200 behind the current best.
4) 2 of our 3 validators are always offline, and it cycles almost perfectly. So the online validator will be A, then next block B, then next block C. That would cause the slow and stalled finality, and probably the lack of collation being advertised.

For reference, we also just registered a parathread on Rococo and put a request through for a temporary parachain slot, currently waiting for onboarding. My hope was to check whether that parachain worked appropriately.

I also tested this exact relay/para chain spec pair locally and it worked perfectly.

Has anyone seen something like this before? Thanks.

EDIT:
Both the relay and the parachain are on polkadot-v0.9.37. We're running the parachain with
```
parachain-node --collator --force-authoring --chain raw-parachain-chainspec.json --base-path /tmp/parachain/alice --port 40333 --ws-port 9944 --rpc-port 9934 --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --rpc-methods Unsafe --name Fennel0 --node-key $(cat para-key.sh) --unsafe-ws-external --rpc-external --rpc-cors=all -- --execution wasm --chain /app/polkadotspec.json --port 30343 --ws-port 9977 --bootnodes /ip4/[relay_ip]/tcp/30333/p2p/12D3KooWLj8FgbwDtLQbA5ozWqqx6vM1n2rmjwQMczSiDveyWa5G --rpc-external --ws-external --prometheus-external --rpc-cors all
```
and the relay bootnode with
```
polkadot --validator --base-path /tmp/relay/alice --chain /app/chainspec.json --port 30333 --ws-port 9944 --rpc-port 9934 --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --name FnlDot0 --node-key $(cat node_key) --rpc-cors all --prometheus-external --rpc-methods Unsafe --rpc-external --ws-external
```

Update:
After re-running, our Relay network is working again. All three nodes are in and finality has been running fine. Our parachain is, however, still not collating.

Here's a pastebin for the boot node's log: https://pastebin.com/raw/VAC1a50W

And one of the collator logs:
https://pastebin.com/raw/EyCUCRKD

**Comment by brunopgalvao** [comment]
Adding for context: https://substrate.stackexchange.com/questions/8899/local-relay-stops-finalizing

**Comment by bkchr** [comment]
> Both the relay and the parachain are on polkadot-v0.9.37

Please try with `0.9.43` because this is maybe already fixed.

**Comment by Romulus10** [comment]
> > Both the relay and the parachain are on polkadot-v0.9.37
> 
> Please try with `0.9.43` because this is maybe already fixed.

The upgrade worked! Thanks everybody.

**Comment by zoveress** [comment]
We are seeing the same issue using version 0.9.40 however it still produces blocks but some of the blocks get stuck and won't be produced on time. Do you reckon the upgrade to 0.4.45 would rectify the situation?
