### ISSUE TITLE
Polkadot OpenGov: Locking periods same as for Kusama

### ISSUE THREAD

**Issue by michalisFr** [paritytech/polkadot#7394]
The locking periods for voting or delegating with conviction are the same as for Kusama (multiples of 7 days), instead of multiples of 28 days as it was with Gov1.

I believe this is an oversight?

<img width="863" alt="Screenshot 2023-06-19 at 3 32 35 PM" src="https://github.com/paritytech/polkadot/assets/45905709/15899f1b-ee4d-47cb-882f-11cba4c03576">

<img width="659" alt="Screenshot 2023-06-19 at 3 39 26 PM" src="https://github.com/paritytech/polkadot/assets/45905709/ad7802e0-6bc9-43c2-934f-9f56f9cac732">

**Comment by ggwpez** [comment]
Should be fixed in the next runtime upgrade including https://github.com/paritytech/polkadot/pull/7595.
