### ISSUE TITLE
Randomly failing test due to a race condition

### ISSUE THREAD

**Issue by koute** [paritytech/polkadot#7407]
We seem to have a new flake-y test that randomly fails.

Steps to reproduce: (on Linux)

```
cd node/network/bitfield-distribution
sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches
cargo test tests::delay_reputation_change
```

Tested on current `master`. (`86213dfa1048f65a3bba6763aac971b6af7d753c`)

On my machine the drop caches line is necessary to trigger the failure; otherwise it only fails on the first run. (Running with a cold cache will make certain things take slightly longer which seems to trigger the race condition.)

**Comment by AndreiEres** [comment]
Thank you, @koute. I'll check it.

**Comment by ggwpez** [comment]
Failing again here https://github.com/paritytech/polkadot/pull/7415, we need to fix/comment this ASAP. I will comment it.
