### ISSUE TITLE
PoV Block Distribution: Gossip

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#742]
Polkadot has a request-response system for validators to fetch PoV blocks, but it requires peers to be directly connected to each other. There is no request forwarding, which means that PoV blocks are often just unavailable. 

Gossiping all PoV blocks is inefficient, but will ensure availability to validators and fishermen.

**Comment by bkchr** [comment]
Do we really want to gossip all POV blocks to all validators/fishermen or just to the validators assigned for a particular parachain?

**Comment by rphmeier** [comment]
I would say we don't want to gossip PoV blocks at all. But given the state of discovery, it seems unlikely that gossiping only within validators assigned to a particular parachain would ensure that they reach the right validators.
