### ISSUE TITLE
node configuration

### ISSUE THREAD

**Issue by TonyS001** [paritytech/polkadot#7463]
I maintain a Polkadot node and `polkadot --help` shows many configuration options. But all of them can only be set by starting commands, which is hard to checkout later and record. I have following questions.
- Is there a configuration file?
- How can I check the setting value when the node is running?
- If I want to run an archive node, what's the different among `--pruning archive`, `--state-pruning archive` and `--blocks-pruning archive`?

**Comment by bkchr** [comment]
> * Is there a configuration file?

No.

> * How can I check the setting value when the node is running?

There is no way to do this.

> * If I want to run an archive node, what's the different among `--pruning archive`, `--state-pruning archive` and `--blocks-pruning archive`?

`pruning` is just an alias of `state-pruning`. `pruning` was the old name and that wasn't really that expressive. So, we introduced `state-pruning` which is about which state to keep and `blocks-pruning` is about which block bodies aka transactions to keep.
