### ISSUE TITLE
How to implement Pallet_sudo

### ISSUE THREAD

**Issue by firebeefaizul** [paritytech/polkadot#7503]
Hi Everyone,
               How to implement Pallet_sudo in https://github.com/paritytech/polkadot
We follow below mentioned method
https://github.com/paritytech/polkadot/commit/791c8b8f9e6fe00b631f2cace0d6d65151487eb4
Kindly support to add sudo in our relaychain.

Thanks in advance,

**Comment by bkchr** [comment]
What is "your relaychain"?

**Comment by firebeefaizul** [comment]
we using below mentioned git code. 
https://github.com/paritytech/polkadot/
Branch : v0.9.42

**Comment by ggwpez** [comment]
Do you mean how to deploy the sudo pallet to your relay runtime?  
You can use rococo as example https://github.com/paritytech/polkadot/blob/e0ed7e862c8c8b6c75eda1731c449543642176ef/runtime/rococo/src/lib.rs#L1358-L1362. 
Just search for "sudo".

**Comment by bkchr** [comment]
So this can be closed?
