### ISSUE TITLE
UI bug: Kusama CC3 title is cropped (Safari)

### ISSUE THREAD

**Issue by edanilov** [paritytech/polkadot#754]
Mac OS, Safari
<img width="324" alt="Screenshot 2020-01-13 at 01 14 57" src="https://user-images.githubusercontent.com/1274876/72244862-04396380-35a4-11ea-8469-6d813272a77e.png">

**Comment by bkchr** [comment]
This is not the `polkadot-js` repo.

CC @jacogr you want to move it?

**Comment by jacogr** [comment]
It can just be logged in the correct repo, the link for that is in the UI.
