### ISSUE TITLE
[Feature request] websocket rate limit flag

### ISSUE THREAD

**Issue by tugytur** [paritytech/polkadot#7549]
RPC nodes are usually used via wss connections. Currently there is no proper way to rate limit this. 

Currently rate limiting can be enforced via reverse proxy for rpc calls, but this does not work for wss connections because for the proxy this looks like one call when it establishes the connection.

We run public rpc endpoints, we are not planning to do rate limiting for the average user. But we occasionally se multiple single websocket connections doing >500 requests per second and the node is not able to keep up with the chain anymore because of the high load.

Would be nice to have two flags to apply rate limiting to individual websocket connections, `--rpc-rate-limit` (in seconds), `--rpc-rate-limit-burst`

**Comment by GauravDhak** [comment]
hey @tugytur can you give more insight about this issue

**Comment by xlc** [comment]
I don't think Substrate/Polkadot will ever have this built in. That's why I am working on [subway](http://github.com/AcalaNetwork/subway/) aims to implement this and many more necessary features for rpc node operation.

**Comment by GauravDhak** [comment]
@xlc if you need to help, please feel free to contact me
