### ISSUE TITLE
Kusama's wiki update

### ISSUE THREAD

**Issue by edanilov** [paritytech/polkadot#755]
up to date docs for Kusama are on Kusama's wiki:
guide.kusama.network/en/latest/try/validate 

from this page: https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-kusama
block: Building and Installing the polkadot Binary

git checkout v0.6 - is old

**Comment by joshua-mir** [comment]
I'm not convinced Kusama docs should be on the Polkadot wiki. once polkadot is live and they are two separate networks with very likely different build and operating instructions, having two very similar pages on the same wiki could be incredibly confusing, especially when using the search feature.

**Comment by Swader** [comment]
Please put polkadot wiki issues into the polkadot wiki repo and same for kusama. Both wikis are open repos. We'll get to these issues fastest that way, thank you!

**Comment by laboon** [comment]
Yeah, this is a remnant from summer when Kusama was just being launched.  For now, I'll just make a quick PR to fix and tell people to look for the latest 0.7.x.  Going forward we can split this up.

**Comment by laboon** [comment]
https://github.com/w3f/polkadot-wiki/pull/207

**Comment by bkchr** [comment]
Sounds like this can be closed.
