### ISSUE TITLE
ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to validate_transaction: Codec error', /build/runtime/kusama/src/lib.rs:1661:1

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/polkadot#7555]
Last week, we observed an increase in panic logs, as shown below:

```
ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to validate_transaction: Codec error', /build/runtime/kusama/src/lib.rs:1661:1
```

![image](https://github.com/paritytech/polkadot/assets/24387396/5f6882cc-c98a-4ac4-8d17-dbcff065b76b)

These logs are present on both Kusama nodes and Kusama parachain nodes.

![image](https://github.com/paritytech/polkadot/assets/24387396/dcafc03a-c44f-4022-bf80-242be72d63e7)

**Comment by aceqbaceq** [comment]
+1

**Comment by ggwpez** [comment]
Just means that someone is sending invalid transactions to the node. Maybe ban the IP after a few tries?

**Comment by bkchr** [comment]
What @ggwpez said.
