### ISSUE TITLE
Double-vote Slash Handler

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#760]
In the attestation process, validators may submit only one `Candidate` message for a given relay chain block. If issuing a `Candidate` message on a parachain block, neither a `Valid` or `Invalid` vote cannot be issued on that parachain block, as the `Candidate` message is an implicit validity vote. Otherwise, it is illegal to cast both a `Valid` and `Invalid` vote on a given parachain block.

Runtime handlers that take two conflicting votes as arguments and slash the offender are needed.

**Comment by burdges** [comment]
I'd expect that parachain validators actually do not know which relay chain block might include their parachain candidate.  If I understand, your "only one" language says: 

If Alice proposes X for parachain rho then Alice cannot make another proposal for rho until some relay chain block includes some parachain candidate for rho.

**Comment by rphmeier** [comment]
The proposals are localized to a relay chain parent hash. So the equivocation here is making two proposals localized to the same parent.

**Comment by burdges** [comment]
I see.  I suppose the relay chain parent is the last relay chain block that included a candidate form the parachain, not necessarily a recent relay chain block.

**Comment by rphmeier** [comment]
No, that would be any recent relay chain block.

**Comment by burdges** [comment]
I tweaked the AnV write up to accommodate the discussion about relay chain validators advancing the parachain blocks without going back to collators that grew out of this in https://github.com/w3f/research/commit/29343da9f1e9adadcb5383fa7c9c450ce0d31e0f but in general there is a bunch of work to be done to harmonize the XCMP and AnV discussions.
