### ISSUE TITLE
visual indicator in logs that validator is para-validating / active

### ISSUE THREAD

**Issue by nicolasochem** [paritytech/polkadot#7616]
Hello,
When looking at validator logs, it's not immediately clear whether it's active or not / para-validating or not.

How about an emoji on every line for this purpose? It could be :orange_circle: (paravalidating) or :green_circle: (active). 

Benefits for operators is that they are less likely to terminate a validator that currently performs some important function, increasing reliability of the network.

**Comment by bkchr** [comment]
There are already metrics for this: `polkadot_node_is_active_validator` and `polkadot_node_is_parachain_validator`.
