### ISSUE TITLE
build error v1.0.0: associated type BlockNumber not found

### ISSUE THREAD

**Issue by ablax** [paritytech/polkadot#7623]
rustc 1.73.0-nightly (180dffba1 2023-08-14)
aarch64-apple-darwin m1 pro
cargo install --git https://github.com/paritytech/polkadot --tag v1.0.0 polkadot --locked

(0.9.43 builds fine)

Received error is:

  error[E0405]: cannot find trait `GenesisBuild` in this scope
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:538:18
      |
  538 |     impl<T: Config> GenesisBuild<T> for GenesisConfig<T> {
      |                     ^^^^^^^^^^^^ not found in this scope
      |
  help: consider importing this trait
      |
  478 +     use frame_support::traits::GenesisBuild;
      |

  error[E0576]: cannot find associated type `BlockNumber` in trait `frame_system::Config`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/disputes.rs:940:67
      |
  940 |         post_conclusion_acceptance_period: <T as frame_system::Config>::BlockNumber,
      |                                                                         ^^^^^^^^^^^ not found in `frame_system::Config`

  error[E0405]: cannot find trait `GenesisBuild` in this scope
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/hrmp.rs:444:18
      |
  444 |     impl<T: Config> GenesisBuild<T> for GenesisConfig {
      |                     ^^^^^^^^^^^^ not found in this scope
      |
  help: consider importing this trait
      |
  235 +     use frame_support::traits::GenesisBuild;
      |

  error[E0405]: cannot find trait `GenesisBuild` in this scope
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/paras/mod.rs:776:18
      |
  776 |     impl<T: Config> GenesisBuild<T> for GenesisConfig {
      |                     ^^^^^^^^^^^^ not found in this scope
      |
  help: consider importing this trait
      |
  531 +     use frame_support::traits::GenesisBuild;
      |

  error[E0576]: cannot find associated type `BlockNumber` in trait `frame_system::Config`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/runtime_api_impl/v5.rs:179:36
      |
  179 | ) -> (<T as frame_system::Config>::BlockNumber, <T as frame_system::Config>::Hash) {
      |                                    ^^^^^^^^^^^ not found in `frame_system::Config`

     Compiling sp-consensus-grandpa v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v1.0.0#948fbd2f)
  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:534:36
      |
  534 |         pub config: HostConfiguration<T::BlockNumber>,
      |                                          ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:555:12
      |
  555 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:571:12
      |
  571 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:587:12
      |
  587 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:668:12
      |
  668 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:684:12
      |
  684 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:700:12
      |
  700 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:771:12
      |
  771 |             new: T::BlockNumber,
      |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:1111:12
       |
  1111 |             new: T::BlockNumber,
       |                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/disputes.rs:450:13
      |
  450 |         Revert(T::BlockNumber),
      |                   ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/inclusion/mod.rs:1165:46
       |
  1165 |     config: configuration::HostConfiguration<T::BlockNumber>,
       |                                                 ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/inclusion/mod.rs:1166:10
       |
  1166 |     now: T::BlockNumber,
       |             ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/inclusion/mod.rs:1167:26
       |
  1167 |     relay_parent_number: T::BlockNumber,
       |                             ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/paras/mod.rs:839:28
      |
  839 |             relay_parent_number: T::BlockNumber,
      |                                     ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `Header` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/paras_inherent/mod.rs:265:36
      |
  265 |             data: ParachainsInherentData<T::Header>,
      |                                             ^^^^^^ there is a similarly named associated type `Header` in the trait `sp_runtime::traits::Block`

     Compiling rand_chacha v0.2.2
  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:1186:48
       |
  1186 |     pub(crate) fn initializer_initialize(_now: T::BlockNumber) -> Weight {
       |                                                   ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:1200:31
       |
  1200 |     ) -> SessionChangeOutcome<T::BlockNumber> {
       |                                  ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:1241:62
       |
  1241 |     pub fn force_set_active_config(config: HostConfiguration<T::BlockNumber>) {
       |                                                                 ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
      --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:1261:50
       |
  1261 |         updater: impl FnOnce(&mut HostConfiguration<T::BlockNumber>),
       |                                                        ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:513:40
      |
  513 |         StorageValue<_, HostConfiguration<T::BlockNumber>, ValueQuery>;
      |                                              ^^^^^^^^^^^ associated type `BlockNumber` not found

  error[E0220]: associated type `BlockNumber` not found for `T`
     --> /Users/muradhamza/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/1ed6e2e/runtime/parachains/src/configuration.rs:524:59
      |
  524 |         StorageValue<_, Vec<(SessionIndex, HostConfiguration<T::BlockNumber>)>, ValueQuery>;
      |                                                                 ^^^^^^^^^^^ associated type `BlockNumber` not found

  Some errors have detailed explanations: E0220, E0405, E0576.
  For more information about an error, try `rustc --explain E0220`.
  error: could not compile `polkadot-runtime-parachains` (lib) due to 26 previous errors
  warning: build failed, waiting for other jobs to finish...
error: failed to compile `polkadot v1.0.0 (https://github.com/paritytech/polkadot?tag=v1.0.0#1ed6e2e5)`,

**Comment by bkchr** [comment]
I can not reproduce. Try stable rust.

**Comment by bkchr** [comment]
Okay, I could actually reproduce it.

Please run the following command to fix the build:
```
SKIP_WASM_BUILD=1 cargo install --git https://github.com/paritytech/polkadot --tag v1.0.0 polkadot --locked
```

The problem is that the wasm builder doesn't respect the `--locked`.

**Comment by ablax** [comment]
I tried with stable as well, but it did not work.

Building from source did build successfully, but running 
cargo install --git https://github.com/paritytech/polkadot --tag v1.0.0 polkadot --locked
after building from source (after ./scripts/init.sh) still fails with the same error

**Comment by bkchr** [comment]
Please check the command I posted above. It starts with `SKIP_WASM_BUILD=1`, please do the same.

**Comment by ablax** [comment]
I did build it with SKIP_WASM_BUILD, but now I cannot start it in dev mode

polkadot --dev
Error: 
   0: Invalid input: Polkadot development wasm not available

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.


-------

RUST_BACKTRACE=full polkadot --dev
Error: 
   0: Invalid input: Polkadot development wasm not available

  ━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━
                                ⋮ 4 frames hidden ⋮                               
   5: polkadot::main::hb6528828b1bb820e
      at <unknown source file>:<unknown line>
   6: std::sys_common::backtrace::__rust_begin_short_backtrace::h815b10214dfb90b3
      at <unknown source file>:<unknown line>
   7: std::rt::lang_start::{{closure}}::h465535b94ff82d4c
      at <unknown source file>:<unknown line>
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0689b9cc840db667
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284
   9: std::panicking::try::do_call::h8d21b0c0c04af112
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500
  10: std::panicking::try::h618481d45c1b815c
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464
  11: std::panic::catch_unwind::hbdeff70f3984ee7b
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142
  12: std::rt::lang_start_internal::{{closure}}::haa4994ba13a3cd15
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148
  13: std::panicking::try::do_call::h39b55541875d339a
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500
  14: std::panicking::try::h93ac0a218f84acad
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464
  15: std::panic::catch_unwind::h07a4f62359dfd8f0
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142
  16: std::rt::lang_start_internal::hdd06e3566639fc5b
      at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148
  17: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

**Comment by bkchr** [comment]
Yeah, the wasm is not build in this case. If you already have checked out the repo, you can just use `cargo build --profile prroduction`.
