### ISSUE TITLE
Polkadot {{ env.VERSION }} Release checklist

### ISSUE THREAD

**Issue by aceqbaceq** [paritytech/polkadot#7644]
polkadot 1.0.0.

Does this version support websocket?  --rpc-port  specify rcp port. --ws-port is not available anymore.

**Comment by ggwpez** [comment]
`--rpc-port` sets the RPC port, which is provided via WebSocket protocol.

**Comment by bkchr** [comment]
See: https://github.com/paritytech/substrate/pull/13384
