### ISSUE TITLE
Candidate messages are not gossiped

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#765]
The parachain candidate message is not gossiped to the relay chain validator to be included into the next relay block. 

Repro: 
1. Use cumulus: https://github.com/paritytech/cumulus/pull/33
2. Start a local test network, register parachain and wait.
3. The parachain head is not updated in the relay chain, but it is validated successfully.

Maybe it is something different, but after some additional logging and debugging it seems that the candidate message is not send to the relay chain validator.

**Comment by bkchr** [comment]
Not my day. Running stuff in release "fixes" it. :( Sorry for the noise.

**Comment by rphmeier** [comment]
No worries!
