### ISSUE TITLE
Strip out old XCMP primitives

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#793]
`Message`, `OutgoingMessages`, `AvailableMessages`, `egress_queue_roots` on `CollationReceipt`, `BlockIngressRoots`, `StructuredUnroutedIngress`, and `ConsolidatedIngress` are all incompatible with the XCMP spec.

Code that uses them should be adapted not to:
  - availability store should just be storing `PoVBlock`, not messages
  - runtime XCMP storage entries should probably be removed, along with the logic that queries and updates them in `set_heads`.

**Comment by rphmeier** [comment]
Can we close that?

**Comment by expenses** [comment]
Think so.
