### ISSUE TITLE
Error: Input("Error opening spec file: No such file or directory (os error 2)")

### ISSUE THREAD

**Issue by Muhammad-Altabba** [paritytech/polkadot#803]
When running polkadot inside docker by:
`docker run -p 30333:30333 -p 9933:9933 -v /my/local/folder:/data chevdor/polkadot:latest polkadot --chain alex`
Or
`docker run -p 30333:30333 -p 9933:9933 -v chevdor/polkadot:latest polkadot --chain alex
`

The following error is printed:

> Error: Input("Error opening spec file: No such file or directory (os error 2)")

I am using Ubuntu and here is the polkadot version:
> $ docker run --rm -it chevdor/polkadot:latest polkadot --version
> polkadot 0.7.18-fc100e65e-x86_64-linux-gnu

**Comment by bkchr** [comment]
Alex doesn't exist anymore, the current test net is `westend`.
