### ISSUE TITLE
Upgradeable validation functions

### ISSUE THREAD

**Issue by rphmeier** [paritytech/polkadot#825]
To support things like Substrate's runtime upgrades, Polkadot has two options: to send the actual "validation Wasm" along with the witness data and execute it as a sandbox, or to allow upgrading of the validation function.

Sending the validation Wasm along with the witness data is expensive, and the overhead is compounded by the fact that it needs to be erasure-coded, so the extra data is passed onto the validators as well.

So we should pursue option #2: support upgrading of the validation Wasm in the runtime. The old validation Wasm needs to be kept available in the runtime as long as we are able to slash for executions of it.

10,000-foot view of implementation parts:
  - Extend `CandidateReceipt` with new validation function field: `Option<Vec<u8>>`
  - Implement fee scheme for parachains to pay for the validation function upgrade.
  - Implement fee scheme for the temporary custody of the prior validation function (and mechanism to ensure it is cleaned up by a protocol participant)
  - Provide a runtime API to search for the validation function used at a particular relay-chain block-height. This API will be used by fishermen and secondary-checkers.

**Comment by rphmeier** [comment]
@alistairstewart Raised the point in a chat that the chain should signal ahead-of-time that the validation function is going to be upgraded, so we can slash things that happen on forks. Otherwise, one fork might set the code to a value which is not on other forks. We wouldn't have the code needed to validate the reported blob, so the offence would go unpunished.

So here's the suggested protocol:
  - A parachain calls an external function `fn upgrade_validation_function(blob) -> BlockNumber`. The `BlockNumber` is the relay chain block number after which the upgrade should be applied. The first parachain block executed in the context of `b >= target_block` should enact the upgrade. The second parachain block executed in the context of `b >= target_block` is actually the first to use the new validation function. We also provide a `fn can_upgrade_validation_function(len) -> Result<Balance>` (returns Ok(fees) if allowed).
  - The relay chain implementation of `can_upgrade_validation_function` computes the fees and returns `Ok` only if it has been `UPGRADE_FREQUENCY` blocks since the last scheduled upgrade.
  - The relay chain implementation of `upgrade_validation_function` panics if any of the checks fail, and returns `now + UPGRADE_DELAY`.
  - After the first parachain block executed in the context of `b >= target_block` is included in the relay chain, the relay-chain swaps the validation function for the old one. The old one is kept available and accessible in the on-chain state for at least `SLASH_PERIOD` blocks.

`UPGRADE_FREQUENCY` is ~2 weeks
`UPGRADE_DELAY` is ~1 day
`SLASH_PERIOD` is the amount of time slashes are possible for an included parachain candidate.

**Comment by bkchr** [comment]
> - The relay chain implementation of can_upgrade_validation_function computes the fees and returns Ok only if it has been UPGRADE_FREQUENCY blocks since the last scheduled upgrade.

I assume that if I call the function after 13 days, it will already return `Ok(fees)`, as the upgrade will be applied after `UPGRADE_DELAY`?

Will `upgrade_validation_function()` already reserve/lock the funds at the relay chain?

**Comment by rphmeier** [comment]
> I assume that if I call the function after 13 days, it will already return Ok(fees), as the upgrade will be applied after UPGRADE_DELAY?

I would do this by comparing to the last block number an upgrade was scheduled, which would give you this property, yes

**Comment by coriolinus** [comment]
Some (dumb) questions:

1. Where is `SLASH_PERIOD` defined? The only reference I've found grepping is [here](https://github.com/paritytech/polkadot/blob/b94febb116fdf5a6ce9828f65198880d65e17875/runtime/common/src/parachains.rs#L128-L131).
1. Is [this](https://github.com/paritytech/substrate/blob/48150f24857e431ecb5066a2f60f59633eef915d/client/service/src/config.rs#L52-L53) the appropriate place to add configuration for `UPGRADE_FREQUENCY` and `UPGRADE_DELAY`?
1. It's not clear to me where to implement `upgrade_validation_function` and `can_upgrade_validation_function`. Are they methods on some struct (`ParachainExt`??), or free functions which live alongside, say, `parachain::wasm_executor::validate_candidate`?
1. How should I calculate the fees within `can_upgrade_validation_function`?

**Comment by bkchr** [comment]
1. & 2. will be probably constants that will be defined by Polkadot.
3. Will be defined by Polkadot as well, Cumulus will just use them.

**Comment by rphmeier** [comment]
@coriolinus Yes, these will be defined by Polkadot. Note that I'm assigned to the issue and have a branch in-progress.

3. These will be externalities (`parachain::wasm_executor::Externalities`, off the top of my head)
4. It would be determined by a fee schedule set forth by the runtime.

Although at this point I'm also considering just doing this on a time basis (fees are more complicated for Cumulus to do accounting) so parachains can upgrade as long as they haven't upgraded for `N` blocks in the past. There is a max code size which acts as a limiter.

**Comment by coriolinus** [comment]
Quoting from Riot:

> @bkchr 
> Maybe we need a function 
> That returns us this value from parachain validator 
> Yeah, I think we will require one 

> @coriolinus 
> Ok. That's part of the Parachain trait?

> @bkchr 
> Best to comment on the issue and to make @rphmeier  aware of it.

The context of all this: we were discussing how precisely Polkadot will communicate to a parachain the block at which an upgrade becomes legal. My first instinct was that it would inject a value with a defined constant key into the parachain's storage, but that apparently won't work.

So where I'm at right now is that a parachain collator needs to have some way to query its validator and get the block number `target_block`, and I'm not sure where is best to put it.

**Comment by rphmeier** [comment]
Good point. I suppose as long as `UPGRADE_DELAY` is communicated somehow, that the parachain and relay chain can do the same calculation. We'll have to be careful on the relay-chain side when we allow in parachain blocks that are not executed in the context if the direct relay-chain ancestor, as we'll have to subtract the differential between the block that the parachain thinks its block is being executed in vs. the block it is actually executed in. Other than that, the calculations should align.
