### ISSUE TITLE
Run erasure coding in native

### ISSUE THREAD

**Issue by burdges** [paritytech/polkadot#844]
Right now, we run Reed-Solomon coding inside the WASM runtime according to https://github.com/paritytech/polkadot/blob/master/erasure-coding/Cargo.toml#L9 but Reed-Solomon might eat up considerable CPU.  We should consider moving it into native if benchmarks show it causing trouble.

**Comment by bkchr** [comment]
We don't run this in wasm. Not sure why you think this?

**Comment by rphmeier** [comment]
We run this in native right now.

**Comment by burdges** [comment]
Oops I mistakenly thought that subcrate was being built in WASM.
