### ISSUE TITLE
WeightToFee coefficient is wrong

### ISSUE THREAD

**Issue by kaichaosun** [paritytech/polkadot#847]
Currency related code [here](https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/constants.rs#L19-L24):
```
pub mod currency {
	use primitives::Balance;

	pub const DOTS: Balance = 1_000_000_000_000;
	pub const DOLLARS: Balance = DOTS;
	pub const CENTS: Balance = DOLLARS / 100;
	pub const MILLICENTS: Balance = CENTS / 1_000;
}
```

WeightToFee code [here](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/impls.rs#L88-L95):
```
pub struct WeightToFee;
impl Convert<Weight, Balance> for WeightToFee {
	fn convert(x: Weight) -> Balance {
		// in Polkadot a weight of 10_000 (smallest non-zero weight) to be mapped to 10^7 units of
		// fees (1/10 CENT), hence:
		Balance::from(x).saturating_mul(1_000)
	}
}
```
smallest non-zero weight maps to 10^7 units of fees, which is not 1/10 CENT, but 1/1000 CENT.
The coefficient is 1000 here, is it wrong?

**Comment by burdges** [comment]
cc @eraysabancilar

**Comment by rphmeier** [comment]
Please submit a PR to fix if this is determined to be wrong.
