### ISSUE TITLE
kusama node sync stops at #688170 or #777936 every time.

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/polkadot#872]
**VPS:**  
```
ubuntu_18_04_x64
4 vCPU 8 GiB Memory, 100GiB SSD
```

**Kusama node version:**  
<img width="660" alt="截屏2020-03-03下午1 02 51" src="https://user-images.githubusercontent.com/34789555/75744986-da551f80-5d50-11ea-9796-c4f9608ca0e4.png">
(Ps: Already tried many versions)

**Logs:**  

1. First time 
![WechatIMG293](https://user-images.githubusercontent.com/34789555/75746126-35d4dc80-5d54-11ea-952b-e69a6769f04f.png)

2. 
![WechatIMG294](https://user-images.githubusercontent.com/34789555/75746155-569d3200-5d54-11ea-803f-b57cee22aa5e.jpeg)

3. 
![WechatIMG295](https://user-images.githubusercontent.com/34789555/75746187-716fa680-5d54-11ea-8c77-1a226238d571.jpeg)

4. Last time
<img width="1052" alt="截屏2020-03-03下午1 02 30" src="https://user-images.githubusercontent.com/34789555/75745067-1c7e6100-5d51-11ea-9a0d-dec49f431396.png">

- The node running as a full node and light client(all tried).
- Command-line options were passed:  
```
docker run -d --restart=always --name=kusama-node -p 30433:30433 -p 9943:9943 -p 9954:9954 -v ~/kusama:/data parity/polkadot:master --ws-port 9954 --rpc-port 9943 --port 30433 --ws-external --rpc-external --ws-max-connections 1000 --rpc-cors=all --pruning=archive
```

**Comment by fiowind** [comment]
+1

**Comment by jiangfuyao** [comment]
@fiowind This issue has been fixed in the Substrate repository, and the next substrate version upgrade of kusama network will solve the problem.

**Comment by fiowind** [comment]
> @fiowind This issue has been fixed in the Substrate repository, and the next substrate version upgrade of kusama network will solve the problem.

How to sync data now?

**Comment by fiowind** [comment]
@jiangfuyao

**Comment by jiangfuyao** [comment]
@fiowind To use the new version.
