### ISSUE TITLE
Client: Structured logging

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot#90]
Eventual aim: a highly detailed version of ethstats.net with clients (optionally!) directly contacting a central web server to provide it with real-time information that is collated and served to web pages.

This is a two-part project; one part is fitting the appropriate logging into the client in order to connect and stream JSON information on the client's operational statistics to a server. The second part is writing such a web app; the server part of the app would receive and collate this information in real time from many polkadot clients and then distribute the resulting information to web-browsers for display.

This issue only describes the first part.

#  Implementation

[slog](https://github.com/slog-rs/slog) can provide the structured logging API. This should be combined with a `lazy_static` and a simple macro in order to get a global logging macro, much like  `trace!` from the `log` crate except that it accepts key/value pairs rather than a formatted string.

This macro should be used throughout the client for all key events (block arrived from network/queued/validated/imported, transaction(s) submitted/arrived/mined, peer connected/disconnected, ...).

The output of the structured log should be directed to a JSON encoder and then sent via a websockets connection to a server (address/port configurable via CLI params ala `polkadot --stats-server=ws://stats.polkadot.io`). On opening the websockets connection, an initial dump of the nodes state should be made (current chain head number/hash, peers, transactions in the pool).

**Comment by vs77bb** [comment]
@gavofyork @maciejhirsz Vivek from Gitcoin here: would either of you mind adding a bit more detail for potential contributor, perhaps an Acceptance Criteria? I will bounty accordingly!

**Comment by gavofyork** [comment]
@vs77bb done :)
