### ISSUE TITLE
Polkadot v0.7.26 - Deadlocked process

### ISSUE THREAD

**Issue by ddorgan** [paritytech/polkadot#909]
Sentry node which was recently updated to v0.7.26 hung and stopped logging, no reply on connections to websockets, jsonrpc or prometheus ports.

Thread dump at: 
https://gist.github.com/ddorgan/3ade8ee8211353164830e6638365f5ec

Posted a copy of the logs in the chat.

**Comment by andresilva** [comment]
Should be fixed by https://github.com/paritytech/substrate/pull/5295.

**Comment by andresilva** [comment]
The fix will be included in the next release. Let's reopen this issue if we run into this again.
