### ISSUE TITLE
Ban multiple versions of parity-util-mem

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot#922]
To avoid issues like https://github.com/paritytech/polkadot/pull/921, having multiple versions of parity-util-mem should be banned. This can be enforced in CI via https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html or simply by running this command
```bash
! grep -qE "parity-util-mem [0-9].+[0-9] \(registry" Cargo.lock
```
To see where multiple versions of parity-util-mem come from, run (install [cargo-tree](https://github.com/sfackler/cargo-tree) first)
```
cargo tree -i -p parity-util-mem:0.6.0
```
and 
```
cargo tree -i -p parity-util-mem:0.5.2
```

**Comment by rphmeier** [comment]
@ordian Will you prepare a PR?

**Comment by burdges** [comment]
Rust should ban duplicate `#[no_mangle]` symbols, no? https://github.com/rust-lang/rust/issues/28179  If so then adding one `#[no_mangle]` symbol should help detect this at compile time, although maybe this fails under some architectures, making the CI check good too.

**Comment by ordian** [comment]
@rphmeier I see @TriplEight self-assigned to this (probably for the CI check). Currently the problem is coming from substrate, memory-db needs to be bumped there in order to avoid multiple versions:
https://github.com/paritytech/substrate/blob/42ec6948af7ee2773d95e68bdf04d89abe2f716b/primitives/trie/Cargo.toml#L22

I know that ring uses thing workaround for detecting this at compile time:
https://github.com/briansmith/ring/blob/ddfa683266e8ce41c06feb9f46503dd4e1d47ab1/Cargo.toml#L15-L16

**Comment by bkchr** [comment]
What is the problem of having this util mem multiple times in the depdendcy graph?

**Comment by ordian** [comment]
@bkchr the problem is that if if one version doesn't enable `jemalloc-global` feature and another does, then you'll get UB, see https://github.com/paritytech/polkadot/pull/921#discussion_r396011592

**Comment by ordian** [comment]
Here is an example which segfaults on `cargo run`: https://github.com/ordian/multiple-parity-util-mem-issue.
