### ISSUE TITLE
Validators finality sometimes stalling on new sessions

### ISSUE THREAD

**Issue by ddorgan** [paritytech/polkadot#923]
Some validators are sometimes having finality stalls on the start of a new session. These nodes aren't as well connected as other validators who are not showing the issue. But they should have plenty of sentry nodes to operate.

[I've posted the logs in chat](https://matrix.to/#/!ctNFjEKQvnJPKUWiJI:web3.foundation/$klKHpq2t-OOLoo_Zd6ajHAJh-aPtgvE6AyXLE_tZsOo?via=web3.foundation&via=matrix.parity.io) (parity access only)

**Comment by TriplEight** [comment]
Now it's even happening not on the start of the session but every hour.
https://kusama-logs.s3.eu-central-1.amazonaws.com/denisp@kusama-sentry-ue1-0_2020-03-30T16-15UTC_kusama.log.gz
https://kusama-logs.s3.eu-central-1.amazonaws.com/denisp@kusama-sentry-ue1-1_2020-03-30T16-15UTC_kusama.log.gz
https://kusama-logs.s3.eu-central-1.amazonaws.com/denisp@kusama-sentry-ew1-1_2020-03-30T16-35UTC_kusama.log.gz
https://kusama-logs.s3.eu-central-1.amazonaws.com/denisp@kusama-sentry-ew1-0_2020-03-30T16-34UTC_kusama.log.gz

**Comment by arkpar** [comment]
I don't see any syncing issues in the logs. @andresilva Could you check what's going on with finality?

**Comment by andresilva** [comment]
Issue seems to be that sentries don't treat their peers preferably regarding gossip. Peer selection is essentially random so the sentry might not select one of its reserved peers and eventually the peer starts getting behind as it doesn't get the latest vote data from anywhere else. The less sentry nodes the validator has the more likely this is to happen and hence why we're seeing it more often on the AWS region validators.

We rolled out a hacky fix to our AWS nodes to see if this was indeed the cause and it seems to have worked so far, we are not observing these hourly stalls anymore.

**Comment by ddorgan** [comment]
@arkpar is this fixed in master? We still have nodes alerting quite frequently on this and would like to test the fix.

**Comment by andresilva** [comment]
Yes, master should have the proper fix that I mentioned above. Keep in mind that the `--sentry` flag now takes a list of validator node addresses, it's no longer needed to add them as reserved nodes.

**Comment by ddorgan** [comment]
Perfect thanks!
