### ISSUE TITLE
Question: Why the default features in common is empty?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/polkadot#956]
polkadot's default is std: https://github.com/paritytech/polkadot/blob/master/runtime/common/Cargo.toml#L51

common's default is no_std: https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/Cargo.toml#L78

But the polkadot depends on common. And I see the claims in common depends std a lot. It seems that set the common's default to std would be more reasonable.

**Comment by bkchr** [comment]
What is the problem here?

It is only missing in`common`, but that is also no greater problem, as `common` is included in the runtime and that controls the features.
